from pathlib import Path

p=Path('/opt/wiener-backend/server.mjs')
s=p.read_text()
marker="\napp.use((_req,res)=>\n  res.status(404).json({ok:false,error:'route_not_enabled_yet'})\n);\n"
if 'WIENER VPS BOT ROUTES V7' in s:
    print('WIENER VPS BOT ROUTES V7 already installed')
    raise SystemExit(0)
if marker not in s:
    raise SystemExit('ERROR: insertion marker not found')

code=r'''
// === WIENER VPS BOT ROUTES V7 ===

async function botSecretV7(){
  const q=await pool.query(`select telegram_webhook_secret from public.app_settings where id=true limit 1`);
  return String(q.rows[0]?.telegram_webhook_secret||'');
}
async function tgV7(method,payload){
  const r=await fetch(`https://api.telegram.org/bot${BOT}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});
  const x=await r.json(); if(!x.ok) throw new Error(x.description||method); return x.result;
}
const kbV7=rows=>({inline_keyboard:rows});
const cbV7=(text,data)=>({text,callback_data:data});
const webV7=(text,url)=>({text,web_app:{url}});
const urlV7=(text,url)=>({text,url});
async function appSettingsV7(){return (await pool.query(`select * from public.app_settings where id=true limit 1`)).rows[0]||{}}
async function userV7(id){return (await pool.query(`select * from public.users where telegram_id=$1 limit 1`,[id])).rows[0]||null}
function appUrlV7(s){return String(s.app_url||'https://wiener-farm.vercel.app').replace(/\/$/,'')}
function fmtV7(v,d=2){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:d})}
async function sendMenuV7(uid){
  const s=await appSettingsV7(),u=await userV7(uid),app=appUrlV7(s);
  if(!u) return tgV7('sendMessage',{chat_id:uid,text:'🌭 WIENER FARM\n\nOpen the Mini App to create your account.',reply_markup:kbV7([[webV7('🌭 OPEN WIENER FARM',app)]])});
  const usd=Number(u.balance||0)/Math.max(1,Number(s.token_per_usdt||10000));
  const text=`🌭 WIENER FARM\n\n💰 ${fmtV7(u.balance)} WIENER · ≈ ${usd.toFixed(4)} USDT\n🔥 ${Number(u.daily_streak||0)} day streak\n📺 ${Number(u.total_ads||0)} ads completed\n👥 ${Number(u.active_referrals_count||0)}/${Number(u.referrals_count||0)} qualified referrals\n\nChoose an option below.`;
  const markup=kbV7([[webV7('🌭 OPEN WIENER FARM',app)],[cbV7('💰 Balance','v7:balance'),cbV7('📊 Profile','v7:profile')],[cbV7('📺 Ads','v7:ads'),cbV7('✅ Tasks','v7:tasks')],[cbV7('👥 Referrals','v7:refs'),cbV7('🏆 Leaderboard','v7:leaderboard')],[cbV7('💸 Withdrawals','v7:wallet'),cbV7('❓ Help','v7:help')]]);
  return tgV7('sendMessage',{chat_id:uid,text,reply_markup:markup,disable_web_page_preview:true});
}
async function menuViewV7(uid,key){
  const s=await appSettingsV7(),u=await userV7(uid),app=appUrlV7(s); if(!u)return {text:'Open WIENER Farm first.',markup:kbV7([[webV7('OPEN',app)]])};
  const back=[cbV7('◀️ MAIN MENU','v7:home')];
  if(key==='balance'){const q=await pool.query(`select amount,description from public.transactions where telegram_id=$1 order by created_at desc limit 3`,[uid]);return{text:`💰 BALANCE\n\nAvailable: ${fmtV7(u.balance)} WIENER\n≈ ${(Number(u.balance||0)/Math.max(1,Number(s.token_per_usdt||10000))).toFixed(4)} USDT\n📈 Total earned: ${fmtV7(u.total_earned)} WIENER\n💸 Total withdrawn: ${fmtV7(u.total_withdrawn)} WIENER\n\n${q.rows.map(x=>`${Number(x.amount)>=0?'➕':'➖'} ${fmtV7(Math.abs(Number(x.amount)))} · ${String(x.description||'Transaction').slice(0,36)}`).join('\n')||'No transactions yet.'}`,markup:kbV7([[webV7('💸 OPEN WALLET',`${app}?page=wallet`)],back])}}
  if(key==='profile')return{text:`📊 PROFILE\n\n${u.first_name||u.username||'WIENER User'}${u.username?` · @${u.username}`:''}\nUID: ${uid}\n\n💰 ${fmtV7(u.balance)} WIENER\n📈 Earned: ${fmtV7(u.total_earned)}\n📺 Ads: ${Number(u.total_ads||0)}\n🔥 Streak: ${Number(u.daily_streak||0)}\n👥 Referrals: ${Number(u.referrals_count||0)}\n✅ Qualified: ${Number(u.active_referrals_count||0)}`,markup:kbV7([[webV7('📊 OPEN PROFILE',`${app}?page=profile`)],back])};
  if(key==='ads')return{text:`📺 ADS\n\nToday: ${Number(u.ads_watched_today||0)}/${Number(s.daily_ad_limit||0)}\nTotal: ${Number(u.total_ads||0)}\nReward: +${fmtV7(s.ad_reward)} WIENER`,markup:kbV7([[webV7('📺 WATCH ADS',`${app}?page=ads`)],back])};
  if(key==='tasks'){const q=await pool.query(`select count(*)::int c from public.task_completions where telegram_id=$1`,[uid]);return{text:`✅ TASKS\n\nCompleted: ${Number(q.rows[0]?.c||0)}`,markup:kbV7([[webV7('✅ VIEW TASKS',`${app}?page=tasks`)],back])};
  if(key==='refs'){const bot=String(s.bot_username||'WienerDogeFarmBot').replace('@',''),link=`https://t.me/${bot}?startapp=ref_${uid}`;return{text:`👥 REFERRALS\n\nInvited: ${Number(u.referrals_count||0)}\nQualified: ${Number(u.active_referrals_count||0)}\nEarned: ${fmtV7(u.referral_earnings)} WIENER`,markup:kbV7([[urlV7('📤 SHARE INVITE',`https://t.me/share/url?url=${encodeURIComponent(link)}`)],[webV7('👥 OPEN REFERRALS',`${app}?page=invite`)],back])};
  if(key==='wallet'){const q=await pool.query(`select status,receive_usdt,network from public.withdrawals where telegram_id=$1 order by created_at desc limit 3`,[uid]);return{text:`💸 WITHDRAWALS\n\nBalance: ${fmtV7(u.balance)} WIENER\n\n${q.rows.map(x=>`${x.status==='paid'?'✅':x.status==='rejected'?'❌':'⏳'} ${Number(x.receive_usdt||0).toFixed(4)} USDT · ${x.network||''}`).join('\n')||'No withdrawals yet.'}`,markup:kbV7([[webV7('💸 OPEN WALLET',`${app}?page=wallet`)],back])};
  if(key==='help')return{text:'❓ WIENER HELP\n\n/menu — Main menu\n/balance — Balance\n/profile — Profile\n/ads — Ads\n/tasks — Tasks\n/referral — Referrals\n/leaderboard — Rankings\n/withdraw — Wallet\n/help — Help',markup:kbV7([[webV7('🌭 OPEN WIENER FARM',app)],back])};
  return {text:'🏆 LEADERBOARD\n\nChoose ranking:',markup:kbV7([[cbV7('👥 TOP REFERRALS','v7lb:inviters'),cbV7('💰 TOTAL EARNED','v7lb:earners')],back])};
}
async function leaderboardV7(uid,mode){const x=await rpc('get_wiener_invite_leaderboards',[uid]);const rows=(x?.[mode]||[]).slice(0,10),me=x?.me?.[mode],med=['🥇','🥈','🥉'];const disp=r=>[r.first_name,r.last_name].filter(Boolean).join(' ').trim()||(r.username?'@'+r.username:`User ${String(r.telegram_id).slice(-4)}`);const unit=v=>mode==='inviters'?`${fmtV7(v)} referrals`:`${fmtV7(v)} WIENER`;return `🏆 WIENER FARM LEADERBOARD\n\n${mode==='inviters'?'👥 TOP REFERRALS':'💰 TOTAL EARNED'}\n\n${rows.map((r,i)=>`${med[i]||`${i+1}.`} ${disp(r)}\n   ${unit(r.value)}`).join('\n')||'No rankings yet.'}\n\n👤 Your rank: ${me?.rank?`#${me.rank}`:'Unranked'} · ${unit(me?.value||0)}`}

async function payoutConfigV7(){
  const s=(await pool.query(`select payout_auto_enabled,payout_polygon_enabled,payout_max_usdt,payout_daily_cap_usdt,payout_chain_id,payout_provider,payout_emergency_paused,payout_high_value_confirm_usdt from public.app_settings where id=true`)).rows[0]||{};
  const daily=await rpc('wiener_payout_daily_total',[]).catch(()=>0);
  return {s,daily:Number(daily||0),rpc:process.env.WIENER_POLYGON_RPC_URL||'',pk:process.env.WIENER_POLYGON_PAYOUT_PRIVATE_KEY||'',token:process.env.WIENER_POLYGON_USDT_CONTRACT||''};
}
async function payoutAdminV7(id){const a=await isAdmin(id);return !!a&&(a.role==='owner'||a.role==='admin'||a.permissions?.withdrawals===true)}
async function polygonLibV7(){const [{createPublicClient,createWalletClient,http,parseUnits,getAddress},{privateKeyToAccount},{polygon}]=await Promise.all([import('viem'),import('viem/accounts'),import('viem/chains')]);return{createPublicClient,createWalletClient,http,parseUnits,getAddress,privateKeyToAccount,polygon}}
const USDT_ABI_V7=[{type:'function',name:'transfer',stateMutability:'nonpayable',inputs:[{name:'to',type:'address'},{name:'value',type:'uint256'}],outputs:[{name:'',type:'bool'}]},{type:'function',name:'balanceOf',stateMutability:'view',inputs:[{name:'account',type:'address'}],outputs:[{name:'',type:'uint256'}]},{type:'function',name:'decimals',stateMutability:'view',inputs:[],outputs:[{name:'',type:'uint8'}]}];
async function payoutPayV7(admin,wid,confirm=false){
  const c=await payoutConfigV7(); if(c.s.payout_emergency_paused)throw new Error('payout_emergency_paused'); if(!c.s.payout_auto_enabled||!c.s.payout_polygon_enabled)throw new Error('auto_payout_disabled'); if(!c.rpc||!c.pk||!c.token)throw new Error('payout_provider_not_configured');
  const w=(await pool.query(`select * from public.withdrawals where id=$1`,[wid])).rows[0]; if(!w)throw new Error('withdrawal_not_found'); if(w.status==='paid')return{already_paid:true,withdrawal:w}; if(w.status!=='pending'||w.network!=='Polygon')throw new Error('withdrawal_not_pending');
  const amount=Number(w.receive_usdt||0),max=Number(c.s.payout_max_usdt||.25),cap=Number(c.s.payout_daily_cap_usdt||2),hi=Number(c.s.payout_high_value_confirm_usdt||.1); if(amount<=0||amount>max)throw new Error('amount_exceeds_auto_payout_limit'); if(c.daily+amount>cap)throw new Error('daily_payout_cap_exceeded'); if(amount>=hi&&!confirm)throw new Error('high_value_confirmation_required');
  const lock=await rpc('acquire_wiener_payout_lock',[wid,admin]); if(!lock?.ok)throw new Error(`payout_${lock?.reason||'locked'}`);
  let hash=null; try{
    const lib=await polygonLibV7(),pk=(c.pk.startsWith('0x')?c.pk:`0x${c.pk}`),account=lib.privateKeyToAccount(pk),to=lib.getAddress(String(w.wallet_address)),token=lib.getAddress(c.token),pc=lib.createPublicClient({chain:lib.polygon,transport:lib.http(c.rpc)}),wc=lib.createWalletClient({account,chain:lib.polygon,transport:lib.http(c.rpc)});
    if(await pc.getChainId()!==137)throw new Error('wrong_rpc_chain'); const decimals=Number(await pc.readContract({address:token,abi:USDT_ABI_V7,functionName:'decimals'})); if(decimals!==6)throw new Error('unexpected_token_decimals'); const units=lib.parseUnits(amount.toFixed(6),decimals),bal=await pc.readContract({address:token,abi:USDT_ABI_V7,functionName:'balanceOf',args:[account.address]}); if(bal<units)throw new Error('payout_wallet_insufficient_usdt');
    await pool.query(`insert into public.wiener_payout_attempts(withdrawal_id,admin_id,network,amount_usdt,wallet_address,state,provider,signer_address,from_address,token_contract,asset,asset_decimals,chain_id,idempotency_key) values($1,$2,'Polygon',$3,$4,'broadcasting','polygon_hot_wallet',$5,$5,$6,'USDT',6,137,$7) on conflict(withdrawal_id) do update set admin_id=excluded.admin_id,state='broadcasting',error=null,failure_code=null,safe_to_retry=false`,[wid,admin,amount,to,account.address,token,`withdrawal:${wid}`]);
    hash=await wc.writeContract({address:token,abi:USDT_ABI_V7,functionName:'transfer',args:[to,units],account}); const explorer=`https://polygonscan.com/tx/${hash}`; await pool.query(`update public.wiener_payout_attempts set state='submitted',tx_hash=$2,provider_tx_id=$2,submitted_at=now(),explorer_url=$3,safe_to_retry=false where withdrawal_id=$1`,[wid,hash,explorer]); const receipt=await pc.waitForTransactionReceipt({hash,confirmations:1,timeout:60000}); if(receipt.status!=='success')throw new Error('transaction_reverted_do_not_retry'); await rpc('mark_withdrawal_paid_v2',[admin,wid,hash,explorer]); await pool.query(`update public.wiener_payout_attempts set state='confirmed',receipt_status=$2,block_number=$3,gas_used=$4,effective_gas_price=$5,confirmations=1,confirmed_at=now(),finalized_at=now(),safe_to_retry=false where withdrawal_id=$1`,[wid,receipt.status,Number(receipt.blockNumber),String(receipt.gasUsed),String(receipt.effectiveGasPrice||'')]); const paid=(await pool.query(`select * from public.withdrawals where id=$1`,[wid])).rows[0]; await withdrawalPaidDeliver(paid); return{withdrawal:paid,tx_hash:hash,explorer_url:explorer};
  }catch(e){if(!hash)await rpc('release_wiener_payout_lock',[wid,admin]).catch(()=>null);throw e}
}
app.post('/functions/v1/wiener-payout',async(req,res)=>{try{const sec=await botSecretV7();if(String(req.headers['x-wiener-internal-secret']||'')!==sec)return res.status(403).send('forbidden');const b=req.body||{},admin=Number(b.admin_id||0);if(!await payoutAdminV7(admin))return res.status(403).json({ok:false,error:'admin_forbidden'});const action=String(b.action||'');if(action==='status'){const c=await payoutConfigV7();return res.json({ok:true,data:{configured:!!c.rpc&&!!c.pk&&!!c.token,rpc_present:!!c.rpc,private_key_present:!!c.pk,token_present:!!c.token,auto_enabled:!!c.s.payout_auto_enabled,polygon_enabled:!!c.s.payout_polygon_enabled,emergency_paused:!!c.s.payout_emergency_paused,max_usdt:Number(c.s.payout_max_usdt||0),daily_cap_usdt:Number(c.s.payout_daily_cap_usdt||0),daily_total_usdt:c.daily,chain_id:Number(c.s.payout_chain_id||137),provider:c.s.payout_provider||'polygon_hot_wallet',high_value_confirm_usdt:Number(c.s.payout_high_value_confirm_usdt||.1)}})}if(action==='pay')return res.json({ok:true,data:await payoutPayV7(admin,String(b.withdrawal_id||''),!!b.confirm_high_value)});throw new Error('unknown_action')}catch(e){return edgeFail(res,e)}});

async function payViewV7(admin){const w=(await pool.query(`select * from public.withdrawals where status='pending' and network='Polygon' order by created_at limit 1`)).rows[0];if(!w)return{text:'✅ No pending Polygon withdrawals.',markup:kbV7([])};return{text:`💸 PENDING WITHDRAWAL\n\n👤 ${w.username?'@'+w.username:`UID ${w.telegram_id}`}\n💵 Gross: ${Number(w.gross_usdt||0).toFixed(4)} USDT\n💰 Pay: ${Number(w.receive_usdt||0).toFixed(4)} USDT\n🌐 Polygon\n👛 ${w.wallet_address}`,markup:kbV7([[cbV7('💸 PAY NOW',`v7pay:pay:${w.id}`)],[cbV7('❌ DECLINE',`v7pay:reject:${w.id}`)],[cbV7('🔄 REFRESH','v7pay:home')]])}}

app.post('/functions/v1/wiener-bot-webhook',async(req,res)=>{
  try{
    const sec=await botSecretV7(); if(!sec||String(req.headers['x-telegram-bot-api-secret-token']||'')!==sec)return res.status(403).send('forbidden'); const up=req.body||{},updateId=Number(up.update_id); if(Number.isFinite(updateId)){try{await pool.query(`insert into public.telegram_processed_updates(update_id) values($1)`,[updateId])}catch(e){if(e?.code==='23505')return res.json({ok:true,duplicate:true});throw e}}
    const done=async()=>{if(Number.isFinite(updateId))await pool.query(`update public.telegram_processed_updates set completed_at=now() where update_id=$1`,[updateId]);return res.json({ok:true})};
    const m=up.message,q=up.callback_query,uid=Number(q?.from?.id||m?.from?.id||0),text=String(m?.text||'').trim();
    if(m?.from?.id&&m?.forward_origin?.sender_user?.id){const src=String(m.forward_origin.sender_user.username||'').toLowerCase();if(src){const vr=await pool.query(`select id,task_id,expected_bot_username from public.bot_task_verifications where telegram_id=$1 and status='pending' order by requested_at desc limit 5`,[uid]);for(const v of vr.rows){if(String(v.expected_bot_username||'').toLowerCase()===src){await pool.query(`update public.bot_task_verifications set status='verified',verified_at=now(),forwarded_bot_username=$2,updated_at=now() where id=$1`,[v.id,src]);await tgV7('sendMessage',{chat_id:uid,text:'✅ Bot task verified. Return to WIENER Farm and tap CLAIM.'});break}}}}
    if(/^\/start(?:@\w+)?(?:\s|$)/i.test(text)&&m?.chat?.type==='private'){
      const parts=text.split(/\s+/),mm=String(parts[1]||'').match(/(?:ref_|r_?)(\d{5,20})/i),ref=mm?Number(mm[1]):null; await rpc('register_or_touch_user',[uid,m.from.username||null,m.from.first_name||null,m.from.last_name||null,null,ref&&ref!==uid?ref:null]); const s=await appSettingsV7(),caption='🌭 Welcome to WIENER FARM! 🚜\n\n💰 Farm WIENER every day\n📺 Watch ads & earn instantly\n✅ Complete tasks for extra rewards\n👥 Invite friends & earn referral rewards\n💸 Withdraw USDT via TON or Polygon\n\n🔥 Your farm is waiting — start earning now!'; const markup=kbV7([[webV7('🌭 OPEN WIENER FARM',appUrlV7(s))],[urlV7('📢 Channel','https://t.me/WienerFarm'),urlV7('💬 Support','https://t.me/WienerSupport')]]); try{await tgV7('sendPhoto',{chat_id:uid,photo:'https://wiener-farm.vercel.app/api/host/welcome-image',caption,reply_markup:markup})}catch{await tgV7('sendMessage',{chat_id:uid,text:caption,reply_markup:markup})}return done();
    }
    if(/^\/pay(?:@\w+)?$/i.test(text)){if(!await payoutAdminV7(uid)){await tgV7('sendMessage',{chat_id:uid,text:'⛔ Admin permission required.'});return done()}const v=await payViewV7(uid);await tgV7('sendMessage',{chat_id:uid,text:v.text,reply_markup:v.markup});return done()}
    if(/^\/(ban|unban)(?:@\w+)?\s+(\d+)/i.test(text)){const mm=text.match(/^\/(ban|unban)(?:@\w+)?\s+(\d+)/i);if(!await isAdmin(uid)){await tgV7('sendMessage',{chat_id:uid,text:'⛔ Admin permission required.'});return done()}const target=Number(mm[2]),ban=mm[1].toLowerCase()==='ban';if(ban)await pool.query(`update public.users set is_banned=true,ban_reason='Admin action' where telegram_id=$1`,[target]);else{await pool.query(`update public.users set is_banned=false,ban_reason=null,device_blocked=false where telegram_id=$1`,[target]);await rpc('admin_unban_device_user',[uid,target]).catch(()=>null)}await tgV7('sendMessage',{chat_id:uid,text:`✅ ${target} ${ban?'banned':'fully unbanned'}.`});return done()}
    if(q&&String(q.data||'').startsWith('v7pay:')){if(!await payoutAdminV7(uid)){await tgV7('answerCallbackQuery',{callback_query_id:q.id,text:'Admin permission required',show_alert:true});return done()}const [,act,wid]=String(q.data).split(':');if(act==='home'){const v=await payViewV7(uid);await tgV7('editMessageText',{chat_id:q.message.chat.id,message_id:q.message.message_id,text:v.text,reply_markup:v.markup});return done()}if(act==='reject'){await rpc('reject_withdrawal_v2',[uid,wid,'Rejected by admin']);await tgV7('answerCallbackQuery',{callback_query_id:q.id,text:'Rejected'});const v=await payViewV7(uid);await tgV7('editMessageText',{chat_id:q.message.chat.id,message_id:q.message.message_id,text:v.text,reply_markup:v.markup});return done()}if(act==='pay'||act==='confirm'){try{const r=await payoutPayV7(uid,wid,act==='confirm');await tgV7('answerCallbackQuery',{callback_query_id:q.id,text:'Paid'});await tgV7('sendMessage',{chat_id:uid,text:`✅ PAID\n\n${Number(r.withdrawal?.receive_usdt||0).toFixed(4)} USDT\n${r.explorer_url||''}`})}catch(e){const msg=String(e.message||e);if(msg.includes('high_value_confirmation_required')){await tgV7('editMessageText',{chat_id:q.message.chat.id,message_id:q.message.message_id,text:'⚠️ High-value payout. Confirm only after review.',reply_markup:kbV7([[cbV7('✅ CONFIRM & PAY',`v7pay:confirm:${wid}`)],[cbV7('❌ CANCEL','v7pay:home')]])});return done()}await tgV7('sendMessage',{chat_id:uid,text:`⚠️ PAYOUT NOT COMPLETED\n\n${msg}`})}return done()}}
    if(q&&String(q.data||'').startsWith('v7lb:')){const mode=String(q.data).endsWith('earners')?'earners':'inviters',txt=await leaderboardV7(uid,mode);await tgV7('editMessageText',{chat_id:q.message.chat.id,message_id:q.message.message_id,text:txt,reply_markup:kbV7([[cbV7('👥 REFERRALS','v7lb:inviters'),cbV7('💰 EARNED','v7lb:earners')]])});await tgV7('answerCallbackQuery',{callback_query_id:q.id});return done()}
    if(q&&String(q.data||'').startsWith('v7:')){const key=String(q.data).slice(3);if(key==='home'){await tgV7('deleteMessage',{chat_id:q.message.chat.id,message_id:q.message.message_id}).catch(()=>null);await sendMenuV7(uid);return done()}const v=await menuViewV7(uid,key);await tgV7('editMessageText',{chat_id:q.message.chat.id,message_id:q.message.message_id,text:v.text,reply_markup:v.markup,disable_web_page_preview:true});await tgV7('answerCallbackQuery',{callback_query_id:q.id});return done()}
    if(/^\/leaderboard(?:@\w+)?$/i.test(text)){await tgV7('sendMessage',{chat_id:uid,text:await leaderboardV7(uid,'inviters'),reply_markup:kbV7([[cbV7('👥 REFERRALS','v7lb:inviters'),cbV7('💰 EARNED','v7lb:earners')]])});return done()}
    const map={menu:'home',balance:'balance',profile:'profile',ads:'ads',tasks:'tasks',referral:'refs',invite:'refs',withdraw:'wallet',wallet:'wallet',help:'help',support:'help'}; const cmd=text.startsWith('/')?text.split(/\s+/)[0].replace(/^\//,'').split('@')[0].toLowerCase():''; if(map[cmd]){if(map[cmd]==='home')await sendMenuV7(uid);else{const v=await menuViewV7(uid,map[cmd]);await tgV7('sendMessage',{chat_id:uid,text:v.text,reply_markup:v.markup,disable_web_page_preview:true})}return done()}
    return done();
  }catch(e){console.error('v7 webhook',e);return res.status(500).json({ok:false,error:String(e.message||e)})}
});

// === END WIENER VPS BOT ROUTES V7 ===
'''
s=s.replace(marker,'\n'+code+'\n'+marker,1)
p.write_text(s)
print('Installed WIENER VPS BOT ROUTES V7')
