from pathlib import Path

p=Path('/opt/wiener-backend/server.mjs')
s=p.read_text()
if 'WIENER VPS BOT HANDLER PARITY V18' in s:
    print('V18 bot handler parity already installed')
    raise SystemExit(0)

# Install V18 before the older V10B partial bot ops so V18 owns restored commands/callbacks.
hook="    try{if(await handleBotOpsV10B(up,uid,text,m,q)) return done();}catch(e){console.error('v10b_bot_ops',String(e?.message||e));}"
if hook not in s:
    raise SystemExit('ERROR: V10B webhook hook not found')
s=s.replace(hook,"    try{if(await handleBotParityV18(up,uid,text,m,q)) return done();}catch(e){console.error('v18_bot_parity',String(e?.message||e));}\n"+hook,1)

marker="\napp.use((_req,res)=>\n  res.status(404).json({ok:false,error:'route_not_enabled_yet'})\n);\n"
if marker not in s:
    raise SystemExit('ERROR: final insertion marker not found')

code=r'''

// === WIENER VPS BOT HANDLER PARITY V18 ===
const n18=v=>Number(v||0), fmt18=(v,d=2)=>n18(v).toLocaleString(undefined,{maximumFractionDigits:d});
const kb18=rows=>({inline_keyboard:rows}), cb18=(t,d)=>({text:t,callback_data:d}), web18=(t,u)=>({text:t,web_app:{url:u}}), url18=(t,u)=>({text:t,url:u});
async function st18(){return (await pool.query(`select * from public.app_settings where id=true limit 1`)).rows[0]||{}}
async function u18(id){return (await pool.query(`select * from public.users where telegram_id=$1 limit 1`,[id])).rows[0]||null}
async function adm18(id,perm=null){const a=await isAdmin(id);if(!a)return null;if(perm&&!(a.role==='owner'||a.role==='admin'||a.permissions?.[perm]===true))return null;return a}
function app18(s){return String(s.app_url||'https://wiener-farm.vercel.app').replace(/\/$/,'')}
async function edit18(q,text,markup){try{return await tgV10('editMessageText',{chat_id:q.message.chat.id,message_id:q.message.message_id,text,reply_markup:markup,disable_web_page_preview:true})}catch{return tgV10('sendMessage',{chat_id:q.from.id,text,reply_markup:markup,disable_web_page_preview:true}).catch(()=>null)}}
async function answer18(q,text='Updated',alert=false){return tgV10('answerCallbackQuery',{callback_query_id:q.id,text,show_alert:alert}).catch(()=>null)}

function homeMarkup18(s){const a=app18(s);return kb18([[web18('🌭 OPEN WIENER FARM',a)],[cb18('💰 Balance','ux:balance'),cb18('📊 Profile','ux:profile')],[cb18('🌾 Farm','ux:farm'),cb18('📺 Ads','ux:ads')],[cb18('✅ Tasks','ux:tasks'),cb18('👥 Referrals','ux:refs')],[cb18('🏆 Leaderboard','ux:leaderboard'),cb18('💸 Withdrawals','ux:wallet')],[cb18('🎁 Promos','ux:promos'),cb18('🎉 Giveaways','ux:giveaways')],[cb18('❓ Help','ux:help')]])}
async function userHome18(uid,s){const u=await u18(uid);if(!u)return {text:'🌭 WIENER FARM\n\nOpen the Mini App to create your account.',markup:kb18([[web18('🌭 OPEN WIENER FARM',app18(s))]])};const usd=n18(u.balance)/Math.max(1,n18(s.token_per_usdt||10000));return {text:`🌭 WIENER FARM\n\n💰 ${fmt18(u.balance)} WIENER · ≈ ${usd.toFixed(4)} USDT\n🔥 ${n18(u.daily_streak)} day streak\n📺 ${n18(u.total_ads)} ads completed\n👥 ${n18(u.active_referrals_count)}/${n18(u.referrals_count)} qualified referrals\n\nChoose an option below.`,markup:homeMarkup18(s)}}
async function userView18(uid,key,s){const u=await u18(uid);if(!u)return userHome18(uid,s);const a=app18(s),back=[cb18('◀️ MAIN MENU','ux:home')];
 if(key==='balance'){const q=await pool.query(`select amount,description from public.transactions where telegram_id=$1 order by created_at desc limit 3`,[uid]);const recent=q.rows.map(x=>`${n18(x.amount)>=0?'➕':'➖'} ${fmt18(Math.abs(n18(x.amount)))} WIENER · ${String(x.description||'Transaction').slice(0,34)}`).join('\n')||'No transactions yet.';return{text:`💰 BALANCE\n\nAvailable: ${fmt18(u.balance)} WIENER\n≈ ${(n18(u.balance)/Math.max(1,n18(s.token_per_usdt||10000))).toFixed(4)} USDT\n📈 Total earned: ${fmt18(u.total_earned)} WIENER\n💸 Total withdrawn: ${fmt18(u.total_withdrawn)}\n\nRecent activity\n${recent}`,markup:kb18([[web18('💸 OPEN WALLET',`${a}?page=wallet`)],back])}}
 if(key==='profile'){const t=await pool.query(`select count(*)::int c from public.task_completions where telegram_id=$1`,[uid]);return{text:`📊 PROFILE\n\n${u.first_name||u.username||'WIENER User'}${u.username?` · @${u.username}`:''}\nUID: ${uid}\n\n💰 Balance: ${fmt18(u.balance)} WIENER\n📈 Total earned: ${fmt18(u.total_earned)} WIENER\n📺 Ads: ${n18(u.total_ads)}\n✅ Tasks: ${n18(t.rows[0]?.c)}\n🌾 Farm sessions: ${n18(u.farm_sessions)}\n🔥 Streak: ${n18(u.daily_streak)} · Best ${n18(u.best_streak)}\n👥 Referrals: ${n18(u.referrals_count)}\n✅ Qualified: ${n18(u.active_referrals_count)}`,markup:kb18([[web18('📊 OPEN PROFILE',`${a}?page=profile`)],back])}}
 if(key==='farm'){let status='Idle';if(u.farm_started_at){const ready=new Date(u.farm_started_at).getTime()+n18(s.farm_claim_cooldown_seconds)*1000;status=Date.now()>=ready?'✅ Reward ready':'🌱 Growing'}return{text:`🌾 FARM\n\nStatus: ${status}\nToday: ${n18(u.farm_claims_today)}/5 claims\nSessions: ${n18(u.farm_sessions)}\nReward: ${fmt18(s.farm_claim_reward)} WIENER`,markup:kb18([[web18('🌾 OPEN FARM',`${a}?page=claim`)],back])}}
 if(key==='ads')return{text:`📺 ADS\n\nToday: ${n18(u.ads_watched_today)}/${n18(s.daily_ad_limit)} rewarded ads\nTotal completed: ${n18(u.total_ads)}\nReward: +${fmt18(s.ad_reward)} WIENER per verified ad`,markup:kb18([[web18('📺 WATCH ADS',`${a}?page=ads`)],back])};
 if(key==='tasks'){const [av,dn,list]=await Promise.all([pool.query(`select count(*)::int c from public.tasks where enabled=true`),pool.query(`select count(*)::int c from public.task_completions where telegram_id=$1`,[uid]),pool.query(`select title,reward from public.tasks where enabled=true order by sort_order nulls last,created_at desc limit 3`)]);return{text:`✅ TASKS\n\nAvailable: ${n18(av.rows[0]?.c)}\nCompleted: ${n18(dn.rows[0]?.c)}\n\n${list.rows.map(x=>`• ${x.title} · +${fmt18(x.reward)} WIENER`).join('\n')||'No tasks available.'}`,markup:kb18([[web18('✅ VIEW TASKS',`${a}?page=tasks`)],back])}}
 if(key==='refs'){const bot=String(s.bot_username||'WienerDogeFarmBot').replace('@',''),link=`https://t.me/${bot}?startapp=ref_${uid}`;return{text:`👥 REFERRALS\n\nInvited: ${n18(u.referrals_count)}\nQualified: ${n18(u.active_referrals_count)}\nEarned: ${fmt18(u.referral_earnings)} WIENER\nReward: +${fmt18(s.referral_active_reward)} WIENER per qualified referral\n\nA referral qualifies after ${n18(s.referral_active_ads_required)} verified ads.`,markup:kb18([[url18('📤 SHARE INVITE',`https://t.me/share/url?url=${encodeURIComponent(link)}&text=${encodeURIComponent('Join WIENER Farm and earn rewards with me!')}`)],[web18('👥 OPEN REFERRALS',`${a}?page=invite`)],[cb18('🏆 TOP REFERRALS','lb:inviters')],back])}}
 if(key==='leaderboard')return{text:'🏆 WIENER FARM LEADERBOARD\n\nChoose a ranking:',markup:kb18([[cb18('👥 TOP REFERRALS','lb:inviters'),cb18('💰 TOTAL EARNED','lb:earners')],[web18('🏆 OPEN LEADERBOARD',`${a}?page=leaderboard`)],back])};
 if(key==='wallet'){const q=await pool.query(`select status,receive_usdt,network from public.withdrawals where telegram_id=$1 order by created_at desc limit 3`,[uid]);const rows=q.rows.map(x=>`${x.status==='paid'?'✅':x.status==='rejected'?'❌':'⏳'} ${n18(x.receive_usdt).toFixed(String(x.network).toUpperCase()==='TON'?6:4)} ${String(x.network).toUpperCase()==='TON'?'GRAM':'USDT'} · ${x.network||''}`).join('\n')||'No withdrawals yet.';return{text:`💸 WITHDRAWALS\n\nBalance: ${fmt18(u.balance)} WIENER\nMinimum: ${fmt18(s.minimum_withdraw)} WIENER\nPortal: ${s.withdrawals_enabled?'✅ OPEN':'⏸ PAUSED'}\n\n${rows}`,markup:kb18([[web18('💸 OPEN WALLET',`${a}?page=wallet`)],back])}}
 if(key==='promos'){const q=await pool.query(`select code,reward,reward_type,max_claims,claims_count from public.promo_codes where enabled=true and (expires_at is null or expires_at>now()) order by created_at desc limit 5`);const rows=q.rows.filter(x=>x.max_claims==null||n18(x.claims_count)<n18(x.max_claims)).map(x=>`🎟 ${x.code} · +${fmt18(x.reward)} ${x.reward_type==='wiener'?'WIENER':x.reward_type==='treasury_key'?'Key':'Point'}`).join('\n')||'No active promo codes.';return{text:`🎁 ACTIVE PROMOS\n\n${rows}`,markup:kb18([[web18('🎁 CLAIM PROMO',a)],back])}}
 if(key==='giveaways'){const q=await pool.query(`select * from public.giveaways where giveaway_type='auto' and status in ('open','processing') order by end_at asc limit 1`),g=q.rows[0];if(!g)return{text:'🎉 GIVEAWAYS\n\nNo active giveaway right now.',markup:kb18([[url18('📢 WIENER FARM','https://t.me/WienerFarm')],back])};return{text:`🎉 ACTIVE GIVEAWAY\n\n🎁 Prize: ${fmt18(g.prize_input||g.total_amount)} WIENER\n🏆 Winners: ${n18(g.winners_count||g.winner_count)}\n📋 Requirement: ${g.requirement_type==='ads'?`Complete ${n18(g.requirement_value)} ads`:String(g.requirement_type||'Participate')}\n⏰ Ends: ${new Date(g.end_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}`,markup:kb18([[url18('🎉 PARTICIPATE',`https://t.me/WienerDogeFarmBot?start=${g.public_code}`)],back])}}
 return{text:'❓ WIENER HELP\n\n/menu — Main menu\n/balance — Balance\n/profile — Profile\n/farm — Farm status\n/ads — Ads status\n/tasks — Tasks\n/referral — Referrals\n/leaderboard — Rankings\n/withdraw — Wallet\n/promo — Promos\n/giveaway — Giveaway\n/help — Help',markup:kb18([[web18('🌭 OPEN WIENER FARM',a)],[url18('💬 SUPPORT',String(s.support_url||'https://t.me/WienerSupport'))],back])}}

async function lb18(uid,mode){let x;try{x=await rpc('get_wiener_invite_leaderboards',[uid])}catch{x={}}const rows=(x?.[mode]||[]).slice(0,10),me=x?.me?.[mode],med=['🥇','🥈','🥉'];const unit=v=>mode==='inviters'?`${fmt18(v)} referrals`:`${fmt18(v)} WIENER`;const name=r=>[r.first_name,r.last_name].filter(Boolean).join(' ').trim()||(r.username?'@'+r.username:`User ${String(r.telegram_id).slice(-4)}`);return `🏆 WIENER FARM LEADERBOARD\n\n${mode==='inviters'?'👥 TOP REFERRALS':'💰 TOTAL EARNED'}\n\n${rows.map((r,i)=>`${med[i]||`${i+1}.`} ${name(r)}\n   ${unit(r.value)}`).join('\n')||'No rankings yet.'}\n\n👤 Your rank: ${me?.rank?`#${me.rank}`:'Unranked'} · ${unit(me?.value||0)}`}

function adminHomeMarkup18(s){return kb18([[cb18('👤 USERS','adm:users'),cb18('🛡 FRAUD','adm:fraud')],[cb18('💸 WITHDRAWALS','adm:wd'),cb18('👥 REFERRALS','adm:refs')],[cb18('📺 ADS','adm:ads'),cb18('✅ TASKS','adm:tasks')],[cb18('🎁 PROMOS','adm:promos'),cb18('🎉 GIVEAWAYS','adm:gives')],[cb18('📢 BROADCAST','adm:broadcast'),cb18('⚙️ SYSTEM','adm:system')],[cb18('📜 AUDIT','adm:audit'),cb18('👮 ADMINS','adm:admins')],[cb18('💸 PAY CENTER','v10pay:home')],[web18('🖥 FULL ADMIN',`${app18(s)}?page=admin`)]])}
async function adminView18(key,s){if(key==='home'){const [u,a,nw,p,hold,rest]=await Promise.all([pool.query(`select count(*)::int c from public.users`),pool.query(`select count(*)::int c from public.users where last_active>=now()-interval '24 hours'`),pool.query(`select count(*)::int c from public.users where created_at>=now()-interval '24 hours'`),pool.query(`select count(*)::int c,coalesce(sum(receive_usdt),0) v from public.withdrawals where status='pending'`),pool.query(`select count(*)::int c from public.user_risk_profiles where enforcement_state='reward_hold'`),pool.query(`select count(*)::int c from public.user_risk_profiles where enforcement_state='restricted'`)]);return{text:`🛡 WIENER FARM ADMIN\n\n👥 Users: ${n18(u.rows[0]?.c)}\n🟢 Active 24h: ${n18(a.rows[0]?.c)}\n🆕 New 24h: ${n18(nw.rows[0]?.c)}\n💸 Pending WD: ${n18(p.rows[0]?.c)} · ${n18(p.rows[0]?.v).toFixed(4)}\n🟠 Reward hold: ${n18(hold.rows[0]?.c)}\n🚫 Restricted: ${n18(rest.rows[0]?.c)}\n\nChoose a control center.`,markup:adminHomeMarkup18(s)}}
 if(key==='users'){const q=await pool.query(`select telegram_id,username,first_name,balance,is_banned from public.users order by last_active desc nulls last limit 8`);return{text:`👤 USERS · RECENT\n\n${q.rows.map(u=>`${u.is_banned?'🚫':'🟢'} ${u.username?'@'+u.username:u.first_name||'User'} · ${u.telegram_id}\n   ${fmt18(u.balance)} WIENER`).join('\n')||'No users'}\n\nSearch: /user <UID or @username>`,markup:kb18([[cb18('🔄 REFRESH','adm:users')],[cb18('◀️ HOME','adm:home')]])}}
 if(key==='fraud'){const q=await pool.query(`select telegram_id,risk_score,enforcement_state from public.user_risk_profiles order by risk_score desc limit 10`);return{text:`🛡 FRAUD & RISK\n\n${q.rows.map(r=>`${n18(r.risk_score)>=80?'🚨':n18(r.risk_score)>=60?'🔴':n18(r.risk_score)>=25?'🟡':'🟢'} UID ${r.telegram_id} · ${n18(r.risk_score)}/100\n   ${r.enforcement_state}`).join('\n')||'No risk profiles'}`,markup:kb18([[cb18('🔄 REFRESH','adm:fraud')],[cb18('◀️ HOME','adm:home')]])}}
 if(key==='wd'){const q=await pool.query(`select telegram_id,username,receive_usdt,network from public.withdrawals where status='pending' order by created_at limit 8`);return{text:`💸 PENDING WITHDRAWALS\n\n${q.rows.map(w=>`🟡 ${w.username?'@'+w.username:'UID '+w.telegram_id}\n   ${n18(w.receive_usdt).toFixed(4)} · ${w.network}`).join('\n')||'✅ No pending withdrawals'}`,markup:kb18([[cb18('💸 OPEN PAY CENTER','v10pay:home')],[cb18('🔄 REFRESH','adm:wd'),cb18('◀️ HOME','adm:home')]])}}
 if(key==='refs'){const q=await pool.query(`select telegram_id,username,first_name,referrals_count,active_referrals_count,referral_earnings from public.users where referrals_count>0 order by referrals_count desc limit 8`);return{text:`👥 REFERRAL CONTROL\n\n${q.rows.map(u=>`${u.username?'@'+u.username:u.first_name||'User'} · ${u.telegram_id}\n   ${n18(u.active_referrals_count)}/${n18(u.referrals_count)} qualified · ${fmt18(u.referral_earnings)} WIENER`).join('\n')||'No referral activity'}`,markup:kb18([[cb18('◀️ HOME','adm:home')]])}}
 if(key==='ads'){const q=await pool.query(`select count(*)::int c from public.ad_sessions where started_at>=date_trunc('day',now())`);return{text:`📺 ADS · TODAY\n\nAdsGram/server sessions: ${n18(q.rows[0]?.c)}\n\nOpen full admin for detailed ad controls.`,markup:kb18([[web18('📺 OPEN AD CONTROLS',`${app18(s)}?page=admin`)],[cb18('◀️ HOME','adm:home')]])}}
 if(key==='tasks'){const q=await pool.query(`select title,reward,enabled,category from public.tasks order by created_at desc limit 8`);return{text:`✅ TASK MANAGER\n\n${q.rows.map(t=>`${t.enabled?'🟢':'⏸'} ${t.title}\n   +${fmt18(t.reward)} WIENER · ${t.category||'official'}`).join('\n')||'No tasks'}`,markup:kb18([[web18('✅ FULL TASK MANAGER',`${app18(s)}?page=admin`)],[cb18('◀️ HOME','adm:home')]])}}
 if(key==='promos'){const q=await pool.query(`select code,reward,claims_count,max_claims,enabled from public.promo_codes order by created_at desc limit 8`);return{text:`🎁 PROMOS\n\n${q.rows.map(p=>`${p.enabled?'🟢':'⏸'} ${p.code} · +${fmt18(p.reward)}\n   ${n18(p.claims_count)}/${p.max_claims??'∞'} claims`).join('\n')||'No promos'}`,markup:kb18([[web18('🎁 MANAGE PROMOS',`${app18(s)}?page=admin`)],[cb18('◀️ HOME','adm:home')]])}}
 if(key==='gives'){const q=await pool.query(`select public_code,status,coalesce(prize_input,total_amount,0) amount,coalesce(winners_count,winner_count,0) winners from public.giveaways order by created_at desc limit 6`);return{text:`🎉 GIVEAWAYS\n\n${q.rows.map(g=>`${g.status==='open'?'🟢':'⚪'} ${g.public_code||'Giveaway'}\n   ${fmt18(g.amount)} WIENER · ${n18(g.winners)} winner(s) · ${g.status}`).join('\n')||'No giveaways'}`,markup:kb18([[cb18('◀️ HOME','adm:home')]])}}
 if(key==='broadcast')return{text:'📢 BROADCAST STUDIO\n\nQuick: /notify <message>\nGuided: /broadcast\n\nDelivery is tracked on VPS.',markup:kb18([[cb18('◀️ HOME','adm:home')]])};
 if(key==='system')return{text:`⚙️ SYSTEM CONTROL\n\n🛠 Maintenance: ${s.maintenance_enabled?'ON':'OFF'}\n💸 Withdrawals: ${s.withdrawals_enabled?'ON':'OFF'}\n📺 Ads: ${s.ads_enabled?'ON':'OFF'}\n✅ Tasks: ${s.tasks_enabled?'ON':'OFF'}\n👥 Referrals: ${s.referrals_enabled?'ON':'OFF'}\n🎁 Promo: ${s.promo_enabled?'ON':'OFF'}`,markup:kb18([[cb18(`🛠 Maintenance ${s.maintenance_enabled?'OFF':'ON'}`,'adm:t:maintenance_enabled'),cb18(`💸 Withdraw ${s.withdrawals_enabled?'OFF':'ON'}`,'adm:t:withdrawals_enabled')],[cb18(`📺 Ads ${s.ads_enabled?'OFF':'ON'}`,'adm:t:ads_enabled'),cb18(`✅ Tasks ${s.tasks_enabled?'OFF':'ON'}`,'adm:t:tasks_enabled')],[cb18(`👥 Referral ${s.referrals_enabled?'OFF':'ON'}`,'adm:t:referrals_enabled'),cb18(`🎁 Promo ${s.promo_enabled?'OFF':'ON'}`,'adm:t:promo_enabled')],[cb18('◀️ HOME','adm:home')]])};
 if(key==='audit'){const q=await pool.query(`select admin_id,action,target_telegram_id from public.bot_admin_audit order by created_at desc limit 10`).catch(()=>({rows:[]}));return{text:`📜 RECENT ADMIN AUDIT\n\n${q.rows.map(a=>`• ${a.action}${a.target_telegram_id?' · UID '+a.target_telegram_id:''}\n  by ${a.admin_id}`).join('\n')||'No audit entries'}`,markup:kb18([[cb18('◀️ HOME','adm:home')]])}}
 if(key==='admins'){const q=await pool.query(`select telegram_id,role,enabled from public.admins order by created_at`);return{text:`👮 ADMINS\n\n${q.rows.map(a=>`${a.enabled?'🟢':'⏸'} ${a.telegram_id} · ${a.role}`).join('\n')||'No admins'}`,markup:kb18([[web18('👮 FULL ADMIN MANAGEMENT',`${app18(s)}?page=admin`)],[cb18('◀️ HOME','adm:home')]])}}
 return adminView18('home',s)}

async function userInspector18(query){let u;if(/^\d{5,20}$/.test(query))u=(await pool.query(`select * from public.users where telegram_id=$1`,[Number(query)])).rows[0];else u=(await pool.query(`select * from public.users where lower(username)=lower($1) limit 1`,[query.replace(/^@/,'')])).rows[0];if(!u)return null;const r=(await pool.query(`select * from public.user_risk_profiles where telegram_id=$1`,[u.telegram_id])).rows[0]||{};const p=(await pool.query(`select coalesce(sum(receive_usdt),0) v from public.withdrawals where telegram_id=$1 and status='pending'`,[u.telegram_id])).rows[0];return{text:`👤 USER INTELLIGENCE\n\n${u.first_name||'Telegram User'}${u.username?' · @'+u.username:''}\nUID: ${u.telegram_id}\n\n💰 Balance: ${fmt18(u.balance)} WIENER\n📈 Total earned: ${fmt18(u.total_earned)} WIENER\n👥 Referrals: ${n18(u.active_referrals_count)}/${n18(u.referrals_count)} qualified\n📺 Ads: ${n18(u.total_ads)}\n🌾 Farms: ${n18(u.farm_sessions)}\n💸 Pending payout: ${n18(p?.v).toFixed(4)}\n\n🛡 Risk: ${n18(r.risk_score)}/100 · ${r.enforcement_state||'normal'}\n🚫 App ban: ${u.is_banned?'YES':'NO'}\n📱 Device blocked: ${u.device_blocked?'YES':'NO'}`,markup:kb18([[cb18(u.is_banned?'🔓 UNBAN':'🚫 BAN',`${u.is_banned?'unban':'ban'}:${u.telegram_id}`)],[web18('🖥 OPEN FULL USER',`${app18(await st18())}?page=admin&user=${u.telegram_id}`)],[cb18('◀️ ADMIN HOME','adm:home')]])}}

async function handleBroadcast18(up,uid,text,m,q){if(q&&String(q.data||'').startsWith('bc18:')){if(!await adm18(uid))return false;const [,act]=String(q.data).split(':');if(act==='cancel'){await pool.query(`delete from public.admin_broadcast_sessions where admin_id=$1`,[uid]).catch(()=>null);await edit18(q,'❌ Broadcast cancelled.',kb18([]));await answer18(q,'Cancelled');return true}if(act==='send'){const ss=(await pool.query(`select * from public.admin_broadcast_sessions where admin_id=$1`,[uid])).rows[0];if(!ss?.draft_message){await answer18(q,'Session expired',true);return true}await answer18(q,'Broadcast started');await edit18(q,'📤 Broadcast started. Delivery is tracked by VPS.',kb18([]));const r=await postLocalV10B('wiener-notify',{admin_id:uid,text:ss.draft_message});await pool.query(`delete from public.admin_broadcast_sessions where admin_id=$1`,[uid]).catch(()=>null);await tgV10('sendMessage',{chat_id:uid,text:`✅ BROADCAST COMPLETED\n\n👤 Users: ${r.users_sent||0}\n💬 Groups/Channels: ${r.chats_sent||0}\n❌ Failed: ${r.failed||0}`});return true}}
 if(m?.chat?.type==='private'&&/^\/broadcast(?:@\w+)?$/i.test(text)){if(!await adm18(uid)){await tgV10('sendMessage',{chat_id:uid,text:'⛔ Admin permission required.'});return true}await pool.query(`insert into public.admin_broadcast_sessions(admin_id,step,draft_message,updated_at) values($1,'awaiting_message',null,now()) on conflict(admin_id) do update set step='awaiting_message',draft_message=null,updated_at=now()`,[uid]).catch(()=>null);await tgV10('sendMessage',{chat_id:uid,text:'📣 BROADCAST CENTER\n\nSend the message to broadcast.\n/cancel to exit.'});return true}
 if(m?.chat?.type==='private'&&!text.startsWith('/')){const ss=(await pool.query(`select * from public.admin_broadcast_sessions where admin_id=$1`,[uid]).catch(()=>({rows:[]}))).rows[0];if(ss?.step==='awaiting_message'){await pool.query(`update public.admin_broadcast_sessions set step='preview',draft_message=$2,updated_at=now() where admin_id=$1`,[uid,text]);await tgV10('sendMessage',{chat_id:uid,text:`📣 BROADCAST PREVIEW\n\n${text}\n\nNothing sent yet.`,reply_markup:kb18([[cb18('✅ SEND NOW','bc18:send')],[cb18('❌ CANCEL','bc18:cancel')]])});return true}}
 return false}

async function syncBot18(uid){if(!await adm18(uid))throw new Error('admin_required');const s=await st18(),secret=String(s.telegram_webhook_secret||''),webhook='https://api.viralaitools.xyz/functions/v1/wiener-bot-webhook';await tgV10('setWebhook',{url:webhook,secret_token:secret,allowed_updates:['message','callback_query','my_chat_member'],drop_pending_updates:false});await tgV10('setMyCommands',{commands:[{command:'start',description:'Open WIENER dashboard'},{command:'menu',description:'Main menu'},{command:'balance',description:'Check WIENER balance'},{command:'farm',description:'Farm status'},{command:'ads',description:'Ads status'},{command:'tasks',description:'Available tasks'},{command:'referral',description:'Referral stats'},{command:'withdraw',description:'Open wallet'},{command:'profile',description:'Account profile'},{command:'leaderboard',description:'WIENER rankings'},{command:'support',description:'Support'},{command:'help',description:'Help and commands'}]});await tgV10('setChatMenuButton',{menu_button:{type:'web_app',text:'🌭 OPEN WIENER FARM',web_app:{url:app18(s)}}});return true}

async function handleBotParityV18(up,uid,text,m,q){
 if(!uid)return false;
 if(await handleBroadcast18(up,uid,text,m,q))return true;
 const s=await st18();
 if(q&&String(q.data||'').startsWith('ux:')){const key=String(q.data).slice(3),x=key==='home'?await userHome18(uid,s):await userView18(uid,key,s);await edit18(q,x.text,x.markup);await answer18(q);return true}
 if(q&&/^lb:(inviters|earners)$/.test(String(q.data||''))){const mode=String(q.data).endsWith('earners')?'earners':'inviters',txt=await lb18(uid,mode);await edit18(q,txt,kb18([[cb18('👥 REFERRALS','lb:inviters'),cb18('💰 EARNED','lb:earners')],[cb18('◀️ MAIN MENU','ux:home')]]));await answer18(q);return true}
 if(q&&String(q.data||'').startsWith('adm:')){if(!await adm18(uid)){await answer18(q,'Admin permission required',true);return true}const p=String(q.data).split(':');if(p[1]==='t'){const key=p[2];if(!['maintenance_enabled','withdrawals_enabled','ads_enabled','tasks_enabled','referrals_enabled','promo_enabled'].includes(key)){await answer18(q,'Invalid setting',true);return true}const cur=!!s[key];await pool.query(`update public.app_settings set ${key}=$1,updated_at=now() where id=true`,[!cur]);const ns=await st18(),x=await adminView18('system',ns);await edit18(q,x.text,x.markup);await answer18(q,!cur?'Enabled':'Disabled');return true}const x=await adminView18(p[1]||'home',s);await edit18(q,x.text,x.markup);await answer18(q);return true}
 if(q&&(String(q.data||'').startsWith('ban:')||String(q.data||'').startsWith('unban:'))){if(!await adm18(uid)){await answer18(q,'Admin required',true);return true}const ban=String(q.data).startsWith('ban:'),target=n18(String(q.data).split(':')[1]);if(ban)await pool.query(`update public.users set is_banned=true,ban_reason='Admin action' where telegram_id=$1`,[target]);else{await pool.query(`update public.users set is_banned=false,ban_reason=null,device_blocked=false,device_blocked_reason=null where telegram_id=$1`,[target]);await rpc('admin_unban_device_user',[uid,target]).catch(()=>null)}const x=await userInspector18(String(target));if(x)await edit18(q,x.text,x.markup);await answer18(q,ban?'User banned':'User fully unbanned');return true}
 if(m?.chat?.type!=='private'||!text.startsWith('/'))return false;
 const parts=text.split(/\s+/),cmd=parts[0].replace(/^\//,'').split('@')[0].toLowerCase();
 const map={menu:'home',balance:'balance',profile:'profile',farm:'farm',ads:'ads',tasks:'tasks',referral:'refs',invite:'refs',withdraw:'wallet',wallet:'wallet',promo:'promos',giveaway:'giveaways',help:'help',support:'help'};
 if(map[cmd]){const x=map[cmd]==='home'?await userHome18(uid,s):await userView18(uid,map[cmd],s);await tgV10('sendMessage',{chat_id:uid,text:x.text,reply_markup:x.markup,disable_web_page_preview:true});return true}
 if(cmd==='leaderboard'){const txt=await lb18(uid,'inviters');await tgV10('sendMessage',{chat_id:uid,text:txt,reply_markup:kb18([[cb18('👥 REFERRALS','lb:inviters'),cb18('💰 EARNED','lb:earners')]])});return true}
 if(cmd==='admin'){if(!await adm18(uid)){await tgV10('sendMessage',{chat_id:uid,text:'⛔ Admin permission required.'});return true}const x=await adminView18('home',s);await tgV10('sendMessage',{chat_id:uid,text:x.text,reply_markup:x.markup});return true}
 if(cmd==='user'){if(!await adm18(uid)){await tgV10('sendMessage',{chat_id:uid,text:'⛔ Admin permission required.'});return true}const query=parts[1]||'';if(!query){await tgV10('sendMessage',{chat_id:uid,text:'Usage: /user <UID or @username>'});return true}const x=await userInspector18(query);await tgV10('sendMessage',{chat_id:uid,text:x?.text||'❌ User not found.',reply_markup:x?.markup});return true}
 if(cmd==='addbalance'||cmd==='removebalance'){if(!await adm18(uid)){await tgV10('sendMessage',{chat_id:uid,text:'⛔ Admin permission required.'});return true}const target=n18(parts[1]),amt=Math.abs(n18(parts[2])),reason=parts.slice(3).join(' ')||`Bot ${cmd}`;if(!target||!amt){await tgV10('sendMessage',{chat_id:uid,text:`Usage: /${cmd} <UID> <amount> [reason]`});return true}const val=cmd==='removebalance'?-amt:amt;try{await rpc('admin_adjust_balance',[uid,target,val,reason])}catch{await pool.query(`update public.users set balance=greatest(0,balance+$2),total_earned=case when $2>0 then total_earned+$2 else total_earned end where telegram_id=$1`,[target,val]);await pool.query(`insert into public.transactions(telegram_id,amount,kind,description,metadata) values($1,$2,'admin_adjustment',$3,$4::jsonb)`,[target,val,reason,JSON.stringify({admin_id:uid})]).catch(()=>null)}await tgV10('sendMessage',{chat_id:uid,text:`✅ Balance Updated\n\nUID: ${target}\nChange: ${val>0?'+':''}${fmt18(val)} WIENER\nReason: ${reason}`});return true}
 if(cmd==='ban'||cmd==='unban'){if(!await adm18(uid)){await tgV10('sendMessage',{chat_id:uid,text:'⛔ Admin permission required.'});return true}const target=n18(parts[1]);if(!target){await tgV10('sendMessage',{chat_id:uid,text:`Usage: /${cmd} <UID>`});return true}if(cmd==='ban')await pool.query(`update public.users set is_banned=true,ban_reason=$2 where telegram_id=$1`,[target,parts.slice(2).join(' ')||'Admin action']);else{await pool.query(`update public.users set is_banned=false,ban_reason=null,device_blocked=false,device_blocked_reason=null where telegram_id=$1`,[target]);await rpc('admin_unban_device_user',[uid,target]).catch(()=>null)}await tgV10('sendMessage',{chat_id:uid,text:cmd==='ban'?`🚫 User Banned\nUID: ${target}`:`✅ User Fully Unbanned\nUID: ${target}`});return true}
 if(cmd==='botsync'||cmd==='syncbot'){try{await syncBot18(uid);await tgV10('sendMessage',{chat_id:uid,text:'✅ Bot webhook, command menu and Mini App menu synchronized.'})}catch(e){await tgV10('sendMessage',{chat_id:uid,text:`❌ ${String(e.message||e)}`})}return true}
 return false;
}
'''

s=s.replace(marker,'\n'+code+marker,1)
p.write_text(s)
print('V18 bot handler parity installed')
