#!/usr/bin/env python3
from pathlib import Path

p=Path('/opt/wiener-backend/server.mjs')
if not p.exists():
    alt=Path('/opt/wiener-backend/server.js')
    if alt.exists(): p=alt
if not p.exists(): raise SystemExit('ERROR: Wiener backend server file not found')
s=p.read_text()
TAG='WIENER GIVEAWAY STUDIO V89'
if TAG in s:
    print('V89 giveaway studio already installed')
    raise SystemExit(0)
for need in ['async function handleBotFullV18','async function adm18','const kb18=','const cb18=','const web18=','async function st18','async function tgV10']:
    if need not in s: raise SystemExit('ERROR: required bot anchor missing: '+need)
anchor='async function handleBotFullV18(up,uid,text,m,q){'
if anchor not in s: raise SystemExit('ERROR: V18 bot handler anchor missing')
code=r'''

// === WIENER GIVEAWAY STUDIO V89 ===
const gw89n=v=>Number(v||0);
const gw89fmt=v=>gw89n(v).toLocaleString(undefined,{maximumFractionDigits:4});
const gw89esc=s=>String(s??'').replace(/[<>]/g,'');
const gw89now=()=>new Date();

async function gw89session(uid){return (await pool.query(`select * from public.giveaway_admin_sessions where admin_id=$1 limit 1`,[uid])).rows[0]||null}
async function gw89setSession(uid,step,data={}){await pool.query(`insert into public.giveaway_admin_sessions(admin_id,step,data,updated_at) values($1,$2,$3::jsonb,now()) on conflict(admin_id) do update set step=excluded.step,data=excluded.data,updated_at=now()`,[uid,step,JSON.stringify(data)]);return {step,data}}
async function gw89clearSession(uid){await pool.query(`delete from public.giveaway_admin_sessions where admin_id=$1`,[uid])}
function gw89Back(){return cb18('◀️ BACK','gw89:home')}
function gw89StudioMarkup(){return kb18([[cb18('➕ CREATE GIVEAWAY','gw89:create')],[cb18('🟢 LIVE','gw89:list:live'),cb18('🕓 SCHEDULED','gw89:list:scheduled')],[cb18('📊 ANALYTICS','gw89:analytics'),cb18('📁 HISTORY','gw89:list:done')]])}
async function gw89Studio(uid){const a=await adm18(uid);if(!a)return null;const q=(await pool.query(`select count(*) filter(where status='live')::int live,count(*) filter(where status='scheduled')::int scheduled,count(*) filter(where status='completed')::int completed from public.giveaway_campaigns`)).rows[0]||{};return{text:`🎁 GIVEAWAY STUDIO\n\nCreate and automate Wiener Farm giveaways.\n\n🟢 Live: ${q.live||0}\n🕓 Scheduled: ${q.scheduled||0}\n✅ Finished: ${q.completed||0}`,markup:gw89StudioMarkup()}}
function gw89GoalMarkup(){return kb18([[cb18('📺 AD ACTIVITY','gw89:goal:ads'),cb18('👥 REFERRALS','gw89:goal:referrals')],[cb18('🎯 TASKS','gw89:goal:tasks'),cb18('📢 COMMUNITY','gw89:goal:community')],[cb18('🔥 DAILY ACTIVITY','gw89:goal:daily'),cb18('🎟 CUSTOM','gw89:goal:custom')],[gw89Back()]])}
function gw89ModeMarkup(){return kb18([[cb18('🎲 SIMPLE DRAW','gw89:mode:simple')],[cb18('🎟 TICKET DRAW','gw89:mode:ticket')],[cb18('🏆 RANKING','gw89:mode:ranking')],[gw89Back()]])}
function gw89AssetMarkup(){return kb18([[cb18('🌭 WIENER','gw89:asset:wiener'),cb18('💎 TON','gw89:asset:ton')],[cb18('💵 USDT','gw89:asset:usdt'),cb18('🎁 CUSTOM','gw89:asset:custom')],[gw89Back()]])}
function gw89Preset(goal){
 if(goal==='ads')return {requirements:{ads:5},ticket_rules:{ads_every:5,daily_push:2,valid_referral:3}};
 if(goal==='referrals')return {requirements:{valid_referrals:1},ticket_rules:{valid_referral:2,ads_every:10}};
 if(goal==='tasks')return {requirements:{tasks:2},ticket_rules:{tasks_every:2,daily_push:1}};
 if(goal==='community')return {requirements:{mandatory_join:true},ticket_rules:{ads_every:5,valid_referral:2}};
 if(goal==='daily')return {requirements:{daily_push:true},ticket_rules:{ads_every:5,daily_push:2}};
 return {requirements:{},ticket_rules:{}};
}
function gw89Summary(d){const r=d.requirements||{},t=d.ticket_rules||{};const req=[];if(r.ads)req.push(`📺 ${r.ads} valid ads`);if(r.tasks)req.push(`🎯 ${r.tasks} tasks`);if(r.valid_referrals)req.push(`👥 ${r.valid_referrals} valid referral${r.valid_referrals>1?'s':''}`);if(r.daily_push)req.push('🔥 Complete Daily Push');if(r.mandatory_join)req.push('📢 Required community joined');if(!req.length)req.push('✅ No extra requirement');const bonus=[];if(t.ads_every)bonus.push(`+1 ticket / ${t.ads_every} ads`);if(t.valid_referral)bonus.push(`+${t.valid_referral} / valid referral`);if(t.daily_push)bonus.push(`+${t.daily_push} / Daily Push`);if(t.tasks_every)bonus.push(`+1 / ${t.tasks_every} tasks`);return `Required\n${req.join('\n')}\n\nBonus tickets\n${bonus.length?bonus.join('\n'):'None'}`}
async function gw89DraftCard(uid){const ss=await gw89session(uid);if(!ss)return gw89Studio(uid);const d=ss.data||{};return{text:`🎁 GIVEAWAY DRAFT\n\nGoal: ${String(d.goal||'—').toUpperCase()}\nMode: ${String(d.mode||'—').toUpperCase()}\nPrize: ${gw89fmt(d.prize_amount)} ${String(d.asset||'—').toUpperCase()}\nWinners: ${d.winners||'—'}\nDuration: ${d.duration_hours?d.duration_hours+'h':'—'}\n\n${gw89Summary(d)}`,markup:kb18([[cb18('⚙️ REQUIREMENTS','gw89:req')],[cb18('🎟 BONUS TICKETS','gw89:tickets')],[cb18('📣 PUBLISH SETTINGS','gw89:publish')],[cb18('✅ CREATE & START','gw89:confirm')],[cb18('🗑 CANCEL','gw89:cancel')]])}}
function gw89ReqMarkup(d){const r=d.requirements||{};const on=(k,t)=>cb18(`${r[k]?'✅':'⬜'} ${t}`,`gw89:reqtoggle:${k}`);return kb18([[on('mandatory_join','Required Join')],[cb18(`📺 Min Ads: ${r.ads||0}`,'gw89:reqnum:ads'),cb18(`🎯 Min Tasks: ${r.tasks||0}`,'gw89:reqnum:tasks')],[cb18(`👥 Min Referrals: ${r.valid_referrals||0}`,'gw89:reqnum:valid_referrals')],[on('daily_push','Daily Push Required')],[cb18('✅ DONE','gw89:draft')]])}
function gw89TicketMarkup(d){const t=d.ticket_rules||{};return kb18([[cb18(`📺 Ads / ticket: ${t.ads_every||0}`,'gw89:ticketnum:ads_every')],[cb18(`👥 Referral tickets: +${t.valid_referral||0}`,'gw89:ticketnum:valid_referral')],[cb18(`🔥 Daily Push: +${t.daily_push||0}`,'gw89:ticketnum:daily_push')],[cb18(`🎯 Tasks / ticket: ${t.tasks_every||0}`,'gw89:ticketnum:tasks_every')],[cb18('✅ DONE','gw89:draft')]])}
async function gw89GenerateCode(){for(let i=0;i<20;i++){const c='GW'+Math.random().toString(36).slice(2,8).toUpperCase();const x=(await pool.query(`select 1 from public.giveaway_campaigns where public_code=$1`,[c])).rowCount;if(!x)return c}throw new Error('giveaway_code_failed')}
async function gw89Create(uid,d){const code=await gw89GenerateCode(),start=new Date(),end=new Date(Date.now()+Math.max(1,gw89n(d.duration_hours))*3600000);const dist=[];const n=Math.max(1,Math.min(100,gw89n(d.winners)||1)),total=gw89n(d.prize_amount);for(let i=0;i<n;i++)dist.push(total/n);const q=await pool.query(`insert into public.giveaway_campaigns(public_code,title,goal,mode,asset,prize_pool,winners_count,distribution,requirements,ticket_rules,status,start_at,end_at,created_by,publish_channel,auto_announce,auto_reward,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10::jsonb,'live',$11,$12,$13,$14,true,true,now(),now()) returning *`,[code,d.title||`${gw89fmt(total)} ${String(d.asset||'wiener').toUpperCase()} Giveaway`,d.goal||'custom',d.mode||'ticket',d.asset||'wiener',total,n,JSON.stringify(dist),JSON.stringify(d.requirements||{}),JSON.stringify(d.ticket_rules||{}),start,end,uid,d.publish_channel||'@WienerFarm']);await pool.query(`insert into public.giveaway_audit(giveaway_id,actor_id,event,data) values($1,$2,'created',$3::jsonb)`,[q.rows[0].id,uid,JSON.stringify({draft:d})]);return q.rows[0]}
async function gw89StatsForUser(uid,g){const r=g.requirements||{};let ads=0,tasks=0,refs=0,daily=false,joined=true;try{ads=gw89n((await pool.query(`select count(*)::int c from public.ad_sessions where telegram_id=$1 and status='credited' and completed_at between $2 and $3`,[uid,g.start_at,g.end_at])).rows[0]?.c)}catch{try{ads=gw89n((await pool.query(`select count(*)::int c from public.wiener_ad_league_events where telegram_id=$1 and created_at between $2 and $3`,[uid,g.start_at,g.end_at])).rows[0]?.c)}catch{}}
 try{tasks=gw89n((await pool.query(`select count(*)::int c from public.task_completions where telegram_id=$1 and created_at between $2 and $3`,[uid,g.start_at,g.end_at])).rows[0]?.c)}catch{}
 try{refs=gw89n((await pool.query(`select count(*)::int c from public.users where referred_by=$1 and created_at between $2 and $3 and coalesce(total_ads,0)>=5`,[uid,g.start_at,g.end_at])).rows[0]?.c)}catch{}
 try{daily=gw89n((await pool.query(`select count(*)::int c from public.wiener_ad_league_events where telegram_id=$1 and event_day=(now() at time zone 'utc')::date`,[uid])).rows[0]?.c)>=10}catch{}
 if(r.mandatory_join){try{const x=(await pool.query(`select count(*)::int c from public.mandatory_channels mc where mc.enabled=true and not exists(select 1 from public.channel_memberships cm where cm.telegram_id=$1 and cm.channel_id=mc.id and cm.is_member=true)`,[uid])).rows[0]?.c;joined=gw89n(x)===0}catch{joined=true}}
 const ok=(!r.ads||ads>=gw89n(r.ads))&&(!r.tasks||tasks>=gw89n(r.tasks))&&(!r.valid_referrals||refs>=gw89n(r.valid_referrals))&&(!r.daily_push||daily)&&(!r.mandatory_join||joined);return {ads,tasks,refs,daily,joined,ok}}
function gw89Tickets(g,x){if(g.mode!=='ticket')return 1;const t=g.ticket_rules||{};let n=1;if(t.ads_every)n+=Math.floor(x.ads/gw89n(t.ads_every));if(t.valid_referral)n+=x.refs*gw89n(t.valid_referral);if(t.daily_push&&x.daily)n+=gw89n(t.daily_push);if(t.tasks_every)n+=Math.floor(x.tasks/gw89n(t.tasks_every));return Math.max(1,Math.min(10000,n))}
async function gw89Current(){return (await pool.query(`select * from public.giveaway_campaigns where status='live' and start_at<=now() and end_at>now() order by end_at asc limit 1`)).rows[0]||null}
async function gw89UserCard(uid,g){if(!g)g=await gw89Current();if(!g)return{text:'🎁 GIVEAWAY\n\nNo active giveaway right now.',markup:kb18([[url18('📢 WIENER FARM','https://t.me/WienerFarm')]])};const x=await gw89StatsForUser(uid,g),entry=(await pool.query(`select * from public.giveaway_entries where giveaway_id=$1 and telegram_id=$2`,[g.id,uid])).rows[0];const tickets=entry?gw89Tickets(g,x):0;const left=Math.max(0,new Date(g.end_at).getTime()-Date.now()),h=Math.floor(left/3600000),m=Math.floor((left%3600000)/60000);return{text:`🎁 ${gw89esc(g.title)}\n\n🏆 ${g.winners_count} winner${g.winners_count>1?'s':''}\n🎁 ${gw89fmt(g.prize_pool)} ${String(g.asset).toUpperCase()}\n⏳ ${h}h ${m}m left\n\n${entry?`🎟 Entry confirmed · ${tickets} ticket${tickets===1?'':'s'}`:x.ok?'✅ You are eligible to enter.':'🔒 Complete the requirements first.'}`,markup:kb18([[cb18(entry?'🔄 REFRESH ENTRY':'🎟 PARTICIPATE',`gw89:user:${g.id}`)],[cb18('📋 REQUIREMENTS',`gw89:userreq:${g.id}`)]])}}
async function gw89Participate(uid,g){const x=await gw89StatsForUser(uid,g);if(!x.ok){const r=g.requirements||{},miss=[];if(r.ads&&x.ads<r.ads)miss.push(`📺 Ads ${x.ads}/${r.ads}`);if(r.tasks&&x.tasks<r.tasks)miss.push(`🎯 Tasks ${x.tasks}/${r.tasks}`);if(r.valid_referrals&&x.refs<r.valid_referrals)miss.push(`👥 Referrals ${x.refs}/${r.valid_referrals}`);if(r.daily_push&&!x.daily)miss.push('🔥 Daily Push incomplete');if(r.mandatory_join&&!x.joined)miss.push('📢 Required community not joined');return {text:`🔐 COMPLETE ${miss.length} MORE STEP${miss.length===1?'':'S'}\n\n${miss.join('\n')}\n\nFinish them and check again.`,markup:kb18([[cb18('🔄 CHECK AGAIN',`gw89:user:${g.id}`)]])}}
 const tickets=gw89Tickets(g,x);await pool.query(`insert into public.giveaway_entries(giveaway_id,telegram_id,tickets,qualified,qualification_snapshot,joined_at,updated_at) values($1,$2,$3,true,$4::jsonb,now(),now()) on conflict(giveaway_id,telegram_id) do update set tickets=excluded.tickets,qualified=true,qualification_snapshot=excluded.qualification_snapshot,updated_at=now()`,[g.id,uid,tickets,JSON.stringify(x)]);return {text:`🎟 ENTRY CONFIRMED\n\nYou're officially in.\n\nTickets: ${tickets}\n\nKeep earning before the giveaway ends to increase your chances.`,markup:kb18([[cb18('⚡ UPDATE TICKETS',`gw89:user:${g.id}`)],[cb18('📋 REQUIREMENTS',`gw89:userreq:${g.id}`)]])}}
async function gw89RequirementsCard(uid,g){const x=await gw89StatsForUser(uid,g),r=g.requirements||{},t=g.ticket_rules||{};const lines=[];if(r.ads)lines.push(`${x.ads>=r.ads?'✅':'⬜'} Ads ${x.ads}/${r.ads}`);if(r.tasks)lines.push(`${x.tasks>=r.tasks?'✅':'⬜'} Tasks ${x.tasks}/${r.tasks}`);if(r.valid_referrals)lines.push(`${x.refs>=r.valid_referrals?'✅':'⬜'} Referrals ${x.refs}/${r.valid_referrals}`);if(r.daily_push)lines.push(`${x.daily?'✅':'⬜'} Daily Push`);if(r.mandatory_join)lines.push(`${x.joined?'✅':'⬜'} Required community`);return{text:`📋 GIVEAWAY REQUIREMENTS\n\n${lines.join('\n')||'✅ No extra entry requirement'}\n\n🎟 Bonus tickets\n${t.ads_every?`+1 every ${t.ads_every} ads\n`:''}${t.valid_referral?`+${t.valid_referral} per valid referral\n`:''}${t.daily_push?`+${t.daily_push} Daily Push\n`:''}${t.tasks_every?`+1 every ${t.tasks_every} tasks`:''}`,markup:kb18([[cb18('🎟 PARTICIPATE / UPDATE',`gw89:user:${g.id}`)]])}}
async function gw89Publish(g){const st=await st18(),bot=String(st.bot_username||'WienerDogeFarmBot').replace('@','');const text=`🎁 ${gw89esc(g.title)}\n\n🏆 ${g.winners_count} Winner${g.winners_count>1?'s':''}\n🎁 ${gw89fmt(g.prize_pool)} ${String(g.asset).toUpperCase()}\n\nComplete the requirements and enter before time runs out.\n\nGood luck 🌭`;
 let chat=String(g.publish_channel||'@WienerFarm');try{const r=await tgV10('sendMessage',{chat_id:chat,text,reply_markup:kb18([[url18('🎟 PARTICIPATE',`https://t.me/${bot}?start=gw_${g.public_code}`)],[url18('🌭 OPEN WIENER FARM',app18(st))]])});await pool.query(`update public.giveaway_campaigns set announcement_chat_id=$2,announcement_message_id=$3 where id=$1`,[g.id,r.chat?.id||chat,r.message_id||null])}catch(e){console.error('gw89_publish',String(e?.message||e))}}
async function gw89SecureDraw(entries,count){const {randomInt}=await import('node:crypto');const poolx=[];for(const e of entries)poolx.push({telegram_id:Number(e.telegram_id),tickets:Math.max(1,gw89n(e.tickets))});const winners=[];while(poolx.length&&winners.length<count){const total=poolx.reduce((a,x)=>a+x.tickets,0);let r=randomInt(0,total),idx=0;for(let i=0;i<poolx.length;i++){if(r<poolx[i].tickets){idx=i;break}r-=poolx[i].tickets}winners.push(poolx[idx]);poolx.splice(idx,1)}return winners}
async function gw89Finalize(g){const c=await pool.connect();try{await c.query('begin');await c.query(`select pg_advisory_xact_lock(hashtext('gw89-'||$1::text))`,[g.id]);const lock=(await c.query(`select * from public.giveaway_campaigns where id=$1 for update`,[g.id])).rows[0];if(!lock||!['live','verifying'].includes(lock.status)){await c.query('commit');return}await c.query(`update public.giveaway_campaigns set status='verifying',updated_at=now() where id=$1`,[g.id]);await c.query('commit')}catch(e){await c.query('rollback');throw e}finally{c.release()}
 const entries=(await pool.query(`select * from public.giveaway_entries where giveaway_id=$1 and qualified=true`,[g.id])).rows;const final=[];for(const e of entries){const x=await gw89StatsForUser(Number(e.telegram_id),g);if(x.ok){const tickets=gw89Tickets(g,x);final.push({...e,tickets});await pool.query(`update public.giveaway_entries set tickets=$3,qualification_snapshot=$4::jsonb,updated_at=now() where giveaway_id=$1 and telegram_id=$2`,[g.id,e.telegram_id,tickets,JSON.stringify(x)])}else await pool.query(`update public.giveaway_entries set qualified=false,disqualified_reason='requirements_not_met_at_close',updated_at=now() where giveaway_id=$1 and telegram_id=$2`,[g.id,e.telegram_id])}
 const winners=await gw89SecureDraw(final,Math.min(g.winners_count,final.length));const dist=Array.isArray(g.distribution)?g.distribution:JSON.parse(g.distribution||'[]');const tx=await pool.connect();try{await tx.query('begin');for(let i=0;i<winners.length;i++){const w=winners[i],prize=gw89n(dist[i]??(g.prize_pool/Math.max(1,g.winners_count)));const rr=await tx.query(`insert into public.giveaway_rewards(giveaway_id,telegram_id,position,asset,amount,status,created_at) values($1,$2,$3,$4,$5,$6,now()) on conflict(giveaway_id,telegram_id) do nothing returning id`,[g.id,w.telegram_id,i+1,g.asset,prize,g.asset==='wiener'?'credited':'pending_external']);if(rr.rowCount&&g.asset==='wiener')await tx.query(`update public.users set balance=coalesce(balance,0)+$2,total_earned=coalesce(total_earned,0)+$2 where telegram_id=$1`,[w.telegram_id,prize]);}
 await tx.query(`update public.giveaway_campaigns set status='completed',finalized_at=now(),eligible_count=$2,total_tickets=$3,updated_at=now() where id=$1`,[g.id,final.length,final.reduce((a,x)=>a+gw89n(x.tickets),0)]);await tx.query(`insert into public.giveaway_audit(giveaway_id,event,data) values($1,'finalized',$2::jsonb)`,[g.id,JSON.stringify({eligible:final.length,total_tickets:final.reduce((a,x)=>a+gw89n(x.tickets),0),winners:winners.map(x=>x.telegram_id)})]);await tx.query('commit')}catch(e){await tx.query('rollback');throw e}finally{tx.release()}
 const rows=(await pool.query(`select r.*,u.username,u.first_name from public.giveaway_rewards r left join public.users u on u.telegram_id=r.telegram_id where r.giveaway_id=$1 order by position`,[g.id])).rows;const result=`🏆 GIVEAWAY RESULTS\n\n${rows.map((x,i)=>`${i===0?'🥇':i===1?'🥈':i===2?'🥉':'🎁'} ${x.username?'@'+x.username:(x.first_name||'Winner')} — ${gw89fmt(x.amount)} ${String(x.asset).toUpperCase()}`).join('\n')}\n\n${g.asset==='wiener'?'✅ Rewards credited automatically.':'✅ Winners selected. External prizes are ready for admin payment.'}\n\nThanks for participating 🌭`;
 try{await tgV10('sendMessage',{chat_id:g.publish_channel||'@WienerFarm',text:result})}catch{}
 for(const x of rows){try{await tgV10('sendMessage',{chat_id:x.telegram_id,text:`🎉 YOU WON\n\nYou were selected in ${gw89esc(g.title)}.\n\n🏆 Prize: ${gw89fmt(x.amount)} ${String(x.asset).toUpperCase()}\n${x.asset==='wiener'?'✅ Added to your balance.':'⏳ Prize is awaiting admin payment.'}`})}catch{}}
}
async function processGiveawaysV89(){await pool.query(`update public.giveaway_campaigns set status='live',updated_at=now() where status='scheduled' and start_at<=now() and end_at>now()`);const due=(await pool.query(`select * from public.giveaway_campaigns where status in ('live','verifying') and end_at<=now() order by end_at asc limit 5`)).rows;for(const g of due)try{await gw89Finalize(g)}catch(e){console.error('gw89_finalize',g.id,String(e?.message||e))}}
setInterval(()=>processGiveawaysV89().catch(e=>console.error('gw89_processor',String(e?.message||e))),30000).unref?.();

async function gw89List(uid,kind){if(!await adm18(uid))return null;let where=kind==='live'?"status='live'":kind==='scheduled'?"status='scheduled'":"status='completed'";const rows=(await pool.query(`select * from public.giveaway_campaigns where ${where} order by created_at desc limit 10`)).rows;return{text:`🎁 ${kind==='done'?'HISTORY':kind.toUpperCase()}\n\n${rows.map(g=>`${g.status==='live'?'🟢':g.status==='scheduled'?'🕓':'✅'} ${g.public_code} · ${gw89fmt(g.prize_pool)} ${String(g.asset).toUpperCase()} · ${g.winners_count} winners`).join('\n')||'Nothing here yet.'}`,markup:kb18([[cb18('◀️ STUDIO','gw89:home')]])}}
async function gw89Analytics(uid){if(!await adm18(uid))return null;const x=(await pool.query(`select count(*)::int giveaways,coalesce(sum(eligible_count),0)::int eligible,coalesce(sum(total_tickets),0)::int tickets,coalesce(sum(prize_pool) filter(where asset='wiener' and status='completed'),0) wiener_awarded from public.giveaway_campaigns`)).rows[0]||{};return{text:`📊 GIVEAWAY ANALYTICS\n\nGiveaways: ${x.giveaways||0}\nEligible entries: ${x.eligible||0}\nTickets generated: ${x.tickets||0}\nWIENER prize pools: ${gw89fmt(x.wiener_awarded||0)}`,markup:kb18([[cb18('◀️ STUDIO','gw89:home')]])}}

async function giveawayBotV89(uid,text,m,q){
 const isPrivate=!!m?m.chat?.type==='private':q?.message?.chat?.type==='private';if(!isPrivate)return false;
 await processGiveawaysV89().catch(()=>{});
 if(m&&text.startsWith('/')){const cmd=text.split(/\s+/)[0].replace(/^\//,'').split('@')[0].toLowerCase();
   if(cmd==='giveaway'){
     const a=await adm18(uid);if(a){await safeTg18('sendMessage',{chat_id:uid,...await gw89Studio(uid)});return true}
     const g=await gw89Current();await safeTg18('sendMessage',{chat_id:uid,...await gw89UserCard(uid,g)});return true
   }
   if(cmd==='start'){
     const arg=text.split(/\s+/).slice(1).join(' ').trim();if(/^gw_/i.test(arg)){const code=arg.replace(/^gw_/i,'').toUpperCase();const g=(await pool.query(`select * from public.giveaway_campaigns where public_code=$1 and status='live' and end_at>now()`,[code])).rows[0];if(g){await register18(m).catch(()=>{});await safeTg18('sendMessage',{chat_id:uid,...await gw89UserCard(uid,g)});return true}}
   }
 }
 if(m&&!text.startsWith('/')){const a=await adm18(uid),ss=a?await gw89session(uid):null;if(ss&&ss.step?.startsWith('input:')){const d=ss.data||{},k=ss.step.slice(6),v=text.trim();if(k==='prize_amount'){const n=Number(v);if(!(n>0))throw new Error('Enter a valid amount');d.prize_amount=n;await gw89setSession(uid,'input:winners',d);await safeTg18('sendMessage',{chat_id:uid,text:'🏆 How many winners?\n\nSend a number from 1 to 100.'});return true}if(k==='winners'){const n=Math.floor(Number(v));if(n<1||n>100)throw new Error('Enter 1–100');d.winners=n;await gw89setSession(uid,'input:duration_hours',d);await safeTg18('sendMessage',{chat_id:uid,text:'⏳ Giveaway duration?\n\nSend number of hours. Example: 48'});return true}if(k==='duration_hours'){const n=Number(v);if(!(n>=1&&n<=2160))throw new Error('Enter 1–2160 hours');d.duration_hours=n;await gw89setSession(uid,'draft',d);await safeTg18('sendMessage',{chat_id:uid,...await gw89DraftCard(uid)});return true}if(k.startsWith('req:')){const key=k.slice(4),n=Math.max(0,Math.floor(Number(v)));d.requirements=d.requirements||{};d.requirements[key]=n;await gw89setSession(uid,'draft',d);await safeTg18('sendMessage',{chat_id:uid,...await gw89DraftCard(uid)});return true}if(k.startsWith('ticket:')){const key=k.slice(7),n=Math.max(0,Math.floor(Number(v)));d.ticket_rules=d.ticket_rules||{};d.ticket_rules[key]=n;await gw89setSession(uid,'draft',d);await safeTg18('sendMessage',{chat_id:uid,...await gw89DraftCard(uid)});return true}}
 }
 if(q&&String(q.data||'').startsWith('gw89:')){const data=String(q.data),parts=data.split(':'),a=await adm18(uid);
   if(data==='gw89:home'){if(!a)return false;await gw89clearSession(uid);await edit18(q,(await gw89Studio(uid)).text,(await gw89Studio(uid)).markup);await answer18(q);return true}
   if(data==='gw89:create'){if(!a)return false;await gw89setSession(uid,'goal',{});await edit18(q,'🎯 WHAT SHOULD THIS GIVEAWAY GROW?\n\nChoose the campaign goal.',gw89GoalMarkup());await answer18(q);return true}
   if(parts[1]==='goal'){if(!a)return false;const goal=parts[2],base=gw89Preset(goal);await gw89setSession(uid,'mode',{goal,...base});await edit18(q,'🎁 CHOOSE GIVEAWAY MODE\n\nSimple draw, activity tickets, or ranking competition.',gw89ModeMarkup());await answer18(q);return true}
   if(parts[1]==='mode'){if(!a)return false;const ss=await gw89session(uid),d=ss?.data||{};d.mode=parts[2];await gw89setSession(uid,'asset',d);await edit18(q,'💰 CHOOSE PRIZE',gw89AssetMarkup());await answer18(q);return true}
   if(parts[1]==='asset'){if(!a)return false;const ss=await gw89session(uid),d=ss?.data||{};d.asset=parts[2];await gw89setSession(uid,'input:prize_amount',d);await edit18(q,`💰 PRIZE POOL\n\nSend the total ${String(d.asset).toUpperCase()} prize amount.`,kb18([[cb18('🗑 CANCEL','gw89:cancel')]]));await answer18(q);return true}
   if(data==='gw89:draft'){if(!a)return false;const c=await gw89DraftCard(uid);await edit18(q,c.text,c.markup);await answer18(q);return true}
   if(data==='gw89:req'){if(!a)return false;const ss=await gw89session(uid),d=ss?.data||{};await edit18(q,`⚙️ ENTRY REQUIREMENTS\n\nChoose what users must complete.`,gw89ReqMarkup(d));await answer18(q);return true}
   if(parts[1]==='reqtoggle'){if(!a)return false;const ss=await gw89session(uid),d=ss?.data||{};d.requirements=d.requirements||{};d.requirements[parts[2]]=!d.requirements[parts[2]];await gw89setSession(uid,'draft',d);await edit18(q,'⚙️ ENTRY REQUIREMENTS\n\nChoose what users must complete.',gw89ReqMarkup(d));await answer18(q);return true}
   if(parts[1]==='reqnum'){if(!a)return false;const ss=await gw89session(uid),d=ss?.data||{};await gw89setSession(uid,'input:req:'+parts[2],d);await edit18(q,'Send the required number.\n\nUse 0 to disable.',kb18([[cb18('🗑 CANCEL','gw89:cancel')]]));await answer18(q);return true}
   if(data==='gw89:tickets'){if(!a)return false;const ss=await gw89session(uid),d=ss?.data||{};await edit18(q,'🎟 BONUS TICKETS\n\nSet optional activity boosts.',gw89TicketMarkup(d));await answer18(q);return true}
   if(parts[1]==='ticketnum'){if(!a)return false;const ss=await gw89session(uid),d=ss?.data||{};await gw89setSession(uid,'input:ticket:'+parts[2],d);await edit18(q,'Send the ticket value / interval.\n\nUse 0 to disable.',kb18([[cb18('🗑 CANCEL','gw89:cancel')]]));await answer18(q);return true}
   if(data==='gw89:publish'){if(!a)return false;const ss=await gw89session(uid),d=ss?.data||{};d.publish_channel='@WienerFarm';await gw89setSession(uid,'draft',d);await edit18(q,'📣 PUBLISH SETTINGS\n\nChannel: @WienerFarm\nAuto result: ✅ ON\nAuto winner DM: ✅ ON\nWIENER auto-credit: ✅ ON\nTON/USDT: winner selected, admin payment pending.',kb18([[cb18('✅ KEEP','gw89:draft')]]));await answer18(q);return true}
   if(data==='gw89:confirm'){if(!a)return false;const ss=await gw89session(uid),d=ss?.data||{};if(!d.prize_amount||!d.winners||!d.duration_hours)throw new Error('Giveaway draft incomplete');const g=await gw89Create(uid,d);await gw89clearSession(uid);await gw89Publish(g);await edit18(q,`✅ GIVEAWAY LIVE\n\nCode: ${g.public_code}\nPrize: ${gw89fmt(g.prize_pool)} ${String(g.asset).toUpperCase()}\nWinners: ${g.winners_count}\n\nThe bot will verify entries, close the giveaway, draw winners and announce results automatically.`,kb18([[cb18('🎁 GIVEAWAY STUDIO','gw89:home')]]));await answer18(q,'Giveaway created');return true}
   if(data==='gw89:cancel'){if(!a)return false;await gw89clearSession(uid);const c=await gw89Studio(uid);await edit18(q,c.text,c.markup);await answer18(q,'Cancelled');return true}
   if(parts[1]==='list'){if(!a)return false;const c=await gw89List(uid,parts[2]);await edit18(q,c.text,c.markup);await answer18(q);return true}
   if(data==='gw89:analytics'){if(!a)return false;const c=await gw89Analytics(uid);await edit18(q,c.text,c.markup);await answer18(q);return true}
   if(parts[1]==='user'){const g=(await pool.query(`select * from public.giveaway_campaigns where id=$1 and status='live' and end_at>now()`,[parts[2]])).rows[0];if(!g){await answer18(q,'Giveaway ended',true);return true}const c=await gw89Participate(uid,g);await edit18(q,c.text,c.markup);await answer18(q,'Entry checked');return true}
   if(parts[1]==='userreq'){const g=(await pool.query(`select * from public.giveaway_campaigns where id=$1`,[parts[2]])).rows[0];if(!g){await answer18(q,'Giveaway not found',true);return true}const c=await gw89RequirementsCard(uid,g);await edit18(q,c.text,c.markup);await answer18(q);return true}
 }
 return false
}
// === END WIENER GIVEAWAY STUDIO V89 ===
'''
s=s.replace(anchor,code+'\n'+anchor,1)
needle="  if(!uid&&!q)return false;\n"
if needle not in s: raise SystemExit('ERROR: handler uid anchor missing')
s=s.replace(needle,needle+"  if(await giveawayBotV89(uid,text,m,q))return true;\n",1)
p.write_text(s)
print('V89 applied: advanced /giveaway studio + participation + automatic draw/results')
