import {useEffect,useMemo,useState} from 'react';
import {api,date,money} from './lib';
import {Admin as OperationsAdmin} from './AdminV2';

type HubTab='users'|'operations';
type UserTab='overview'|'timeline'|'invites'|'ads'|'tasks'|'money'|'security';
const compactDate=(v:any)=>v?new Date(v).toLocaleString(undefined,{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const badge=(ok:boolean,a:string,b:string)=><span className={ok?'aui-badge good':'aui-badge bad'}>{ok?a:b}</span>;

export function AdminHub({say}:{say:any}){
 const [tab,setTab]=useState<HubTab>('users');
 return <div className="ahub"><div className="ahub-switch"><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}><span>⌕</span><b>User Intelligence</b><small>History · invites · security</small></button><button className={tab==='operations'?'active':''} onClick={()=>setTab('operations')}><span>⚙</span><b>Operations</b><small>Existing admin controls</small></button></div>{tab==='users'?<UserIntelligence say={say}/>:<OperationsAdmin say={say}/>}</div>
}

function UserIntelligence({say}:{say:any}){
 const [q,setQ]=useState(''),[rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState(false),[selected,setSelected]=useState<any>(null),[profile,setProfile]=useState<any>(null),[tab,setTab]=useState<UserTab>('overview');
 const search=async(value=q)=>{try{setBusy(true);const r=await api('admin_user_search',{query:value});setRows(r.users||[])}catch(e:any){say(e.message)}finally{setBusy(false)}};
 useEffect(()=>{search('')},[]);
 const inspect=async(u:any)=>{try{setSelected(u);setProfile(null);setTab('overview');setBusy(true);setProfile(await api('admin_user_inspect',{telegram_id:u.telegram_id}))}catch(e:any){say(e.message);setSelected(null)}finally{setBusy(false)}};
 const health=useMemo(()=>{if(!profile)return null;const u=profile.user,s=profile.summary;return {risk:!!(u.is_banned||u.device_blocked||s.abuse_flags),valid:s.valid_referrals,total:s.direct_referrals}},[profile]);
 return <section className="aui-shell">
  <div className="aui-head"><div><span>USER INTELLIGENCE</span><h3>Inspect any account</h3><p>Read-only activity view. Sensitive changes remain in Operations.</p></div><button onClick={()=>search()} disabled={busy}>↻</button></div>
  <form className="aui-search" onSubmit={e=>{e.preventDefault();search()}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="UID, @username or name"/><button disabled={busy}>{busy?'…':'SEARCH'}</button></form>
  <div className="aui-results">{rows.map(u=><button key={u.telegram_id} onClick={()=>inspect(u)}><div className="aui-avatar">{String(u.first_name||u.username||'U').slice(0,1).toUpperCase()}</div><div className="aui-user"><b>{u.first_name||u.username||`User ${u.telegram_id}`}</b><small>{u.username?`@${u.username} · `:''}{u.telegram_id}</small><span>Last active {compactDate(u.last_active)}</span></div><div className="aui-row-right"><strong>{money(u.balance)}</strong>{badge(!u.is_banned&&!u.device_blocked,'ACTIVE',u.is_banned?'BANNED':'BLOCKED')}</div></button>)}</div>
  {selected&&<div className="aui-backdrop" onClick={()=>setSelected(null)}><div className="aui-sheet" onClick={e=>e.stopPropagation()}>{!profile?<div className="aui-loading">Loading full user history…</div>:<>
   <div className="aui-profile-head"><div className="aui-avatar big">{String(profile.user.first_name||profile.user.username||'U').slice(0,1).toUpperCase()}</div><div><span>USER DOSSIER</span><h3>{profile.user.first_name||profile.user.username||profile.user.telegram_id}</h3><small>{profile.user.username?`@${profile.user.username} · `:''}UID {profile.user.telegram_id}</small></div><button onClick={()=>setSelected(null)}>×</button></div>
   <div className="aui-kpis"><div><small>BALANCE</small><b>{money(profile.user.balance)}</b><span>WIENER</span></div><div><small>ADS</small><b>{profile.user.total_ads||0}</b><span>{profile.summary.credited_ads} tracked credited</span></div><div><small>INVITES</small><b>{health?.valid}/{health?.total}</b><span>valid / direct</span></div><div><small>RISK</small><b>{health?.risk?'CHECK':'CLEAR'}</b><span>{profile.summary.abuse_flags} flags</span></div></div>
   <div className="aui-tabs">{(['overview','timeline','invites','ads','tasks','money','security'] as UserTab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div>
   <div className="aui-content">{tab==='overview'&&<Overview p={profile}/>} {tab==='timeline'&&<Timeline rows={profile.activity.timeline}/>} {tab==='invites'&&<Invites p={profile}/>} {tab==='ads'&&<Ads rows={profile.activity.ads}/>} {tab==='tasks'&&<Tasks rows={profile.activity.tasks}/>} {tab==='money'&&<Money p={profile}/>} {tab==='security'&&<Security p={profile}/>}</div>
  </>}</div></div>}
 </section>
}

function Overview({p}:{p:any}){const u=p.user,s=p.summary;return <div className="aui-grid2"><Card title="Account"><Line k="Status" v={u.is_banned?'Banned':u.device_blocked?'Device blocked':'Active'}/><Line k="Created" v={date(u.created_at)}/><Line k="Last active" v={date(u.last_active)}/><Line k="Streak" v={`${u.daily_streak||0} · best ${u.best_streak||0}`}/></Card><Card title="Earnings"><Line k="Balance" v={`${money(u.balance)} WIENER`}/><Line k="Total earned" v={`${money(u.total_earned)} WIENER`}/><Line k="Withdrawn" v={`${money(u.total_withdrawn)} WIENER`}/><Line k="Referral earned" v={`${money(u.referral_earnings)} WIENER`}/></Card><Card title="Activity"><Line k="Ads watched" v={String(u.total_ads||0)}/><Line k="Tasks completed" v={String(s.tasks_completed)}/><Line k="Farm sessions" v={String(u.farm_sessions||0)}/><Line k="Transactions" v={String(s.transactions)}/></Card><Card title="Referral status"><Line k="Referred by" v={u.referred_by?String(u.referred_by):'Organic'}/><Line k="Direct" v={String(s.direct_referrals)}/><Line k="Valid" v={String(s.valid_referrals)}/><Line k="Invalid / pending" v={String(s.invalid_referrals)}/></Card></div>}
function Timeline({rows}:{rows:any[]}){return <div className="aui-feed">{rows.length?rows.map((x:any,i:number)=><div key={`${x.type}-${x.at}-${i}`}><i className={`type-${x.type}`}>{x.type==='ad'?'▶':x.type==='task'?'✓':x.type==='withdrawal'?'↓':x.type==='referral'?'↗':x.type==='promo'?'★':'•'}</i><div><b>{x.title}</b><small>{x.detail||x.type} · {compactDate(x.at)}</small></div>{x.amount?<strong className={Number(x.amount)>=0?'plus':'minus'}>{Number(x.amount)>0?'+':''}{money(x.amount)}</strong>:null}</div>):<Empty/>}</div>}
function Invites({p}:{p:any}){return <><div className="aui-summaryline"><span>Direct <b>{p.summary.direct_referrals}</b></span><span>Valid <b>{p.summary.valid_referrals}</b></span><span>Invalid <b>{p.summary.invalid_referrals}</b></span><span>Level 2 <b>{p.summary.second_level_referrals}</b></span></div><h4 className="aui-subtitle">Direct invite tree</h4><div className="aui-feed">{p.referrals.level1.length?p.referrals.level1.map((x:any)=><div key={x.telegram_id}><i>{x.referral_active?'✓':'!'}</i><div><b>{x.username?`@${x.username}`:(x.first_name||x.telegram_id)}</b><small>UID {x.telegram_id} · {x.total_ads||0} ads · {compactDate(x.created_at)}</small><em>{x.referral_active?'Valid':(x.referral_ineligible_reason||'Invalid / pending')}</em></div>{badge(!!x.referral_active,'VALID','INVALID')}</div>):<Empty/>}</div>{p.referrals.level2.length>0&&<><h4 className="aui-subtitle">Second level</h4><div className="aui-feed compact">{p.referrals.level2.map((x:any)=><div key={x.telegram_id}><i>↳</i><div><b>{x.username?`@${x.username}`:(x.first_name||x.telegram_id)}</b><small>Invited by {x.referred_by} · UID {x.telegram_id}</small></div></div>)}</div></>}</>}
function Ads({rows}:{rows:any[]}){return <div className="aui-feed">{rows.length?rows.map((x:any,i:number)=><div key={`${x.id||i}-${x.provider}`}><i>▶</i><div><b>{String(x.provider||'ad').toUpperCase()}</b><small>{x.status||'unknown'} · {compactDate(x.credited_at||x.started_at||x.created_at)}</small></div><strong>+{money(x.reward||0)}</strong></div>):<Empty/>}</div>}
function Tasks({rows}:{rows:any[]}){return <div className="aui-feed">{rows.length?rows.map((x:any)=><div key={x.id}><i>✓</i><div><b>{x.tasks?.title||'Task'}</b><small>{x.tasks?.category||'task'} · {compactDate(x.created_at)}</small></div><strong>+{money(x.reward||0)}</strong></div>):<Empty/>}</div>}
function Money({p}:{p:any}){return <><h4 className="aui-subtitle">Withdrawals</h4><div className="aui-feed">{p.activity.withdrawals.length?p.activity.withdrawals.map((x:any)=><div key={x.id}><i>↓</i><div><b>{Number(x.receive_usdt||x.gross_usdt||0).toFixed(4)} USDT · {x.network||x.method_key}</b><small>{x.status} · {compactDate(x.created_at)}</small></div><span className={`aui-badge ${x.status==='paid'?'good':x.status==='rejected'?'bad':''}`}>{String(x.status).toUpperCase()}</span></div>):<Empty/>}</div><h4 className="aui-subtitle">Transactions</h4><Timeline rows={p.activity.transactions.map((x:any)=>({type:'transaction',at:x.created_at,title:x.description||x.kind,detail:x.kind,amount:x.amount}))}/></>}
function Security({p}:{p:any}){const u=p.user;return <div className="aui-grid2"><Card title="Device"><Line k="Device blocked" v={u.device_blocked?'YES':'NO'}/><Line k="Admin approved" v={u.device_admin_approved?'YES':'NO'}/><Line k="Blocked reason" v={u.device_blocked_reason||'—'}/><Line k="Device ID" v={u.device_id||'—'}/><Line k="Fingerprint" v={u.device_fingerprint?String(u.device_fingerprint).slice(0,22)+'…':'—'}/></Card><Card title="Referral security"><Line k="Eligible" v={u.referral_reward_eligible===false?'NO':'YES'}/><Line k="Reason" v={u.referral_ineligible_reason||'—'}/><Line k="Abuse flags" v={String(p.summary.abuse_flags)}/><Line k="Manual unbans" v={String(p.security.device_unbans.length)}/></Card><div className="aui-wide"><h4>Abuse flags</h4><div className="aui-feed compact">{p.security.flags.length?p.security.flags.map((x:any)=><div key={x.id}><i>!</i><div><b>{x.reason}</b><small>Related UID {x.related_telegram_id||'—'} · {compactDate(x.created_at)}</small></div></div>):<Empty/>}</div></div></div>}
function Card({title,children}:{title:string;children:any}){return <div className="aui-card"><h4>{title}</h4>{children}</div>}
function Line({k,v}:{k:string;v:any}){return <div className="aui-line"><span>{k}</span><b>{v??'—'}</b></div>}
function Empty(){return <div className="aui-empty">No records found.</div>}
