import {useEffect,useMemo,useState} from 'react';
import {api,date,money} from './lib';
import {MandatoryAdmin} from './MandatoryJoin';
import {AdminWithdrawUpgrade} from './WithdrawV2';
import {InternalTransferAdmin} from './InternalTransferAdmin';
import {MainTreasuryAdmin} from './MainTreasuryAdmin';
import {Splash} from './ui';
import './styles-admin-hub.css';

type MainTab='dashboard'|'users'|'content'|'money'|'system';
type UserTab='overview'|'timeline'|'invites'|'ads'|'tasks'|'money'|'security'|'actions';
type ContentTab='tasks'|'promos'|'mandatory';
type MoneyTab='treasury'|'withdrawals'|'rewards'|'payouts'|'internal';
type SystemTab='controls'|'identity'|'admins'|'audit';
const compactDate=(v:any)=>v?new Date(v).toLocaleString(undefined,{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
const badge=(ok:boolean,a:string,b:string)=><span className={ok?'aui-badge good':'aui-badge bad'}>{ok?a:b}</span>;
const nav:{key:MainTab;icon:string;label:string}[]=[
 {key:'dashboard',icon:'⌂',label:'Dashboard'},
 {key:'users',icon:'👥',label:'Users'},
 {key:'content',icon:'◫',label:'Content'},
 {key:'money',icon:'₿',label:'Money'},
 {key:'system',icon:'⚙',label:'System'}
];

export function AdminHub({say}:{say:any}){
 const [tab,setTab]=useState<MainTab>('dashboard'),[d,setD]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{setBusy(true);setError('');const raw:any=await api('admin_get');if(!raw||typeof raw!=='object'||raw.error||raw.ok===false){throw new Error(raw?.message||raw?.error||'Failed to load admin data')}setD(raw)}catch(e:any){const msg=String(e?.message||e||'Failed to load admin data');setError(msg);say?.(msg)}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const safeD=useMemo(()=>({
  settings:d?.settings||{},
  users:Array.isArray(d?.users)?d.users:[],
  tasks:Array.isArray(d?.tasks)?d.tasks:[],
  promos:Array.isArray(d?.promos)?d.promos:[],
  withdrawals:Array.isArray(d?.withdrawals)?d.withdrawals:[],
  audit:Array.isArray(d?.audit)?d.audit:[],
  admins:Array.isArray(d?.admins)?d.admins:[],
  notifications:Array.isArray(d?.notifications)?d.notifications:[],
  stats:(d?.stats&&typeof d.stats==='object')?d.stats:{}
 }),[d]);
 if(!d){
  if(error){
   return <div className="adminx">
    <div className="adminx-top"><div><span>WIENER CONTROL CENTER</span><h2>Offline</h2></div><button onClick={load} disabled={busy}>{busy?'…':'↻'}</button></div>
    <section className="adminx-panel" style={{textAlign:'center',padding:'28px 16px',margin:'14px 0'}}>
     <div style={{fontSize:36,marginBottom:10}}>⚠️</div>
     <h3 style={{margin:'0 0 8px',fontSize:17}}>Admin Control Center Reconnection</h3>
     <p style={{margin:'0 0 16px',fontSize:12,opacity:0.7,lineHeight:1.4}}>{error}</p>
     <button className="adminx-primary" onClick={load} disabled={busy} style={{margin:'0 auto',minWidth:140}}>
      {busy?'CONNECTING…':'RETRY NOW'}
     </button>
    </section>
   </div>;
  }
  return <Splash text="Loading admin control center…"/>;
 }
 return <div className="adminx">
  <div className="adminx-top"><div><span>WIENER CONTROL CENTER</span><h2>{nav.find(x=>x.key===tab)?.label}</h2></div><button onClick={load} disabled={busy}>{busy?'…':'↻'}</button></div>
  <div className="adminx-nav">{nav.map(x=><button key={x.key} className={tab===x.key?'active':''} onClick={()=>setTab(x.key)}><i>{x.icon}</i><span>{x.label}</span></button>)}</div>
  <div className="adminx-body">
   {tab==='dashboard'&&<Dashboard d={safeD} go={setTab}/>} 
   {tab==='users'&&<UserIntelligence say={say}/>} 
   {tab==='content'&&<ContentCenter d={safeD} say={say} reload={load}/>} 
   {tab==='money'&&<MoneyCenter d={safeD} setD={setD} say={say} reload={load}/>} 
   {tab==='system'&&<SystemCenter d={safeD} setD={setD} say={say} reload={load}/>} 
  </div>
 </div>;
}

function Dashboard({d,go}:{d:any;go:(x:MainTab)=>void}){
 const withdrawals=Array.isArray(d?.withdrawals)?d.withdrawals:[],tasks=Array.isArray(d?.tasks)?d.tasks:[],promos=Array.isArray(d?.promos)?d.promos:[],stats=(d?.stats&&typeof d.stats==='object')?d.stats:{};
 const now=Date.now();
 const totalUsers=Number(stats.total_users||0);
 const activeToday=Number(stats.active_24h||0);
 const newToday=Number(stats.new_24h||0);
 const pending=withdrawals.filter((x:any)=>x?.status==='pending').length;
 const banned=Number(stats.banned_users||0);
 const activeTasks=tasks.filter((x:any)=>x?.enabled).length;
 const activePromos=promos.filter((x:any)=>x?.enabled&&(!x.expires_at||new Date(x.expires_at).getTime()>now)).length;
 const alerts=[pending?`${pending} pending withdrawal${pending===1?'':'s'}`:'',banned?`${banned} banned account${banned===1?'':'s'}`:'',d.settings?.maintenance_enabled?'Maintenance is enabled':''].filter(Boolean);
 return <div className="adminx-page">
  <div className="adminx-kpis"><Kpi label="Users" value={totalUsers} note={`${activeToday} active today`}/><Kpi label="New today" value={newToday} note="accounts"/><Kpi label="Pending payout" value={pending} note={`${withdrawals.filter((x:any)=>x?.status==='paid').length} paid`}/><Kpi label="Content" value={activeTasks+activePromos} note={`${activeTasks} tasks · ${activePromos} promos`}/></div>
  <section className="adminx-panel"><div className="adminx-panel-head"><div><span>STATUS</span><h3>System health</h3></div></div><div className="adminx-status"><Status ok={!d.settings?.maintenance_enabled} text={d.settings?.maintenance_enabled?'Maintenance ON':'App live'}/><Status ok={!!d.settings?.ads_enabled} text={d.settings?.ads_enabled?'Ads ON':'Ads OFF'}/><Status ok={!!d.settings?.tasks_enabled} text={d.settings?.tasks_enabled?'Tasks ON':'Tasks OFF'}/><Status ok={!!d.settings?.withdrawals_enabled} text={d.settings?.withdrawals_enabled?'Withdrawals ON':'Withdrawals OFF'}/></div></section>
  <section className="adminx-panel"><div className="adminx-panel-head"><div><span>ATTENTION</span><h3>Alerts</h3></div></div>{alerts.length?<div className="adminx-alerts">{alerts.map(x=><div key={x}><i>!</i><span>{x}</span></div>)}</div>:<div className="adminx-empty">No admin alerts right now.</div>}</section>
  <section className="adminx-panel"><div className="adminx-panel-head"><div><span>QUICK ACCESS</span><h3>Manage</h3></div></div><div className="adminx-quick"><button onClick={()=>go('users')}>👥<b>Users</b><small>Inspect & act</small></button><button onClick={()=>go('content')}>🎯<b>Content</b><small>Tasks & promos</small></button><button onClick={()=>go('money')}>💸<b>Money</b><small>Payouts & rewards</small></button><button onClick={()=>go('system')}>⚙️<b>System</b><small>Controls & admins</small></button></div></section>
 </div>;
}
function Kpi({label,value,note}:{label:string;value:any;note:string}){return <div><small>{label}</small><b>{value}</b><span>{note}</span></div>}
function Status({ok,text}:{ok:boolean;text:string}){return <span className={ok?'ok':'warn'}><i/> {text}</span>}

function UserIntelligence({say}:{say:any}){
 const [q,setQ]=useState(''),[rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState(false),[selected,setSelected]=useState<any>(null),[profile,setProfile]=useState<any>(null),[tab,setTab]=useState<UserTab>('overview');
 const search=async(value=q)=>{try{setBusy(true);const r:any=await api('admin_user_search',{query:value});setRows(Array.isArray(r?.users)?r.users:[])}catch(e:any){say(e.message);setRows([])}finally{setBusy(false)}};
 useEffect(()=>{search('')},[]);
 const inspect=async(u:any)=>{try{setSelected(u);setProfile(null);setTab('overview');setBusy(true);const p:any=await api('admin_user_inspect',{telegram_id:u.telegram_id});setProfile(p&&typeof p==='object'?p:null)}catch(e:any){say(e.message);setSelected(null)}finally{setBusy(false)}};
 const refreshProfile=async()=>{if(!selected)return;try{const p:any=await api('admin_user_inspect',{telegram_id:selected.telegram_id});setProfile(p&&typeof p==='object'?p:null)}catch(e:any){say(e.message)}};
 const health=useMemo(()=>{if(!profile)return null;const u=profile.user||{},s=profile.summary||{};return {risk:!!(u.is_banned||u.device_blocked||s.abuse_flags),valid:Number(s.valid_referrals||0),total:Number(s.direct_referrals||0)}},[profile]);
 return <section className="aui-shell">
  <div className="adminx-section-title"><div><span>USER INTELLIGENCE</span><h3>Accounts</h3><p>Search the full user database and inspect complete activity.</p></div></div>
  <form className="aui-search" onSubmit={e=>{e.preventDefault();search()}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="UID, @username or name"/><button disabled={busy}>{busy?'…':'SEARCH'}</button></form>
  <div className="aui-results">{(rows||[]).map(u=><button key={u.telegram_id} onClick={()=>inspect(u)}><div className="aui-avatar">{String(u.first_name||u.username||'U').slice(0,1).toUpperCase()}</div><div className="aui-user"><b>{u.first_name||u.username||`User ${u.telegram_id}`}</b><small>{u.username?`@${u.username} · `:''}{u.telegram_id}</small><span>Last active {compactDate(u.last_active)}</span></div><div className="aui-row-right"><strong>{money(u.balance)}</strong>{badge(!u.is_banned&&!u.device_blocked,'ACTIVE',u.is_banned?'BANNED':'BLOCKED')}</div></button>)}</div>
  {selected&&<div className="aui-backdrop" onClick={()=>setSelected(null)}><div className="aui-sheet" onClick={e=>e.stopPropagation()}>{!profile?<div className="aui-loading">Loading full user history…</div>:<>
   <div className="aui-profile-head"><div className="aui-avatar big">{String(profile.user?.first_name||profile.user?.username||'U').slice(0,1).toUpperCase()}</div><div><span>USER DOSSIER</span><h3>{profile.user?.first_name||profile.user?.username||profile.user?.telegram_id}</h3><small>{profile.user?.username?`@${profile.user?.username} · `:''}UID {profile.user?.telegram_id}</small></div><button onClick={()=>setSelected(null)}>×</button></div>
   <div className="aui-kpis"><div><small>BALANCE</small><b>{money(profile.user?.balance)}</b><span>WIENER</span></div><div><small>ADS</small><b>{profile.user?.total_ads||0}</b><span>{profile.summary?.credited_ads||0} tracked</span></div><div><small>INVITES</small><b>{health?.valid||0}/{health?.total||0}</b><span>valid / direct</span></div><div><small>RISK</small><b>{health?.risk?'CHECK':'CLEAR'}</b><span>{profile.summary?.abuse_flags||0} flags</span></div></div>
   <div className="aui-tabs">{(['overview','timeline','invites','ads','tasks','money','security','actions'] as UserTab[]).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div>
   <div className="aui-content">{tab==='overview'&&<Overview p={profile}/>} {tab==='timeline'&&<Timeline rows={profile.activity?.timeline||[]}/>} {tab==='invites'&&<Invites p={profile}/>} {tab==='ads'&&<Ads rows={profile.activity?.ads||[]}/>} {tab==='tasks'&&<TaskHistory rows={profile.activity?.tasks||[]}/>} {tab==='money'&&<UserMoney p={profile}/>} {tab==='security'&&<Security p={profile}/>} {tab==='actions'&&<UserActions p={profile} say={say} refresh={refreshProfile}/>}</div>
  </>}</div></div>}
 </section>;
}

function Overview({p}:{p:any}){const u=p?.user||{},s=p?.summary||{};return <div className="aui-grid2"><Card title="Account"><Line k="Status" v={u.is_banned?'Banned':u.device_blocked?'Device blocked':'Active'}/><Line k="Created" v={date(u.created_at)}/><Line k="Last active" v={date(u.last_active)}/><Line k="Streak" v={`${u.daily_streak||0} · best ${u.best_streak||0}`}/></Card><Card title="Earnings"><Line k="Balance" v={`${money(u.balance)} WIENER`}/><Line k="Total earned" v={`${money(u.total_earned)} WIENER`}/><Line k="Withdrawn" v={`${money(u.total_withdrawn)} WIENER`}/><Line k="Referral earned" v={`${money(u.referral_earnings)} WIENER`}/></Card><Card title="Activity"><Line k="Ads watched" v={String(u.total_ads||0)}/><Line k="Tasks completed" v={String(s.tasks_completed||0)}/><Line k="Farm sessions" v={String(u.farm_sessions||0)}/><Line k="Transactions" v={String(s.transactions||0)}/></Card><Card title="Referral status"><Line k="Referred by" v={u.referred_by?String(u.referred_by):'Organic'}/><Line k="Direct" v={String(s.direct_referrals||0)}/><Line k="Valid" v={String(s.valid_referrals||0)}/><Line k="Invalid / pending" v={String(s.invalid_referrals||0)}/></Card></div>}
function Timeline({rows}:{rows:any[]}){const list=Array.isArray(rows)?rows:[];return <div className="aui-feed">{list.length?list.map((x:any,i:number)=><div key={`${x.type}-${x.at}-${i}`}><i>{x.type==='ad'?'▶':x.type==='task'?'✓':x.type==='withdrawal'?'↓':x.type==='referral'?'↗':x.type==='promo'?'★':'•'}</i><div><b>{x.title}</b><small>{x.detail||x.type} · {compactDate(x.at)}</small></div>{x.amount?<strong className={Number(x.amount)>=0?'plus':'minus'}>{Number(x.amount)>0?'+':''}{money(x.amount)}</strong>:null}</div>):<Empty/>}</div>}
function Invites({p}:{p:any}){const l1=Array.isArray(p?.referrals?.level1)?p.referrals.level1:[],l2=Array.isArray(p?.referrals?.level2)?p.referrals.level2:[],s=p?.summary||{};return <><div className="aui-summaryline"><span>Direct <b>{s.direct_referrals||0}</b></span><span>Valid <b>{s.valid_referrals||0}</b></span><span>Invalid <b>{s.invalid_referrals||0}</b></span><span>Level 2 <b>{s.second_level_referrals||0}</b></span></div><h4 className="aui-subtitle">Direct invite tree</h4><div className="aui-feed">{l1.length?l1.map((x:any)=><div key={x.telegram_id}><i>{x.referral_active?'✓':'!'}</i><div><b>{x.username?`@${x.username}`:(x.first_name||x.telegram_id)}</b><small>UID {x.telegram_id} · {x.total_ads||0} ads · {compactDate(x.created_at)}</small><em>{x.referral_active?'Valid':(x.referral_ineligible_reason||'Invalid / pending')}</em></div>{badge(!!x.referral_active,'VALID','INVALID')}</div>):<Empty/>}</div>{l2.length>0&&<><h4 className="aui-subtitle">Second level</h4><div className="aui-feed compact">{l2.map((x:any)=><div key={x.telegram_id}><i>↳</i><div><b>{x.username?`@${x.username}`:(x.first_name||x.telegram_id)}</b><small>Invited by {x.referred_by} · UID {x.telegram_id}</small></div></div>)}</div></>}</>}
function Ads({rows}:{rows:any[]}){const list=Array.isArray(rows)?rows:[];return <div className="aui-feed">{list.length?list.map((x:any,i:number)=><div key={`${x.id||i}-${x.provider}`}><i>▶</i><div><b>{String(x.provider||'ad').toUpperCase()}</b><small>{x.status||'unknown'} · {compactDate(x.credited_at||x.started_at||x.created_at)}</small></div><strong>+{money(x.reward||0)}</strong></div>):<Empty/>}</div>}
function TaskHistory({rows}:{rows:any[]}){const list=Array.isArray(rows)?rows:[];return <div className="aui-feed">{list.length?list.map((x:any)=><div key={x.id}><i>✓</i><div><b>{x.tasks?.title||'Task'}</b><small>{x.tasks?.category||'task'} · {compactDate(x.created_at)}</small></div><strong>+{money(x.reward||0)}</strong></div>):<Empty/>}</div>}
function UserMoney({p}:{p:any}){const wds=Array.isArray(p?.activity?.withdrawals)?p.activity.withdrawals:[],txs=Array.isArray(p?.activity?.transactions)?p.activity.transactions:[];return <><h4 className="aui-subtitle">Withdrawals</h4><div className="aui-feed">{wds.length?wds.map((x:any)=><div key={x.id}><i>↓</i><div><b>{money(x.receive_usdt||x.gross_usdt||0,4)} USDT · {x.network||x.method_key}</b><small>{x.status} · {compactDate(x.created_at)}</small></div><span className={`aui-badge ${x.status==='paid'?'good':x.status==='rejected'?'bad':''}`}>{String(x.status).toUpperCase()}</span></div>):<Empty/>}</div><h4 className="aui-subtitle">Transactions</h4><Timeline rows={txs.map((x:any)=>({type:'transaction',at:x.created_at,title:x.description||x.kind,detail:x.kind,amount:x.amount}))}/></>}
function Security({p}:{p:any}){const u=p?.user||{},s=p?.summary||{},sec=p?.security||{};const flags=Array.isArray(sec.flags)?sec.flags:[],unbans=Array.isArray(sec.device_unbans)?sec.device_unbans:[];return <div className="aui-grid2"><Card title="Device"><Line k="Device blocked" v={u.device_blocked?'YES':'NO'}/><Line k="Admin approved" v={u.device_admin_approved?'YES':'NO'}/><Line k="Blocked reason" v={u.device_blocked_reason||'—'}/><Line k="Device ID" v={u.device_id||'—'}/><Line k="Fingerprint" v={u.device_fingerprint?String(u.device_fingerprint).slice(0,22)+'…':'—'}/></Card><Card title="Referral security"><Line k="Eligible" v={u.referral_reward_eligible===false?'NO':'YES'}/><Line k="Reason" v={u.referral_ineligible_reason||'—'}/><Line k="Abuse flags" v={String(s.abuse_flags||0)}/><Line k="Manual unbans" v={String(unbans.length)}/></Card><div className="aui-wide"><h4>Abuse flags</h4><div className="aui-feed compact">{flags.length?flags.map((x:any)=><div key={x.id}><i>!</i><div><b>{x.reason}</b><small>Related UID {x.related_telegram_id||'—'} · {compactDate(x.created_at)}</small></div></div>):<Empty/>}</div></div></div>}
function UserActions({p,say,refresh}:{p:any;say:any;refresh:any}){const u=p?.user||{},[amount,setAmount]=useState(''),[reason,setReason]=useState('Admin adjustment'),[busy,setBusy]=useState(false);const adjust=async()=>{const v=Number(amount);if(!Number.isFinite(v)||v===0)return say('Enter a non-zero amount');if(!confirm(`Apply ${v>0?'+':''}${v} WIENER to UID ${u.telegram_id}?`))return;try{setBusy(true);await api('admin_user_update',{telegram_id:u.telegram_id,amount:v,reason});say('✅ Balance updated');setAmount('');await refresh()}catch(e:any){say(e.message)}finally{setBusy(false)}};const ban=async()=>{if(!confirm(u.is_banned?'Unban this user?':'Ban this user?'))return;try{setBusy(true);await api('admin_user_update',{telegram_id:u.telegram_id,is_banned:!u.is_banned,ban_reason:!u.is_banned?(reason||'Banned by admin'):null});say(u.is_banned?'✅ User unbanned':'🚫 User banned');await refresh()}catch(e:any){say(e.message)}finally{setBusy(false)}};return <div className="adminx-action-stack"><div className="adminx-danger-note">Sensitive changes require confirmation and are handled by the existing secured admin API.</div><label><span>Balance change (+ / -)</span><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Example: 100 or -50"/></label><label><span>Reason</span><input value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="adminx-primary" disabled={busy} onClick={adjust}>APPLY BALANCE CHANGE</button><button className={u.is_banned?'adminx-primary':'adminx-danger'} disabled={busy} onClick={ban}>{u.is_banned?'UNBAN USER':'BAN USER'}</button></div>}

function ContentCenter({d,say,reload}:{d:any;say:any;reload:any}){const [tab,setTab]=useState<ContentTab>('tasks');return <div className="adminx-page"><Subnav value={tab} setValue={setTab} items={[["tasks","Tasks"],["promos","Promo Codes"],["mandatory","Mandatory Join"]]}/>{tab==='tasks'&&<TaskManager rows={d.tasks||[]} say={say} reload={reload}/>} {tab==='promos'&&<PromoManager rows={d.promos||[]} say={say} reload={reload}/>} {tab==='mandatory'&&<section className="adminx-embed"><MandatoryAdmin say={say}/></section>}</div>}
function TaskManager({rows,say,reload}:{rows:any[];say:any;reload:any}){const [edit,setEdit]=useState<any>(null),[busy,setBusy]=useState(false);const start=(x:any=null)=>setEdit(x?{...x}:{title:'',description:'',category:'official',task_type:'telegram',reward:10,url:'',telegram_chat_id:'',enabled:true,sort_order:0});const save=async()=>{try{setBusy(true);if(!String(edit.title||'').trim())throw Error('Task title is required');if(Number(edit.reward)<=0)throw Error('Reward must be above 0');const raw=String(edit.telegram_chat_id||'').trim(),isBot=edit.task_type==='bot',clean=raw.replace(/^@/,'').replace(/^https?:\/\/t\.me\//i,'').split(/[?\/]/)[0];const task={...edit,reward:Number(edit.reward),telegram_chat_id:(isBot?`@${clean}`:raw)||null,url:(edit.url||(isBot&&clean?`https://t.me/${clean}`:''))||null,verification:isBot?'bot_forward':raw?'telegram_member':'none'};await api('admin_task_save',{task});say('✅ Task saved');setEdit(null);await reload()}catch(e:any){say(e.message)}finally{setBusy(false)}};const list=Array.isArray(rows)?rows:[];return <section className="adminx-panel"><div className="adminx-panel-head"><div><span>CONTENT</span><h3>Tasks</h3><p>{list.length} total</p></div><button onClick={()=>start()}>+ NEW</button></div>{edit?<div className="adminx-form"><div className="adminx-grid"><Field label="Title" value={edit.title} set={(v:any)=>setEdit({...edit,title:v})}/><Field label="Reward WIENER" type="number" value={edit.reward} set={(v:any)=>setEdit({...edit,reward:Number(v)})}/><Select label="Placement" value={edit.category} set={(v:any)=>setEdit({...edit,category:v})} options={[["official","Official"],["exclusive","Exclusive"],["partner","Partner"]]}/><Select label="Type" value={edit.task_type} set={(v:any)=>setEdit({...edit,task_type:v})} options={[["telegram","Channel / Group"],["bot","Bot"]]}/><Field label="Task URL" value={edit.url||''} set={(v:any)=>setEdit({...edit,url:v})}/><Field label="Telegram @username / chat ID" value={edit.telegram_chat_id||''} set={(v:any)=>setEdit({...edit,telegram_chat_id:v})}/></div><label className="adminx-switch"><input type="checkbox" checked={edit.enabled!==false} onChange={e=>setEdit({...edit,enabled:e.target.checked})}/><span>Task enabled</span></label><div className="adminx-form-actions"><button onClick={()=>setEdit(null)}>CANCEL</button><button className="adminx-primary" disabled={busy} onClick={save}>SAVE TASK</button></div></div>:<div className="adminx-list">{list.map(x=><div key={x.id}><div><b>{x.title}</b><small>{String(x.category||'official').toUpperCase()} · {x.verification||'none'} · {x.completed_count||0} completions</small></div><div><strong>+{x.reward}</strong>{badge(x.enabled!==false,'ACTIVE','OFF')}<button onClick={()=>start(x)}>EDIT</button><button className="danger" onClick={async()=>{if(confirm(`Delete ${x.title}?`)){await api('admin_task_delete',{id:x.id});reload()}}}>DELETE</button></div></div>)}</div>}</section>}
function PromoManager({rows,say,reload}:{rows:any[];say:any;reload:any}){const [edit,setEdit]=useState<any>(null),[busy,setBusy]=useState(false);const start=(x:any=null)=>setEdit(x?{...x}:{code:'',reward:50,max_claims:100,expires_at:'',enabled:true});const save=async()=>{try{setBusy(true);const code=String(edit.code||'').trim().toUpperCase();if(code.length<4)throw Error('Promo code must be at least 4 characters');if(Number(edit.reward)<=0)throw Error('Reward must be above 0');await api('admin_promo_save',{promo:{...edit,code,reward:Number(edit.reward),max_claims:edit.max_claims===''?null:Number(edit.max_claims),expires_at:edit.expires_at||null}});say(`✅ Promo ${code} saved`);setEdit(null);await reload()}catch(e:any){say(e.message)}finally{setBusy(false)}};const list=Array.isArray(rows)?rows:[];return <section className="adminx-panel"><div className="adminx-panel-head"><div><span>CONTENT</span><h3>Promo Codes</h3><p>{list.length} total</p></div><button onClick={()=>start()}>+ NEW</button></div>{edit?<div className="adminx-form"><div className="adminx-grid"><Field label="Code" value={edit.code} set={(v:any)=>setEdit({...edit,code:String(v).toUpperCase()})}/><Field label="Reward WIENER" type="number" value={edit.reward} set={(v:any)=>setEdit({...edit,reward:Number(v)})}/><Field label="Claim limit" type="number" value={edit.max_claims??''} set={(v:any)=>setEdit({...edit,max_claims:v})}/><Field label="Expiry" type="datetime-local" value={edit.expires_at?String(edit.expires_at).slice(0,16):''} set={(v:any)=>setEdit({...edit,expires_at:v})}/></div><label className="adminx-switch"><input type="checkbox" checked={edit.enabled!==false} onChange={e=>setEdit({...edit,enabled:e.target.checked})}/><span>Promo enabled</span></label><div className="adminx-form-actions"><button onClick={()=>setEdit(null)}>CANCEL</button><button className="adminx-primary" disabled={busy} onClick={save}>SAVE PROMO</button></div></div>:<div className="adminx-list">{list.map(x=>{const expired=x.expires_at&&new Date(x.expires_at)<=new Date(),full=x.max_claims!=null&&Number(x.claims_count)>=Number(x.max_claims),active=x.enabled&&!expired&&!full;return <div key={x.code}><div><b>{x.code}</b><small>+{x.reward} WIENER · {x.claims_count}/{x.max_claims??'∞'} claims</small></div><div>{badge(active,'ACTIVE',expired?'EXPIRED':full?'FULL':'OFF')}<button onClick={()=>start(x)}>EDIT</button><button className="danger" onClick={async()=>{if(confirm(`Delete promo ${x.code}?`)){await api('admin_promo_delete',{code:x.code});reload()}}}>DELETE</button></div></div>})}</div>}</section>}

function MoneyCenter({d,setD,say,reload}:{d:any;setD:any;say:any;reload:any}){const [tab,setTab]=useState<MoneyTab>('treasury');return <div className="adminx-page"><Subnav value={tab} setValue={setTab} items={[["treasury","Main Treasury"],["withdrawals","Withdrawals"],["payouts","Payout Control"],["rewards","Rewards"],["internal","Internal Transfer"]]}/>{tab==='treasury'&&<section className="adminx-embed"><MainTreasuryAdmin say={say}/></section>} {tab==='withdrawals'&&<WithdrawalOverview rows={d.withdrawals||[]}/>} {tab==='rewards'&&<RewardSettings value={d.settings} setValue={(v:any)=>setD({...d,settings:v})} say={say} reload={reload}/>} {tab==='payouts'&&<section className="adminx-embed"><AdminWithdrawUpgrade say={say}/></section>} {tab==='internal'&&<section className="adminx-embed"><InternalTransferAdmin say={say}/></section>}</div>}
function WithdrawalOverview({rows}:{rows:any[]}){const [filter,setFilter]=useState('pending'),raw=Array.isArray(rows)?rows:[],list=raw.filter(x=>filter==='all'||x?.status===filter);return <section className="adminx-panel"><div className="adminx-kpis mini"><Kpi label="Pending" value={raw.filter(x=>x?.status==='pending').length} note="awaiting review"/><Kpi label="Paid" value={raw.filter(x=>x?.status==='paid').length} note="completed"/><Kpi label="Rejected" value={raw.filter(x=>x?.status==='rejected').length} note="declined"/><Kpi label="Total" value={raw.length} note="requests"/></div><div className="adminx-filter">{['pending','paid','rejected','all'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="adminx-list">{list.map(x=><div key={x.id}><div><b>{money(x.gross_usdt||0,4)} USDT · {x.network}</b><small>{x.username||`UID ${x.telegram_id}`} · {compactDate(x.created_at)}</small></div><div><strong>{money(x.receive_usdt||0,4)}</strong><span className={`aui-badge ${x.status==='paid'?'good':x.status==='rejected'?'bad':''}`}>{String(x.status).toUpperCase()}</span></div></div>)}</div></section>}
function RewardSettings({value,setValue,say,reload}:{value:any;setValue:any;say:any;reload:any}){const [busy,setBusy]=useState(false);const val=(value&&typeof value==='object')?value:{};const f=(k:string,v:any)=>setValue({...val,[k]:v}),daily=Array.isArray(val.daily_rewards)?val.daily_rewards:[3,4,5,6,7,8,14];const save=async()=>{try{setBusy(true);await api('admin_settings_save',{settings:val});say('✅ Reward settings saved');await reload()}catch(e:any){say(e.message)}finally{setBusy(false)}};return <section className="adminx-panel"><div className="adminx-panel-head"><div><span>ECONOMY</span><h3>Reward configuration</h3><p>Uses the existing settings API.</p></div></div><div className="adminx-grid"><Field label="Farm claim reward" type="number" value={val.farm_claim_reward} set={(v:any)=>f('farm_claim_reward',Number(v))}/><Field label="Farm cooldown seconds" type="number" value={val.farm_claim_cooldown_seconds} set={(v:any)=>f('farm_claim_cooldown_seconds',Number(v))}/><Field label="Ad reward" type="number" value={val.ad_reward} set={(v:any)=>f('ad_reward',Number(v))}/><Field label="Daily ad limit" type="number" value={val.daily_ad_limit} set={(v:any)=>f('daily_ad_limit',Number(v))}/><Field label="Verified referral reward" type="number" value={val.referral_active_reward} set={(v:any)=>f('referral_active_reward',Number(v))}/><Field label="Ads required for referral" type="number" value={val.referral_active_ads_required} set={(v:any)=>f('referral_active_ads_required',Number(v))}/><Field label="Lifetime commission %" type="number" value={val.referral_commission_percent} set={(v:any)=>f('referral_commission_percent',Number(v))}/><Field label="WIENER per USDT" type="number" value={val.token_per_usdt} set={(v:any)=>f('token_per_usdt',Number(v))}/></div><h4 className="adminx-subtitle">Daily rewards</h4><div className="adminx-days">{daily.map((x:any,i:number)=><label key={i}><span>Day {i+1}</span><input type="number" value={x} onChange={e=>{const z=[...daily];z[i]=Number(e.target.value||0);f('daily_rewards',z)}}/></label>)}</div><button className="adminx-primary wide" disabled={busy} onClick={save}>{busy?'SAVING…':'SAVE REWARD SETTINGS'}</button></section>}

function SystemCenter({d,setD,say,reload}:{d:any;setD:any;say:any;reload:any}){const [tab,setTab]=useState<SystemTab>('controls');return <div className="adminx-page"><Subnav value={tab} setValue={setTab} items={[["controls","App Controls"],["identity","Identity"],["admins","Admins"],["audit","Audit"]]}/>{tab==='controls'&&<SystemControls value={d.settings} setValue={(v:any)=>setD({...d,settings:v})} say={say} reload={reload}/>} {tab==='identity'&&<Identity value={d.settings} setValue={(v:any)=>setD({...d,settings:v})} say={say} reload={reload}/>} {tab==='admins'&&<AdminManager rows={d.admins||[]} say={say} reload={reload}/>} {tab==='audit'&&<Audit rows={d.audit||[]}/>}</div>}
function SystemControls({value,setValue,say,reload}:{value:any;setValue:any;say:any;reload:any}){const [busy,setBusy]=useState(false);const val=(value&&typeof value==='object')?value:{};const f=(k:string,v:any)=>setValue({...val,[k]:v});const save=async()=>{try{setBusy(true);await api('admin_settings_save',{settings:val});say('✅ System controls saved');await reload()}catch(e:any){say(e.message)}finally{setBusy(false)}};return <section className="adminx-panel"><div className="adminx-panel-head"><div><span>LIVE CONTROLS</span><h3>Modules</h3><p>Disable a module without deleting configuration.</p></div></div><div className="adminx-switches"><Switch label="Maintenance" note="Blocks normal users" value={!!val.maintenance_enabled} set={(v:boolean)=>f('maintenance_enabled',v)}/><Switch label="Withdrawals" value={!!val.withdrawals_enabled} set={(v:boolean)=>f('withdrawals_enabled',v)}/><Switch label="Ads" value={!!val.ads_enabled} set={(v:boolean)=>f('ads_enabled',v)}/><Switch label="Tasks" value={!!val.tasks_enabled} set={(v:boolean)=>f('tasks_enabled',v)}/><Switch label="Promo Codes" value={!!val.promo_enabled} set={(v:boolean)=>f('promo_enabled',v)}/><Switch label="Referrals" value={!!val.referrals_enabled} set={(v:boolean)=>f('referrals_enabled',v)}/></div><Field label="Maintenance message" value={val.maintenance_message||''} set={(v:any)=>f('maintenance_message',v)}/><button className="adminx-primary wide" disabled={busy} onClick={save}>SAVE APP CONTROLS</button></section>}
function Identity({value,setValue,say,reload}:{value:any;setValue:any;say:any;reload:any}){const [busy,setBusy]=useState(false);const val=(value&&typeof value==='object')?value:{};const f=(k:string,v:any)=>setValue({...val,[k]:v});const save=async()=>{try{setBusy(true);await api('admin_settings_save',{settings:val});say('✅ Identity settings saved');await reload()}catch(e:any){say(e.message)}finally{setBusy(false)}};return <section className="adminx-panel"><div className="adminx-panel-head"><div><span>INTEGRATIONS</span><h3>App identity</h3></div></div><div className="adminx-grid"><Field label="App name" value={val.app_name} set={(v:any)=>f('app_name',v)}/><Field label="Bot username" value={val.bot_username} set={(v:any)=>f('bot_username',v)}/><Field label="Production app URL" value={val.app_url} set={(v:any)=>f('app_url',v)}/><Field label="Support URL" value={val.support_url} set={(v:any)=>f('support_url',v)}/><Field label="Payout channel" value={val.payout_channel} set={(v:any)=>f('payout_channel',v)}/><Field label="AdsGram block ID" value={val.adsgram_block_id} set={(v:any)=>f('adsgram_block_id',v)}/></div><button className="adminx-primary wide" disabled={busy} onClick={save}>SAVE IDENTITY</button></section>}
function AdminManager({rows,say,reload}:{rows:any[];say:any;reload:any}){const [uid,setUid]=useState(''),[busy,setBusy]=useState(false);const add=async()=>{const id=Number(uid);if(!id)return say('Enter a valid Telegram UID');try{setBusy(true);await api('admin_admin_save',{telegram_id:id,role:'admin',enabled:true,permissions:{}});say('✅ Admin added');setUid('');await reload()}catch(e:any){say(e.message)}finally{setBusy(false)}};const list=Array.isArray(rows)?rows:[];return <section className="adminx-panel"><div className="adminx-panel-head"><div><span>ACCESS</span><h3>Admins</h3><p>Owner cannot be removed here.</p></div></div><div className="adminx-inline"><input type="number" placeholder="Telegram UID" value={uid} onChange={e=>setUid(e.target.value)}/><button className="adminx-primary" disabled={busy} onClick={add}>ADD ADMIN</button></div><div className="adminx-list">{list.map(x=><div key={x.telegram_id}><div><b>UID {x.telegram_id}</b><small>{x.role} · {x.enabled?'enabled':'disabled'}</small></div><div>{badge(x.enabled,String(x.role).toUpperCase(),'DISABLED')}{x.role!=='owner'&&<button className="danger" onClick={async()=>{if(confirm(`Remove admin ${x.telegram_id}?`)){await api('admin_admin_delete',{telegram_id:x.telegram_id});reload()}}}>REMOVE</button>}</div></div>)}</div></section>}
function Audit({rows}:{rows:any[]}){const [q,setQ]=useState(''),raw=Array.isArray(rows)?rows:[],list=raw.filter(x=>`${x?.action||''} ${x?.actor_telegram_id||''} ${x?.target_id||''}`.toLowerCase().includes(q.toLowerCase()));return <section className="adminx-panel"><div className="adminx-panel-head"><div><span>SECURITY</span><h3>Audit log</h3><p>Latest sensitive actions.</p></div></div><input className="adminx-search" placeholder="Filter action / UID" value={q} onChange={e=>setQ(e.target.value)}/><div className="adminx-audit">{list.map(x=><div key={x.id}><b>{x.action}</b><small>{x.actor_telegram_id||'system'} · {compactDate(x.created_at)}</small><code>{typeof x.details==='object'?JSON.stringify(x.details):String(x.details||'')}</code></div>)}</div></section>}

function Subnav({value,setValue,items}:{value:any;setValue:any;items:any[]}){return <div className="adminx-subnav">{items.map(([k,l])=><button key={k} className={value===k?'active':''} onClick={()=>setValue(k)}>{l}</button>)}</div>}
function Field({label,value,set,type='text'}:{label:string;value:any;set:any;type?:string}){return <label className="adminx-field"><span>{label}</span><input type={type} value={value??''} onChange={e=>set(e.target.value)}/></label>}
function Select({label,value,set,options}:{label:string;value:any;set:any;options:any[]}){return <label className="adminx-field"><span>{label}</span><select value={value} onChange={e=>set(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Switch({label,note,value,set}:{label:string;note?:string;value:boolean;set:any}){return <label className="adminx-switch"><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/><div><b>{label}</b>{note&&<small>{note}</small>}</div><span>{value?'ON':'OFF'}</span></label>}
function Card({title,children}:{title:string;children:any}){return <div className="aui-card"><h4>{title}</h4>{children}</div>}
function Line({k,v}:{k:string;v:any}){return <div className="aui-line"><span>{k}</span><b>{v??'—'}</b></div>}
function Empty(){return <div className="aui-empty">No records found.</div>}
