import {useEffect,useRef,useState} from 'react';
import {api,getInitData,pageFromUrl,registerDevice,type Snapshot,type Tab} from './lib';
import {Admin} from './AdminV2';
import {Ads} from './AdsPage';
import {Invite} from './InviteShare';
import {MandatoryAdmin,MandatoryGate,checkMandatoryAccess} from './MandatoryJoin';
import {ClaimPage,DailyPage,LeaderboardPage,ProfilePage} from './pages';
import {HomeWithPromo} from './PromoClaim';
import {Tasks} from './TasksPage';
import {WalletV2,AdminWithdrawUpgrade} from './WithdrawV2';
import {Brand,Nav,OpenTelegram,Splash,StateScreen} from './ui';
import {trackAdInteraction} from './adInteraction';

function MultiAccountBlocked(){const support=()=>window.Telegram?.WebApp?.openTelegramLink?.('https://t.me/WienerSupport');return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:'24px',background:'radial-gradient(circle at 50% 42%,rgba(24,108,63,.28),transparent 36%),#002b18'}}><div style={{width:'min(100%,400px)',padding:'42px 28px',textAlign:'center',borderRadius:'36px',border:'1px solid rgba(255,255,255,.16)',background:'linear-gradient(145deg,rgba(255,255,255,.10),rgba(255,255,255,.045))',boxShadow:'inset 0 1px 0 rgba(255,255,255,.12),0 28px 70px rgba(0,0,0,.28)',backdropFilter:'blur(26px)',WebkitBackdropFilter:'blur(26px)'}}><div style={{fontSize:'70px',lineHeight:1}}>🚫</div><h1 style={{margin:'26px 0 8px',fontSize:'30px',letterSpacing:'-.7px'}}>Account Blocked</h1><p style={{margin:'0 auto',maxWidth:'290px',fontSize:'15px',lineHeight:1.55,opacity:.62}}>Multiple accounts detected on this device.<br/>Only one WIENER Farm account is allowed per device.</p><p style={{margin:'22px 0 14px',fontSize:'12px',opacity:.55}}>Think this is a mistake?</p><button onClick={support} style={{width:'100%',height:'58px',border:0,borderRadius:'18px',background:'linear-gradient(180deg,#fff05d,#ffd20b 64%,#eeb900)',color:'#211b00',fontSize:'14px',fontWeight:950}}>CONTACT SUPPORT</button></div></div>}
function App(){
 const [tab,setTab]=useState<Tab>(()=>pageFromUrl()),[data,setData]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState(''),[mandatory,setMandatory]=useState<any>(null),[multiBlocked,setMultiBlocked]=useState(false),[farmWarning,setFarmWarning]=useState(false);const openedSent=useRef(false);
 const refresh=async()=>{try{setError('');const d=await api('bootstrap');setData(d);return d}catch(e:any){setError(e.message);return null}};
 useEffect(()=>{const t=window.Telegram?.WebApp;t?.ready?.();t?.expand?.();(async()=>{const d=await refresh();if(d){if(!d.is_admin){try{const device:any=await registerDevice();setMultiBlocked(device?.blocked===true)}catch(e:any){const m=String(e?.message||'');if(/multiple|same_or_reused_device|device.*linked|device.*account/i.test(m))setMultiBlocked(true)}}else setMultiBlocked(false);if(!d.is_admin){try{setMandatory(await checkMandatoryAccess())}catch{setMandatory({all_joined:true,items:[]})}}else setMandatory({all_joined:true,items:[]})}setLoading(false)})()},[]);
 useEffect(()=>{if(data&&!openedSent.current){openedSent.current=true;api('app_opened').catch(()=>{})}},[data]);
 const say=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2200)};
 const run=async(action:string,b:any={},ok='Done')=>{try{await api(action,b);say(ok);await refresh()}catch(e:any){say(e.message)}};
 const runFarm=async(action:string,b:any={},ok='Done')=>{if(action!=='farm_claim')return run(action,b,ok);if(!data)return;const interaction=trackAdInteraction();try{if(!data.settings.adsgram_block_id)throw Error('AdsGram Block ID is not configured');const c=window.Adsgram?.init({blockId:String(data.settings.adsgram_block_id)});if(!c)throw Error('AdsGram SDK unavailable');interaction.start();const result=await c.show();if(result&&result.done===false)throw Error(result.description||'Ad was not completed');if(!interaction.interacted()){setFarmWarning(true);return}const r=await api('farm_claim',b);say(`+${Number(r?.reward||data.settings.farm_claim_reward||0)} WIENER claimed`);await refresh()}catch(e:any){say(String(e?.message||'Complete the ad and try again.'))}finally{interaction.stop()}};
 if(loading)return <Splash text="Securing WIENER…"/>;if(!getInitData())return <OpenTelegram/>;if(multiBlocked)return <MultiAccountBlocked/>;if(error.includes('banned'))return <StateScreen icon="⛔" title="Account restricted" text="Your WIENER account is currently unavailable."/>;if(error&&!data)return <StateScreen icon="⚠" title="Unable to open" text={error}/>;if(data?.settings?.maintenance_enabled&&!data.is_admin)return <StateScreen icon="🛠" title="Maintenance" text={data.settings.maintenance_message}/>;if(!data)return null;if(!data.is_admin&&mandatory&&!mandatory.all_joined)return <MandatoryGate initial={mandatory} onUnlocked={()=>setMandatory((x:any)=>({...x,all_joined:true}))}/>;
 return <div className="app-shell"><Brand data={data}/><main className="content">{tab==='home'&&<HomeWithPromo data={data} run={runFarm} setTab={setTab} refresh={refresh} say={say}/>} {tab==='ads'&&<Ads data={data} refresh={refresh} say={say}/>} {tab==='tasks'&&<Tasks data={data} run={run} say={say} refresh={refresh}/>} {tab==='invite'&&<Invite data={data} say={say}/>} {tab==='wallet'&&<WalletV2 data={data} setTab={setTab}/>} {tab==='daily'&&<DailyPage data={data} run={run}/>} {tab==='claim'&&<ClaimPage data={data} run={runFarm}/>} {tab==='leaderboard'&&<LeaderboardPage data={data}/>} {tab==='profile'&&<ProfilePage data={data} setTab={setTab}/>} {tab==='admin'&&data.is_admin&&<><MandatoryAdmin say={say}/><AdminWithdrawUpgrade say={say}/><Admin say={say}/></>}</main><Nav tab={tab} setTab={setTab} admin={data.is_admin}/>{farmWarning&&<div style={{position:'fixed',inset:0,zIndex:10050,display:'grid',placeItems:'center',padding:28,background:'rgba(0,22,12,.72)',backdropFilter:'blur(8px)'}}><div style={{width:'min(100%,300px)',padding:'18px 16px 16px',textAlign:'center',border:'1.5px solid #ffd91a',borderRadius:18,background:'linear-gradient(180deg,rgba(25,79,54,.98),rgba(11,61,39,.98))'}}><div style={{width:44,height:44,margin:'0 auto 13px',display:'grid',placeItems:'center',border:'1.5px solid rgba(255,217,26,.45)',borderRadius:12,fontSize:25,color:'#ffd91a'}}>⚠</div><div style={{margin:'0 auto 16px',maxWidth:245,fontSize:16,lineHeight:1.28,fontWeight:900,color:'#ffd91a'}}>YOU MUST CLICK ON ADS BANNER TO CLAIM REWARD</div><button style={{width:'100%',minHeight:42,border:0,borderRadius:11,background:'linear-gradient(180deg,#ffe54d,#ffc900)',color:'#211b00',fontSize:14,fontWeight:900}} onClick={()=>setFarmWarning(false)}>CLOSE</button></div></div>}{toast&&<div className="toast">{toast}</div>}</div>
}
export default App;
