import {useEffect,useRef,useState} from 'react';
import {api,getInitData,pageFromUrl,registerDevice,type Snapshot,type Tab} from './lib';
import {AdminHub} from './AdminHub';
import {AdminPromoCreator} from './AdminPromoCreator';
import {AdminMiniAppTaskCreator} from './AdminMiniAppTaskCreator';
import {AdminSpecialTasks} from './AdminSpecialTasks';
import {EconomyUiPatch} from './EconomyUiPatch';
import {Ads} from './AdsPage';
import {Invite} from './InviteShare';
import {MandatoryGate,checkMandatoryAccess} from './MandatoryJoin';
import {ClaimPage,DailyPage} from './pages';
import {LeaderboardPageV2,ProfilePageV2} from './ProfileLeaderboardV2';
import {HomeWithPromo} from './PromoClaim';
import {Tasks} from './TasksPage';
import {SpecialTasks} from './SpecialTasks';
import {WalletV2} from './WithdrawV2';
import {Brand,Nav,OpenTelegram,Splash,StateScreen} from './ui';
import {FarmClaimModal} from './FarmClaimModal';
import {TreasuryPage} from './Treasury';
import {useI18n} from './i18n';
import {RestrictedSticker} from './RestrictedSticker';

function RestrictedScreen({reason='Suspicious or multiple-account activity detected.'}:{reason?:string}){const support=()=>window.Telegram?.WebApp?.openTelegramLink?.('https://t.me/WienerSupport');return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:'24px 18px 34px',background:'radial-gradient(circle at 50% 24%,rgba(255,55,55,.17),transparent 30%),radial-gradient(circle at 50% 75%,rgba(255,190,0,.07),transparent 34%),#03130d',color:'#fff'}}><div style={{width:'min(100%,410px)',textAlign:'center'}}><div style={{width:'148px',height:'148px',margin:'0 auto 22px',display:'grid',placeItems:'center',borderRadius:'50%',background:'radial-gradient(circle,rgba(255,65,65,.22),rgba(255,65,65,.04) 58%,transparent 72%)',filter:'drop-shadow(0 0 26px rgba(255,57,57,.28))'}}><RestrictedSticker/></div><div style={{fontSize:'11px',fontWeight:900,letterSpacing:'2.4px',color:'#ff8b8b',textTransform:'uppercase'}}>WIENER FARM SECURITY</div><h1 style={{margin:'10px 0 10px',fontSize:'31px',fontWeight:950,letterSpacing:'-.8px',color:'#ff6868',textShadow:'0 0 22px rgba(255,67,67,.2)'}}>ACCOUNT RESTRICTED</h1><p style={{margin:'0 auto',maxWidth:'330px',fontSize:'14px',lineHeight:1.6,color:'rgba(255,255,255,.64)'}}>{reason}</p><div style={{marginTop:'28px',padding:'22px 20px',textAlign:'left',borderRadius:'24px',border:'1px solid rgba(255,194,77,.2)',background:'linear-gradient(145deg,rgba(255,255,255,.075),rgba(255,255,255,.025))',boxShadow:'inset 0 1px 0 rgba(255,255,255,.08),0 22px 55px rgba(0,0,0,.28)',backdropFilter:'blur(24px)',WebkitBackdropFilter:'blur(24px)'}}><div style={{display:'flex',gap:'11px',alignItems:'center',fontSize:'18px',fontWeight:900}}><span style={{fontSize:'22px'}}>✉️</span>Need Help?</div><p style={{margin:'12px 0 0',fontSize:'13px',lineHeight:1.65,color:'rgba(255,255,255,.57)'}}>If you believe this restriction is a mistake, contact WIENER Support with your Telegram user ID and a short explanation. Your account can be reviewed manually.</p></div><button onClick={support} style={{marginTop:'18px',width:'100%',height:'60px',border:0,borderRadius:'19px',background:'linear-gradient(180deg,#ffe85a,#ffc900 62%,#e5ad00)',boxShadow:'0 14px 34px rgba(255,194,0,.22),inset 0 1px 0 rgba(255,255,255,.62)',color:'#1f1a00',fontSize:'15px',fontWeight:950,letterSpacing:'.2px'}}>💬 CONTACT SUPPORT</button><div style={{marginTop:'16px',fontSize:'12px',fontWeight:700,color:'rgba(255,255,255,.38)'}}>Support: @WienerSupport</div></div></div>}
function MultiAccountBlocked(){return <RestrictedScreen reason="Multiple accounts appear to be linked to this device. Only one WIENER Farm account is allowed per device."/>}
function App(){
 const {t}=useI18n();
 const [tab,setTab]=useState<Tab>(()=>pageFromUrl()),[data,setData]=useState<Snapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState(''),[mandatory,setMandatory]=useState<any>(null),[multiBlocked,setMultiBlocked]=useState(false),[farmClaimOpen,setFarmClaimOpen]=useState(false);const openedSent=useRef(false),openAdShown=useRef(false);
 const refresh=async()=>{try{setError('');const d=await api('bootstrap');setData(d);return d}catch(e:any){setError(e.message);return null}};
 useEffect(()=>{const tg=window.Telegram?.WebApp;tg?.ready?.();tg?.expand?.();(async()=>{const d=await refresh();if(d){if(!d.is_admin){try{const device:any=await registerDevice();setMultiBlocked(device?.blocked===true)}catch(e:any){const m=String(e?.message||'');if(/multiple|same_or_reused_device|device.*linked|device.*account/i.test(m))setMultiBlocked(true)}}else setMultiBlocked(false);if(!d.is_admin){try{setMandatory(await checkMandatoryAccess())}catch{setMandatory({all_joined:true,items:[]})}}else setMandatory({all_joined:true,items:[]})}setLoading(false)})()},[]);
 useEffect(()=>{if(data&&!openedSent.current){openedSent.current=true;api('app_opened').catch(()=>{})}},[data]);
 useEffect(()=>{if(loading||!data||multiBlocked||error||!mandatory?.all_joined||openAdShown.current)return;let cancelled=false;const timer=window.setTimeout(async()=>{if(cancelled||openAdShown.current)return;try{let tries=0;while(!window.Adsgram?.init&&tries<10&&!cancelled){await new Promise(r=>setTimeout(r,200));tries++}if(cancelled||!window.Adsgram?.init)return;const controller=window.Adsgram.init({blockId:'int-44861'});if(!controller)return;openAdShown.current=true;await controller.show()}catch(e){console.warn('opening_interstitial_failed',e)}},2000);return()=>{cancelled=true;window.clearTimeout(timer)}},[loading,multiBlocked,error,mandatory?.all_joined]);
 const say=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2200)};
 const run=async(action:string,b:any={},ok=t('common.done'))=>{try{await api(action,b);say(ok);await refresh()}catch(e:any){say(e.message)}};
 const runFarm=async(action:string,b:any={},ok=t('common.done'))=>{if(action!=='farm_claim')return run(action,b,ok);if(!data)return;setFarmClaimOpen(true)};
 if(loading)return <Splash text="Securing WIENER…"/>;if(!getInitData())return <OpenTelegram/>;if(multiBlocked)return <MultiAccountBlocked/>;if(error.includes('banned'))return <RestrictedScreen reason="This WIENER Farm account is currently restricted. If you believe this is a mistake, request a manual review."/>;if(error&&!data)return <StateScreen icon="⚠" title={t('system.unable')} text={error}/>;if(data?.settings?.maintenance_enabled&&!data.is_admin)return <StateScreen icon="🛠" title={t('system.maintenance')} text={data.settings.maintenance_message}/>;if(!data)return null;if(!data.is_admin&&mandatory&&!mandatory.all_joined)return <MandatoryGate initial={mandatory} onUnlocked={()=>setMandatory((x:any)=>({...x,all_joined:true}))}/>;
 return <div className="app-shell"><EconomyUiPatch/><Brand data={data}/><main className="content">{tab==='home'&&<HomeWithPromo data={data} run={runFarm} setTab={setTab} refresh={refresh} say={say}/>} {tab==='ads'&&<Ads data={data} refresh={refresh} say={say}/>} {tab==='tasks'&&<><SpecialTasks data={data} say={say} refresh={refresh}/><Tasks data={data} run={run} say={say} refresh={refresh}/></>} {tab==='invite'&&<Invite data={data} say={say}/>} {tab==='wallet'&&<WalletV2 data={data} setTab={setTab}/>} {tab==='daily'&&<DailyPage data={data} run={run}/>} {tab==='claim'&&<ClaimPage data={data} run={runFarm}/>} {tab==='leaderboard'&&<LeaderboardPageV2 data={data}/>} {tab==='profile'&&<ProfilePageV2 data={data} setTab={setTab}/>} {tab==='treasury'&&<TreasuryPage data={data} refresh={refresh} say={say} setTab={setTab}/>} {tab==='admin'&&data.is_admin&&<><AdminHub say={say}/><AdminSpecialTasks say={say}/><AdminMiniAppTaskCreator say={say}/><AdminPromoCreator say={say}/></>}</main><Nav tab={tab} setTab={setTab} admin={data.is_admin}/><FarmClaimModal open={farmClaimOpen} data={data} onClose={()=>setFarmClaimOpen(false)} refresh={refresh} say={say}/>{toast&&<div className="toast">{toast}</div>}</div>
}
export default App;
