import {useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {api,type Snapshot} from './lib';

export function DailyBioClaimGate({open,data,run,onClose,successMessage}:{open:boolean;data:Snapshot;run:any;onClose:()=>void;successMessage:string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 const link=useMemo(()=>{const bot=String(data.settings?.bot_username||'@WienerDogeFarmBot').replace(/^@/,'');return `https://t.me/${bot}?startapp=ref_${data.user.telegram_id}`},[data.settings?.bot_username,data.user.telegram_id]);
 if(!open)return null;
 const copy=async()=>{try{await navigator.clipboard.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{try{const el=document.createElement('textarea');el.value=link;el.style.position='fixed';el.style.opacity='0';document.body.appendChild(el);el.select();document.execCommand('copy');el.remove();setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{setError('Could not copy the link. Press and hold the link to copy it.')}}};
 const check=async()=>{if(busy)return;try{setBusy(true);setError('');await api('daily_bio_check');await run('daily_claim',{},successMessage);onClose()}catch(e:any){const raw=String(e?.message||e||'').replace(/_/g,' ');setError(/bio|referral link|daily/i.test(raw)?'Referral link not found in your Telegram bio yet. Add the exact link below, make your bio visible, then try again.':raw)}finally{setBusy(false)}};
 const modal=<div className="daily-bio-backdrop" role="dialog" aria-modal="true" aria-label="Daily reward requirement"><style>{`
.daily-bio-backdrop{position:fixed!important;inset:0!important;z-index:2147483000!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:20px 16px calc(20px + env(safe-area-inset-bottom))!important;background:rgba(10,4,1,.74)!important;backdrop-filter:blur(16px)!important;-webkit-backdrop-filter:blur(16px)!important}
.daily-bio-card{position:relative;width:min(100%,370px);max-height:min(82vh,650px);overflow:auto;padding:23px 18px 18px;border-radius:28px;border:1px solid rgba(255,151,32,.55);background:radial-gradient(circle at 50% -12%,rgba(255,145,20,.28),transparent 37%),linear-gradient(165deg,#281108 0%,#180b07 58%,#100805 100%);box-shadow:0 26px 80px rgba(0,0,0,.64),0 0 0 1px rgba(255,118,12,.08),inset 0 1px 0 rgba(255,255,255,.1);text-align:center;color:#fff}
.daily-bio-close{position:absolute;right:14px;top:14px;width:34px!important;height:34px!important;min-height:34px!important;padding:0!important;border-radius:50%!important;border:1px solid rgba(255,151,32,.28)!important;background:rgba(255,119,12,.08)!important;color:#ffbd72!important;font-size:21px!important;line-height:1!important;font-weight:500!important}
.daily-bio-icon{width:56px;height:56px;margin:1px auto 12px;border-radius:18px;display:grid;place-items:center;border:1px solid rgba(255,151,32,.32);background:linear-gradient(160deg,rgba(255,139,17,.18),rgba(255,105,5,.06));box-shadow:inset 0 1px 0 rgba(255,255,255,.06);font-size:24px;color:#ff9f26}
.daily-bio-card h3{margin:0;font-size:22px;font-weight:950;letter-spacing:-.35px}.daily-bio-sub{margin:8px auto 16px;max-width:325px;font-size:12px;line-height:1.55;color:rgba(255,236,218,.61)}
.daily-bio-steps{display:grid;gap:9px;text-align:left;margin:0 0 14px}.daily-bio-step{display:grid;grid-template-columns:30px 1fr;gap:10px;align-items:center;padding:10px 11px;border-radius:15px;background:rgba(255,255,255,.025);border:1px solid rgba(255,139,23,.09);font-size:12px;line-height:1.45;color:rgba(255,245,235,.9)}.daily-bio-step b{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:rgba(255,132,12,.13);border:1px solid rgba(255,153,30,.27);color:#ffab40;font-size:12px}.daily-bio-step strong{color:#ffb14b}
.daily-bio-link{display:flex;align-items:center;gap:8px;padding:12px 12px;border-radius:16px;border:1px solid rgba(255,142,24,.25);background:rgba(0,0,0,.22);text-align:left}.daily-bio-link code{min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px;color:#ffd0a0}.daily-bio-copy{width:auto!important;min-width:62px!important;min-height:34px!important;padding:5px 8px!important;border:0!important;background:transparent!important;color:#ff9f25!important;font-size:11px!important;font-weight:950!important}
.daily-bio-warning{margin:11px 0 13px;padding:10px 11px;border-radius:14px;border:1px solid rgba(255,153,42,.18);background:rgba(255,119,12,.06);font-size:10px;line-height:1.45;color:rgba(255,210,164,.78)}.daily-bio-error{margin:0 0 11px;padding:9px 10px;border-radius:12px;background:rgba(255,76,76,.09);border:1px solid rgba(255,96,96,.2);color:#ffb0b0;font-size:10px;line-height:1.4}.daily-bio-actions{display:grid;grid-template-columns:.78fr 1.22fr;gap:9px}.daily-bio-actions button{min-height:48px;border-radius:16px;font-weight:950}.daily-bio-later{border:1px solid rgba(255,151,32,.13);background:rgba(255,255,255,.035);color:rgba(255,236,218,.7)}.daily-bio-check{border:1px solid rgba(255,194,107,.45);background:linear-gradient(180deg,#ffb52d,#ff8816 55%,#ed6900);color:#2b1100;box-shadow:0 10px 26px rgba(255,111,0,.24),inset 0 1px 0 rgba(255,255,255,.45)}.daily-bio-check:disabled{opacity:.55}
@media(max-height:680px){.daily-bio-card{max-height:88vh;padding-top:19px}.daily-bio-icon{width:48px;height:48px;margin-bottom:9px}.daily-bio-card h3{font-size:20px}.daily-bio-sub{margin-bottom:12px}.daily-bio-step{padding:8px 9px}.daily-bio-warning{margin:9px 0 10px}}
`}</style><div className="daily-bio-card"><button type="button" className="daily-bio-close" onClick={onClose} disabled={busy} aria-label="Close">×</button><div className="daily-bio-icon">↗</div><h3>Add your link to claim</h3><p className="daily-bio-sub">To claim your Daily WIENER, add your personal WIENER Farm referral link to your Telegram bio.</p><div className="daily-bio-steps"><div className="daily-bio-step"><b>1</b><span>Copy your referral link below.</span></div><div className="daily-bio-step"><b>2</b><span>Open Telegram → Profile → Edit → Bio, then paste the link.</span></div><div className="daily-bio-step"><b>3</b><span>Come back and tap <strong>Check & claim</strong>.</span></div></div><div className="daily-bio-link"><code>{link}</code><button type="button" className="daily-bio-copy" onClick={copy}>{copied?'COPIED':'COPY'}</button></div><div className="daily-bio-warning">⚠️ Keep your Telegram bio visible so WIENER Farm can verify the link. If you just changed it, wait a few seconds and check again.</div>{error&&<div className="daily-bio-error">{error}</div>}<div className="daily-bio-actions"><button type="button" className="daily-bio-later" disabled={busy} onClick={onClose}>Later</button><button type="button" className="daily-bio-check" disabled={busy} onClick={check}>{busy?'CHECKING…':'Check & claim'}</button></div></div></div>;
 return createPortal(modal,document.body);
}
