import {useMemo,useState} from 'react';
import {api,type Snapshot} from './lib';

export function DailyBioClaimGate({open,data,run,onClose,successMessage}:{open:boolean;data:Snapshot;run:any;onClose:()=>void;successMessage:string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 const link=useMemo(()=>{const bot=String(data.settings?.bot_username||'@WienerDogeFarmBot').replace(/^@/,'');return `https://t.me/${bot}?startapp=ref_${data.user.telegram_id}`},[data.settings?.bot_username,data.user.telegram_id]);
 if(!open)return null;
 const copy=async()=>{try{await navigator.clipboard.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{try{const el=document.createElement('textarea');el.value=link;el.style.position='fixed';el.style.opacity='0';document.body.appendChild(el);el.select();document.execCommand('copy');el.remove();setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{setError('Could not copy the link. Press and hold the link to copy it.')}}};
 const check=async()=>{if(busy)return;try{setBusy(true);setError('');await api('daily_bio_check');await run('daily_claim',{},successMessage);onClose()}catch(e:any){const raw=String(e?.message||e||'').replace(/_/g,' ');setError(/bio|referral link|daily/i.test(raw)?'Referral link not found in your Telegram bio yet. Add the exact link below, make your bio visible, then try again.':raw)}finally{setBusy(false)}};
 return <div className="daily-bio-backdrop" role="dialog" aria-modal="true" aria-label="Daily reward requirement"><style>{`
.daily-bio-backdrop{position:fixed;inset:0;z-index:13050;display:grid;place-items:center;padding:18px;background:rgba(2,11,8,.82);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px)}
.daily-bio-card{width:min(100%,390px);max-height:88vh;overflow:auto;padding:22px 18px 18px;border-radius:26px;border:1px solid rgba(255,215,66,.34);background:radial-gradient(circle at 50% 0,rgba(255,196,25,.13),transparent 35%),linear-gradient(165deg,rgba(18,55,40,.99),rgba(5,28,20,.99));box-shadow:0 26px 70px rgba(0,0,0,.48),inset 0 1px 0 rgba(255,255,255,.08);text-align:center;color:#fff}
.daily-bio-icon{width:58px;height:58px;margin:0 auto 13px;border-radius:18px;display:grid;place-items:center;border:1px solid rgba(255,210,54,.28);background:rgba(255,198,25,.08);font-size:26px;color:#ffd33d}
.daily-bio-card h3{margin:0;font-size:21px;font-weight:950;letter-spacing:-.25px}.daily-bio-sub{margin:8px auto 15px;max-width:330px;font-size:12px;line-height:1.55;color:rgba(255,255,255,.62)}
.daily-bio-steps{display:grid;gap:9px;text-align:left;margin:0 2px 14px}.daily-bio-step{display:grid;grid-template-columns:27px 1fr;gap:10px;align-items:start;font-size:12px;line-height:1.48}.daily-bio-step b{width:27px;height:27px;border-radius:50%;display:grid;place-items:center;background:rgba(255,211,61,.1);border:1px solid rgba(255,211,61,.24);color:#ffd94e;font-size:11px}
.daily-bio-link{display:flex;align-items:center;gap:8px;padding:11px 12px;border-radius:15px;border:1px solid rgba(255,213,66,.21);background:rgba(0,0,0,.17);text-align:left}.daily-bio-link code{min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px;color:#ffe8a4}.daily-bio-copy{width:auto!important;min-width:58px!important;min-height:32px!important;padding:5px 8px!important;border:0!important;background:transparent!important;color:#ffd744!important;font-size:11px!important;font-weight:900!important}
.daily-bio-warning{margin:11px 0 13px;padding:10px 11px;border-radius:14px;border:1px solid rgba(255,203,59,.18);background:rgba(255,190,32,.055);font-size:10px;line-height:1.45;color:rgba(255,234,169,.78)}.daily-bio-error{margin:0 0 11px;padding:9px 10px;border-radius:12px;background:rgba(255,76,76,.09);border:1px solid rgba(255,96,96,.2);color:#ffb0b0;font-size:10px;line-height:1.4}.daily-bio-actions{display:grid;grid-template-columns:.85fr 1.35fr;gap:9px}.daily-bio-actions button{min-height:46px;border-radius:15px;font-weight:950}.daily-bio-later{border:1px solid rgba(255,255,255,.08);background:rgba(0,0,0,.18);color:rgba(255,255,255,.68)}.daily-bio-check{border:0;background:linear-gradient(180deg,#75ef48,#36b91f);color:#062906;box-shadow:0 9px 24px rgba(67,205,39,.18),inset 0 1px 0 rgba(255,255,255,.35)}.daily-bio-check:disabled{opacity:.55}
`}</style><div className="daily-bio-card"><div className="daily-bio-icon">↗</div><h3>Add your link to claim</h3><p className="daily-bio-sub">To claim your Daily WIENER, add your personal WIENER Farm referral link to your Telegram bio.</p><div className="daily-bio-steps"><div className="daily-bio-step"><b>1</b><span>Copy your referral link below.</span></div><div className="daily-bio-step"><b>2</b><span>Open Telegram → Profile → Edit → Bio, then paste the link.</span></div><div className="daily-bio-step"><b>3</b><span>Come back here and tap <strong>Check & claim</strong>.</span></div></div><div className="daily-bio-link"><code>{link}</code><button type="button" className="daily-bio-copy" onClick={copy}>{copied?'COPIED':'COPY'}</button></div><div className="daily-bio-warning">⚠️ The bot must be able to read your Telegram bio. If you just changed it, wait a few seconds before checking again.</div>{error&&<div className="daily-bio-error">{error}</div>}<div className="daily-bio-actions"><button type="button" className="daily-bio-later" disabled={busy} onClick={onClose}>Later</button><button type="button" className="daily-bio-check" disabled={busy} onClick={check}>{busy?'CHECKING…':'Check & claim'}</button></div></div></div>
}
