import {useEffect,useState} from 'react';
import {gramQuestApi} from './lib';

const GRAM_ICON='https://pixlinkhost.vercel.app/i/1AcOzN0LcQ';
type QuestStatus={enabled?:boolean;day?:string;used?:number;required?:number;remaining?:number;reward_gram?:number;claimed?:boolean;claimed_at?:string|null;gram_balance?:number};

export function DailyGramQuest({refresh,say}:{refresh?:()=>Promise<any>|any;say:(m:string)=>void}){
 const [st,setSt]=useState<QuestStatus|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const load=async()=>{try{const x=await gramQuestApi('status');setSt(x)}catch(e:any){say(String(e?.message||e))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 if(loading)return <section className="gram-quest gram-quest-loading"><div className="gram-quest-shimmer"/></section>;
 if(!st?.enabled)return null;
 const used=Math.max(0,Number(st.used||0)),required=Math.max(1,Number(st.required||50)),remaining=Math.max(0,required-used),reward=Number(st.reward_gram||.03),pct=Math.min(100,used/required*100),ready=!st.claimed&&remaining===0;
 const claim=async()=>{if(!ready||busy)return;try{setBusy(true);const x=await gramQuestApi('claim');setSt(x);say(`✅ +${Number(x?.reward_gram||reward)} GRAM claimed`);await refresh?.()}catch(e:any){say(String(e?.message||e))}finally{setBusy(false)}};
 return <><style>{`
.gram-quest{position:relative;overflow:hidden;margin:0 0 12px;padding:16px;border-radius:24px;border:1px solid rgba(255,210,70,.28);background:radial-gradient(circle at 92% 0%,rgba(255,196,45,.18),transparent 34%),linear-gradient(155deg,rgba(38,12,18,.96),rgba(18,8,12,.98));box-shadow:inset 0 1px rgba(255,255,255,.08),0 16px 38px rgba(0,0,0,.22)}
.gram-quest-top{display:flex;align-items:center;gap:11px}.gram-quest-icon{width:50px;height:50px;border-radius:16px;display:grid;place-items:center;background:linear-gradient(145deg,#ffd33d,#e9980b);box-shadow:0 9px 24px rgba(255,184,20,.22)}.gram-quest-icon img{width:30px;height:30px;border-radius:50%;object-fit:cover}.gram-quest-copy{min-width:0;flex:1}.gram-quest-kicker{font-size:9px;font-weight:950;letter-spacing:1.1px;color:#ffd45a}.gram-quest-copy h3{margin:3px 0 2px;font-size:18px}.gram-quest-copy p{margin:0;font-size:11px;opacity:.68}.gram-quest-reward{padding:7px 9px;border-radius:12px;background:rgba(255,207,55,.11);border:1px solid rgba(255,207,55,.2);text-align:right}.gram-quest-reward b{display:block;color:#ffd34e;font-size:15px}.gram-quest-reward span{font-size:8px;font-weight:900;opacity:.55}.gram-quest-progress{margin-top:14px;padding:12px;border-radius:17px;background:rgba(0,0,0,.18);border:1px solid rgba(255,255,255,.055)}.gram-quest-progress-head{display:flex;justify-content:space-between;align-items:end;gap:8px;font-size:10px;font-weight:850;opacity:.72}.gram-quest-progress-head strong{font-size:20px;color:#ffd34e;opacity:1}.gram-quest-bar{height:8px;margin:9px 0 8px;border-radius:99px;background:rgba(255,255,255,.07);overflow:hidden}.gram-quest-bar span{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#ffbe1a,#ffe76e);box-shadow:0 0 16px rgba(255,205,45,.35);transition:width .35s ease}.gram-quest-left{text-align:center;font-size:11px;font-weight:850;color:#ffd45a}.gram-quest button{width:100%;min-height:48px;margin-top:12px;border:0;border-radius:16px;background:linear-gradient(180deg,#ffcb27,#e49a08);color:#251500;font-weight:950;font-size:13px;box-shadow:inset 0 1px rgba(255,255,255,.35),0 10px 24px rgba(225,151,7,.17)}.gram-quest button:disabled{opacity:.45;filter:saturate(.55)}.gram-quest-note{margin-top:8px;text-align:center;font-size:9px;opacity:.5}.gram-quest-claimed{color:#7cf0a2!important}.gram-quest-loading{min-height:170px}.gram-quest-shimmer{height:138px;border-radius:18px;background:linear-gradient(90deg,rgba(255,255,255,.03),rgba(255,255,255,.09),rgba(255,255,255,.03));background-size:220% 100%;animation:gramQuestShimmer 1.2s linear infinite}@keyframes gramQuestShimmer{to{background-position:-220% 0}}
`}</style><section className="gram-quest"><div className="gram-quest-top"><div className="gram-quest-icon"><img src={GRAM_ICON} alt=""/></div><div className="gram-quest-copy"><div className="gram-quest-kicker">DAILY SPONSOR QUEST</div><h3>GRAM Daily Ads</h3><p>Complete your main AdsGram quota today</p></div><div className="gram-quest-reward"><b>{reward} GRAM</b><span>DAILY REWARD</span></div></div><div className="gram-quest-progress"><div className="gram-quest-progress-head"><span>Total Quest Progress</span><strong>{used}<small> / {required}</small></strong></div><div className="gram-quest-bar"><span style={{width:`${pct}%`}}/></div><div className={`gram-quest-left ${st.claimed?'gram-quest-claimed':''}`}>{st.claimed?'✓ TODAY’S GRAM CLAIMED':remaining>0?`⚡ ${remaining} MAIN ADS REMAINING`:'💎 QUEST COMPLETE — CLAIM READY'}</div></div><button type="button" disabled={!ready||busy} onClick={claim}>{st.claimed?'✓ 0.03 GRAM CLAIMED':busy?'CLAIMING…':ready?`💎 CLAIM ${reward} GRAM`:`🔒 CLAIM ${reward} GRAM — ${remaining} ADS LEFT`}</button><div className="gram-quest-note">Only server-verified Main Ads count · resets daily at 00:00 UTC</div></section></>;
}
