import {useEffect,useMemo,useState} from 'react';
import {getInitData,money} from './lib';

type OffersStatus={providers?:{offerwallgg?:{ready:boolean;name:string}};rate?:{wiener_per_usd:number};history?:any[];totals?:{wiener?:number;usd?:number}};
type OpenLog={id:string;opened_at:string;last_seen_at?:string;status:'opened'};
const OPEN_LOG_KEY='wiener_offerwallgg_open_activity_v1';

async function offersApi(action:'status'|'open',body:any={}){const r=await fetch('/functions/v1/wiener-offers',{method:'POST',headers:{'Content-Type':'application/json','cache-control':'no-cache'},cache:'no-store',body:JSON.stringify({action,initData:getInitData(),...body})});const x=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok||x?.ok===false)throw new Error(String(x?.message||x?.error||'Offers service unavailable').replace(/_/g,' '));return x.data??x}
const glass:React.CSSProperties={background:'linear-gradient(145deg,rgba(255,255,255,.075),rgba(255,255,255,.025))',border:'1px solid rgba(255,255,255,.09)',boxShadow:'0 16px 50px rgba(0,0,0,.18)',backdropFilter:'blur(18px)',WebkitBackdropFilter:'blur(18px)'};
const readOpenLogs=():OpenLog[]=>{try{return JSON.parse(localStorage.getItem(OPEN_LOG_KEY)||'[]')}catch{return[]}};
const saveOpenLog=()=>{try{const now=new Date().toISOString();const logs=readOpenLogs();logs.unshift({id:`session-${Date.now()}`,opened_at:now,last_seen_at:now,status:'opened'});localStorage.setItem(OPEN_LOG_KEY,JSON.stringify(logs.slice(0,12)))}catch{}};
const when=(v:any)=>{if(!v)return '—';const d=new Date(v);if(Number.isNaN(d.getTime()))return '—';const diff=Date.now()-d.getTime();if(diff>=0&&diff<60000)return 'Just now';if(diff>=0&&diff<3600000)return `${Math.max(1,Math.floor(diff/60000))}m ago`;if(diff>=0&&diff<86400000)return `${Math.floor(diff/3600000)}h ago`;return d.toLocaleDateString(undefined,{day:'2-digit',month:'short'})+' · '+d.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})};
const statusMeta=(s:any)=>{const x=String(s||'').toLowerCase();if(['verified','completed','approved','credited','success'].includes(x))return{label:'VERIFIED',fg:'#78f5a7',bg:'rgba(73,232,132,.11)',dot:'#67ef9a'};if(['reversed','rejected','failed','chargeback'].includes(x))return{label:x==='reversed'||x==='chargeback'?'REVERSED':'REJECTED',fg:'#ff8d8d',bg:'rgba(255,91,91,.10)',dot:'#ff7676'};if(['pending','tracked','processing'].includes(x))return{label:'PENDING',fg:'#ffd477',bg:'rgba(255,190,60,.10)',dot:'#ffc85c'};return{label:'OPENED',fg:'#9ecbff',bg:'rgba(92,161,255,.11)',dot:'#84baff'}};

export function EarnPage(){
 const [status,setStatus]=useState<OffersStatus|null>(null),[loading,setLoading]=useState(true),[opening,setOpening]=useState(false),[offerUrl,setOfferUrl]=useState(''),[frameLoading,setFrameLoading]=useState(false),[confirmOpen,setConfirmOpen]=useState(false),[error,setError]=useState(''),[openLogs,setOpenLogs]=useState<OpenLog[]>(()=>readOpenLogs()),[detail,setDetail]=useState<any|null>(null);
 const refresh=async()=>{try{setError('');setLoading(true);setStatus(await offersApi('status'));setOpenLogs(readOpenLogs())}catch(e:any){setError(String(e?.message||e))}finally{setLoading(false)}};useEffect(()=>{refresh()},[]);
 const launch=async()=>{if(opening)return;try{setOpening(true);setConfirmOpen(false);setError('');const x=await offersApi('open',{provider:'offerwallgg'});const url=String(x?.url||'');if(!/^https:\/\//i.test(url))throw new Error('Provider link unavailable');saveOpenLog();setOpenLogs(readOpenLogs());try{(window.Telegram?.WebApp as any)?.HapticFeedback?.impactOccurred?.('medium')}catch{}setFrameLoading(true);setOfferUrl(url)}catch(e:any){setError(String(e?.message||e))}finally{setOpening(false)}};
 const close=()=>{setOfferUrl('');setFrameLoading(false);refresh()};const reload=()=>{const u=offerUrl;setOfferUrl('');setFrameLoading(true);requestAnimationFrame(()=>setOfferUrl(u))};const ready=!!status?.providers?.offerwallgg?.ready;
 const activity=useMemo(()=>{const verified=(status?.history||[]).filter(x=>x.provider==='offerwallgg').map((x:any)=>({...x,_kind:'transaction',_time:x.updated_at||x.created_at||x.completed_at||x.timestamp}));const opens=openLogs.map(x=>({...x,provider:'offerwallgg',title:'Offerwall.GG session',_kind:'session',_time:x.opened_at,user_reward_wiener:0}));return[...verified,...opens].sort((a:any,b:any)=>new Date(b._time||0).getTime()-new Date(a._time||0).getTime()).slice(0,10)},[status,openLogs]);
 if(offerUrl)return <section style={{position:'fixed',inset:0,zIndex:80,display:'flex',flexDirection:'column',background:'linear-gradient(180deg,#0c1110,#090c0b)',animation:'offerEnter .22s ease-out'}}><style>{`@keyframes offerEnter{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}@keyframes offerPulse{0%,100%{opacity:.45;transform:scale(.94)}50%{opacity:1;transform:scale(1)}}`}</style><div style={{padding:'max(10px,env(safe-area-inset-top)) 12px 10px',display:'grid',gridTemplateColumns:'44px 1fr 44px',alignItems:'center',gap:8,background:'rgba(12,17,16,.94)',borderBottom:'1px solid rgba(255,255,255,.07)',backdropFilter:'blur(20px)'}}><button onClick={close} style={{height:40,width:40,borderRadius:14,border:'1px solid rgba(255,255,255,.09)',background:'rgba(255,255,255,.06)',color:'#fff',fontSize:19}}>‹</button><div style={{textAlign:'center'}}><b style={{fontSize:13}}>Offerwall.GG</b><div style={{fontSize:9,opacity:.42,marginTop:2}}>WIENER EARN</div></div><button onClick={reload} style={{height:40,width:40,borderRadius:14,border:'1px solid rgba(255,255,255,.09)',background:'rgba(255,255,255,.06)',color:'#fff',fontSize:16}}>↻</button></div><div style={{position:'relative',flex:1,minHeight:0}}>{frameLoading&&<div style={{position:'absolute',inset:0,zIndex:2,display:'grid',placeItems:'center',background:'#0c1110'}}><div style={{textAlign:'center'}}><div style={{width:42,height:42,margin:'0 auto 13px',borderRadius:15,display:'grid',placeItems:'center',fontWeight:1000,fontSize:18,background:'rgba(94,255,156,.14)',animation:'offerPulse 1.25s ease-in-out infinite'}}>W</div><b style={{fontSize:12}}>Loading offers</b><div style={{fontSize:10,opacity:.42,marginTop:5}}>Finding offers for you…</div></div></div>}<iframe title="Offerwall.GG" src={offerUrl} onLoad={()=>setFrameLoading(false)} allow="clipboard-read; clipboard-write; fullscreen; payment" referrerPolicy="strict-origin-when-cross-origin" style={{width:'100%',height:'100%',border:0,display:'block',background:'#fff'}}/></div></section>;
 return <section style={{paddingBottom:20}}><style>{`@keyframes earnGlow{0%,100%{opacity:.45}50%{opacity:.75}}@keyframes modalIn{from{opacity:0;transform:translateY(14px) scale(.98)}to{opacity:1;transform:none}}`}</style>
 <div style={{...glass,position:'relative',overflow:'hidden',borderRadius:24,padding:20,marginBottom:12}}><div style={{position:'absolute',width:180,height:180,borderRadius:'50%',right:-80,top:-100,background:'rgba(66,255,142,.10)',filter:'blur(20px)',animation:'earnGlow 3s ease-in-out infinite'}}/><div style={{position:'relative'}}><div style={{display:'flex',alignItems:'center',gap:8,marginBottom:10}}><span style={{fontSize:9,fontWeight:900,letterSpacing:'.16em',opacity:.5}}>EARN</span><span style={{width:4,height:4,borderRadius:99,background:'#6dffa4'}}/><span style={{fontSize:9,fontWeight:900,color:'#79f5a8'}}>OFFERWALL.GG</span></div><h2 style={{fontSize:25,lineHeight:1.08,margin:'0 0 9px',letterSpacing:'-.035em'}}>Play. Complete.<br/>Earn WIENER.</h2><p style={{margin:0,maxWidth:310,fontSize:12,lineHeight:1.6,opacity:.55}}>Explore games, apps and offers. Rewards are credited after verification.</p></div></div>
 <div style={{...glass,borderRadius:22,padding:16,marginBottom:12}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,marginBottom:14}}><div style={{display:'flex',alignItems:'center',gap:11}}><div style={{width:44,height:44,borderRadius:15,display:'grid',placeItems:'center',fontSize:18,fontWeight:1000,background:'linear-gradient(145deg,rgba(89,255,151,.16),rgba(255,211,77,.08))'}}>W</div><div><b style={{display:'block',fontSize:14}}>Offerwall.GG</b><small style={{fontSize:10,opacity:.43}}>Games · Apps · Offers</small></div></div><span style={{padding:'6px 9px',borderRadius:999,fontSize:9,fontWeight:900,background:ready?'rgba(73,232,132,.11)':'rgba(255,190,60,.09)',color:ready?'#79f5a8':'#ffd26a'}}>{loading?'CHECKING':ready?'● LIVE':'OFFLINE'}</span></div><button className="primary" disabled={loading||opening||!ready} onClick={()=>setConfirmOpen(true)} style={{height:50,borderRadius:16,fontWeight:900}}>{loading?'CHECKING OFFERS…':ready?'EXPLORE OFFERS  →':'OFFERS TEMPORARILY UNAVAILABLE'}</button></div>
 {error&&<div className="info-box" style={{marginBottom:12,borderRadius:16}}>{error}</div>}
 <div style={{...glass,borderRadius:22,padding:16}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,marginBottom:5}}><div><div style={{fontSize:9,fontWeight:900,letterSpacing:'.14em',opacity:.38}}>OFFER LOG</div><h3 style={{margin:'4px 0 0',fontSize:16}}>Recent activity</h3></div><button onClick={refresh} disabled={loading} style={{height:34,padding:'0 11px',borderRadius:11,border:'1px solid rgba(255,255,255,.07)',background:'rgba(255,255,255,.04)',color:'inherit',fontSize:10,fontWeight:800}}>↻</button></div><p style={{fontSize:9,opacity:.32,margin:'0 0 10px'}}>Your latest Offerwall sessions and verified rewards</p>
 {!activity.length?<div style={{padding:'24px 0 10px',textAlign:'center'}}><div style={{fontSize:24,opacity:.22}}>◇</div><b style={{display:'block',fontSize:11,opacity:.5,marginTop:7}}>No activity yet</b><div style={{fontSize:9,opacity:.28,marginTop:4}}>Open the offerwall to start your activity log</div></div>:<div>{activity.map((x:any)=>{const sm=statusMeta(x.status);const reward=Number(x.user_reward_wiener||0);return <button key={`${x._kind}-${x.id}`} onClick={()=>setDetail(x)} style={{width:'100%',display:'grid',gridTemplateColumns:'36px 1fr auto',alignItems:'center',gap:10,padding:'12px 0',border:0,borderTop:'1px solid rgba(255,255,255,.05)',background:'transparent',color:'inherit',textAlign:'left'}}><div style={{width:36,height:36,borderRadius:12,display:'grid',placeItems:'center',background:sm.bg,color:sm.fg,fontSize:14}}>↗</div><div style={{minWidth:0}}><div style={{display:'flex',alignItems:'center',gap:6,minWidth:0}}><b style={{fontSize:11,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{x.title||'Offerwall.GG Offer'}</b><span style={{fontSize:7,fontWeight:900,padding:'3px 5px',borderRadius:99,background:sm.bg,color:sm.fg,flex:'0 0 auto'}}>{sm.label}</span></div><div style={{fontSize:9,opacity:.34,marginTop:4}}>{x._kind==='session'?'Opened':'Updated'} · {when(x._time)}</div></div><div style={{textAlign:'right'}}>{reward>0?<b style={{display:'block',fontSize:11,color:'#ffe36b'}}>+{money(reward)} W</b>:<span style={{fontSize:13,opacity:.25}}>›</span>}<small style={{fontSize:8,opacity:.28}}>{reward>0?'REWARD':''}</small></div></button>})}</div>}</div>
 {confirmOpen&&<div onClick={()=>!opening&&setConfirmOpen(false)} style={{position:'fixed',inset:0,zIndex:100,display:'flex',alignItems:'flex-end',justifyContent:'center',padding:'18px 14px max(18px,env(safe-area-inset-bottom))',background:'rgba(0,0,0,.58)',backdropFilter:'blur(8px)'}}><div onClick={e=>e.stopPropagation()} style={{...glass,width:'100%',maxWidth:460,borderRadius:26,padding:18,animation:'modalIn .2s ease-out',background:'linear-gradient(165deg,rgba(27,34,31,.98),rgba(14,18,17,.98))'}}><div style={{width:38,height:4,borderRadius:99,background:'rgba(255,255,255,.14)',margin:'0 auto 17px'}}/><h3 style={{fontSize:19,margin:'0 0 7px'}}>Explore Offerwall.GG</h3><p style={{fontSize:11,lineHeight:1.6,opacity:.5,margin:'0 0 14px'}}>Offers open securely inside Wiener Farm. Complete the exact requirements to receive verified rewards.</p><button className="primary" disabled={opening} onClick={launch} style={{height:50,borderRadius:16,fontWeight:900}}>{opening?'OPENING…':'CONTINUE TO OFFERS'}</button><button disabled={opening} onClick={()=>setConfirmOpen(false)} style={{width:'100%',height:42,marginTop:7,border:0,background:'transparent',color:'inherit',fontSize:11,fontWeight:800,opacity:.5}}>NOT NOW</button></div></div>}
 {detail&&(()=>{const sm=statusMeta(detail.status),reward=Number(detail.user_reward_wiener||0);return <div onClick={()=>setDetail(null)} style={{position:'fixed',inset:0,zIndex:110,display:'flex',alignItems:'flex-end',justifyContent:'center',padding:'18px 14px max(18px,env(safe-area-inset-bottom))',background:'rgba(0,0,0,.62)',backdropFilter:'blur(9px)'}}><div onClick={e=>e.stopPropagation()} style={{...glass,width:'100%',maxWidth:460,borderRadius:26,padding:18,animation:'modalIn .2s ease-out',background:'linear-gradient(165deg,rgba(27,34,31,.99),rgba(14,18,17,.99))'}}><div style={{width:38,height:4,borderRadius:99,background:'rgba(255,255,255,.14)',margin:'0 auto 17px'}}/><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:12}}><div><div style={{fontSize:9,fontWeight:900,letterSpacing:'.12em',opacity:.35}}>ACTIVITY DETAILS</div><h3 style={{fontSize:18,margin:'5px 0'}}>{detail.title||'Offerwall.GG Offer'}</h3></div><span style={{fontSize:8,fontWeight:900,padding:'6px 8px',borderRadius:99,background:sm.bg,color:sm.fg}}>{sm.label}</span></div><div style={{margin:'14px 0',padding:14,borderRadius:17,background:'rgba(255,255,255,.035)'}}>{[['Provider','Offerwall.GG'],['Opened / updated',when(detail._time)],['Reward',reward>0?`+${money(reward)} WIENER`:'Waiting for verification'],['Reference',String(detail.transaction_id||detail.offer_id||detail.id||'—')]].map(([a,b])=><div key={a} style={{display:'flex',justifyContent:'space-between',gap:12,padding:'8px 0',borderBottom:'1px solid rgba(255,255,255,.04)'}}><span style={{fontSize:10,opacity:.38}}>{a}</span><b style={{fontSize:10,maxWidth:'60%',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{b}</b></div>)}</div><div style={{display:'flex',alignItems:'center',gap:9,padding:'3px 2px 15px'}}><span style={{width:8,height:8,borderRadius:99,background:sm.dot,boxShadow:`0 0 12px ${sm.dot}`}}/><div><b style={{fontSize:10}}>{sm.label==='VERIFIED'?'Reward verified':sm.label==='OPENED'?'Offerwall opened':'Status updated'}</b><div style={{fontSize:9,opacity:.34,marginTop:2}}>{sm.label==='OPENED'?'Complete an offer and wait for provider verification.':'This status comes from your Offerwall activity.'}</div></div></div><button className="primary" onClick={()=>setDetail(null)} style={{height:46,borderRadius:15,fontWeight:900}}>DONE</button></div></div>})()}
 </section>}
