import {useEffect,useMemo,useState} from 'react';
import {getInitData,PUBLISHABLE_KEY,SUPABASE_URL} from './lib';
const ENDPOINT=`${SUPABASE_URL}/functions/v1/wiener-exclusive`;
async function exApi(action:string,body:any={}){const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUBLISHABLE_KEY},body:JSON.stringify({action,initData:getInitData(),...body})});const x=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok||!x.ok)throw new Error(x.message||x.error||'Request failed');return x.data}
const packages=[{ton:.05,members:20,label:'Mini'},{ton:.1,members:45,label:'Starter',discount:true},{ton:.25,members:125,label:'Growth',discount:true},{ton:.5,members:275,label:'Popular',discount:true},{ton:1,members:600,label:'Pro',discount:true}];
const memberRate=(ton:number)=>ton>=1?600:ton>=.5?550:ton>=.25?500:ton>=.1?450:400;
const membersFor=(ton:number)=>Math.max(0,Math.floor(ton*memberRate(ton)));
const statusText:Record<string,string>={awaiting_payment:'Awaiting payment',under_review:'Under review',live:'Live',completed:'Completed',rejected:'Rejected'};
const friendlyError=(m:string)=>m==='wiener_bot_must_be_admin'?'Add the WIENER bot as an admin in this channel/group first.':m==='wiener_bot_needs_invite_users_permission'?'Enable “Invite Users / Add Subscribers” for the WIENER bot and check again.':m==='target_chat_not_found'?'Channel/group not found. Check the username/link and bot access.':m==='cannot_verify_wiener_bot_admin'?'Could not verify WIENER bot permissions.':m==='invalid_package'?'Custom amount must be at least 0.05 TON.':m;
export function ExclusivePromote({say,isAdmin=false,tasks=[]}:{say:(s:string)=>void;isAdmin?:boolean;tasks?:any[]}){
 const [open,setOpen]=useState(false),[kind,setKind]=useState<'telegram'|'bot'>('telegram'),[title,setTitle]=useState(''),[target,setTarget]=useState(''),[description,setDescription]=useState(''),[pkg,setPkg]=useState<number|null>(.05),[customTon,setCustomTon]=useState(''),[orders,setOrders]=useState<any[]>([]),[pay,setPay]=useState<any>(null),[tx,setTx]=useState(''),[busy,setBusy]=useState(false),[moderation,setModeration]=useState<any[]>([]),[targetVerified,setTargetVerified]=useState(false),[verifiedBot,setVerifiedBot]=useState('WIENER bot');
 const amount=useMemo(()=>pkg??Number(customTon||0),[pkg,customTon]);
 const selected=useMemo(()=>pkg!==null?packages.find(x=>x.ton===pkg):null,[pkg]);
 const memberCount=selected?.members??membersFor(amount);
 const progressOf=(o:any)=>Number(tasks.find(x=>x.id===o.task_id)?.completed_count||0);
 const load=()=>exApi('list').then(setOrders).catch(()=>{}),loadAdmin=()=>isAdmin?exApi('admin_list').then(setModeration).catch(()=>{}):Promise.resolve();
 useEffect(()=>{load();loadAdmin()},[]); useEffect(()=>{setTargetVerified(kind==='bot')},[kind,target]);
 const verifyTarget=async()=>{if(kind==='bot'){setTargetVerified(true);return}if(!target.trim())return say('Enter channel/group first');try{setBusy(true);const x=await exApi('verify_target',{task_kind:kind,target});setTargetVerified(!!x?.ok);if(x?.bot_username)setVerifiedBot(x.bot_username);say(`✅ ${x?.bot_username||'WIENER bot'} verified`)}catch(e:any){setTargetVerified(false);say(friendlyError(e.message))}finally{setBusy(false)}};
 const create=async()=>{try{setBusy(true);if(kind==='telegram'&&!targetVerified)throw new Error('Verify WIENER bot permission first');if(!Number.isFinite(amount)||amount<.05)throw new Error('invalid_package');const o=await exApi('create',{task_kind:kind,title,target,description,package_ton:amount});setPay(o);setOpen(false);setTx('');await load();say('Payment request created')}catch(e:any){say(friendlyError(e.message))}finally{setBusy(false)}};
 const verify=async()=>{if(!pay||!tx.trim())return;try{setBusy(true);const o=await exApi('verify_payment',{order_id:pay.id,tx_hash:tx.trim()});setPay(o);await load();await loadAdmin();say('✅ Payment verified — sent for moderation')}catch(e:any){say(friendlyError(e.message))}finally{setBusy(false)}};
 const approve=async(o:any)=>{try{setBusy(true);await exApi('admin_approve',{order_id:o.id});say('✅ Exclusive task published');await loadAdmin();await load()}catch(e:any){say(friendlyError(e.message))}finally{setBusy(false)}};
 const reject=async(o:any)=>{const reason=prompt('Reason for rejection','Task does not meet requirements')||'Rejected by admin';try{setBusy(true);await exApi('admin_reject',{order_id:o.id,reason});say('Task rejected');await loadAdmin()}catch(e:any){say(friendlyError(e.message))}finally{setBusy(false)}};
 const copy=async(v:string,label:string)=>{try{await navigator.clipboard.writeText(v);say(`${label} copied`)}catch{say(v)}}; const selectOrder=(o:any)=>{setPay(o);setTx(o.tx_hash||'')};
 return <section className="exclusive-market">
  <div className="card exclusive-cta"><div><span className="eyebrow">EXCLUSIVE MARKETPLACE</span><h3>Promote your Telegram task</h3><p>Verified members from <b>0.05 TON</b>. Workers earn <b>10 WIENER</b> per completion.</p></div><button className="primary" onClick={()=>setOpen(v=>!v)}>+ ADD YOUR TASK</button></div>
  {open&&<section className="card exclusive-builder"><div className="section-head"><div><h3>Create promotion</h3><p>Select a pack or enter a custom TON amount.</p></div></div>
   <label>Task type</label><div className="category-choices"><button className={kind==='telegram'?'active':''} onClick={()=>setKind('telegram')}><span>📢</span><b>Channel / Group</b><small>Membership verify</small></button><button className={kind==='bot'?'active':''} onClick={()=>setKind('bot')}><span>🤖</span><b>Bot Start</b><small>Forward verify</small></button></div>
   <label>Task title</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Join our Telegram community"/><label>{kind==='bot'?'Bot @username':'Channel / Group @username or link'}</label><input value={target} onChange={e=>setTarget(e.target.value)} placeholder={kind==='bot'?'@ExampleBot':'@ExampleChannel'}/>
   {kind==='telegram'&&<div className={`info-box ${targetVerified?'verified':''}`}><b>{targetVerified?'✅ WIENER bot verified':'Required before payment'}</b><br/>Add <b>{verifiedBot}</b> as <b>Admin</b> and enable <b>Invite Users / Add Subscribers</b>.<br/><button className="primary small" disabled={busy||!target.trim()} onClick={verifyTarget}>{busy?'CHECKING…':targetVerified?'✓ VERIFIED':'VERIFY BOT PERMISSION'}</button></div>}
   <label>Description <small>(optional)</small></label><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Short task description"/>
   <label>Choose package</label><div className="exclusive-packages five-pack">{packages.map(x=><button key={x.ton} className={pkg===x.ton?'active':''} onClick={()=>{setPkg(x.ton);setCustomTon('')}}><span>{x.label}{x.discount&&<em>DISCOUNT</em>}</span><b>{x.ton} TON</b><small>{x.members} verified members</small></button>)}<button className={pkg===null?'active custom-pack':''} onClick={()=>setPkg(null)}><span>Custom</span><b>Custom TON</b><small>Min 0.05 TON</small></button></div>
   {pkg===null&&<div className="custom-order"><label>Custom amount</label><div className="custom-input-wrap"><input type="number" min="0.05" step="0.01" inputMode="decimal" value={customTon} onChange={e=>setCustomTon(e.target.value)} placeholder="0.05"/><span>TON</span></div><div className="custom-preview"><span>Estimated members</span><b>{amount>=.05?memberCount:0}</b><small>{amount>=.05?`${memberRate(amount)} members / TON tier`:'Minimum 0.05 TON'}</small></div></div>}
   <div className="exclusive-summary"><span>Members <b>{memberCount}</b></span><span>Worker reward <b>10 WIENER each</b></span><span>Total <b>{amount||0} TON</b></span></div><button className="primary" disabled={busy||!title.trim()||!target.trim()||(kind==='telegram'&&!targetVerified)||amount<.05} onClick={create}>{busy?'CREATING…':'CONTINUE TO PAYMENT'}</button>
  </section>}
  {pay&&<section className="card exclusive-payment"><div className="section-head"><div><h3>{pay.payment_status==='verified'?'Payment verified':'Pay with TON'}</h3><p>{pay.title} · {pay.target_completions} members</p></div><span className={`tag ${pay.payment_status==='verified'?'verified':''}`}>{statusText[pay.status]||pay.status}</span></div>{pay.payment_status!=='verified'?<><div className="pay-amount"><span>Send exactly</span><b>{pay.package_ton} TON</b></div><label>TON address</label><div className="copy-line"><code>{pay.payment_address}</code><button onClick={()=>copy(pay.payment_address,'Address')}>COPY</button></div><label>Memo / Comment <b>required</b></label><div className="copy-line"><code>{pay.payment_memo}</code><button onClick={()=>copy(pay.payment_memo,'Memo')}>COPY</button></div><div className="info-box">Use the exact memo, then paste the TXID. Fake, reused, wrong-address, wrong-amount or memo-less transactions are rejected server-side.</div><label>Transaction hash / TXID</label><input value={tx} onChange={e=>setTx(e.target.value.trim())} placeholder="Paste TON transaction hash"/><button className="primary" disabled={busy||!tx} onClick={verify}>{busy?'VERIFYING ON-CHAIN…':'VERIFY PAYMENT'}</button></>:<div className="info-box">✅ Payment verified. Waiting for admin moderation.</div>}{(pay.status==='under_review'||pay.status==='rejected')&&<button className="support-btn" onClick={()=>window.Telegram?.WebApp?.openTelegramLink?.('https://t.me/WienerSupport')}>Task not listed? @WienerSupport</button>}{pay.status==='live'&&<div className="exclusive-progress"><b>{pay.title}</b><span>Live · {progressOf(pay)}/{pay.target_completions} verified members</span><div className="progress"><span style={{width:`${Math.min(100,progressOf(pay)/Number(pay.target_completions||1)*100)}%`}}/></div></div>}{pay.status==='completed'&&<div className="info-box">✅ Campaign completed.</div>}{pay.status==='rejected'&&<div className="info-box">Reason: {pay.rejection_reason||'Not approved'} · Contact @WienerSupport.</div>}</section>}
  {orders.length>0&&<section className="card my-promotions"><div className="section-head"><div><h3>My promotions</h3><p>Payment, moderation and delivery status</p></div></div>{orders.map(o=><button className="promotion-row" key={o.id} onClick={()=>selectOrder(o)}><div><b>{o.title}</b><small>{o.package_ton} TON · {progressOf(o)}/{o.target_completions} members</small></div><span>{statusText[o.status]||o.status}</span></button>)}</section>}
  {isAdmin&&moderation.some(o=>o.status==='under_review')&&<section className="card exclusive-moderation"><div className="section-head"><div><span className="eyebrow">ADMIN MODERATION</span><h3>Paid tasks waiting</h3><p>Only server-verified TON payments appear here.</p></div></div>{moderation.filter(o=>o.status==='under_review').map(o=><div className="moderation-row" key={o.id}><div><b>{o.title}</b><small>UID {o.telegram_id} · {o.package_ton} TON · {o.target_completions} members<br/>{o.task_kind==='bot'?'Bot':'Channel/Group'} · {o.target_ref}<br/>TX: {String(o.tx_hash||'').slice(0,18)}…</small></div><div className="row-actions"><button className="good" disabled={busy} onClick={()=>approve(o)}>APPROVE</button><button className="danger" disabled={busy} onClick={()=>reject(o)}>REJECT</button></div></div>)}</section>}
 </section>;
}
