import {useEffect,useMemo,useState} from 'react';
import {getInitData,PUBLISHABLE_KEY,SUPABASE_URL} from './lib';
const ENDPOINT=`${SUPABASE_URL}/functions/v1/wiener-exclusive`;
const ADD_CHANNEL='https://t.me/WienerDogeFarmBot?startchannel&admin=invite_users',ADD_GROUP='https://t.me/WienerDogeFarmBot?startgroup&admin=invite_users';
type PromotionKind='telegram'|'bot'|'miniapp'|'referral'|'website';
async function exApi(action:string,body:any={}){const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUBLISHABLE_KEY},body:JSON.stringify({action,initData:getInitData(),...body})});const x=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok||!x.ok)throw new Error(x.message||x.error||'Request failed');return x.data}
const packages=[{ton:.05,members:20,label:'Mini'},{ton:.1,members:45,label:'Starter',discount:true},{ton:.25,members:125,label:'Growth',discount:true},{ton:.5,members:275,label:'Popular',discount:true},{ton:1,members:600,label:'Pro',discount:true}];
const kinds:{id:PromotionKind;icon:string;name:string;hint:string}[]=[{id:'telegram',icon:'📢',name:'Channel / Group',hint:'Membership verify'},{id:'bot',icon:'🤖',name:'Bot Start',hint:'Forward verify'},{id:'miniapp',icon:'📱',name:'Mini App',hint:'Open + timed verify'},{id:'referral',icon:'🔗',name:'Referral / Raffer',hint:'Keeps referral params'},{id:'website',icon:'🌐',name:'Website',hint:'HTTPS link'}];
const labels:Record<PromotionKind,string>={telegram:'Channel / Group @username or link',bot:'Bot @username',miniapp:'Mini App HTTPS URL',referral:'Referral / Raffer HTTPS URL',website:'Website HTTPS URL'};
const placeholders:Record<PromotionKind,string>={telegram:'@ExampleChannel',bot:'@ExampleBot',miniapp:'https://t.me/MyBot/app',referral:'https://t.me/MyBot?start=ABC123',website:'https://example.com'};
const memberRate=(ton:number)=>ton>=1?600:ton>=.5?550:ton>=.25?500:ton>=.1?450:400,membersFor=(ton:number)=>Math.max(0,Math.floor(ton*memberRate(ton)));
const statusText:Record<string,string>={awaiting_payment:'Awaiting payment',under_review:'Under review',live:'Live',completed:'Completed',rejected:'Rejected'};
const friendlyError=(m:string)=>m==='wiener_bot_must_be_admin'?'Add @WienerDogeFarmBot as admin first.':m==='wiener_bot_needs_invite_users_permission'?'Enable Invite Users / Add Subscribers for @WienerDogeFarmBot.':m==='target_chat_not_found'?'Channel/group not found. Check the username/link and bot access.':m==='cannot_verify_wiener_bot_admin'?'Could not verify WIENER bot permissions.':m==='invalid_package'?'Custom amount must be at least 0.05 TON.':m==='https_url_required'?'Use a valid HTTPS URL.':m==='private_url_not_allowed'?'Private/local URLs are not allowed.':m==='invalid_url'?'Enter a valid URL.':m;
export function ExclusivePromote({say,isAdmin=false,tasks=[]}:{say:(s:string)=>void;isAdmin?:boolean;tasks?:any[]}){
 const [open,setOpen]=useState(false),[kind,setKind]=useState<PromotionKind>('telegram'),[title,setTitle]=useState(''),[target,setTarget]=useState(''),[description,setDescription]=useState(''),[pkg,setPkg]=useState<number|null>(.05),[customTon,setCustomTon]=useState(''),[orders,setOrders]=useState<any[]>([]),[pay,setPay]=useState<any>(null),[tx,setTx]=useState(''),[busy,setBusy]=useState(false),[moderation,setModeration]=useState<any[]>([]),[targetVerified,setTargetVerified]=useState(false),[verifiedBot,setVerifiedBot]=useState('@WienerDogeFarmBot');
 const amount=useMemo(()=>pkg??Number(customTon||0),[pkg,customTon]),selected=useMemo(()=>pkg!==null?packages.find(x=>x.ton===pkg):null,[pkg]),memberCount=selected?.members??membersFor(amount),progressOf=(o:any)=>Number(tasks.find(x=>x.id===o.task_id)?.completed_count||0);
 const load=()=>exApi('list').then(setOrders).catch(()=>{}),loadAdmin=()=>isAdmin?exApi('admin_list').then(setModeration).catch(()=>{}):Promise.resolve();
 useEffect(()=>{load();loadAdmin()},[]);useEffect(()=>{setTargetVerified(false)},[kind,target]);
 const openTg=(url:string)=>window.Telegram?.WebApp?.openTelegramLink?.(url)||window.open(url,'_blank');
 const verifyTarget=async()=>{if(!target.trim())return say('Enter a target first');try{setBusy(true);const x=await exApi('verify_target',{task_kind:kind,target});setTargetVerified(!!x?.ok);if(x?.bot_username)setVerifiedBot(x.bot_username);say(kind==='telegram'?`✅ ${x?.bot_username||verifiedBot} verified`:'✅ Target link verified')}catch(e:any){setTargetVerified(false);say(friendlyError(e.message))}finally{setBusy(false)}};
 const create=async()=>{try{setBusy(true);if(!targetVerified)throw new Error('Verify the target first');if(!Number.isFinite(amount)||amount<.05)throw new Error('invalid_package');const o=await exApi('create',{task_kind:kind,title,target,description,package_ton:amount});setPay(o);setOpen(false);setTx('');await load();say('Payment request created')}catch(e:any){say(friendlyError(e.message))}finally{setBusy(false)}};
 const verify=async()=>{if(!pay||!tx.trim())return;try{setBusy(true);const o=await exApi('verify_payment',{order_id:pay.id,tx_hash:tx.trim()});setPay(o);await load();await loadAdmin();say('✅ Payment verified — sent for moderation')}catch(e:any){say(friendlyError(e.message))}finally{setBusy(false)}};
 const approve=async(o:any)=>{try{setBusy(true);await exApi('admin_approve',{order_id:o.id});say('✅ Exclusive task published');await loadAdmin();await load()}catch(e:any){say(friendlyError(e.message))}finally{setBusy(false)}};
 const reject=async(o:any)=>{const reason=prompt('Reason for rejection','Task does not meet requirements')||'Rejected by admin';try{setBusy(true);await exApi('admin_reject',{order_id:o.id,reason});say('Task rejected');await loadAdmin()}catch(e:any){say(friendlyError(e.message))}finally{setBusy(false)}};
 const copy=async(v:string,label:string)=>{try{await navigator.clipboard.writeText(v);say(`${label} copied`)}catch{say(v)}},selectOrder=(o:any)=>{setPay(o);setTx(o.tx_hash||'')};
 return <section className="exclusive-market">
  <div className="card exclusive-cta"><div><span className="eyebrow">EXCLUSIVE MARKETPLACE</span><h3>Promote any task</h3><p>Telegram, bots, Mini Apps, referral links and websites from <b>0.05 TON</b>.</p></div><button className="primary" onClick={()=>setOpen(v=>!v)}>+ ADD YOUR TASK</button></div>
  {open&&<section className="card exclusive-builder"><div className="section-head"><div><h3>Create promotion</h3><p>Choose what you want WIENER workers to visit or join.</p></div></div>
   <label>Promotion type</label><div className="category-choices promotion-kinds">{kinds.map(x=><button key={x.id} className={kind===x.id?'active':''} onClick={()=>setKind(x.id)}><span>{x.icon}</span><b>{x.name}</b><small>{x.hint}</small></button>)}</div>
   <label>Task title</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Join, open or visit"/><label>{labels[kind]}</label><input value={target} onChange={e=>setTarget(e.target.value)} placeholder={placeholders[kind]}/>
   {kind==='telegram'?<div className={`info-box ${targetVerified?'verified':''}`}><b>{targetVerified?'✅ WIENER bot verified':'Bot admin required before payment'}</b><br/>Add <b>{verifiedBot}</b> as admin with <b>Invite Users / Add Subscribers</b> permission.<div className="admin-link-row"><button className="small" onClick={()=>openTg(ADD_CHANNEL)}>ADD TO CHANNEL</button><button className="small" onClick={()=>openTg(ADD_GROUP)}>ADD TO GROUP</button></div><button className="primary small" disabled={busy||!target.trim()} onClick={verifyTarget}>{busy?'CHECKING…':targetVerified?'✓ VERIFIED':'VERIFY BOT PERMISSION'}</button></div>:<div className={`info-box ${targetVerified?'verified':''}`}><b>{targetVerified?'✅ Target verified':'Validate before payment'}</b><br/>{kind==='bot'?'Checks the bot username.':kind==='referral'?'The complete referral URL and query parameters are preserved.':'Only safe HTTPS links are accepted.'}<button className="primary small" disabled={busy||!target.trim()} onClick={verifyTarget}>{busy?'CHECKING…':targetVerified?'✓ VERIFIED':'VERIFY TARGET'}</button></div>}
   <label>Description <small>(optional)</small></label><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Short task instructions"/>
   <label>Choose package</label><div className="exclusive-packages five-pack">{packages.map(x=><button key={x.ton} className={pkg===x.ton?'active':''} onClick={()=>{setPkg(x.ton);setCustomTon('')}}><span>{x.label}{x.discount&&<em>DISCOUNT</em>}</span><b>{x.ton} TON</b><small>{x.members} verified members</small></button>)}<button className={pkg===null?'active custom-pack':''} onClick={()=>setPkg(null)}><span>Custom</span><b>Custom TON</b><small>Min 0.05 TON</small></button></div>
   {pkg===null&&<div className="custom-order"><label>Custom amount</label><div className="custom-input-wrap"><input type="number" min="0.05" step="0.01" inputMode="decimal" value={customTon} onChange={e=>setCustomTon(e.target.value)} placeholder="0.05"/><span>TON</span></div><div className="custom-preview"><span>Estimated members</span><b>{amount>=.05?memberCount:0}</b><small>{amount>=.05?`${memberRate(amount)} members / TON tier`:'Minimum 0.05 TON'}</small></div></div>}
   <div className="exclusive-summary"><span>Members <b>{memberCount}</b></span><span>Worker reward <b>10 WIENER each</b></span><span>Total <b>{amount||0} TON</b></span></div><button className="primary" disabled={busy||!title.trim()||!target.trim()||!targetVerified||amount<.05} onClick={create}>{busy?'CREATING…':'CONTINUE TO PAYMENT'}</button>
  </section>}
  {pay&&<section className="card exclusive-payment"><div className="section-head"><div><h3>{pay.payment_status==='verified'?'Payment verified':'Pay with TON'}</h3><p>{pay.title} · {pay.target_completions} members</p></div><span className={`tag ${pay.payment_status==='verified'?'verified':''}`}>{statusText[pay.status]||pay.status}</span></div>{pay.payment_status!=='verified'?<><div className="pay-amount"><span>Send exactly</span><b>{pay.package_ton} TON</b></div><label>TON address</label><div className="copy-line"><code>{pay.payment_address}</code><button onClick={()=>copy(pay.payment_address,'Address')}>COPY</button></div><label>Memo / Comment <b>required</b></label><div className="copy-line"><code>{pay.payment_memo}</code><button onClick={()=>copy(pay.payment_memo,'Memo')}>COPY</button></div><div className="info-box">The backend verifies address, amount, memo, transaction age and TXID reuse on-chain.</div><label>Transaction hash / TXID</label><input value={tx} onChange={e=>setTx(e.target.value.trim())} placeholder="Paste TON transaction hash"/><button className="primary" disabled={busy||!tx} onClick={verify}>{busy?'VERIFYING ON-CHAIN…':'VERIFY PAYMENT'}</button></>:<div className="info-box">✅ Payment verified. Waiting for admin moderation.</div>}{(pay.status==='under_review'||pay.status==='rejected')&&<button className="support-btn" onClick={()=>openTg('https://t.me/WienerSupport')}>Task not listed? @WienerSupport</button>}{pay.status==='live'&&<div className="exclusive-progress"><b>{pay.title}</b><span>Live · {progressOf(pay)}/{pay.target_completions} verified members</span><div className="progress"><span style={{width:`${Math.min(100,progressOf(pay)/Number(pay.target_completions||1)*100)}%`}}/></div></div>}{pay.status==='completed'&&<div className="info-box">✅ Campaign completed.</div>}{pay.status==='rejected'&&<div className="info-box">Reason: {pay.rejection_reason||'Not approved'} · Contact @WienerSupport.</div>}</section>}
  {orders.length>0&&<section className="card my-promotions"><div className="section-head"><div><h3>My promotions</h3><p>Payment, moderation and delivery status</p></div></div>{orders.map(o=><button className="promotion-row" key={o.id} onClick={()=>selectOrder(o)}><div><b>{o.title}</b><small>{o.package_ton} TON · {progressOf(o)}/{o.target_completions} members</small></div><span>{statusText[o.status]||o.status}</span></button>)}</section>}
  {isAdmin&&moderation.some(o=>o.status==='under_review')&&<section className="card exclusive-moderation"><div className="section-head"><div><span className="eyebrow">ADMIN MODERATION</span><h3>Paid tasks waiting</h3><p>Only server-verified TON payments appear here.</p></div></div>{moderation.filter(o=>o.status==='under_review').map(o=><div className="moderation-row" key={o.id}><div><b>{o.title}</b><small>UID {o.telegram_id} · {o.package_ton} TON · {o.target_completions} members<br/>{kinds.find(k=>k.id===o.task_kind)?.name||o.task_kind} · {o.target_url||o.target_ref}<br/>TX: {String(o.tx_hash||'').slice(0,18)}…</small></div><div className="row-actions"><button className="good" disabled={busy} onClick={()=>approve(o)}>APPROVE</button><button className="danger" disabled={busy} onClick={()=>reject(o)}>REJECT</button></div></div>)}</section>}
 </section>;
}
