import {useState} from 'react';
import {api,type Snapshot} from './lib';
import {AnimatedIcon} from './icons';

type FarmState='ready'|'showing'|'claiming'|'success'|'failed';
function trackAdFocusLoss(){let interacted=false,started=false;const mark=()=>{if(started)interacted=true};const onVisibility=()=>{if(document.visibilityState==='hidden')mark()};const onBlur=()=>mark();document.addEventListener('visibilitychange',onVisibility,true);window.addEventListener('blur',onBlur,true);return{start:()=>{started=true},clicked:()=>interacted,stop:()=>{document.removeEventListener('visibilitychange',onVisibility,true);window.removeEventListener('blur',onBlur,true)}}}

export function FarmClaimModal({open,data,onClose,refresh,say}:{open:boolean;data:Snapshot;onClose:()=>void;refresh:any;say:any}){
  const [state,setState]=useState<FarmState>('ready'),[error,setError]=useState(''),[balance,setBalance]=useState<number|null>(null),[understood,setUnderstood]=useState(false);
  if(!open)return null;
  const reward=Number(data.settings.farm_claim_reward||0),busy=state==='showing'||state==='claiming';
  const close=()=>{if(busy)return;setState('ready');setError('');setBalance(null);setUnderstood(false);onClose()};
  const claim=async()=>{if(busy||!understood)return;const focusTracker=trackAdFocusLoss();try{setError('');if(!data.settings.adsgram_block_id)throw new Error('AdsGram Block ID is not configured');setState('showing');const controller=window.Adsgram?.init({blockId:String(data.settings.adsgram_block_id)});if(!controller)throw new Error('AdsGram SDK unavailable');focusTracker.start();const result=await controller.show();if(result&&result.done===false)throw new Error(result.description||'Complete the ad to claim your farm reward');if(!focusTracker.clicked())throw new Error('Tap the ad / CTA (Visit, Play or Open) before finishing the ad to unlock your farm reward.');setState('claiming');const r=await api('farm_claim');const fresh=await refresh();setBalance(Number(fresh?.user?.balance??r?.balance??data.user.balance));setState('success');say(`+${reward} WIENER claimed`)}catch(e:any){setError(String(e?.message||'Complete the ad and try again.'));setState('failed')}finally{focusTracker.stop()}};
  const retry=()=>{setState('ready');setError('');setUnderstood(false)};
  return <div className="farm-claim-overlay" role="dialog" aria-modal="true" aria-label="Claim farm reward"><style>{`
.farm-claim-overlay{position:fixed;inset:0;z-index:10020;display:flex;align-items:center;justify-content:center;padding:16px;background:rgba(4,8,10,.72);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);animation:farmFade .18s ease-out}.farm-claim-modal{width:min(100%,380px);padding:17px;border:1px solid rgba(255,255,255,.12);border-radius:24px;background:linear-gradient(155deg,rgba(20,28,30,.95),rgba(8,13,15,.93));box-shadow:0 18px 55px rgba(0,0,0,.46),inset 0 1px rgba(255,255,255,.06);animation:farmPop .24s cubic-bezier(.2,.8,.2,1)}.farm-claim-head{text-align:center;margin-bottom:11px}.farm-claim-icon{width:54px;height:54px;margin:0 auto 9px;display:grid;place-items:center;border-radius:18px;background:rgba(255,255,255,.06);box-shadow:inset 0 0 0 1px rgba(255,255,255,.08)}.farm-claim-head h3{margin:0;font-size:19px}.farm-claim-head p{margin:5px 0 0;font-size:12px;opacity:.62}.farm-claim-note{display:flex;gap:10px;align-items:flex-start;margin:10px 0;padding:12px;border:1px solid rgba(255,255,255,.1);border-radius:17px;background:rgba(255,255,255,.045)}.farm-claim-note-icon{font-size:20px}.farm-claim-note strong{display:block;font-size:13px;margin-bottom:2px}.farm-claim-note small{display:block;font-size:11px;line-height:1.4;opacity:.62}.farm-claim-reward{margin:10px 0;padding:13px;text-align:center;border:1px solid rgba(255,255,255,.09);border-radius:17px;background:rgba(255,255,255,.035)}.farm-claim-reward span{display:block;font-size:10px;opacity:.55;margin-bottom:3px}.farm-claim-reward strong{font-size:23px}.farm-claim-check{display:flex;gap:9px;align-items:center;margin:9px 0 12px;padding:10px;border-radius:14px;background:rgba(255,255,255,.035);font-size:11px;line-height:1.35;cursor:pointer}.farm-claim-check input{width:18px;height:18px;accent-color:currentColor;flex:0 0 auto}.farm-claim-actions{display:grid;gap:8px}.farm-claim-actions button{width:100%;min-height:44px;border-radius:14px;font-size:12px}.farm-claim-cancel{border:1px solid rgba(255,255,255,.1);background:transparent;color:inherit;opacity:.75}.farm-claim-status{text-align:center;padding:17px 6px 7px}.farm-claim-status .big{font-size:32px;margin-bottom:7px}.farm-claim-status h3{margin:0 0 5px;font-size:18px}.farm-claim-status p{margin:0 0 12px;font-size:12px;opacity:.65}.farm-claim-success strong{display:block;font-size:25px;margin:5px 0}.farm-claim-success small{opacity:.6;font-size:11px}.farm-claim-spinner{width:36px;height:36px;margin:3px auto 12px;border:3px solid rgba(255,255,255,.12);border-top-color:currentColor;border-radius:50%;animation:farmSpin .8s linear infinite}@keyframes farmSpin{to{transform:rotate(360deg)}}@keyframes farmFade{from{opacity:0}to{opacity:1}}@keyframes farmPop{from{opacity:0;transform:translateY(8px) scale(.97)}to{opacity:1;transform:none}}`}</style><div className="farm-claim-modal">
{state==='ready'&&<><div className="farm-claim-head"><div className="farm-claim-icon"><AnimatedIcon name="bolt" active/></div><h3>CLAIM FARM REWARD</h3><p>Watch a short ad to claim +{reward} WIENER.</p></div><div className="farm-claim-note"><div className="farm-claim-note-icon">☝️</div><div><strong>Tap inside the ad</strong><small>Open the advertiser CTA (Visit / Play / Open) before finishing the ad.</small></div></div><div className="farm-claim-reward"><span>REWARD WAITING</span><strong>+{reward} WIENER</strong></div><label className="farm-claim-check"><input type="checkbox" checked={understood} onChange={e=>setUnderstood(e.target.checked)}/><span>I understand I should tap the ad / CTA before claiming.</span></label><div className="farm-claim-actions"><button className="primary" disabled={!understood} onClick={claim}>▶ WATCH AD TO CLAIM</button><button className="farm-claim-cancel" onClick={close}>Cancel</button></div></>}
{state==='showing'&&<div className="farm-claim-status"><div className="farm-claim-spinner"/><h3>AD IN PROGRESS…</h3><p>Tap the ad / CTA and complete it to collect +{reward} WIENER.</p></div>}{state==='claiming'&&<div className="farm-claim-status"><div className="farm-claim-spinner"/><h3>CLAIMING REWARD…</h3><p>Ad interaction confirmed. Adding your farm reward.</p></div>}{state==='success'&&<div className="farm-claim-status farm-claim-success"><div className="big">✅</div><h3>REWARD CLAIMED</h3><strong>+{reward} WIENER</strong>{balance!=null&&<small>Balance: {balance.toLocaleString()} WIENER</small>}<p style={{marginTop:10}}>Your next farming cycle has started.</p><div className="farm-claim-actions"><button className="primary" onClick={close}>DONE</button></div></div>}{state==='failed'&&<div className="farm-claim-status"><div className="big">⚠️</div><h3>REWARD NOT CLAIMED</h3><p>{error||'Tap the ad / CTA, complete the rewarded ad and try again.'}</p><div className="farm-claim-actions"><button className="primary" onClick={retry}>CLAIM AGAIN</button><button className="farm-claim-cancel" onClick={close}>Cancel</button></div></div>}</div></div>
}
