import {useEffect,useRef,useState} from 'react';
import {api,type Snapshot} from './lib';

type FarmState='idle'|'showing'|'claiming'|'success'|'failed';
type FarmResult={reward:number;balance:number|null};

export function FarmClaimModal({open,data,onClose,refresh,say}:{open:boolean;data:Snapshot;onClose:()=>void;refresh:any;say:any}){
 const [state,setState]=useState<FarmState>('idle'),[error,setError]=useState(''),[result,setResult]=useState<FarmResult|null>(null);const started=useRef(false);
 const close=()=>{if(state==='showing'||state==='claiming')return;setState('idle');setError('');setResult(null);started.current=false;onClose()};
 const claim=async()=>{if(started.current)return;started.current=true;try{setError('');setResult(null);setState('showing');const start:any=await api('farm_ad_start');const c=window.Adsgram?.init({blockId:String(start?.block_id||data.settings.adsgram_block_id||'')});if(!c)throw Error('Claim ad is temporarily unavailable');const shown=await c.show();if(shown&&shown.done===false)throw Error(shown.description||'Complete the ad to claim your farm reward');setState('claiming');const r:any=await api('farm_claim',{session_id:start.session_id});const fresh=await refresh();setResult({reward:Number(r?.reward||0),balance:Number(fresh?.user?.balance??r?.balance??data.user.balance)});setState('success')}catch(e:any){const m=String(e?.message||'Complete the ad and try again.');setError(/farm_ad_verification_pending/i.test(m)?'Ad verification is still processing. Please try again.':m);setState('failed')}};
 useEffect(()=>{if(open&&!started.current)claim();if(!open){started.current=false;setState('idle');setError('');setResult(null)}},[open]);
 const retry=()=>{if(state==='showing'||state==='claiming')return;started.current=false;setError('');setResult(null);claim()};
 if(!open)return null;if(state==='idle')return null;
 if(state==='showing'||state==='claiming')return <div className="farm-claim-overlay" role="dialog" aria-modal="true"><style>{`.farm-claim-overlay{position:fixed;inset:0;z-index:10020;display:grid;place-items:center;padding:22px;background:rgba(4,12,9,.76);backdrop-filter:blur(12px)}.farm-claim-modal{width:min(100%,320px);padding:20px 18px;border:1px solid rgba(255,255,255,.12);border-radius:23px;background:linear-gradient(160deg,rgba(24,62,45,.98),rgba(7,38,27,.98));box-shadow:0 22px 60px rgba(0,0,0,.42);text-align:center}.farm-loader{width:42px;height:42px;margin:0 auto 14px;border:4px solid rgba(255,255,255,.15);border-top-color:#ffe33b;border-radius:50%;animation:farmSpin .8s linear infinite}@keyframes farmSpin{to{transform:rotate(360deg)}}.farm-claim-modal h3{margin:0 0 6px;font-size:17px}.farm-claim-modal p{margin:0;font-size:12px;opacity:.67}`}</style><div className="farm-claim-modal"><div className="farm-loader"/><h3>{state==='showing'?'OPENING CLAIM AD':'VERIFYING REWARD…'}</h3><p>Please wait. Don’t tap claim again.</p></div></div>;
 return <div className="farm-claim-overlay" role="dialog" aria-modal="true"><style>{`.farm-claim-overlay{position:fixed;inset:0;z-index:10020;display:grid;place-items:center;padding:22px;background:rgba(4,12,9,.76);backdrop-filter:blur(12px)}.farm-claim-modal{width:min(100%,320px);padding:20px 18px;border:1px solid rgba(255,255,255,.12);border-radius:23px;background:linear-gradient(160deg,rgba(24,62,45,.98),rgba(7,38,27,.98));box-shadow:0 22px 60px rgba(0,0,0,.42);text-align:center}.farm-claim-icon{width:50px;height:50px;margin:0 auto 10px;display:grid;place-items:center;border-radius:50%;background:rgba(255,224,52,.1);font-size:24px}.farm-claim-modal h3{margin:0 0 6px;font-size:17px}.farm-claim-modal p{margin:0 0 14px;font-size:12px;line-height:1.45;opacity:.67}.farm-claim-reward{font-size:35px;font-weight:950;color:#ffe33b;margin:7px 0 10px}.farm-claim-actions{display:grid;gap:8px}.farm-claim-actions button{width:100%;min-height:44px}.farm-claim-cancel{border:1px solid rgba(255,255,255,.1);background:transparent;color:inherit;border-radius:14px}.farm-claim-stats{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:13px 0}.farm-claim-stats div{padding:10px;border-radius:14px;background:rgba(255,255,255,.055)}.farm-claim-stats b{display:block;font-size:19px}.farm-claim-stats span{font-size:9px;opacity:.55;font-weight:800}`}</style><div className="farm-claim-modal">
 {state==='success'&&result&&<><div className="farm-claim-icon">🌾</div><h3>FARM REWARD UNLOCKED</h3><div className="farm-claim-reward">+{result.reward} WIENER</div><p>Your completed claim ad was verified by the server. Start the next farm manually whenever you’re ready.</p><div className="farm-claim-stats"><div><b>1</b><span>AD COMPLETED</span></div><div><b>✓</b><span>SERVER VERIFIED</span></div></div><div className="farm-claim-actions"><button className="primary" onClick={close}>CLAIMED ✓</button></div></>}
 {state==='failed'&&<><div className="farm-claim-icon">⚠️</div><h3>CLAIM NOT COMPLETED</h3><p>{error}</p><div className="farm-claim-actions"><button className="primary" onClick={retry}>TRY AGAIN</button><button className="farm-claim-cancel" onClick={close}>Cancel</button></div></>}
 </div></div>
}
