import {useState} from 'react';
import {api,type Snapshot} from './lib';
import {AnimatedIcon} from './icons';
import {trackAdInteraction} from './adInteraction';

type FarmState='ready'|'showing'|'claiming'|'success'|'failed';
type FarmResult={reward:number;full_reward:number;remaining:number;interaction_detected:boolean;balance:number|null};

export function FarmClaimModal({open,data,onClose,refresh,say}:{open:boolean;data:Snapshot;onClose:()=>void;refresh:any;say:any}){
 const [state,setState]=useState<FarmState>('ready'),[error,setError]=useState(''),[result,setResult]=useState<FarmResult|null>(null);
 if(!open)return null;
 const full=Number(data.settings.farm_claim_reward||0),busy=state==='showing'||state==='claiming';
 const close=()=>{if(busy)return;setState('ready');setError('');setResult(null);onClose()};
 const claim=async()=>{if(busy)return;const interaction=trackAdInteraction();try{setError('');setResult(null);if(!data.settings.adsgram_block_id)throw Error('AdsGram Block ID is not configured');setState('showing');const c=window.Adsgram?.init({blockId:String(data.settings.adsgram_block_id)});if(!c)throw Error('AdsGram SDK unavailable');interaction.start();const shown=await c.show();if(shown&&shown.done===false)throw Error(shown.description||'Complete the ad to claim your farm reward');const interacted=interaction.interacted();setState('claiming');const r:any=await api('farm_claim',{interacted});const fresh=await refresh();setResult({reward:Number(r?.reward||0),full_reward:Number(r?.full_reward||full),remaining:Number(r?.remaining||0),interaction_detected:!!r?.interaction_detected,balance:Number(fresh?.user?.balance??r?.balance??data.user.balance)});setState('success')}catch(e:any){setError(String(e?.message||'Complete the ad and try again.'));setState('failed')}finally{interaction.stop()}};
 const retry=()=>{setState('ready');setError('');setResult(null)};
 const partial=!!result&&result.remaining>0;
 return <div className="farm-claim-overlay" role="dialog" aria-modal="true"><style>{`.farm-claim-overlay{position:fixed;inset:0;z-index:10020;display:grid;place-items:center;padding:22px;background:rgba(4,12,9,.76);backdrop-filter:blur(12px)}.farm-claim-modal{width:min(100%,320px);padding:20px 18px;border:1px solid rgba(255,255,255,.12);border-radius:23px;background:linear-gradient(160deg,rgba(24,62,45,.98),rgba(7,38,27,.98));box-shadow:0 22px 60px rgba(0,0,0,.42);text-align:center}.farm-claim-icon{width:50px;height:50px;margin:0 auto 10px;display:grid;place-items:center;border-radius:50%;background:rgba(255,224,52,.1)}.farm-claim-modal h3{margin:0 0 6px;font-size:17px}.farm-claim-modal p{margin:0 0 14px;font-size:12px;line-height:1.45;opacity:.67}.farm-claim-reward{font-size:35px;font-weight:950;color:#ffe33b;margin:7px 0 10px}.farm-claim-actions{display:grid;gap:8px}.farm-claim-actions button{width:100%;min-height:44px}.farm-claim-cancel{border:1px solid rgba(255,255,255,.1);background:transparent;color:inherit;border-radius:14px}.farm-claim-spinner{width:36px;height:36px;margin:5px auto 14px;border:3px solid rgba(255,255,255,.12);border-top-color:currentColor;border-radius:50%;animation:farmSpin .8s linear infinite}.farm-claim-stats{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:13px 0}.farm-claim-stats div{padding:10px;border-radius:14px;background:rgba(255,255,255,.055)}.farm-claim-stats b{display:block;font-size:19px}.farm-claim-stats span{font-size:9px;opacity:.55;font-weight:800}@keyframes farmSpin{to{transform:rotate(360deg)}}`}</style><div className="farm-claim-modal">
 {state==='ready'&&<><div className="farm-claim-icon"><AnimatedIcon name="bolt" active/></div><h3>CLAIM FARM REWARD</h3><div className="farm-claim-reward">UP TO +{full}</div><p>Complete the claim ad. Visit the advertiser during the ad to unlock the full farm reward.</p><div className="farm-claim-actions"><button className="primary" onClick={claim}>▶ WATCH AD TO CLAIM</button><button className="farm-claim-cancel" onClick={close}>Cancel</button></div></>}
 {state==='showing'&&<><div className="farm-claim-spinner"/><h3>AD IN PROGRESS…</h3><p>Complete the ad to collect your farm reward.</p></>}
 {state==='claiming'&&<><div className="farm-claim-spinner"/><h3>CLAIMING REWARD…</h3><p>Securing your reward.</p></>}
 {state==='success'&&result&&<><div className="farm-claim-icon">{partial?'🌱':'🌾'}</div><h3>{partial?'PARTIAL FARM REWARD':'FARM REWARD UNLOCKED'}</h3><div className="farm-claim-reward">+{result.reward} WIENER</div>{partial?<p>You could’ve earned <b>{result.remaining} more WIENER</b> by visiting the advertiser.</p>:<p>Nice! You unlocked the full farm reward. Keep it up!</p>}<div className="farm-claim-stats"><div><b>1</b><span>CLAIM AD</span></div><div><b>{result.interaction_detected?1:0}</b><span>INTERACTION</span></div></div>{partial&&<p>Tip: Visit the advertiser during the claim ad to unlock the full reward next time.</p>}<div className="farm-claim-actions"><button className="primary" onClick={close}>{partial?'GOT IT':'CLAIMED ✓'}</button></div></>}
 {state==='failed'&&<><div className="farm-claim-icon">⚠️</div><h3>AD NOT COMPLETED</h3><p>{error}</p><div className="farm-claim-actions"><button className="primary" onClick={retry}>TRY AGAIN</button><button className="farm-claim-cancel" onClick={close}>Cancel</button></div></>}
 </div></div>
}
