import {useEffect} from 'react';
import {useI18n,type LangCode} from './i18n';

type P=Record<string,string>;
export const FULL_UI_PACKS:Partial<Record<LangCode,P>>={
 hi:{
  'ADS TASK':'विज्ञापन टास्क','Bonus Ads':'बोनस विज्ञापन','today':'आज','DONE':'पूरा','WATCH':'देखें','OPENING AD':'विज्ञापन खुल रहा है','Please wait. Don’t tap watch again.':'कृपया प्रतीक्षा करें। दोबारा देखें पर टैप न करें।','BONUS UNLOCKED':'बोनस अनलॉक','REWARD RECEIVED':'रिवॉर्ड मिला','Visit/click the ad to receive the full reward.':'पूरा रिवॉर्ड पाने के लिए विज्ञापन खोलें/क्लिक करें।','Your ad reward has been credited with bonus.':'आपका विज्ञापन रिवॉर्ड बोनस के साथ जमा हो गया।','Congratulations! Your ad reward has been credited.':'बधाई! आपका विज्ञापन रिवॉर्ड जमा हो गया।','Click to know how':'कैसे करें जानें','GOT IT':'समझ गया','SPIN & EARN':'स्पिन और कमाएँ','Win WIENER & TON':'WIENER और TON जीतें','AVAILABLE SPINS':'उपलब्ध स्पिन','SPIN TON BALANCE':'स्पिन TON बैलेंस','YOU WON':'आप जीते','SPINNING…':'स्पिन हो रहा है…','SPIN NOW':'अभी स्पिन करें','NO SPINS LEFT':'कोई स्पिन बाकी नहीं','OPENING AD…':'विज्ञापन खुल रहा है…','TON rewards accumulate separately':'TON रिवॉर्ड अलग बैलेंस में जुड़ते हैं','Withdraw':'निकासी','REQUEST WITHDRAWAL':'निकासी अनुरोध भेजें','Your Daily Spin is ready!':'आपका डेली स्पिन तैयार है!','You have a Spin available!':'आपके पास एक स्पिन उपलब्ध है!','Your free daily spin is waiting.':'आपका मुफ्त डेली स्पिन तैयार है।','You already have a spin ready to use.':'आपके पास उपयोग के लिए स्पिन तैयार है।','Maybe later':'बाद में','Add your link to claim':'क्लेम करने के लिए लिंक जोड़ें','Copy your referral link below.':'नीचे अपना रेफरल लिंक कॉपी करें।','Open Telegram → Profile → Edit → Bio, then paste the link.':'Telegram → Profile → Edit → Bio खोलें और लिंक पेस्ट करें।','Come back and tap Check & claim.':'वापस आएँ और जाँचें और क्लेम करें पर टैप करें।','COPY':'कॉपी','COPIED':'कॉपी हो गया','Later':'बाद में','Check & claim':'जाँचें और क्लेम करें','CHECKING…':'जाँच हो रही है…','TOTAL BALANCE':'कुल बैलेंस','Sessions':'सेशन','Referrals':'रेफरल','Today’s farms':'आज के फार्म','START FARM':'फार्म शुरू करें','STARTING…':'शुरू हो रहा है…','WIENER IS GROWING':'WIENER बढ़ रहा है','DAILY FARM LIMIT REACHED':'डेली फार्म सीमा पूरी','Promo Code':'प्रोमो कोड','Redeem a code for WIENER':'WIENER के लिए कोड रिडीम करें','ENTER CODE':'कोड डालें','APPLY':'लागू करें','Tasks':'टास्क','View all':'सभी देखें','Invite':'आमंत्रित करें','Watch Ads':'विज्ञापन देखें','Your Progress':'आपकी प्रगति','current tasks completed':'मौजूदा टास्क पूरे','Official':'आधिकारिक','Exclusive':'एक्सक्लूसिव','Partner':'पार्टनर','DAILY':'डेली','DAILY WIENER':'डेली WIENER','WIENER FARM':'WIENER फार्म','Farm is idle':'फार्म निष्क्रिय है','Your WIENER is ready':'आपका WIENER तैयार है','Your next WIENER is growing':'आपका अगला WIENER बढ़ रहा है','COME BACK TOMORROW':'कल वापस आएँ','Ready now':'अभी तैयार','Secure Telegram session':'सुरक्षित Telegram सेशन','Earn · Grow · Withdraw':'कमाएँ · बढ़ाएँ · निकालें','Home':'होम','Ads':'विज्ञापन','Wallet':'वॉलेट'
 },
 bn:{'ADS TASK':'বিজ্ঞাপন টাস্ক','Bonus Ads':'বোনাস বিজ্ঞাপন','today':'আজ','DONE':'সম্পন্ন','WATCH':'দেখুন','OPENING AD':'বিজ্ঞাপন খোলা হচ্ছে','BONUS UNLOCKED':'বোনাস আনলক হয়েছে','REWARD RECEIVED':'পুরস্কার পাওয়া গেছে','GOT IT':'বুঝেছি','SPIN & EARN':'স্পিন ও আয়','Win WIENER & TON':'WIENER ও TON জিতুন','AVAILABLE SPINS':'উপলব্ধ স্পিন','SPIN TON BALANCE':'স্পিন TON ব্যালেন্স','YOU WON':'আপনি জিতেছেন','SPINNING…':'স্পিন হচ্ছে…','SPIN NOW':'এখন স্পিন করুন','NO SPINS LEFT':'কোনো স্পিন বাকি নেই','Withdraw':'উত্তোলন','REQUEST WITHDRAWAL':'উত্তোলনের অনুরোধ','Your Daily Spin is ready!':'আপনার দৈনিক স্পিন প্রস্তুত!','Maybe later':'পরে','Add your link to claim':'ক্লেইম করতে লিঙ্ক যোগ করুন','COPY':'কপি','COPIED':'কপি হয়েছে','Later':'পরে','Check & claim':'যাচাই ও ক্লেইম','CHECKING…':'যাচাই হচ্ছে…','TOTAL BALANCE':'মোট ব্যালেন্স','Sessions':'সেশন','Referrals':'রেফারেল','Today’s farms':'আজকের ফার্ম','START FARM':'ফার্ম শুরু করুন','WIENER IS GROWING':'WIENER বাড়ছে','Promo Code':'প্রোমো কোড','ENTER CODE':'কোড লিখুন','APPLY':'প্রয়োগ করুন','Tasks':'টাস্ক','View all':'সব দেখুন','Invite':'আমন্ত্রণ','Watch Ads':'বিজ্ঞাপন দেখুন','Your Progress':'আপনার অগ্রগতি','Official':'অফিশিয়াল','Exclusive':'এক্সক্লুসিভ','Partner':'পার্টনার','DAILY':'দৈনিক','Farm is idle':'ফার্ম নিষ্ক্রিয়','Your WIENER is ready':'আপনার WIENER প্রস্তুত','COME BACK TOMORROW':'আগামীকাল আসুন','Ready now':'এখন প্রস্তুত','Home':'হোম','Ads':'বিজ্ঞাপন','Wallet':'ওয়ালেট'},
 es:{'ADS TASK':'TAREA DE ANUNCIOS','Bonus Ads':'Anuncios extra','today':'hoy','DONE':'HECHO','WATCH':'VER','OPENING AD':'ABRIENDO ANUNCIO','BONUS UNLOCKED':'BONO DESBLOQUEADO','REWARD RECEIVED':'RECOMPENSA RECIBIDA','GOT IT':'ENTENDIDO','SPIN & EARN':'GIRA Y GANA','Win WIENER & TON':'Gana WIENER y TON','AVAILABLE SPINS':'GIROS DISPONIBLES','SPIN TON BALANCE':'SALDO TON DE GIROS','YOU WON':'GANASTE','SPINNING…':'GIRANDO…','SPIN NOW':'GIRAR AHORA','NO SPINS LEFT':'SIN GIROS','Withdraw':'Retirar','REQUEST WITHDRAWAL':'SOLICITAR RETIRO','Your Daily Spin is ready!':'¡Tu giro diario está listo!','Maybe later':'Más tarde','Add your link to claim':'Añade tu enlace para reclamar','COPY':'COPIAR','COPIED':'COPIADO','Later':'Más tarde','Check & claim':'Verificar y reclamar','CHECKING…':'VERIFICANDO…','TOTAL BALANCE':'SALDO TOTAL','Sessions':'Sesiones','Referrals':'Referidos','Today’s farms':'Granjas de hoy','START FARM':'INICIAR GRANJA','WIENER IS GROWING':'WIENER ESTÁ CRECIENDO','Promo Code':'Código promo','ENTER CODE':'INTRODUCE CÓDIGO','APPLY':'APLICAR','Tasks':'Tareas','View all':'Ver todo','Invite':'Invitar','Watch Ads':'Ver anuncios','Your Progress':'Tu progreso','Official':'Oficial','Exclusive':'Exclusivo','Partner':'Socio','DAILY':'DIARIO','Farm is idle':'La granja está inactiva','Your WIENER is ready':'Tu WIENER está listo','COME BACK TOMORROW':'VUELVE MAÑANA','Ready now':'Listo ahora','Home':'Inicio','Ads':'Anuncios','Wallet':'Billetera'},
 de:{'ADS TASK':'WERBEAUFGABE','Bonus Ads':'Bonus-Werbung','today':'heute','DONE':'FERTIG','WATCH':'ANSEHEN','OPENING AD':'WERBUNG WIRD GEÖFFNET','BONUS UNLOCKED':'BONUS FREIGESCHALTET','REWARD RECEIVED':'BELOHNUNG ERHALTEN','GOT IT':'VERSTANDEN','SPIN & EARN':'DREHEN & VERDIENEN','Win WIENER & TON':'WIENER & TON gewinnen','AVAILABLE SPINS':'VERFÜGBARE DREHS','SPIN TON BALANCE':'SPIN-TON-GUTHABEN','YOU WON':'DU HAST GEWONNEN','SPINNING…':'DREHT…','SPIN NOW':'JETZT DREHEN','NO SPINS LEFT':'KEINE DREHS ÜBRIG','Withdraw':'Auszahlen','REQUEST WITHDRAWAL':'AUSZAHLUNG ANFORDERN','Your Daily Spin is ready!':'Dein täglicher Dreh ist bereit!','Maybe later':'Später','Add your link to claim':'Link zum Abholen hinzufügen','COPY':'KOPIEREN','COPIED':'KOPIERT','Later':'Später','Check & claim':'Prüfen & abholen','CHECKING…':'PRÜFUNG…','TOTAL BALANCE':'GESAMTGUTHABEN','Sessions':'Sitzungen','Referrals':'Empfehlungen','Today’s farms':'Heutige Farmen','START FARM':'FARM STARTEN','WIENER IS GROWING':'WIENER WÄCHST','Promo Code':'Promo-Code','ENTER CODE':'CODE EINGEBEN','APPLY':'ANWENDEN','Tasks':'Aufgaben','View all':'Alle ansehen','Invite':'Einladen','Watch Ads':'Werbung ansehen','Your Progress':'Dein Fortschritt','Official':'Offiziell','Exclusive':'Exklusiv','Partner':'Partner','DAILY':'TÄGLICH','Farm is idle':'Farm ist inaktiv','Your WIENER is ready':'Dein WIENER ist bereit','COME BACK TOMORROW':'MORGEN WIEDERKOMMEN','Ready now':'Jetzt bereit','Home':'Start','Ads':'Werbung','Wallet':'Wallet'},
 fr:{'ADS TASK':'TÂCHE PUBLICITAIRE','Bonus Ads':'Pubs bonus','today':'aujourd’hui','DONE':'TERMINÉ','WATCH':'REGARDER','OPENING AD':'OUVERTURE DE LA PUB','BONUS UNLOCKED':'BONUS DÉBLOQUÉ','REWARD RECEIVED':'RÉCOMPENSE REÇUE','GOT IT':'COMPRIS','SPIN & EARN':'TOURNEZ ET GAGNEZ','Win WIENER & TON':'Gagnez des WIENER et TON','AVAILABLE SPINS':'TOURS DISPONIBLES','SPIN TON BALANCE':'SOLDE TON DES TOURS','YOU WON':'VOUS AVEZ GAGNÉ','SPINNING…':'TOUR EN COURS…','SPIN NOW':'TOURNER','NO SPINS LEFT':'PLUS DE TOURS','Withdraw':'Retirer','REQUEST WITHDRAWAL':'DEMANDER LE RETRAIT','Your Daily Spin is ready!':'Votre tour quotidien est prêt !','Maybe later':'Plus tard','Add your link to claim':'Ajoutez votre lien pour réclamer','COPY':'COPIER','COPIED':'COPIÉ','Later':'Plus tard','Check & claim':'Vérifier et réclamer','CHECKING…':'VÉRIFICATION…','TOTAL BALANCE':'SOLDE TOTAL','Sessions':'Sessions','Referrals':'Parrainages','Today’s farms':'Fermes du jour','START FARM':'DÉMARRER LA FERME','WIENER IS GROWING':'WIENER GRANDIT','Promo Code':'Code promo','ENTER CODE':'ENTRER LE CODE','APPLY':'APPLIQUER','Tasks':'Tâches','View all':'Voir tout','Invite':'Inviter','Watch Ads':'Voir les pubs','Your Progress':'Votre progression','Official':'Officiel','Exclusive':'Exclusif','Partner':'Partenaire','DAILY':'QUOTIDIEN','Farm is idle':'La ferme est inactive','Your WIENER is ready':'Votre WIENER est prêt','COME BACK TOMORROW':'REVENEZ DEMAIN','Ready now':'Prêt maintenant','Home':'Accueil','Ads':'Pubs','Wallet':'Portefeuille'},
 pt:{'ADS TASK':'TAREFA DE ANÚNCIOS','Bonus Ads':'Anúncios bônus','today':'hoje','DONE':'CONCLUÍDO','WATCH':'ASSISTIR','OPENING AD':'ABRINDO ANÚNCIO','BONUS UNLOCKED':'BÔNUS DESBLOQUEADO','REWARD RECEIVED':'RECOMPENSA RECEBIDA','GOT IT':'ENTENDI','SPIN & EARN':'GIRE E GANHE','Win WIENER & TON':'Ganhe WIENER e TON','AVAILABLE SPINS':'GIROS DISPONÍVEIS','SPIN TON BALANCE':'SALDO TON DOS GIROS','YOU WON':'VOCÊ GANHOU','SPINNING…':'GIRANDO…','SPIN NOW':'GIRAR AGORA','NO SPINS LEFT':'SEM GIROS','Withdraw':'Sacar','REQUEST WITHDRAWAL':'SOLICITAR SAQUE','Your Daily Spin is ready!':'Seu giro diário está pronto!','Maybe later':'Mais tarde','Add your link to claim':'Adicione seu link para resgatar','COPY':'COPIAR','COPIED':'COPIADO','Later':'Mais tarde','Check & claim':'Verificar e resgatar','CHECKING…':'VERIFICANDO…','TOTAL BALANCE':'SALDO TOTAL','Sessions':'Sessões','Referrals':'Indicações','Today’s farms':'Farms de hoje','START FARM':'INICIAR FARM','WIENER IS GROWING':'WIENER ESTÁ CRESCENDO','Promo Code':'Código promocional','ENTER CODE':'DIGITE O CÓDIGO','APPLY':'APLICAR','Tasks':'Tarefas','View all':'Ver tudo','Invite':'Convidar','Watch Ads':'Assistir anúncios','Your Progress':'Seu progresso','Official':'Oficial','Exclusive':'Exclusivo','Partner':'Parceiro','DAILY':'DIÁRIO','Farm is idle':'Farm inativa','Your WIENER is ready':'Seu WIENER está pronto','COME BACK TOMORROW':'VOLTE AMANHÃ','Ready now':'Pronto agora','Home':'Início','Ads':'Anúncios','Wallet':'Carteira'},
 'pt-BR':{},
 tr:{'ADS TASK':'REKLAM GÖREVİ','Bonus Ads':'Bonus Reklamlar','today':'bugün','DONE':'TAMAM','WATCH':'İZLE','OPENING AD':'REKLAM AÇILIYOR','BONUS UNLOCKED':'BONUS AÇILDI','REWARD RECEIVED':'ÖDÜL ALINDI','GOT IT':'ANLADIM','SPIN & EARN':'ÇEVİR & KAZAN','Win WIENER & TON':'WIENER & TON kazan','AVAILABLE SPINS':'KULLANILABİLİR ÇEVİRMELER','SPIN TON BALANCE':'ÇEVİRME TON BAKİYESİ','YOU WON':'KAZANDIN','SPINNING…':'ÇEVRİLİYOR…','SPIN NOW':'ŞİMDİ ÇEVİR','NO SPINS LEFT':'ÇEVİRME KALMADI','Withdraw':'Çek','REQUEST WITHDRAWAL':'ÇEKİM TALEP ET','Your Daily Spin is ready!':'Günlük çevirmen hazır!','Maybe later':'Daha sonra','Add your link to claim':'Almak için bağlantını ekle','COPY':'KOPYALA','COPIED':'KOPYALANDI','Later':'Daha sonra','Check & claim':'Kontrol et & al','CHECKING…':'KONTROL EDİLİYOR…','TOTAL BALANCE':'TOPLAM BAKİYE','Sessions':'Oturumlar','Referrals':'Referanslar','Today’s farms':'Bugünkü farmlar','START FARM':'FARMI BAŞLAT','WIENER IS GROWING':'WIENER BÜYÜYOR','Promo Code':'Promosyon Kodu','ENTER CODE':'KODU GİR','APPLY':'UYGULA','Tasks':'Görevler','View all':'Tümünü gör','Invite':'Davet et','Watch Ads':'Reklam İzle','Your Progress':'İlerlemen','Official':'Resmî','Exclusive':'Özel','Partner':'Ortak','DAILY':'GÜNLÜK','Farm is idle':'Farm boşta','Your WIENER is ready':'WIENER hazır','COME BACK TOMORROW':'YARIN GEL','Ready now':'Şimdi hazır','Home':'Ana Sayfa','Ads':'Reklamlar','Wallet':'Cüzdan'},
 uk:{'ADS TASK':'ЗАВДАННЯ З РЕКЛАМОЮ','Bonus Ads':'Бонусна реклама','today':'сьогодні','DONE':'ГОТОВО','WATCH':'ДИВИТИСЯ','OPENING AD':'ВІДКРИВАЄМО РЕКЛАМУ','BONUS UNLOCKED':'БОНУС РОЗБЛОКОВАНО','REWARD RECEIVED':'НАГОРОДУ ОТРИМАНО','GOT IT':'ЗРОЗУМІЛО','SPIN & EARN':'КРУТИ ТА ЗАРОБЛЯЙ','Win WIENER & TON':'Вигравай WIENER і TON','AVAILABLE SPINS':'ДОСТУПНІ ОБЕРТИ','SPIN TON BALANCE':'TON БАЛАНС ОБЕРТІВ','YOU WON':'ВИ ВИГРАЛИ','SPINNING…':'ОБЕРТАННЯ…','SPIN NOW':'КРУТИТИ','NO SPINS LEFT':'ОБЕРТІВ НЕМАЄ','Withdraw':'Вивести','REQUEST WITHDRAWAL':'ЗАПИТ НА ВИВЕДЕННЯ','Your Daily Spin is ready!':'Ваш щоденний оберт готовий!','Maybe later':'Пізніше','Add your link to claim':'Додайте посилання для отримання','COPY':'КОПІЮВАТИ','COPIED':'СКОПІЙОВАНО','Later':'Пізніше','Check & claim':'Перевірити й отримати','CHECKING…':'ПЕРЕВІРКА…','TOTAL BALANCE':'ЗАГАЛЬНИЙ БАЛАНС','Sessions':'Сесії','Referrals':'Реферали','Today’s farms':'Фарм сьогодні','START FARM':'ПОЧАТИ ФАРМ','WIENER IS GROWING':'WIENER ЗРОСТАЄ','Promo Code':'Промокод','ENTER CODE':'ВВЕДІТЬ КОД','APPLY':'ЗАСТОСУВАТИ','Tasks':'Завдання','View all':'Показати все','Invite':'Запросити','Watch Ads':'Дивитися рекламу','Your Progress':'Ваш прогрес','Official':'Офіційні','Exclusive':'Ексклюзивні','Partner':'Партнерські','DAILY':'ЩОДЕННЕ','Farm is idle':'Фарм неактивний','Your WIENER is ready':'Ваш WIENER готовий','COME BACK TOMORROW':'ПОВЕРНІТЬСЯ ЗАВТРА','Ready now':'Готово зараз','Home':'Головна','Ads':'Реклама','Wallet':'Гаманець'},
 ru:{'ADS TASK':'ЗАДАНИЕ С РЕКЛАМОЙ','Bonus Ads':'Бонусная реклама','today':'сегодня','DONE':'ГОТОВО','WATCH':'СМОТРЕТЬ','OPENING AD':'ОТКРЫВАЕМ РЕКЛАМУ','BONUS UNLOCKED':'БОНУС РАЗБЛОКИРОВАН','REWARD RECEIVED':'НАГРАДА ПОЛУЧЕНА','GOT IT':'ПОНЯТНО','SPIN & EARN':'КРУТИ И ЗАРАБАТЫВАЙ','Win WIENER & TON':'Выигрывай WIENER и TON','AVAILABLE SPINS':'ДОСТУПНЫЕ ВРАЩЕНИЯ','SPIN TON BALANCE':'TON БАЛАНС ВРАЩЕНИЙ','YOU WON':'ВЫ ВЫИГРАЛИ','SPINNING…':'ВРАЩЕНИЕ…','SPIN NOW':'КРУТИТЬ','NO SPINS LEFT':'ВРАЩЕНИЙ НЕТ','Withdraw':'Вывести','REQUEST WITHDRAWAL':'ЗАПРОСИТЬ ВЫВОД','Your Daily Spin is ready!':'Ваш ежедневный спин готов!','Maybe later':'Позже','Add your link to claim':'Добавьте ссылку для получения','COPY':'КОПИРОВАТЬ','COPIED':'СКОПИРОВАНО','Later':'Позже','Check & claim':'Проверить и получить','CHECKING…':'ПРОВЕРКА…','TOTAL BALANCE':'ОБЩИЙ БАЛАНС','Sessions':'Сессии','Referrals':'Рефералы','Today’s farms':'Фарм сегодня','START FARM':'НАЧАТЬ ФАРМ','WIENER IS GROWING':'WIENER РАСТЁТ','Promo Code':'Промокод','ENTER CODE':'ВВЕДИТЕ КОД','APPLY':'ПРИМЕНИТЬ','Tasks':'Задания','View all':'Показать все','Invite':'Пригласить','Watch Ads':'Смотреть рекламу','Your Progress':'Ваш прогресс','Official':'Официальные','Exclusive':'Эксклюзивные','Partner':'Партнёрские','DAILY':'ЕЖЕДНЕВНО','Farm is idle':'Фарм неактивен','Your WIENER is ready':'Ваш WIENER готов','COME BACK TOMORROW':'ВЕРНИТЕСЬ ЗАВТРА','Ready now':'Готово сейчас','Home':'Главная','Ads':'Реклама','Wallet':'Кошелёк'},
 id:{'ADS TASK':'TUGAS IKLAN','Bonus Ads':'Iklan Bonus','today':'hari ini','DONE':'SELESAI','WATCH':'TONTON','OPENING AD':'MEMBUKA IKLAN','BONUS UNLOCKED':'BONUS TERBUKA','REWARD RECEIVED':'HADIAH DITERIMA','GOT IT':'MENGERTI','SPIN & EARN':'PUTAR & DAPATKAN','Win WIENER & TON':'Menangkan WIENER & TON','AVAILABLE SPINS':'SPIN TERSEDIA','SPIN TON BALANCE':'SALDO TON SPIN','YOU WON':'KAMU MENANG','SPINNING…':'MEMUTAR…','SPIN NOW':'PUTAR SEKARANG','NO SPINS LEFT':'SPIN HABIS','Withdraw':'Tarik','REQUEST WITHDRAWAL':'MINTA PENARIKAN','Your Daily Spin is ready!':'Spin harianmu siap!','Maybe later':'Nanti','Add your link to claim':'Tambahkan tautan untuk klaim','COPY':'SALIN','COPIED':'TERSALIN','Later':'Nanti','Check & claim':'Periksa & klaim','CHECKING…':'MEMERIKSA…','TOTAL BALANCE':'TOTAL SALDO','Sessions':'Sesi','Referrals':'Referral','Today’s farms':'Farm hari ini','START FARM':'MULAI FARM','WIENER IS GROWING':'WIENER SEDANG TUMBUH','Promo Code':'Kode Promo','ENTER CODE':'MASUKKAN KODE','APPLY':'TERAPKAN','Tasks':'Tugas','View all':'Lihat semua','Invite':'Undang','Watch Ads':'Tonton Iklan','Your Progress':'Progresmu','Official':'Resmi','Exclusive':'Eksklusif','Partner':'Partner','DAILY':'HARIAN','Farm is idle':'Farm tidak aktif','Your WIENER is ready':'WIENER-mu siap','COME BACK TOMORROW':'KEMBALI BESOK','Ready now':'Siap sekarang','Home':'Beranda','Ads':'Iklan','Wallet':'Dompet'},
 ar:{'ADS TASK':'مهمة الإعلانات','Bonus Ads':'إعلانات إضافية','today':'اليوم','DONE':'تم','WATCH':'مشاهدة','OPENING AD':'جارٍ فتح الإعلان','BONUS UNLOCKED':'تم فتح المكافأة','REWARD RECEIVED':'تم استلام المكافأة','GOT IT':'فهمت','SPIN & EARN':'أدر واربح','Win WIENER & TON':'اربح WIENER و TON','AVAILABLE SPINS':'الدورات المتاحة','SPIN TON BALANCE':'رصيد TON للدوران','YOU WON':'لقد ربحت','SPINNING…':'جارٍ الدوران…','SPIN NOW':'أدر الآن','NO SPINS LEFT':'لا توجد دورات','Withdraw':'سحب','REQUEST WITHDRAWAL':'طلب سحب','Your Daily Spin is ready!':'دورتك اليومية جاهزة!','Maybe later':'لاحقًا','Add your link to claim':'أضف رابطك للمطالبة','COPY':'نسخ','COPIED':'تم النسخ','Later':'لاحقًا','Check & claim':'تحقق واستلم','CHECKING…':'جارٍ التحقق…','TOTAL BALANCE':'الرصيد الإجمالي','Sessions':'الجلسات','Referrals':'الإحالات','Today’s farms':'مزارع اليوم','START FARM':'ابدأ المزرعة','WIENER IS GROWING':'WIENER ينمو','Promo Code':'رمز ترويجي','ENTER CODE':'أدخل الرمز','APPLY':'تطبيق','Tasks':'المهام','View all':'عرض الكل','Invite':'دعوة','Watch Ads':'مشاهدة الإعلانات','Your Progress':'تقدمك','Official':'رسمي','Exclusive':'حصري','Partner':'شريك','DAILY':'يومي','Farm is idle':'المزرعة متوقفة','Your WIENER is ready':'WIENER الخاص بك جاهز','COME BACK TOMORROW':'عد غدًا','Ready now':'جاهز الآن','Home':'الرئيسية','Ads':'الإعلانات','Wallet':'المحفظة'},
 'zh-CN':{'ADS TASK':'广告任务','Bonus Ads':'奖励广告','today':'今天','DONE':'完成','WATCH':'观看','OPENING AD':'正在打开广告','BONUS UNLOCKED':'奖励已解锁','REWARD RECEIVED':'已收到奖励','GOT IT':'知道了','SPIN & EARN':'转盘赚取','Win WIENER & TON':'赢取 WIENER 和 TON','AVAILABLE SPINS':'可用次数','SPIN TON BALANCE':'转盘 TON 余额','YOU WON':'你赢得了','SPINNING…':'转动中…','SPIN NOW':'立即转动','NO SPINS LEFT':'没有可用次数','Withdraw':'提现','REQUEST WITHDRAWAL':'申请提现','Your Daily Spin is ready!':'你的每日转盘已准备好！','Maybe later':'稍后','Add your link to claim':'添加链接以领取','COPY':'复制','COPIED':'已复制','Later':'稍后','Check & claim':'检查并领取','CHECKING…':'检查中…','TOTAL BALANCE':'总余额','Sessions':'次数','Referrals':'邀请','Today’s farms':'今日农场','START FARM':'开始农场','WIENER IS GROWING':'WIENER 正在增长','Promo Code':'兑换码','ENTER CODE':'输入代码','APPLY':'使用','Tasks':'任务','View all':'查看全部','Invite':'邀请','Watch Ads':'观看广告','Your Progress':'你的进度','Official':'官方','Exclusive':'专属','Partner':'合作','DAILY':'每日','Farm is idle':'农场未启动','Your WIENER is ready':'你的 WIENER 已准备好','COME BACK TOMORROW':'明天再来','Ready now':'现在可领取','Home':'主页','Ads':'广告','Wallet':'钱包'},
 'zh-TW':{'ADS TASK':'廣告任務','Bonus Ads':'獎勵廣告','today':'今天','DONE':'完成','WATCH':'觀看','OPENING AD':'正在開啟廣告','BONUS UNLOCKED':'獎勵已解鎖','REWARD RECEIVED':'已收到獎勵','GOT IT':'知道了','SPIN & EARN':'轉盤賺取','Win WIENER & TON':'贏取 WIENER 和 TON','AVAILABLE SPINS':'可用次數','SPIN TON BALANCE':'轉盤 TON 餘額','YOU WON':'你贏得了','SPINNING…':'轉動中…','SPIN NOW':'立即轉動','NO SPINS LEFT':'沒有可用次數','Withdraw':'提領','REQUEST WITHDRAWAL':'申請提領','Your Daily Spin is ready!':'你的每日轉盤已準備好！','Maybe later':'稍後','Add your link to claim':'新增連結以領取','COPY':'複製','COPIED':'已複製','Later':'稍後','Check & claim':'檢查並領取','CHECKING…':'檢查中…','TOTAL BALANCE':'總餘額','Sessions':'次數','Referrals':'邀請','Today’s farms':'今日農場','START FARM':'開始農場','WIENER IS GROWING':'WIENER 正在成長','Promo Code':'兌換碼','ENTER CODE':'輸入代碼','APPLY':'使用','Tasks':'任務','View all':'查看全部','Invite':'邀請','Watch Ads':'觀看廣告','Your Progress':'你的進度','Official':'官方','Exclusive':'專屬','Partner':'合作','DAILY':'每日','Farm is idle':'農場未啟動','Your WIENER is ready':'你的 WIENER 已準備好','COME BACK TOMORROW':'明天再來','Ready now':'現在可領取','Home':'首頁','Ads':'廣告','Wallet':'錢包'}
};
FULL_UI_PACKS['pt-BR']=FULL_UI_PACKS.pt;

const originalText=new WeakMap<Text,string>();
const originalPlaceholder=new WeakMap<HTMLInputElement|string extends never?never:any,string>();
function translateDynamic(text:string,map:P){
 if(map[text])return map[text];
 let m=text.match(/^AdsGram — (\d+) ads$/);if(m)return `AdsGram — ${m[1]} ${map.Ads||'ads'}`;
 m=text.match(/^Bonus Ads — (\d+) ads$/);if(m)return `${map['Bonus Ads']||'Bonus Ads'} — ${m[1]} ${map.Ads||'ads'}`;
 m=text.match(/^(.+) WIENER · (\d+)\/(\d+) today$/);if(m)return `${m[1]} WIENER · ${m[2]}/${m[3]} ${map.today||'today'}`;
 m=text.match(/^WATCH AD → \+1 SPIN \((\d+) left\)$/);if(m)return `${map.WATCH||'WATCH'} AD → +1 SPIN (${m[1]})`;
 m=text.match(/^Minimum withdrawal (.+) TON$/);if(m)return `${map.Withdraw||'Withdraw'} · ${m[1]} TON`;
 m=text.match(/^Minimum (.+) TON$/);if(m)return `${map.Withdraw||'Withdraw'} ${m[1]} TON`;
 m=text.match(/^Ready in (.+)$/);if(m)return `${map['Ready now']||'Ready'} ${m[1]}`;
 return text;
}
function skip(el:Element|null){if(!el)return true;return !!el.closest('script,style,code,pre,.language-list,.language-current,[data-no-translate]')}
export function FullUiTranslator(){
 const {lang}=useI18n();
 useEffect(()=>{
  const map=FULL_UI_PACKS[lang];if(!map||lang==='en')return;
  const apply=()=>{
   const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n:Node|null;
   while((n=w.nextNode())){const t=n as Text;if(skip(t.parentElement))continue;const raw=originalText.get(t)??t.nodeValue??'';if(!originalText.has(t))originalText.set(t,raw);const lead=raw.match(/^\s*/)?.[0]||'',trail=raw.match(/\s*$/)?.[0]||'',core=raw.trim();if(!core)continue;const out=translateDynamic(core,map);const next=lead+out+trail;if(t.nodeValue!==next)t.nodeValue=next}
   document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('input[placeholder],textarea[placeholder]').forEach(el=>{if(skip(el))return;const raw=(el as any).__wfOriginalPlaceholder??el.placeholder;(el as any).__wfOriginalPlaceholder=raw;const out=translateDynamic(raw,map);if(el.placeholder!==out)el.placeholder=out});
  };
  apply();const o=new MutationObserver(()=>queueMicrotask(apply));o.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>o.disconnect();
 },[lang]);
 return null;
}
