export const V75_KEYS=[
'Securing WIENER…','Opening your farm…','Syncing your rewards…','Growing your dashboard…','Almost ready…','EARN · GROW · WITHDRAW',
'Daily reward requirement','Add your link to claim','To claim your Daily WIENER, add your personal WIENER Farm referral link to your Telegram bio.','⚠️ Keep your Telegram bio visible so WIENER Farm can verify the link. If you just changed it, wait a few seconds and check again.','Could not copy the link. Press and hold the link to copy it.','Complete 4 weekly streaks to unlock a Loyalty Chest automatically.','CHECKING BIO…',
'Invite & Earn Together','Your Friends','REWARD TIERS','Per friend','On successful join','After 5 verified ads','When active','A referral becomes active after 5 verified ads. The same 5-ad rule applies to all eligible referrals.','No friends yet — share your link to start earning.','Eligible earnings','Lifetime cut','Top Earners','Top Inviters','🏆 Referral Leaderboard',
'Weekly Missions','Complete weekly goals. Claim extra WIENER.','SPECIAL MISSIONS','Extra ways to earn','AUTO CHECK','DIRECT CLAIM','Complete this mission and claim your reward.','Loading weekly missions…',
'1 FREE DAILY · +14 FROM ADS','BONUS SPINS EXTRA','1 free daily · up to 14 ad spins · won spins are extra','Daily Spin','Your free daily spin is waiting. Spin now and try to win WIENER, TON or bonus spins.',
'Create Sponsored Task','Official Tasks · easy setup','Checking task…','Checking Mini App link…','🎁 Reward per completion:','TOTAL PRICE','CONTINUE TO TON PAYMENT','Automatic verification · no TX hash','Connect a TON wallet to continue','CHECK PAYMENT','My Sponsored Tasks','Manage Sponsored Task','Add more completions','Custom completions','Top-up history','PENDING PAYMENT','TON payments · automatic verification','↻ REFRESH STATUS',
'Unlock Withdrawal','Checking withdrawal requirements…','Watch 5 sponsor ads today to unlock the withdrawal flow.','Watch the full sponsor ad before returning. Short views do not count.','Only counted sponsor views unlock withdrawal. Progress resets daily (UTC).','Withdrawal Unlocked','Your withdrawal access is unlocked for today.','✓ UNLOCKED FOR TODAY',
'GRAM WALLET · TON','Connect your TON wallet','Connect your TON wallet above to continue. WIENER Farm never receives your seed phrase or private key.','Secure TON Connect · No seed phrase','ENTER AMOUNT IN WIENER','Live Gram Price','Loading Gram price…','Estimated Gram','Final Gram amount may move slightly because the backend refreshes the TON price on confirmation.','Review Gram','CONFIRM GRAM WITHDRAWAL','WITHDRAW GRAM','Withdrawal pending · wait for processing before another request.','Withdrawals are temporarily disabled.','This TON wallet is already connected to another WIENER Farm account.','Live TON price is temporarily unavailable. Please try again shortly.','Gram withdrawal request failed','OPENING WALLET…','SYNCING…','Ready for Gram withdrawal','Next withdrawal in',
'Complete the ad to claim your farm reward','FARM REWARD RECEIVED','Congratulations! Your farm reward has been credited.','Bonus not unlocked. Visiting the advertiser can unlock the bonus next time.','Loading live rankings…','Current Streak','Top Referrals','No partner tasks right now.','No sponsored task right now','Open the task, then tap CHECK','Return after 15 seconds and tap CHECK.','Checking again automatically…','✅ Verified — tap CLAIM to receive your reward','Loading next task','Task verification failed','Sponsor ad is unavailable right now. Try again shortly.','Ad session expired. Tap WATCH AD and try again.'
] as const;
export type V75Phrase=typeof V75_KEYS[number];
export type V75Pack=Partial<Record<V75Phrase,string>>;
export const makeV75=(values:string[]):V75Pack=>Object.fromEntries(V75_KEYS.map((k,i)=>[k,values[i]||k])) as V75Pack;
