export type ExtraDict=Record<string,string>;
export const EXTRA_PACKS:Record<string,ExtraDict>={
 hi:{
  'common.loading':'लोड हो रहा है…','common.done':'पूरा','common.join':'जॉइन करें','common.watch':'देखें','common.wait':'रुकें','common.apply':'लागू करें','common.back':'वापस','common.continue':'जारी रखें','common.review':'समीक्षा','common.status':'स्थिति','common.network':'नेटवर्क','common.fee':'फीस','common.amount':'राशि','common.totalEarned':'कुल कमाई','common.rank':'रैंक','common.referrals':'रेफरल','common.qualified':'क्वालिफाइड','common.tasks':'टास्क','common.days':'दिन','common.unavailable':'अस्थायी रूप से उपलब्ध नहीं',
  'home.todayFarms':'आज के फार्म','home.starting':'शुरू हो रहा है…','home.growing':'WIENER बढ़ रहा है','home.dailyLimit':'आज की फार्म सीमा पूरी हो गई','home.viewAll':'सभी देखें','daily.streak':'स्ट्रीक','daily.claimedToday':'आज क्लेम किया','daily.bestStreak':'सर्वश्रेष्ठ स्ट्रीक','daily.keep':'स्ट्रीक बनाए रखने के लिए हर दिन क्लेम करें।',
  'promo.subtitle':'क्लेम करने के लिए एक रिवॉर्डेड विज्ञापन देखें','promo.enter':'कोड दर्ज करें','promo.showing':'विज्ञापन दिखाया जा रहा है…','promo.claimAgain':'फिर से क्लेम करें','promo.claimed':'प्रोमो क्लेम हुआ','promo.gotIt':'समझ गया','promo.complete':'रिवॉर्डेड विज्ञापन पूरा करें, फिर प्रोमो रिवॉर्ड जुड़ जाएगा।',
  'tasks.completed':'मौजूदा टास्क पूरे','tasks.official':'ऑफिशियल','tasks.exclusive':'एक्सक्लूसिव','tasks.partner':'पार्टनर','tasks.daily':'डेली','tasks.none':'अभी कोई टास्क नहीं है।',
  'invite.subtitle':'दोस्तों को WIENER में आमंत्रित करें और क्वालिफाई होने पर रिवॉर्ड कमाएं।','invite.invited':'आमंत्रित','invite.earned':'कमाया','invite.link':'आपका इनवाइट लिंक','invite.share':'इनवाइट शेयर करें','invite.perQualified':'प्रति क्वालिफाइड','invite.recent':'हाल के रेफरल','invite.copied':'इनवाइट लिंक कॉपी हुआ',
  'profile.streak':'स्ट्रीक','profile.bestStreak':'सर्वश्रेष्ठ स्ट्रीक','profile.openWallet':'वॉलेट खोलें',
  'wallet.selectHint':'सही नेटवर्क चुनें। WIENER इसे अपने आप नहीं बदलता।','wallet.minimum':'न्यूनतम','wallet.wienerUsed':'उपयोग हुआ WIENER','wallet.enterAmount':'निकासी राशि दर्ज करें','wallet.walletAddress':'वॉलेट पता','wallet.reviewTitle':'निकासी की समीक्षा','wallet.creating':'बनाया जा रहा है…','wallet.historyHint':'पूरी जानकारी के लिए किसी पंक्ति पर टैप करें।','wallet.noHistory':'अभी कोई निकासी नहीं।','wallet.details':'निकासी विवरण','wallet.pending':'लंबित','wallet.paid':'भुगतान हुआ','wallet.rejected':'अस्वीकृत','wallet.pendingExisting':'आपकी एक निकासी पहले से लंबित है।','wallet.nextAvailable':'अगली निकासी उपलब्ध होगी','wallet.invalid':'अमान्य वॉलेट पता।','wallet.insufficient':'WIENER बैलेंस पर्याप्त नहीं है।','wallet.openExplorer':'ब्लॉकचेन एक्सप्लोरर खोलें',
  'system.secure':'सुरक्षित Telegram सेशन','system.loadingRewards':'आपके रिवॉर्ड लोड हो रहे हैं','system.openTelegram':'WIENER खोलें','system.restricted':'अकाउंट प्रतिबंधित','system.unable':'खोला नहीं जा सका','system.maintenance':'मेंटेनेंस','system.blocked':'अकाउंट ब्लॉक है','system.contactSupport':'सपोर्ट से संपर्क करें',
  'dynamic.readyIn':'तैयार होने में {value}','dynamic.todayFarms':'आज के फार्म · {value}','dynamic.minimumIs':'न्यूनतम {value} है।','dynamic.nextWithdrawal':'अगली निकासी {value} में उपलब्ध होगी','dynamic.tasksCompleted':'{value} मौजूदा टास्क पूरे','dynamic.dayOf':'दिन {value} / 7','dynamic.bestStreak':'सर्वश्रेष्ठ स्ट्रीक: {value} दिन।','dynamic.adsToday':'आज {value}','dynamic.each':'प्रत्येक {value}','dynamic.ends':'समाप्त {value}'
 },
 bn:{
  'common.loading':'লোড হচ্ছে…','common.done':'সম্পন্ন','common.join':'যোগ দিন','common.watch':'দেখুন','common.wait':'অপেক্ষা','common.apply':'প্রয়োগ','common.back':'ফিরে যান','common.continue':'চালিয়ে যান','common.review':'পর্যালোচনা','common.status':'অবস্থা','common.network':'নেটওয়ার্ক','common.fee':'ফি','common.amount':'পরিমাণ','common.totalEarned':'মোট আয়','common.rank':'র‍্যাঙ্ক','common.referrals':'রেফারেল','common.qualified':'যোগ্য','common.tasks':'টাস্ক','common.days':'দিন','common.unavailable':'সাময়িকভাবে অনুপলব্ধ',
  'home.todayFarms':'আজকের ফার্ম','home.starting':'শুরু হচ্ছে…','home.growing':'WIENER বাড়ছে','home.dailyLimit':'আজকের ফার্ম সীমা শেষ','home.viewAll':'সব দেখুন','daily.streak':'স্ট্রিক','daily.claimedToday':'আজ ক্লেইম করা হয়েছে','daily.bestStreak':'সেরা স্ট্রিক','daily.keep':'স্ট্রিক চালু রাখতে প্রতিদিন ক্লেইম করুন।',
  'promo.subtitle':'ক্লেইম করতে একটি রিওয়ার্ডেড বিজ্ঞাপন দেখুন','promo.enter':'কোড লিখুন','promo.showing':'বিজ্ঞাপন চলছে…','promo.claimAgain':'আবার ক্লেইম','promo.claimed':'প্রোমো ক্লেইম হয়েছে','promo.gotIt':'বুঝেছি','promo.complete':'রিওয়ার্ডেড বিজ্ঞাপন সম্পূর্ণ করুন, তারপর প্রোমো রিওয়ার্ড যোগ হবে।',
  'tasks.completed':'বর্তমান টাস্ক সম্পন্ন','tasks.official':'অফিশিয়াল','tasks.exclusive':'এক্সক্লুসিভ','tasks.partner':'পার্টনার','tasks.daily':'দৈনিক','tasks.none':'এখন কোনো টাস্ক নেই।',
  'invite.subtitle':'বন্ধুদের WIENER-এ আমন্ত্রণ করুন এবং যোগ্য হলে রিওয়ার্ড পান।','invite.invited':'আমন্ত্রিত','invite.earned':'আয়','invite.link':'আপনার আমন্ত্রণ লিংক','invite.share':'আমন্ত্রণ শেয়ার করুন','invite.perQualified':'প্রতি যোগ্য','invite.recent':'সাম্প্রতিক রেফারেল','invite.copied':'আমন্ত্রণ লিংক কপি হয়েছে',
  'profile.streak':'স্ট্রিক','profile.bestStreak':'সেরা স্ট্রিক','profile.openWallet':'ওয়ালেট খুলুন',
  'wallet.withdrawable':'সর্বোচ্চ উত্তোলনযোগ্য','wallet.selectHint':'সঠিক নেটওয়ার্ক বেছে নিন। WIENER নিজে থেকে এটি বদলায় না।','wallet.minimum':'সর্বনিম্ন','wallet.wienerUsed':'ব্যবহৃত WIENER','wallet.enterAmount':'উত্তোলনের পরিমাণ লিখুন','wallet.walletAddress':'ওয়ালেট ঠিকানা','wallet.reviewTitle':'উত্তোলন পর্যালোচনা','wallet.confirm':'উত্তোলন নিশ্চিত করুন','wallet.creating':'তৈরি হচ্ছে…','wallet.historyHint':'সম্পূর্ণ তথ্যের জন্য যেকোনো সারিতে ট্যাপ করুন।','wallet.noHistory':'এখনও কোনো উত্তোলন নেই।','wallet.details':'উত্তোলন বিবরণ','wallet.pending':'অপেক্ষমান','wallet.paid':'পরিশোধিত','wallet.rejected':'বাতিল','wallet.pendingExisting':'আপনার ইতিমধ্যে একটি উত্তোলন অপেক্ষমান।','wallet.nextAvailable':'পরবর্তী উত্তোলন উপলব্ধ হবে','wallet.invalid':'অবৈধ ওয়ালেট ঠিকানা।','wallet.insufficient':'WIENER ব্যালেন্স যথেষ্ট নয়।','wallet.openExplorer':'ব্লকচেইন এক্সপ্লোরার খুলুন',
  'dynamic.readyIn':'প্রস্তুত হবে {value}','dynamic.todayFarms':'আজকের ফার্ম · {value}','dynamic.minimumIs':'সর্বনিম্ন {value}।','dynamic.nextWithdrawal':'পরবর্তী উত্তোলন {value} পরে','dynamic.tasksCompleted':'{value} বর্তমান টাস্ক সম্পন্ন','dynamic.dayOf':'দিন {value} / 7','dynamic.bestStreak':'সেরা স্ট্রিক: {value} দিন।','dynamic.adsToday':'আজ {value}','dynamic.each':'প্রতি {value}','dynamic.ends':'শেষ {value}'
 },
 am:{
  'common.loading':'በመጫን ላይ…','common.done':'ተጠናቋል','common.join':'ተቀላቀል','common.watch':'ተመልከት','common.wait':'ጠብቅ','common.apply':'ተግብር','common.back':'ተመለስ','common.continue':'ቀጥል','common.review':'ገምግም','common.status':'ሁኔታ','common.network':'ኔትወርክ','common.fee':'ክፍያ','common.amount':'መጠን','common.totalEarned':'ጠቅላላ ገቢ','common.rank':'ደረጃ','common.referrals':'ሪፈራሎች','common.qualified':'ብቁ','common.tasks':'ተግባሮች','common.days':'ቀናት','common.unavailable':'ለጊዜው አይገኝም',
  'home.todayFarms':'የዛሬ ፋርም','home.starting':'በመጀመር ላይ…','home.growing':'WIENER እያደገ ነው','home.dailyLimit':'የዛሬ ፋርም ገደብ ደርሷል','home.viewAll':'ሁሉን ይመልከቱ','daily.streak':'ተከታታይ','daily.claimedToday':'ዛሬ ተወስዷል','daily.bestStreak':'ምርጥ ተከታታይ','daily.keep':'እንዲቀጥል በየቀኑ ይውሰዱ።',
  'promo.subtitle':'ለመውሰድ አንድ የሽልማት ማስታወቂያ ይመልከቱ','promo.enter':'ኮድ ያስገቡ','promo.showing':'ማስታወቂያ እየታየ ነው…','promo.claimAgain':'እንደገና ይውሰዱ','promo.claimed':'ፕሮሞ ተወስዷል','promo.gotIt':'ገብቶኛል','promo.complete':'የሽልማት ማስታወቂያውን ያጠናቁ፣ ከዚያ ሽልማቱ ይጨመራል።',
  'tasks.completed':'የአሁን ተግባሮች ተጠናቀቁ','tasks.official':'ኦፊሴላዊ','tasks.exclusive':'ልዩ','tasks.partner':'አጋር','tasks.daily':'ዕለታዊ','tasks.none':'አሁን ምንም ተግባር የለም።',
  'invite.subtitle':'ጓደኞችን ወደ WIENER ይጋብዙ እና ብቁ ሲሆኑ ሽልማት ያግኙ።','invite.invited':'ተጋብዘዋል','invite.earned':'የተገኘ','invite.link':'የግብዣ አገናኝ','invite.share':'ግብዣ አጋራ','invite.perQualified':'ለእያንዳንዱ ብቁ','invite.recent':'የቅርብ ሪፈራሎች','profile.openWallet':'ዋሌት ክፈት',
  'wallet.withdrawable':'ከፍተኛ ሊወጣ የሚችል','wallet.selectHint':'ትክክለኛውን ኔትወርክ ይምረጡ። WIENER በራሱ አይቀይረውም።','wallet.minimum':'ዝቅተኛ','wallet.youReceive':'የሚያገኙት','wallet.wienerUsed':'የተጠቀመ WIENER','wallet.enterAmount':'የመውጫ መጠን ያስገቡ','wallet.walletAddress':'ዋሌት አድራሻ','wallet.reviewTitle':'መውጫ ገምግም','wallet.confirm':'መውጫ አረጋግጥ','wallet.historyHint':'ሙሉ ዝርዝር ለማየት ረድፉን ይንኩ።','wallet.noHistory':'ገና መውጫ የለም።','wallet.details':'የመውጫ ዝርዝር','wallet.pending':'በመጠባበቅ ላይ','wallet.paid':'ተከፍሏል','wallet.rejected':'ውድቅ','wallet.pendingExisting':'አንድ መውጫ በመጠባበቅ ላይ አለ።','wallet.invalid':'የተሳሳተ ዋሌት አድራሻ።','wallet.insufficient':'በቂ WIENER ቀሪ ሂሳብ የለም።',
  'dynamic.readyIn':'ዝግጁ በ {value}','dynamic.todayFarms':'የዛሬ ፋርም · {value}','dynamic.minimumIs':'ዝቅተኛው {value} ነው።','dynamic.tasksCompleted':'{value} ተግባሮች ተጠናቀቁ','dynamic.dayOf':'ቀን {value} / 7','dynamic.bestStreak':'ምርጥ ተከታታይ: {value} ቀናት።'
 },
 es:{
  'common.loading':'Cargando…','common.done':'Hecho','common.wait':'Espera','common.apply':'Aplicar','common.back':'Atrás','common.continue':'Continuar','common.review':'Revisar','common.status':'Estado','common.network':'Red','common.fee':'Comisión','common.amount':'Cantidad','common.totalEarned':'Total ganado','common.rank':'Rango','common.referrals':'Referidos','common.qualified':'Calificado','common.tasks':'Tareas','common.days':'días','common.unavailable':'Temporalmente no disponible',
  'home.todayFarms':'Granjas de hoy','home.starting':'Iniciando…','home.growing':'WIENER está creciendo','home.dailyLimit':'Límite diario de granja alcanzado','home.viewAll':'Ver todo','daily.streak':'Racha','daily.claimedToday':'Reclamado hoy','daily.bestStreak':'Mejor racha','daily.keep':'Reclama cada día para mantenerla activa.',
  'promo.subtitle':'Mira un anuncio recompensado para reclamar','promo.enter':'Introduce el código','promo.showing':'Mostrando anuncio…','promo.claimAgain':'Reclamar de nuevo','promo.claimed':'Promo reclamada','promo.gotIt':'Entendido','promo.complete':'Completa el anuncio recompensado y después se acreditará tu recompensa.',
  'tasks.completed':'tareas actuales completadas','tasks.official':'Oficial','tasks.exclusive':'Exclusivo','tasks.partner':'Socio','tasks.daily':'Diario','tasks.none':'No hay tareas ahora.',
  'invite.subtitle':'Invita amigos a WIENER y gana recompensas cuando se califiquen.','invite.invited':'Invitados','invite.earned':'Ganado','invite.link':'Tu enlace de invitación','invite.share':'Compartir invitación','invite.perQualified':'Por calificado','invite.recent':'Referidos recientes','invite.copied':'Enlace copiado',
  'profile.streak':'Racha','profile.bestStreak':'Mejor racha','profile.openWallet':'Abrir billetera',
  'wallet.selectHint':'Elige la red exacta. WIENER nunca la cambia automáticamente.','wallet.minimum':'Mínimo','wallet.wienerUsed':'WIENER usado','wallet.enterAmount':'Introduce el monto del retiro','wallet.walletAddress':'Dirección de billetera','wallet.reviewTitle':'Revisar retiro','wallet.creating':'Creando…','wallet.historyHint':'Toca una fila para ver todos los detalles.','wallet.noHistory':'Aún no hay retiros.','wallet.details':'Detalles del retiro','wallet.pending':'Pendiente','wallet.paid':'Pagado','wallet.rejected':'Rechazado','wallet.pendingExisting':'Ya tienes un retiro pendiente.','wallet.nextAvailable':'Próximo retiro disponible en','wallet.invalid':'Dirección de billetera inválida.','wallet.insufficient':'Saldo WIENER insuficiente.','wallet.openExplorer':'Abrir explorador blockchain',
  'system.secure':'Sesión segura de Telegram','system.loadingRewards':'Cargando tus recompensas','system.openTelegram':'Abrir WIENER','system.restricted':'Cuenta restringida','system.unable':'No se pudo abrir','system.maintenance':'Mantenimiento','system.blocked':'Cuenta bloqueada','system.contactSupport':'Contactar soporte',
  'dynamic.readyIn':'Listo en {value}','dynamic.todayFarms':'Granjas de hoy · {value}','dynamic.minimumIs':'El mínimo es {value}.','dynamic.nextWithdrawal':'Próximo retiro disponible en {value}','dynamic.tasksCompleted':'{value} tareas actuales completadas','dynamic.dayOf':'Día {value} de 7','dynamic.bestStreak':'Mejor racha: {value} días.','dynamic.adsToday':'{value} hoy','dynamic.each':'{value} cada uno','dynamic.ends':'Termina {value}'
 },
 nl:{
  'common.loading':'Laden…','common.done':'Klaar','common.join':'Deelnemen','common.watch':'Bekijken','common.wait':'Wachten','common.apply':'Toepassen','common.back':'Terug','common.continue':'Doorgaan','common.review':'Controleren','common.status':'Status','common.network':'Netwerk','common.fee':'Kosten','common.amount':'Bedrag','common.totalEarned':'Totaal verdiend','common.rank':'Rang','common.referrals':'Verwijzingen','common.qualified':'Gekwalificeerd','common.tasks':'Taken','common.days':'dagen','common.unavailable':'Tijdelijk niet beschikbaar',
  'home.todayFarms':'Farms van vandaag','home.starting':'Starten…','home.growing':'WIENER groeit','home.dailyLimit':'Dagelijkse farmlimiet bereikt','home.viewAll':'Alles bekijken','daily.streak':'Reeks','daily.claimedToday':'Vandaag geclaimd','daily.bestStreak':'Beste reeks','daily.keep':'Claim elke dag om je reeks actief te houden.',
  'promo.subtitle':'Bekijk één beloonde advertentie om te claimen','promo.enter':'Voer code in','promo.showing':'Advertentie wordt getoond…','promo.claimAgain':'Opnieuw claimen','promo.claimed':'Promo geclaimd','promo.gotIt':'Begrepen','promo.complete':'Voltooi de beloonde advertentie; daarna wordt je promo-beloning toegevoegd.',
  'tasks.completed':'huidige taken voltooid','tasks.official':'Officieel','tasks.exclusive':'Exclusief','tasks.partner':'Partner','tasks.daily':'Dagelijks','tasks.none':'Momenteel geen taken.',
  'invite.subtitle':'Nodig vrienden uit voor WIENER en verdien beloningen wanneer ze kwalificeren.','invite.invited':'Uitgenodigd','invite.earned':'Verdiend','invite.link':'Jouw uitnodigingslink','invite.share':'Uitnodiging delen','invite.perQualified':'Per gekwalificeerde','invite.recent':'Recente verwijzingen','invite.copied':'Uitnodigingslink gekopieerd',
  'profile.streak':'Reeks','profile.bestStreak':'Beste reeks','profile.openWallet':'Wallet openen',
  'wallet.selectHint':'Kies exact het juiste netwerk. WIENER verandert dit nooit automatisch.','wallet.minimum':'Min','wallet.wienerUsed':'Gebruikte WIENER','wallet.enterAmount':'Voer opnamebedrag in','wallet.walletAddress':'Walletadres','wallet.reviewTitle':'Opname controleren','wallet.creating':'Aanmaken…','wallet.historyHint':'Tik op een rij voor alle details.','wallet.noHistory':'Nog geen opnames.','wallet.details':'Opnamedetails','wallet.pending':'In behandeling','wallet.paid':'Betaald','wallet.rejected':'Afgewezen','wallet.pendingExisting':'Je hebt al een lopende opname.','wallet.nextAvailable':'Volgende opname beschikbaar over','wallet.invalid':'Ongeldig walletadres.','wallet.insufficient':'Onvoldoende WIENER-saldo.','wallet.openExplorer':'Blockchainverkenner openen',
  'dynamic.readyIn':'Klaar over {value}','dynamic.todayFarms':'Farms van vandaag · {value}','dynamic.minimumIs':'Minimum is {value}.','dynamic.nextWithdrawal':'Volgende opname beschikbaar over {value}','dynamic.tasksCompleted':'{value} huidige taken voltooid','dynamic.dayOf':'Dag {value} van 7','dynamic.bestStreak':'Beste reeks: {value} dagen.','dynamic.adsToday':'{value} vandaag','dynamic.each':'{value} per stuk','dynamic.ends':'Eindigt {value}'
 },
 ar:{
  'common.loading':'جارٍ التحميل…','common.done':'تم','common.join':'انضم','common.watch':'شاهد','common.wait':'انتظر','common.apply':'تطبيق','common.back':'رجوع','common.continue':'متابعة','common.review':'مراجعة','common.status':'الحالة','common.network':'الشبكة','common.fee':'الرسوم','common.amount':'المبلغ','common.totalEarned':'إجمالي الأرباح','common.rank':'الترتيب','common.referrals':'الإحالات','common.qualified':'مؤهل','common.tasks':'المهام','common.days':'أيام','common.unavailable':'غير متاح مؤقتًا',
  'home.todayFarms':'مزارع اليوم','home.starting':'جارٍ البدء…','home.growing':'WIENER ينمو','home.dailyLimit':'تم الوصول إلى الحد اليومي للمزرعة','home.viewAll':'عرض الكل','daily.streak':'السلسلة','daily.claimedToday':'تم الاستلام اليوم','daily.bestStreak':'أفضل سلسلة','daily.keep':'استلم كل يوم للحفاظ على السلسلة.',
  'promo.subtitle':'شاهد إعلانًا بمكافأة واحدة للاستلام','promo.enter':'أدخل الرمز','promo.showing':'جارٍ عرض الإعلان…','promo.claimAgain':'استلم مرة أخرى','promo.claimed':'تم استلام العرض','promo.gotIt':'حسنًا','promo.complete':'أكمل الإعلان بمكافأة ثم ستتم إضافة مكافأة العرض.',
  'tasks.completed':'مهام حالية مكتملة','tasks.official':'رسمي','tasks.exclusive':'حصري','tasks.partner':'شريك','tasks.daily':'يومي','tasks.none':'لا توجد مهام الآن.',
  'invite.subtitle':'ادعُ الأصدقاء إلى WIENER واكسب المكافآت عندما يصبحون مؤهلين.','invite.invited':'تمت دعوتهم','invite.earned':'المكتسب','invite.link':'رابط الدعوة الخاص بك','invite.share':'مشاركة الدعوة','invite.perQualified':'لكل مؤهل','invite.recent':'الإحالات الأخيرة','invite.copied':'تم نسخ رابط الدعوة',
  'profile.streak':'السلسلة','profile.bestStreak':'أفضل سلسلة','profile.openWallet':'فتح المحفظة',
  'wallet.selectHint':'اختر الشبكة الصحيحة. WIENER لا يغيرها تلقائيًا.','wallet.minimum':'الحد الأدنى','wallet.wienerUsed':'WIENER المستخدم','wallet.enterAmount':'أدخل مبلغ السحب','wallet.walletAddress':'عنوان المحفظة','wallet.reviewTitle':'مراجعة السحب','wallet.creating':'جارٍ الإنشاء…','wallet.historyHint':'اضغط على أي صف لعرض التفاصيل كاملة.','wallet.noHistory':'لا توجد عمليات سحب بعد.','wallet.details':'تفاصيل السحب','wallet.pending':'قيد الانتظار','wallet.paid':'مدفوع','wallet.rejected':'مرفوض','wallet.pendingExisting':'لديك بالفعل عملية سحب قيد الانتظار.','wallet.nextAvailable':'السحب التالي متاح خلال','wallet.invalid':'عنوان المحفظة غير صالح.','wallet.insufficient':'رصيد WIENER غير كافٍ.','wallet.openExplorer':'فتح مستكشف البلوكشين',
  'system.secure':'جلسة Telegram آمنة','system.loadingRewards':'جارٍ تحميل مكافآتك','system.openTelegram':'فتح WIENER','system.restricted':'الحساب مقيد','system.unable':'تعذر الفتح','system.maintenance':'صيانة','system.blocked':'الحساب محظور','system.contactSupport':'التواصل مع الدعم',
  'dynamic.readyIn':'جاهز خلال {value}','dynamic.todayFarms':'مزارع اليوم · {value}','dynamic.minimumIs':'الحد الأدنى هو {value}.','dynamic.nextWithdrawal':'السحب التالي متاح خلال {value}','dynamic.tasksCompleted':'تم إكمال {value} من المهام الحالية','dynamic.dayOf':'اليوم {value} من 7','dynamic.bestStreak':'أفضل سلسلة: {value} أيام.','dynamic.adsToday':'{value} اليوم','dynamic.each':'{value} لكل إعلان','dynamic.ends':'ينتهي {value}'
 },
 de:{
  'common.loading':'Wird geladen…','common.done':'Erledigt','common.join':'Beitreten','common.watch':'Ansehen','common.wait':'Warten','common.apply':'Anwenden','common.back':'Zurück','common.continue':'Weiter','common.review':'Prüfen','common.status':'Status','common.network':'Netzwerk','common.fee':'Gebühr','common.amount':'Betrag','common.totalEarned':'Gesamt verdient','common.rank':'Rang','common.referrals':'Empfehlungen','common.qualified':'Qualifiziert','common.tasks':'Aufgaben','common.days':'Tage','common.unavailable':'Vorübergehend nicht verfügbar',
  'home.todayFarms':'Heutige Farms','home.starting':'Wird gestartet…','home.growing':'WIENER wächst','home.dailyLimit':'Tägliches Farm-Limit erreicht','home.viewAll':'Alle anzeigen','daily.streak':'Serie','daily.claimedToday':'Heute abgeholt','daily.bestStreak':'Beste Serie','daily.keep':'Jeden Tag abholen, um die Serie aktiv zu halten.',
  'promo.subtitle':'Eine belohnte Anzeige ansehen, um abzuholen','promo.enter':'Code eingeben','promo.showing':'Anzeige wird gezeigt…','promo.claimAgain':'Erneut abholen','promo.claimed':'Promo abgeholt','promo.gotIt':'Verstanden','promo.complete':'Schließe die belohnte Anzeige ab; danach wird die Promo-Belohnung gutgeschrieben.',
  'tasks.completed':'aktuelle Aufgaben erledigt','tasks.official':'Offiziell','tasks.exclusive':'Exklusiv','tasks.partner':'Partner','tasks.daily':'Täglich','tasks.none':'Derzeit keine Aufgaben.',
  'invite.subtitle':'Lade Freunde zu WIENER ein und verdiene Belohnungen, wenn sie sich qualifizieren.','invite.invited':'Eingeladen','invite.earned':'Verdient','invite.link':'Dein Einladungslink','invite.share':'Einladung teilen','invite.perQualified':'Pro Qualifiziertem','invite.recent':'Letzte Empfehlungen','invite.copied':'Einladungslink kopiert',
  'profile.streak':'Serie','profile.bestStreak':'Beste Serie','profile.openWallet':'Wallet öffnen',
  'wallet.selectHint':'Wähle das genaue Netzwerk. WIENER ändert es niemals automatisch.','wallet.minimum':'Min','wallet.wienerUsed':'Verwendete WIENER','wallet.enterAmount':'Auszahlungsbetrag eingeben','wallet.walletAddress':'Wallet-Adresse','wallet.reviewTitle':'Auszahlung prüfen','wallet.creating':'Wird erstellt…','wallet.historyHint':'Tippe auf eine Zeile für alle Details.','wallet.noHistory':'Noch keine Auszahlungen.','wallet.details':'Auszahlungsdetails','wallet.pending':'Ausstehend','wallet.paid':'Bezahlt','wallet.rejected':'Abgelehnt','wallet.pendingExisting':'Du hast bereits eine ausstehende Auszahlung.','wallet.nextAvailable':'Nächste Auszahlung verfügbar in','wallet.invalid':'Ungültige Wallet-Adresse.','wallet.insufficient':'Nicht genügend WIENER-Guthaben.','wallet.openExplorer':'Blockchain-Explorer öffnen',
  'dynamic.readyIn':'Bereit in {value}','dynamic.todayFarms':'Heutige Farms · {value}','dynamic.minimumIs':'Minimum ist {value}.','dynamic.nextWithdrawal':'Nächste Auszahlung verfügbar in {value}','dynamic.tasksCompleted':'{value} aktuelle Aufgaben erledigt','dynamic.dayOf':'Tag {value} von 7','dynamic.bestStreak':'Beste Serie: {value} Tage.','dynamic.adsToday':'{value} heute','dynamic.each':'{value} jeweils','dynamic.ends':'Endet {value}'
 },
 fr:{
  'common.loading':'Chargement…','common.done':'Terminé','common.join':'Rejoindre','common.watch':'Regarder','common.wait':'Attendre','common.apply':'Appliquer','common.back':'Retour','common.continue':'Continuer','common.review':'Vérifier','common.status':'Statut','common.network':'Réseau','common.fee':'Frais','common.amount':'Montant','common.totalEarned':'Total gagné','common.rank':'Rang','common.referrals':'Parrainages','common.qualified':'Qualifié','common.tasks':'Tâches','common.days':'jours','common.unavailable':'Temporairement indisponible',
  'home.todayFarms':'Farms du jour','home.starting':'Démarrage…','home.growing':'WIENER grandit','home.dailyLimit':'Limite quotidienne de farm atteinte','home.viewAll':'Tout voir','daily.streak':'Série','daily.claimedToday':'Réclamé aujourd’hui','daily.bestStreak':'Meilleure série','daily.keep':'Réclamez chaque jour pour garder la série active.',
  'promo.subtitle':'Regardez une publicité récompensée pour réclamer','promo.enter':'Entrez le code','promo.showing':'Affichage de la pub…','promo.claimAgain':'Réclamer à nouveau','promo.claimed':'Promo réclamée','promo.gotIt':'Compris','promo.complete':'Terminez la publicité récompensée puis la récompense promo sera créditée.',
  'tasks.completed':'tâches actuelles terminées','tasks.official':'Officiel','tasks.exclusive':'Exclusif','tasks.partner':'Partenaire','tasks.daily':'Quotidien','tasks.none':'Aucune tâche pour le moment.',
  'invite.subtitle':'Invitez des amis sur WIENER et gagnez des récompenses lorsqu’ils se qualifient.','invite.invited':'Invités','invite.earned':'Gagné','invite.link':'Votre lien d’invitation','invite.share':'Partager l’invitation','invite.perQualified':'Par qualifié','invite.recent':'Parrainages récents','invite.copied':'Lien d’invitation copié',
  'profile.streak':'Série','profile.bestStreak':'Meilleure série','profile.openWallet':'Ouvrir le portefeuille',
  'wallet.selectHint':'Choisissez le réseau exact. WIENER ne le modifie jamais automatiquement.','wallet.minimum':'Min','wallet.wienerUsed':'WIENER utilisés','wallet.enterAmount':'Entrez le montant du retrait','wallet.walletAddress':'Adresse du portefeuille','wallet.reviewTitle':'Vérifier le retrait','wallet.creating':'Création…','wallet.historyHint':'Touchez une ligne pour voir tous les détails.','wallet.noHistory':'Aucun retrait pour le moment.','wallet.details':'Détails du retrait','wallet.pending':'En attente','wallet.paid':'Payé','wallet.rejected':'Rejeté','wallet.pendingExisting':'Vous avez déjà un retrait en attente.','wallet.nextAvailable':'Prochain retrait disponible dans','wallet.invalid':'Adresse de portefeuille invalide.','wallet.insufficient':'Solde WIENER insuffisant.','wallet.openExplorer':'Ouvrir l’explorateur blockchain',
  'dynamic.readyIn':'Prêt dans {value}','dynamic.todayFarms':'Farms du jour · {value}','dynamic.minimumIs':'Le minimum est {value}.','dynamic.nextWithdrawal':'Prochain retrait disponible dans {value}','dynamic.tasksCompleted':'{value} tâches actuelles terminées','dynamic.dayOf':'Jour {value} sur 7','dynamic.bestStreak':'Meilleure série : {value} jours.','dynamic.adsToday':'{value} aujourd’hui','dynamic.each':'{value} chacun','dynamic.ends':'Se termine {value}'
 },
 it:{'common.done':'Fatto','common.join':'Partecipa','common.watch':'Guarda','common.wait':'Attendi','common.apply':'Applica','common.back':'Indietro','common.continue':'Continua','common.review':'Rivedi','common.status':'Stato','common.network':'Rete','common.fee':'Commissione','common.amount':'Importo','common.totalEarned':'Totale guadagnato','common.rank':'Classifica','common.referrals':'Referral','common.qualified':'Qualificato','common.tasks':'Attività','home.todayFarms':'Farm di oggi','home.starting':'Avvio…','home.growing':'WIENER sta crescendo','home.dailyLimit':'Limite giornaliero raggiunto','home.viewAll':'Vedi tutto','daily.streak':'Serie','daily.claimedToday':'Riscattato oggi','promo.subtitle':'Guarda un annuncio premiato per riscattare','promo.enter':'Inserisci codice','promo.showing':'Annuncio in corso…','promo.claimAgain':'Riscatta di nuovo','promo.claimed':'Promo riscattata','tasks.completed':'attività attuali completate','tasks.official':'Ufficiale','tasks.exclusive':'Esclusivo','tasks.partner':'Partner','tasks.daily':'Giornaliero','invite.invited':'Invitati','invite.earned':'Guadagnato','invite.link':'Il tuo link invito','invite.share':'Condividi invito','profile.openWallet':'Apri portafoglio','wallet.withdrawable':'Massimo prelevabile','wallet.selectHint':'Scegli la rete esatta. WIENER non la cambia automaticamente.','wallet.minimum':'Min','wallet.wienerUsed':'WIENER usati','wallet.enterAmount':'Inserisci importo prelievo','wallet.walletAddress':'Indirizzo wallet','wallet.reviewTitle':'Rivedi prelievo','wallet.confirm':'Conferma prelievo','wallet.historyHint':'Tocca una riga per tutti i dettagli.','wallet.noHistory':'Nessun prelievo ancora.','wallet.details':'Dettagli prelievo','wallet.pending':'In attesa','wallet.paid':'Pagato','wallet.rejected':'Rifiutato','wallet.invalid':'Indirizzo wallet non valido.','wallet.insufficient':'Saldo WIENER insufficiente.','dynamic.readyIn':'Pronto tra {value}','dynamic.minimumIs':'Il minimo è {value}.','dynamic.tasksCompleted':'{value} attività attuali completate'},
 pt:{'common.done':'Concluído','common.join':'Aderir','common.watch':'Ver','common.wait':'Aguardar','common.apply':'Aplicar','common.back':'Voltar','common.continue':'Continuar','common.review':'Rever','common.status':'Estado','common.network':'Rede','common.fee':'Taxa','common.amount':'Montante','common.totalEarned':'Total ganho','common.rank':'Posição','common.referrals':'Referências','common.qualified':'Qualificado','common.tasks':'Tarefas','home.todayFarms':'Farms de hoje','home.starting':'A iniciar…','home.growing':'WIENER está a crescer','home.dailyLimit':'Limite diário atingido','home.viewAll':'Ver tudo','daily.streak':'Sequência','daily.claimedToday':'Reclamado hoje','promo.subtitle':'Veja um anúncio recompensado para reclamar','promo.enter':'Introduza o código','promo.claimAgain':'Reclamar novamente','tasks.completed':'tarefas atuais concluídas','invite.link':'O seu link de convite','invite.share':'Partilhar convite','profile.openWallet':'Abrir carteira','wallet.withdrawable':'Máximo disponível','wallet.selectHint':'Escolha a rede exata. WIENER nunca a altera automaticamente.','wallet.minimum':'Mín','wallet.wienerUsed':'WIENER usados','wallet.enterAmount':'Introduza o montante','wallet.walletAddress':'Endereço da carteira','wallet.reviewTitle':'Rever levantamento','wallet.confirm':'Confirmar levantamento','wallet.pending':'Pendente','wallet.paid':'Pago','wallet.rejected':'Rejeitado','wallet.invalid':'Endereço inválido.','wallet.insufficient':'Saldo WIENER insuficiente.','dynamic.readyIn':'Pronto em {value}','dynamic.minimumIs':'O mínimo é {value}.','dynamic.tasksCompleted':'{value} tarefas atuais concluídas'},
 'pt-BR':{'common.done':'Concluído','common.join':'Participar','common.watch':'Assistir','common.wait':'Aguarde','common.apply':'Aplicar','common.back':'Voltar','common.continue':'Continuar','common.review':'Revisar','common.status':'Status','common.network':'Rede','common.fee':'Taxa','common.amount':'Valor','common.totalEarned':'Total ganho','common.rank':'Posição','common.referrals':'Indicações','common.qualified':'Qualificado','common.tasks':'Tarefas','home.todayFarms':'Farms de hoje','home.starting':'Iniciando…','home.growing':'WIENER está crescendo','home.dailyLimit':'Limite diário atingido','home.viewAll':'Ver tudo','daily.streak':'Sequência','daily.claimedToday':'Resgatado hoje','promo.subtitle':'Assista a um anúncio recompensado para resgatar','promo.enter':'Digite o código','promo.claimAgain':'Resgatar novamente','tasks.completed':'tarefas atuais concluídas','invite.link':'Seu link de convite','invite.share':'Compartilhar convite','profile.openWallet':'Abrir carteira','wallet.withdrawable':'Máximo para saque','wallet.selectHint':'Escolha a rede exata. WIENER nunca muda automaticamente.','wallet.minimum':'Mín','wallet.wienerUsed':'WIENER usados','wallet.enterAmount':'Digite o valor do saque','wallet.walletAddress':'Endereço da carteira','wallet.reviewTitle':'Revisar saque','wallet.confirm':'Confirmar saque','wallet.pending':'Pendente','wallet.paid':'Pago','wallet.rejected':'Rejeitado','wallet.invalid':'Endereço inválido.','wallet.insufficient':'Saldo WIENER insuficiente.','dynamic.readyIn':'Pronto em {value}','dynamic.minimumIs':'O mínimo é {value}.','dynamic.tasksCompleted':'{value} tarefas atuais concluídas'},
 tr:{'common.done':'Tamam','common.join':'Katıl','common.watch':'İzle','common.wait':'Bekle','common.apply':'Uygula','common.back':'Geri','common.continue':'Devam','common.review':'İncele','common.status':'Durum','common.network':'Ağ','common.fee':'Ücret','common.amount':'Tutar','common.totalEarned':'Toplam kazanç','common.rank':'Sıra','common.referrals':'Referanslar','common.qualified':'Uygun','common.tasks':'Görevler','home.todayFarms':'Bugünkü farm','home.starting':'Başlatılıyor…','home.growing':'WIENER büyüyor','home.dailyLimit':'Günlük farm limiti doldu','home.viewAll':'Tümünü gör','daily.streak':'Seri','daily.claimedToday':'Bugün alındı','promo.subtitle':'Almak için bir ödüllü reklam izle','promo.enter':'Kodu gir','promo.claimAgain':'Tekrar al','tasks.completed':'mevcut görev tamamlandı','invite.link':'Davet bağlantın','invite.share':'Daveti paylaş','profile.openWallet':'Cüzdanı aç','wallet.withdrawable':'Maksimum çekilebilir','wallet.selectHint':'Doğru ağı seç. WIENER bunu otomatik değiştirmez.','wallet.minimum':'Min','wallet.wienerUsed':'Kullanılan WIENER','wallet.enterAmount':'Çekim tutarını gir','wallet.walletAddress':'Cüzdan adresi','wallet.reviewTitle':'Çekimi incele','wallet.confirm':'Çekimi onayla','wallet.pending':'Bekliyor','wallet.paid':'Ödendi','wallet.rejected':'Reddedildi','wallet.invalid':'Geçersiz cüzdan adresi.','wallet.insufficient':'Yetersiz WIENER bakiyesi.','dynamic.readyIn':'{value} içinde hazır','dynamic.minimumIs':'Minimum {value}.','dynamic.tasksCompleted':'{value} mevcut görev tamamlandı'},
 pl:{'common.done':'Gotowe','common.join':'Dołącz','common.watch':'Obejrzyj','common.wait':'Czekaj','common.apply':'Zastosuj','common.back':'Wstecz','common.continue':'Dalej','common.review':'Sprawdź','common.status':'Status','common.network':'Sieć','common.fee':'Opłata','common.amount':'Kwota','common.totalEarned':'Łącznie zarobiono','common.rank':'Pozycja','common.referrals':'Polecenia','common.qualified':'Zakwalifikowany','common.tasks':'Zadania','home.todayFarms':'Dzisiejsze farmy','home.starting':'Uruchamianie…','home.growing':'WIENER rośnie','home.dailyLimit':'Dzienny limit osiągnięty','home.viewAll':'Zobacz wszystko','daily.streak':'Seria','daily.claimedToday':'Odebrano dziś','promo.subtitle':'Obejrzyj reklamę z nagrodą, aby odebrać','promo.enter':'Wpisz kod','tasks.completed':'bieżące zadania ukończone','invite.link':'Twój link zaproszenia','invite.share':'Udostępnij zaproszenie','profile.openWallet':'Otwórz portfel','wallet.withdrawable':'Maksymalna wypłata','wallet.selectHint':'Wybierz dokładną sieć. WIENER nigdy nie zmienia jej automatycznie.','wallet.minimum':'Min','wallet.wienerUsed':'Użyte WIENER','wallet.enterAmount':'Wpisz kwotę wypłaty','wallet.walletAddress':'Adres portfela','wallet.reviewTitle':'Sprawdź wypłatę','wallet.confirm':'Potwierdź wypłatę','wallet.pending':'Oczekuje','wallet.paid':'Wypłacono','wallet.rejected':'Odrzucono','wallet.invalid':'Nieprawidłowy adres portfela.','wallet.insufficient':'Niewystarczające saldo WIENER.','dynamic.readyIn':'Gotowe za {value}','dynamic.minimumIs':'Minimum to {value}.','dynamic.tasksCompleted':'{value} bieżących zadań ukończono'},
 uk:{'common.done':'Готово','common.join':'Приєднатися','common.watch':'Дивитися','common.wait':'Чекайте','common.apply':'Застосувати','common.back':'Назад','common.continue':'Далі','common.review':'Перевірити','common.status':'Статус','common.network':'Мережа','common.fee':'Комісія','common.amount':'Сума','common.totalEarned':'Усього зароблено','common.rank':'Ранг','common.referrals':'Реферали','common.qualified':'Кваліфікований','common.tasks':'Завдання','home.todayFarms':'Фарми сьогодні','home.starting':'Запуск…','home.growing':'WIENER росте','home.dailyLimit':'Денний ліміт досягнуто','home.viewAll':'Переглянути все','daily.streak':'Серія','daily.claimedToday':'Отримано сьогодні','promo.subtitle':'Перегляньте рекламу з винагородою, щоб отримати','promo.enter':'Введіть код','tasks.completed':'поточних завдань виконано','invite.link':'Ваше реферальне посилання','invite.share':'Поділитися запрошенням','profile.openWallet':'Відкрити гаманець','wallet.withdrawable':'Максимум до виведення','wallet.selectHint':'Виберіть точну мережу. WIENER не змінює її автоматично.','wallet.minimum':'Мін','wallet.wienerUsed':'Використано WIENER','wallet.enterAmount':'Введіть суму виведення','wallet.walletAddress':'Адреса гаманця','wallet.reviewTitle':'Перевірити виведення','wallet.confirm':'Підтвердити виведення','wallet.pending':'Очікує','wallet.paid':'Сплачено','wallet.rejected':'Відхилено','wallet.invalid':'Невірна адреса гаманця.','wallet.insufficient':'Недостатньо WIENER.','dynamic.readyIn':'Готово через {value}','dynamic.minimumIs':'Мінімум {value}.','dynamic.tasksCompleted':'{value} поточних завдань виконано'},
 ru:{'common.done':'Готово','common.join':'Присоединиться','common.watch':'Смотреть','common.wait':'Ждите','common.apply':'Применить','common.back':'Назад','common.continue':'Далее','common.review':'Проверить','common.status':'Статус','common.network':'Сеть','common.fee':'Комиссия','common.amount':'Сумма','common.totalEarned':'Всего заработано','common.rank':'Ранг','common.referrals':'Рефералы','common.qualified':'Квалифицирован','common.tasks':'Задания','home.todayFarms':'Фермы сегодня','home.starting':'Запуск…','home.growing':'WIENER растёт','home.dailyLimit':'Дневной лимит достигнут','home.viewAll':'Показать всё','daily.streak':'Серия','daily.claimedToday':'Получено сегодня','promo.subtitle':'Посмотрите рекламу с наградой, чтобы получить','promo.enter':'Введите код','tasks.completed':'текущих заданий выполнено','invite.link':'Ваша ссылка приглашения','invite.share':'Поделиться приглашением','profile.openWallet':'Открыть кошелёк','wallet.withdrawable':'Максимум к выводу','wallet.selectHint':'Выберите точную сеть. WIENER не меняет её автоматически.','wallet.minimum':'Мин','wallet.wienerUsed':'Использовано WIENER','wallet.enterAmount':'Введите сумму вывода','wallet.walletAddress':'Адрес кошелька','wallet.reviewTitle':'Проверить вывод','wallet.confirm':'Подтвердить вывод','wallet.pending':'Ожидает','wallet.paid':'Оплачено','wallet.rejected':'Отклонено','wallet.invalid':'Неверный адрес кошелька.','wallet.insufficient':'Недостаточно WIENER.','dynamic.readyIn':'Готово через {value}','dynamic.minimumIs':'Минимум {value}.','dynamic.tasksCompleted':'{value} текущих заданий выполнено'},
 id:{'common.done':'Selesai','common.join':'Gabung','common.watch':'Tonton','common.wait':'Tunggu','common.apply':'Terapkan','common.back':'Kembali','common.continue':'Lanjut','common.review':'Tinjau','common.status':'Status','common.network':'Jaringan','common.fee':'Biaya','common.amount':'Jumlah','common.totalEarned':'Total diperoleh','common.rank':'Peringkat','common.referrals':'Referral','common.qualified':'Memenuhi syarat','common.tasks':'Tugas','home.todayFarms':'Farm hari ini','home.starting':'Memulai…','home.growing':'WIENER sedang tumbuh','home.dailyLimit':'Batas farm harian tercapai','home.viewAll':'Lihat semua','daily.streak':'Streak','daily.claimedToday':'Diklaim hari ini','promo.subtitle':'Tonton satu iklan berhadiah untuk klaim','promo.enter':'Masukkan kode','tasks.completed':'tugas saat ini selesai','invite.link':'Tautan undangan Anda','invite.share':'Bagikan undangan','profile.openWallet':'Buka dompet','wallet.withdrawable':'Maksimum dapat ditarik','wallet.selectHint':'Pilih jaringan yang tepat. WIENER tidak pernah mengubahnya otomatis.','wallet.minimum':'Min','wallet.wienerUsed':'WIENER digunakan','wallet.enterAmount':'Masukkan jumlah penarikan','wallet.walletAddress':'Alamat dompet','wallet.reviewTitle':'Tinjau penarikan','wallet.confirm':'Konfirmasi penarikan','wallet.pending':'Tertunda','wallet.paid':'Dibayar','wallet.rejected':'Ditolak','wallet.invalid':'Alamat dompet tidak valid.','wallet.insufficient':'Saldo WIENER tidak cukup.','dynamic.readyIn':'Siap dalam {value}','dynamic.minimumIs':'Minimum {value}.','dynamic.tasksCompleted':'{value} tugas saat ini selesai'},
 fil:{'common.done':'Tapos','common.join':'Sumali','common.watch':'Panoorin','common.wait':'Maghintay','common.apply':'Ilapat','common.back':'Bumalik','common.continue':'Magpatuloy','common.review':'Suriin','common.status':'Status','common.network':'Network','common.fee':'Bayad','common.amount':'Halaga','common.totalEarned':'Kabuuang kinita','common.rank':'Ranggo','common.referrals':'Mga referral','common.qualified':'Kwalipikado','common.tasks':'Mga gawain','home.todayFarms':'Mga farm ngayon','home.starting':'Nagsisimula…','home.growing':'Lumalaki ang WIENER','home.dailyLimit':'Naabot ang daily farm limit','home.viewAll':'Tingnan lahat','daily.streak':'Streak','daily.claimedToday':'Na-claim ngayon','promo.subtitle':'Manood ng rewarded ad para mag-claim','promo.enter':'Ilagay ang code','tasks.completed':'kasalukuyang gawain ang natapos','invite.link':'Iyong invite link','invite.share':'I-share ang invite','profile.openWallet':'Buksan ang wallet','wallet.withdrawable':'Pinakamataas na ma-withdraw','wallet.selectHint':'Piliin ang eksaktong network. Hindi ito awtomatikong binabago ng WIENER.','wallet.minimum':'Min','wallet.wienerUsed':'WIENER na ginamit','wallet.enterAmount':'Ilagay ang withdrawal amount','wallet.walletAddress':'Wallet address','wallet.reviewTitle':'Suriin ang withdrawal','wallet.confirm':'Kumpirmahin ang withdrawal','wallet.pending':'Pending','wallet.paid':'Bayad','wallet.rejected':'Tinanggihan','wallet.invalid':'Hindi valid ang wallet address.','wallet.insufficient':'Kulang ang WIENER balance.','dynamic.readyIn':'Handa sa {value}','dynamic.minimumIs':'Minimum ay {value}.','dynamic.tasksCompleted':'{value} kasalukuyang gawain ang natapos'},
 vi:{'common.done':'Xong','common.join':'Tham gia','common.watch':'Xem','common.wait':'Chờ','common.apply':'Áp dụng','common.back':'Quay lại','common.continue':'Tiếp tục','common.review':'Kiểm tra','common.status':'Trạng thái','common.network':'Mạng','common.fee':'Phí','common.amount':'Số tiền','common.totalEarned':'Tổng đã kiếm','common.rank':'Hạng','common.referrals':'Giới thiệu','common.qualified':'Đủ điều kiện','common.tasks':'Nhiệm vụ','home.todayFarms':'Farm hôm nay','home.starting':'Đang bắt đầu…','home.growing':'WIENER đang tăng','home.dailyLimit':'Đã đạt giới hạn farm hôm nay','home.viewAll':'Xem tất cả','daily.streak':'Chuỗi','daily.claimedToday':'Đã nhận hôm nay','promo.subtitle':'Xem một quảng cáo thưởng để nhận','promo.enter':'Nhập mã','tasks.completed':'nhiệm vụ hiện tại đã hoàn thành','invite.link':'Liên kết mời của bạn','invite.share':'Chia sẻ lời mời','profile.openWallet':'Mở ví','wallet.withdrawable':'Rút tối đa','wallet.selectHint':'Chọn đúng mạng. WIENER không tự động thay đổi mạng.','wallet.minimum':'Tối thiểu','wallet.wienerUsed':'WIENER đã dùng','wallet.enterAmount':'Nhập số tiền rút','wallet.walletAddress':'Địa chỉ ví','wallet.reviewTitle':'Kiểm tra rút tiền','wallet.confirm':'Xác nhận rút','wallet.pending':'Đang chờ','wallet.paid':'Đã trả','wallet.rejected':'Bị từ chối','wallet.invalid':'Địa chỉ ví không hợp lệ.','wallet.insufficient':'Không đủ WIENER.','dynamic.readyIn':'Sẵn sàng sau {value}','dynamic.minimumIs':'Tối thiểu là {value}.','dynamic.tasksCompleted':'{value} nhiệm vụ hiện tại đã hoàn thành'},
 th:{'common.done':'เสร็จ','common.join':'เข้าร่วม','common.watch':'ดู','common.wait':'รอ','common.apply':'ใช้','common.back':'กลับ','common.continue':'ดำเนินการต่อ','common.review':'ตรวจสอบ','common.status':'สถานะ','common.network':'เครือข่าย','common.fee':'ค่าธรรมเนียม','common.amount':'จำนวน','common.totalEarned':'รายได้ทั้งหมด','common.rank':'อันดับ','common.referrals':'ผู้แนะนำ','common.qualified':'ผ่านเกณฑ์','common.tasks':'งาน','home.todayFarms':'ฟาร์มวันนี้','home.starting':'กำลังเริ่ม…','home.growing':'WIENER กำลังเติบโต','home.dailyLimit':'ถึงขีดจำกัดฟาร์มรายวัน','home.viewAll':'ดูทั้งหมด','daily.streak':'สตรีค','daily.claimedToday':'รับแล้ววันนี้','promo.subtitle':'ดูโฆษณารางวัลหนึ่งรายการเพื่อรับ','promo.enter':'ใส่โค้ด','tasks.completed':'งานปัจจุบันเสร็จแล้ว','invite.link':'ลิงก์เชิญของคุณ','invite.share':'แชร์คำเชิญ','profile.openWallet':'เปิดกระเป๋า','wallet.withdrawable':'ถอนได้สูงสุด','wallet.selectHint':'เลือกเครือข่ายที่ถูกต้อง WIENER จะไม่เปลี่ยนอัตโนมัติ','wallet.minimum':'ขั้นต่ำ','wallet.wienerUsed':'WIENER ที่ใช้','wallet.enterAmount':'ใส่จำนวนถอน','wallet.walletAddress':'ที่อยู่กระเป๋า','wallet.reviewTitle':'ตรวจสอบการถอน','wallet.confirm':'ยืนยันการถอน','wallet.pending':'รอดำเนินการ','wallet.paid':'จ่ายแล้ว','wallet.rejected':'ถูกปฏิเสธ','wallet.invalid':'ที่อยู่กระเป๋าไม่ถูกต้อง','wallet.insufficient':'ยอด WIENER ไม่เพียงพอ','dynamic.readyIn':'พร้อมใน {value}','dynamic.minimumIs':'ขั้นต่ำคือ {value}','dynamic.tasksCompleted':'เสร็จแล้ว {value} งานปัจจุบัน'},
 ms:{'common.done':'Selesai','common.join':'Sertai','common.watch':'Tonton','common.wait':'Tunggu','common.apply':'Guna','common.back':'Kembali','common.continue':'Teruskan','common.review':'Semak','common.status':'Status','common.network':'Rangkaian','common.fee':'Fi','common.amount':'Jumlah','common.totalEarned':'Jumlah diperoleh','common.rank':'Kedudukan','common.referrals':'Rujukan','common.qualified':'Layak','common.tasks':'Tugasan','home.todayFarms':'Farm hari ini','home.starting':'Memulakan…','home.growing':'WIENER sedang berkembang','home.dailyLimit':'Had farm harian dicapai','home.viewAll':'Lihat semua','daily.streak':'Siri','daily.claimedToday':'Dituntut hari ini','promo.subtitle':'Tonton satu iklan ganjaran untuk tuntut','promo.enter':'Masukkan kod','tasks.completed':'tugasan semasa selesai','invite.link':'Pautan jemputan anda','invite.share':'Kongsi jemputan','profile.openWallet':'Buka dompet','wallet.withdrawable':'Maksimum boleh dikeluarkan','wallet.selectHint':'Pilih rangkaian yang tepat. WIENER tidak menukarnya secara automatik.','wallet.minimum':'Min','wallet.wienerUsed':'WIENER digunakan','wallet.enterAmount':'Masukkan jumlah pengeluaran','wallet.walletAddress':'Alamat dompet','wallet.reviewTitle':'Semak pengeluaran','wallet.confirm':'Sahkan pengeluaran','wallet.pending':'Menunggu','wallet.paid':'Dibayar','wallet.rejected':'Ditolak','wallet.invalid':'Alamat dompet tidak sah.','wallet.insufficient':'Baki WIENER tidak mencukupi.','dynamic.readyIn':'Sedia dalam {value}','dynamic.minimumIs':'Minimum ialah {value}.','dynamic.tasksCompleted':'{value} tugasan semasa selesai'},
 ja:{'common.done':'完了','common.join':'参加','common.watch':'見る','common.wait':'待機','common.apply':'適用','common.back':'戻る','common.continue':'続行','common.review':'確認','common.status':'ステータス','common.network':'ネットワーク','common.fee':'手数料','common.amount':'金額','common.totalEarned':'合計獲得','common.rank':'ランク','common.referrals':'紹介','common.qualified':'対象','common.tasks':'タスク','home.todayFarms':'今日のファーム','home.starting':'開始中…','home.growing':'WIENER 成長中','home.dailyLimit':'1日のファーム上限に達しました','home.viewAll':'すべて見る','daily.streak':'連続','daily.claimedToday':'本日受取済み','promo.subtitle':'報酬広告を1つ見て受け取る','promo.enter':'コードを入力','tasks.completed':'現在のタスク完了','invite.link':'招待リンク','invite.share':'招待を共有','profile.openWallet':'ウォレットを開く','wallet.withdrawable':'最大出金可能額','wallet.selectHint':'正しいネットワークを選択してください。WIENER は自動で変更しません。','wallet.minimum':'最小','wallet.wienerUsed':'使用 WIENER','wallet.enterAmount':'出金額を入力','wallet.walletAddress':'ウォレットアドレス','wallet.reviewTitle':'出金を確認','wallet.confirm':'出金を確定','wallet.pending':'保留中','wallet.paid':'支払済み','wallet.rejected':'拒否','wallet.invalid':'ウォレットアドレスが無効です。','wallet.insufficient':'WIENER 残高が不足しています。','dynamic.readyIn':'{value}後に準備完了','dynamic.minimumIs':'最低額は {value} です。','dynamic.tasksCompleted':'現在のタスク {value} 件完了'},
 ko:{'common.done':'완료','common.join':'참여','common.watch':'보기','common.wait':'대기','common.apply':'적용','common.back':'뒤로','common.continue':'계속','common.review':'검토','common.status':'상태','common.network':'네트워크','common.fee':'수수료','common.amount':'금액','common.totalEarned':'총 획득','common.rank':'순위','common.referrals':'추천','common.qualified':'자격 충족','common.tasks':'작업','home.todayFarms':'오늘의 Farm','home.starting':'시작 중…','home.growing':'WIENER 성장 중','home.dailyLimit':'일일 Farm 한도 도달','home.viewAll':'모두 보기','daily.streak':'연속','daily.claimedToday':'오늘 수령 완료','promo.subtitle':'보상 광고 1개를 보고 수령하세요','promo.enter':'코드 입력','tasks.completed':'현재 작업 완료','invite.link':'초대 링크','invite.share':'초대 공유','profile.openWallet':'지갑 열기','wallet.withdrawable':'최대 출금 가능','wallet.selectHint':'정확한 네트워크를 선택하세요. WIENER는 자동 변경하지 않습니다.','wallet.minimum':'최소','wallet.wienerUsed':'사용 WIENER','wallet.enterAmount':'출금 금액 입력','wallet.walletAddress':'지갑 주소','wallet.reviewTitle':'출금 검토','wallet.confirm':'출금 확인','wallet.pending':'대기 중','wallet.paid':'지급됨','wallet.rejected':'거절됨','wallet.invalid':'잘못된 지갑 주소입니다.','wallet.insufficient':'WIENER 잔액이 부족합니다.','dynamic.readyIn':'{value} 후 준비','dynamic.minimumIs':'최소 금액은 {value}입니다.','dynamic.tasksCompleted':'현재 작업 {value}개 완료'},
 'zh-CN':{'common.done':'完成','common.join':'加入','common.watch':'观看','common.wait':'等待','common.apply':'应用','common.back':'返回','common.continue':'继续','common.review':'检查','common.status':'状态','common.network':'网络','common.fee':'手续费','common.amount':'金额','common.totalEarned':'总收益','common.rank':'排名','common.referrals':'邀请','common.qualified':'已达标','common.tasks':'任务','home.todayFarms':'今日 Farm','home.starting':'正在开始…','home.growing':'WIENER 正在增长','home.dailyLimit':'已达到每日 Farm 上限','home.viewAll':'查看全部','daily.streak':'连续签到','daily.claimedToday':'今日已领取','promo.subtitle':'观看一个奖励广告即可领取','promo.enter':'输入代码','tasks.completed':'当前任务已完成','invite.link':'你的邀请链接','invite.share':'分享邀请','profile.openWallet':'打开钱包','wallet.withdrawable':'最大可提现','wallet.selectHint':'请选择准确的网络。WIENER 不会自动更改。','wallet.minimum':'最低','wallet.wienerUsed':'使用的 WIENER','wallet.enterAmount':'输入提现金额','wallet.walletAddress':'钱包地址','wallet.reviewTitle':'检查提现','wallet.confirm':'确认提现','wallet.pending':'待处理','wallet.paid':'已支付','wallet.rejected':'已拒绝','wallet.invalid':'钱包地址无效。','wallet.insufficient':'WIENER 余额不足。','dynamic.readyIn':'{value} 后可领取','dynamic.minimumIs':'最低为 {value}。','dynamic.tasksCompleted':'已完成 {value} 个当前任务'},
 'zh-TW':{'common.done':'完成','common.join':'加入','common.watch':'觀看','common.wait':'等待','common.apply':'套用','common.back':'返回','common.continue':'繼續','common.review':'檢查','common.status':'狀態','common.network':'網路','common.fee':'手續費','common.amount':'金額','common.totalEarned':'總收益','common.rank':'排名','common.referrals':'邀請','common.qualified':'已達標','common.tasks':'任務','home.todayFarms':'今日 Farm','home.starting':'正在開始…','home.growing':'WIENER 正在成長','home.dailyLimit':'已達每日 Farm 上限','home.viewAll':'查看全部','daily.streak':'連續','daily.claimedToday':'今日已領取','promo.subtitle':'觀看一個獎勵廣告即可領取','promo.enter':'輸入代碼','tasks.completed':'目前任務已完成','invite.link':'你的邀請連結','invite.share':'分享邀請','profile.openWallet':'開啟錢包','wallet.withdrawable':'最大可提款','wallet.selectHint':'請選擇正確網路。WIENER 不會自動更改。','wallet.minimum':'最低','wallet.wienerUsed':'使用的 WIENER','wallet.enterAmount':'輸入提款金額','wallet.walletAddress':'錢包地址','wallet.reviewTitle':'檢查提款','wallet.confirm':'確認提款','wallet.pending':'待處理','wallet.paid':'已支付','wallet.rejected':'已拒絕','wallet.invalid':'錢包地址無效。','wallet.insufficient':'WIENER 餘額不足。','dynamic.readyIn':'{value} 後可領取','dynamic.minimumIs':'最低為 {value}。','dynamic.tasksCompleted':'已完成 {value} 個目前任務'}
};
