import {createContext,useContext,useEffect,useMemo,useState,type ReactNode} from 'react';
import {EXTRA_PACKS} from './i18n-extra';
import {POPUP_PACKS} from './i18n-popups';

export type LangCode='en'|'hi'|'bn'|'am'|'es'|'nl'|'ar'|'de'|'fr'|'it'|'pt'|'pt-BR'|'tr'|'pl'|'uk'|'ru'|'id'|'fil'|'vi'|'th'|'ms'|'ja'|'ko'|'zh-CN'|'zh-TW';
export type Language={code:LangCode;name:string;native:string;flag:string;rtl?:boolean};
export const LANGUAGES:Language[]=[
 {code:'en',name:'English',native:'English',flag:'🇺🇸'},
 {code:'hi',name:'Hindi',native:'हिन्दी',flag:'🇮🇳'},
 {code:'bn',name:'Bengali',native:'বাংলা',flag:'🇧🇩'},
 {code:'am',name:'Amharic',native:'አማርኛ',flag:'🇪🇹'},
 {code:'es',name:'Spanish',native:'Español',flag:'🇪🇸'},
 {code:'nl',name:'Dutch',native:'Nederlands',flag:'🇳🇱'},
 {code:'ar',name:'Arabic',native:'العربية',flag:'🇪🇬',rtl:true},
 {code:'de',name:'German',native:'Deutsch',flag:'🇩🇪'},
 {code:'fr',name:'French',native:'Français',flag:'🇫🇷'},
 {code:'it',name:'Italian',native:'Italiano',flag:'🇮🇹'},
 {code:'pt',name:'Portuguese',native:'Português',flag:'🇵🇹'},
 {code:'pt-BR',name:'Portuguese (Brazil)',native:'Português (Brasil)',flag:'🇧🇷'},
 {code:'tr',name:'Turkish',native:'Türkçe',flag:'🇹🇷'},
 {code:'pl',name:'Polish',native:'Polski',flag:'🇵🇱'},
 {code:'uk',name:'Ukrainian',native:'Українська',flag:'🇺🇦'},
 {code:'ru',name:'Russian',native:'Русский',flag:'🇷🇺'},
 {code:'id',name:'Indonesian',native:'Bahasa Indonesia',flag:'🇮🇩'},
 {code:'fil',name:'Filipino',native:'Filipino',flag:'🇵🇭'},
 {code:'vi',name:'Vietnamese',native:'Tiếng Việt',flag:'🇻🇳'},
 {code:'th',name:'Thai',native:'ไทย',flag:'🇹🇭'},
 {code:'ms',name:'Malay',native:'Bahasa Melayu',flag:'🇲🇾'},
 {code:'ja',name:'Japanese',native:'日本語',flag:'🇯🇵'},
 {code:'ko',name:'Korean',native:'한국어',flag:'🇰🇷'},
 {code:'zh-CN',name:'Chinese (Simplified)',native:'简体中文',flag:'🇨🇳'},
 {code:'zh-TW',name:'Chinese (Traditional)',native:'繁體中文',flag:'🇹🇼'},
];

type Dict=Record<string,string>;
const en:Dict={
 'language.title':'Language','language.search':'Search language','language.current':'Current language','language.choose':'Choose language',
 'nav.home':'Home','nav.ads':'Ads','nav.tasks':'Tasks','nav.invite':'Invite','nav.wallet':'Wallet',
 'brand.tagline':'Earn · Invite · Reward','common.loading':'Loading…','common.done':'Done','common.join':'Join','common.watch':'Watch','common.wait':'Wait','common.claim':'Claim','common.apply':'Apply','common.back':'Back','common.continue':'Continue','common.review':'Review','common.balance':'Balance','common.status':'Status','common.network':'Network','common.fee':'Fee','common.amount':'Amount','common.totalEarned':'Total Earned','common.rank':'Rank','common.referrals':'Referrals','common.qualified':'Qualified','common.tasks':'Tasks','common.days':'days','common.unavailable':'Temporarily unavailable',
 'home.totalBalance':'Total Balance','home.sessions':'Sessions','home.ads':'Ads','home.referrals':'Referrals','home.todayFarms':'Today’s farms','home.startFarm':'Start Farm','home.starting':'Starting…','home.growing':'WIENER is growing','home.dailyLimit':'Daily farm limit reached','home.tasks':'Tasks','home.viewAll':'View all','home.invite':'Invite','home.watchAds':'Watch Ads',
 'daily.title':'Daily Bonus','daily.streak':'Streak','daily.claimedToday':'Claimed today','daily.bestStreak':'Best streak','daily.keep':'Claim every day to keep it active.',
 'promo.title':'Promo Code','promo.subtitle':'Watch one rewarded ad to claim','promo.enter':'Enter code','promo.showing':'Showing ad…','promo.claimAgain':'Claim again','promo.claimed':'Promo Claimed','promo.gotIt':'Got it','promo.complete':'Complete the rewarded ad, then your promo reward will be credited.',
 'tasks.progress':'Your Progress','tasks.completed':'current tasks completed','tasks.official':'Official','tasks.exclusive':'Exclusive','tasks.partner':'Partner','tasks.daily':'Daily','tasks.none':'No tasks right now.',
 'invite.title':'Invite Friends','invite.subtitle':'Invite friends to WIENER and earn rewards when they qualify.','invite.invited':'Invited','invite.earned':'Earned','invite.link':'Your Invite Link','invite.share':'Share Invite','invite.perQualified':'Per qualified','invite.recent':'Recent referrals','invite.copied':'Invite link copied',
 'profile.title':'WIENER Profile','profile.streak':'Streak','profile.bestStreak':'Best Streak','profile.openWallet':'Open Wallet',
 'wallet.available':'Available Balance','wallet.withdrawable':'Max withdrawable','wallet.selectMethod':'Select withdrawal method','wallet.selectHint':'Choose the exact network. WIENER never changes it automatically.','wallet.minimum':'Min','wallet.youReceive':'You receive','wallet.wienerUsed':'WIENER used','wallet.enterAmount':'Enter withdrawal amount','wallet.walletAddress':'Wallet address','wallet.reviewTitle':'Review Withdrawal','wallet.confirm':'Confirm Withdrawal','wallet.creating':'Creating…','wallet.history':'Withdrawal History','wallet.historyHint':'Tap any row for full details.','wallet.noHistory':'No withdrawals yet.','wallet.details':'Withdrawal Details','wallet.pending':'Pending','wallet.paid':'Paid','wallet.rejected':'Rejected','wallet.pendingExisting':'You already have a pending withdrawal.','wallet.nextAvailable':'Next withdrawal available in','wallet.invalid':'Invalid wallet address.','wallet.insufficient':'Insufficient WIENER balance.','wallet.openExplorer':'Open Blockchain Explorer',
 'system.secure':'Secure Telegram session','system.loadingRewards':'Loading your rewards','system.openTelegram':'Open WIENER','system.restricted':'Account restricted','system.unable':'Unable to open','system.maintenance':'Maintenance','system.blocked':'Account Blocked','system.contactSupport':'Contact Support'
};

const packs:Partial<Record<LangCode,Dict>>={
 hi:{'language.title':'भाषा','language.search':'भाषा खोजें','nav.home':'होम','nav.ads':'विज्ञापन','nav.tasks':'टास्क','nav.invite':'आमंत्रित करें','nav.wallet':'वॉलेट','common.balance':'बैलेंस','common.claim':'क्लेम','common.watch':'देखें','common.join':'जॉइन','home.totalBalance':'कुल बैलेंस','home.sessions':'सेशन','home.referrals':'रेफरल','home.startFarm':'फार्म शुरू करें','home.watchAds':'विज्ञापन देखें','daily.title':'डेली बोनस','promo.title':'प्रोमो कोड','tasks.progress':'आपकी प्रगति','invite.title':'दोस्तों को आमंत्रित करें','profile.title':'WIENER प्रोफाइल','wallet.available':'उपलब्ध बैलेंस','wallet.withdrawable':'अधिकतम निकासी','wallet.selectMethod':'निकासी का तरीका चुनें','wallet.youReceive':'आपको मिलेगा','wallet.confirm':'निकासी कन्फर्म करें','wallet.history':'निकासी इतिहास'},
 bn:{'language.title':'ভাষা','language.search':'ভাষা খুঁজুন','nav.home':'হোম','nav.ads':'বিজ্ঞাপন','nav.tasks':'টাস্ক','nav.invite':'আমন্ত্রণ','nav.wallet':'ওয়ালেট','common.balance':'ব্যালেন্স','common.claim':'ক্লেইম','home.totalBalance':'মোট ব্যালেন্স','home.startFarm':'ফার্ম শুরু করুন','daily.title':'দৈনিক বোনাস','promo.title':'প্রোমো কোড','tasks.progress':'আপনার অগ্রগতি','invite.title':'বন্ধু আমন্ত্রণ করুন','profile.title':'WIENER প্রোফাইল','wallet.available':'উপলব্ধ ব্যালেন্স','wallet.selectMethod':'উইথড্র পদ্ধতি বেছে নিন','wallet.youReceive':'আপনি পাবেন','wallet.history':'উইথড্র ইতিহাস'},
 am:{'language.title':'ቋንቋ','language.search':'ቋንቋ ፈልግ','nav.home':'መነሻ','nav.ads':'ማስታወቂያ','nav.tasks':'ተግባሮች','nav.invite':'ጋብዝ','nav.wallet':'ዋሌት','common.balance':'ቀሪ ሂሳብ','home.totalBalance':'ጠቅላላ ቀሪ ሂሳብ','daily.title':'ዕለታዊ ጉርሻ','promo.title':'ፕሮሞ ኮድ','invite.title':'ጓደኞችን ጋብዝ','profile.title':'WIENER ፕሮፋይል','wallet.available':'ያለው ቀሪ ሂሳብ','wallet.selectMethod':'የመውጫ ዘዴ ይምረጡ','wallet.history':'የመውጫ ታሪክ'},
 es:{'language.title':'Idioma','language.search':'Buscar idioma','nav.home':'Inicio','nav.ads':'Anuncios','nav.tasks':'Tareas','nav.invite':'Invitar','nav.wallet':'Billetera','common.balance':'Saldo','common.claim':'Reclamar','common.watch':'Ver','common.join':'Unirse','home.totalBalance':'Saldo total','home.sessions':'Sesiones','home.referrals':'Referidos','home.startFarm':'Iniciar granja','home.watchAds':'Ver anuncios','daily.title':'Bono diario','promo.title':'Código promo','tasks.progress':'Tu progreso','invite.title':'Invita amigos','profile.title':'Perfil WIENER','wallet.available':'Saldo disponible','wallet.withdrawable':'Máximo retirable','wallet.selectMethod':'Selecciona método de retiro','wallet.youReceive':'Recibes','wallet.confirm':'Confirmar retiro','wallet.history':'Historial de retiros'},
 nl:{'language.title':'Taal','language.search':'Taal zoeken','nav.home':'Home','nav.ads':'Advertenties','nav.tasks':'Taken','nav.invite':'Uitnodigen','nav.wallet':'Wallet','common.balance':'Saldo','common.claim':'Claimen','home.totalBalance':'Totaal saldo','daily.title':'Dagbonus','promo.title':'Promocode','tasks.progress':'Je voortgang','invite.title':'Vrienden uitnodigen','profile.title':'WIENER-profiel','wallet.available':'Beschikbaar saldo','wallet.withdrawable':'Maximaal opneembaar','wallet.selectMethod':'Kies opnamemethode','wallet.youReceive':'Je ontvangt','wallet.confirm':'Opname bevestigen','wallet.history':'Opnamegeschiedenis'},
 ar:{'language.title':'اللغة','language.search':'ابحث عن لغة','nav.home':'الرئيسية','nav.ads':'الإعلانات','nav.tasks':'المهام','nav.invite':'دعوة','nav.wallet':'المحفظة','common.balance':'الرصيد','common.claim':'استلام','common.watch':'مشاهدة','common.join':'انضمام','home.totalBalance':'إجمالي الرصيد','daily.title':'المكافأة اليومية','promo.title':'رمز ترويجي','tasks.progress':'تقدمك','invite.title':'دعوة الأصدقاء','profile.title':'ملف WIENER','wallet.available':'الرصيد المتاح','wallet.withdrawable':'الحد الأقصى للسحب','wallet.selectMethod':'اختر طريقة السحب','wallet.youReceive':'ستستلم','wallet.confirm':'تأكيد السحب','wallet.history':'سجل السحب'},
 de:{'language.title':'Sprache','language.search':'Sprache suchen','nav.home':'Start','nav.ads':'Werbung','nav.tasks':'Aufgaben','nav.invite':'Einladen','nav.wallet':'Wallet','common.balance':'Guthaben','common.claim':'Abholen','home.totalBalance':'Gesamtguthaben','daily.title':'Täglicher Bonus','promo.title':'Promo-Code','tasks.progress':'Dein Fortschritt','invite.title':'Freunde einladen','profile.title':'WIENER Profil','wallet.available':'Verfügbares Guthaben','wallet.withdrawable':'Maximal auszahlbar','wallet.selectMethod':'Auszahlungsmethode wählen','wallet.youReceive':'Du erhältst','wallet.confirm':'Auszahlung bestätigen','wallet.history':'Auszahlungsverlauf'},
 fr:{'language.title':'Langue','language.search':'Rechercher une langue','nav.home':'Accueil','nav.ads':'Pubs','nav.tasks':'Tâches','nav.invite':'Inviter','nav.wallet':'Portefeuille','common.balance':'Solde','common.claim':'Réclamer','home.totalBalance':'Solde total','daily.title':'Bonus quotidien','promo.title':'Code promo','tasks.progress':'Votre progression','invite.title':'Inviter des amis','profile.title':'Profil WIENER','wallet.available':'Solde disponible','wallet.withdrawable':'Retrait maximum','wallet.selectMethod':'Choisir le mode de retrait','wallet.youReceive':'Vous recevez','wallet.confirm':'Confirmer le retrait','wallet.history':'Historique des retraits'},
 it:{'language.title':'Lingua','nav.home':'Home','nav.ads':'Annunci','nav.tasks':'Attività','nav.invite':'Invita','nav.wallet':'Portafoglio','common.balance':'Saldo','home.totalBalance':'Saldo totale','daily.title':'Bonus giornaliero','promo.title':'Codice promo','invite.title':'Invita amici','profile.title':'Profilo WIENER','wallet.available':'Saldo disponibile','wallet.selectMethod':'Seleziona metodo di prelievo','wallet.youReceive':'Ricevi','wallet.history':'Cronologia prelievi'},
 pt:{'language.title':'Idioma','nav.home':'Início','nav.ads':'Anúncios','nav.tasks':'Tarefas','nav.invite':'Convidar','nav.wallet':'Carteira','common.balance':'Saldo','home.totalBalance':'Saldo total','daily.title':'Bónus diário','promo.title':'Código promocional','invite.title':'Convidar amigos','profile.title':'Perfil WIENER','wallet.available':'Saldo disponível','wallet.selectMethod':'Escolher método de levantamento','wallet.youReceive':'Recebe','wallet.history':'Histórico de levantamentos'},
 'pt-BR':{'language.title':'Idioma','nav.home':'Início','nav.ads':'Anúncios','nav.tasks':'Tarefas','nav.invite':'Convidar','nav.wallet':'Carteira','common.balance':'Saldo','home.totalBalance':'Saldo total','daily.title':'Bônus diário','promo.title':'Código promocional','invite.title':'Convidar amigos','profile.title':'Perfil WIENER','wallet.available':'Saldo disponível','wallet.selectMethod':'Escolha o método de saque','wallet.youReceive':'Você recebe','wallet.history':'Histórico de saques'},
 tr:{'language.title':'Dil','nav.home':'Ana Sayfa','nav.ads':'Reklamlar','nav.tasks':'Görevler','nav.invite':'Davet','nav.wallet':'Cüzdan','common.balance':'Bakiye','home.totalBalance':'Toplam bakiye','daily.title':'Günlük bonus','promo.title':'Promosyon kodu','invite.title':'Arkadaşlarını davet et','profile.title':'WIENER Profili','wallet.available':'Kullanılabilir bakiye','wallet.selectMethod':'Çekim yöntemini seç','wallet.youReceive':'Alacağınız','wallet.history':'Çekim geçmişi'},
 pl:{'language.title':'Język','nav.home':'Start','nav.ads':'Reklamy','nav.tasks':'Zadania','nav.invite':'Zaproś','nav.wallet':'Portfel','common.balance':'Saldo','home.totalBalance':'Łączne saldo','daily.title':'Dzienny bonus','promo.title':'Kod promocyjny','invite.title':'Zaproś znajomych','profile.title':'Profil WIENER','wallet.available':'Dostępne saldo','wallet.selectMethod':'Wybierz metodę wypłaty','wallet.youReceive':'Otrzymasz','wallet.history':'Historia wypłat'},
 uk:{'language.title':'Мова','nav.home':'Головна','nav.ads':'Реклама','nav.tasks':'Завдання','nav.invite':'Запросити','nav.wallet':'Гаманець','common.balance':'Баланс','home.totalBalance':'Загальний баланс','daily.title':'Щоденний бонус','promo.title':'Промокод','invite.title':'Запросити друзів','profile.title':'Профіль WIENER','wallet.available':'Доступний баланс','wallet.selectMethod':'Оберіть спосіб виведення','wallet.youReceive':'Ви отримаєте','wallet.history':'Історія виведень'},
 ru:{'language.title':'Язык','nav.home':'Главная','nav.ads':'Реклама','nav.tasks':'Задания','nav.invite':'Пригласить','nav.wallet':'Кошелёк','common.balance':'Баланс','home.totalBalance':'Общий баланс','daily.title':'Ежедневный бонус','promo.title':'Промокод','invite.title':'Пригласить друзей','profile.title':'Профиль WIENER','wallet.available':'Доступный баланс','wallet.selectMethod':'Выберите способ вывода','wallet.youReceive':'Вы получите','wallet.history':'История выводов'},
 id:{'language.title':'Bahasa','nav.home':'Beranda','nav.ads':'Iklan','nav.tasks':'Tugas','nav.invite':'Undang','nav.wallet':'Dompet','common.balance':'Saldo','home.totalBalance':'Total saldo','daily.title':'Bonus harian','promo.title':'Kode promo','invite.title':'Undang teman','profile.title':'Profil WIENER','wallet.available':'Saldo tersedia','wallet.selectMethod':'Pilih metode penarikan','wallet.youReceive':'Anda menerima','wallet.history':'Riwayat penarikan'},
 fil:{'language.title':'Wika','nav.home':'Home','nav.ads':'Ads','nav.tasks':'Mga Gawain','nav.invite':'Imbitahin','nav.wallet':'Wallet','common.balance':'Balanse','home.totalBalance':'Kabuuang balanse','daily.title':'Daily Bonus','promo.title':'Promo Code','invite.title':'Mag-imbita ng Kaibigan','profile.title':'WIENER Profile','wallet.available':'Available Balance','wallet.selectMethod':'Piliin ang withdrawal method','wallet.youReceive':'Matatanggap mo','wallet.history':'Withdrawal History'},
 vi:{'language.title':'Ngôn ngữ','nav.home':'Trang chủ','nav.ads':'Quảng cáo','nav.tasks':'Nhiệm vụ','nav.invite':'Mời','nav.wallet':'Ví','common.balance':'Số dư','home.totalBalance':'Tổng số dư','daily.title':'Thưởng hằng ngày','promo.title':'Mã khuyến mãi','invite.title':'Mời bạn bè','profile.title':'Hồ sơ WIENER','wallet.available':'Số dư khả dụng','wallet.selectMethod':'Chọn phương thức rút','wallet.youReceive':'Bạn nhận','wallet.history':'Lịch sử rút tiền'},
 th:{'language.title':'ภาษา','nav.home':'หน้าหลัก','nav.ads':'โฆษณา','nav.tasks':'งาน','nav.invite':'เชิญ','nav.wallet':'กระเป๋า','common.balance':'ยอดคงเหลือ','home.totalBalance':'ยอดรวม','daily.title':'โบนัสรายวัน','promo.title':'โค้ดโปรโมชั่น','invite.title':'เชิญเพื่อน','profile.title':'โปรไฟล์ WIENER','wallet.available':'ยอดที่ใช้ได้','wallet.selectMethod':'เลือกวิธีถอน','wallet.youReceive':'คุณจะได้รับ','wallet.history':'ประวัติการถอน'},
 ms:{'language.title':'Bahasa','nav.home':'Utama','nav.ads':'Iklan','nav.tasks':'Tugasan','nav.invite':'Jemput','nav.wallet':'Dompet','common.balance':'Baki','home.totalBalance':'Jumlah baki','daily.title':'Bonus harian','promo.title':'Kod promo','invite.title':'Jemput rakan','profile.title':'Profil WIENER','wallet.available':'Baki tersedia','wallet.selectMethod':'Pilih kaedah pengeluaran','wallet.youReceive':'Anda terima','wallet.history':'Sejarah pengeluaran'},
 ja:{'language.title':'言語','nav.home':'ホーム','nav.ads':'広告','nav.tasks':'タスク','nav.invite':'招待','nav.wallet':'ウォレット','common.balance':'残高','home.totalBalance':'合計残高','daily.title':'デイリーボーナス','promo.title':'プロモコード','invite.title':'友達を招待','profile.title':'WIENER プロフィール','wallet.available':'利用可能残高','wallet.selectMethod':'出金方法を選択','wallet.youReceive':'受取額','wallet.history':'出金履歴'},
 ko:{'language.title':'언어','nav.home':'홈','nav.ads':'광고','nav.tasks':'작업','nav.invite':'초대','nav.wallet':'지갑','common.balance':'잔액','home.totalBalance':'총 잔액','daily.title':'일일 보너스','promo.title':'프로모 코드','invite.title':'친구 초대','profile.title':'WIENER 프로필','wallet.available':'사용 가능 잔액','wallet.selectMethod':'출금 방법 선택','wallet.youReceive':'받는 금액','wallet.history':'출금 내역'},
 'zh-CN':{'language.title':'语言','nav.home':'首页','nav.ads':'广告','nav.tasks':'任务','nav.invite':'邀请','nav.wallet':'钱包','common.balance':'余额','home.totalBalance':'总余额','daily.title':'每日奖励','promo.title':'优惠码','invite.title':'邀请好友','profile.title':'WIENER 资料','wallet.available':'可用余额','wallet.selectMethod':'选择提现方式','wallet.youReceive':'你将收到','wallet.history':'提现记录'},
 'zh-TW':{'language.title':'語言','nav.home':'首頁','nav.ads':'廣告','nav.tasks':'任務','nav.invite':'邀請','nav.wallet':'錢包','common.balance':'餘額','home.totalBalance':'總餘額','daily.title':'每日獎勵','promo.title':'優惠碼','invite.title':'邀請好友','profile.title':'WIENER 個人資料','wallet.available':'可用餘額','wallet.selectMethod':'選擇提款方式','wallet.youReceive':'你將收到','wallet.history':'提款紀錄'}
};

const STORAGE='wiener_language_v1';
function deviceLang():LangCode{try{const raw=(window.Telegram?.WebApp as any)?.initDataUnsafe?.user?.language_code||navigator.language||'en',v=String(raw).toLowerCase();if(v.startsWith('pt-br'))return'pt-BR';if(v.startsWith('zh-tw')||v.startsWith('zh-hk'))return'zh-TW';if(v.startsWith('zh'))return'zh-CN';if(v.startsWith('fil')||v.startsWith('tl'))return'fil';const short=v.split('-')[0] as LangCode;return LANGUAGES.some(x=>x.code===short)?short:'en'}catch{return'en'}}
function initial():LangCode{try{const saved=localStorage.getItem(STORAGE) as LangCode|null;if(saved&&LANGUAGES.some(x=>x.code===saved))return saved}catch{}return deviceLang()}

type I18nValue={lang:LangCode;language:Language;setLang:(x:LangCode)=>void;t:(key:string,fallback?:string)=>string};
const Ctx=createContext<I18nValue>({lang:'en',language:LANGUAGES[0],setLang:()=>{},t:(k,f)=>f||en[k]||k});
export function I18nProvider({children}:{children:ReactNode}){const[lang,setLangState]=useState<LangCode>(initial);const language=LANGUAGES.find(x=>x.code===lang)||LANGUAGES[0];const setLang=(x:LangCode)=>{setLangState(x);try{localStorage.setItem(STORAGE,x)}catch{}};useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=language.rtl?'rtl':'ltr';document.body.dataset.lang=lang},[lang,language.rtl]);const value=useMemo<I18nValue>(()=>({lang,language,setLang,t:(key,fallback)=>POPUP_PACKS[lang]?.[key]||EXTRA_PACKS[lang]?.[key]||packs[lang]?.[key]||en[key]||fallback||key}),[lang,language]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>}
export const useI18n=()=>useContext(Ctx);
