import {useEffect,useState} from 'react';
import {getInitData,money,PUBLISHABLE_KEY,shareApi,SUPABASE_URL,type Snapshot} from './lib';
import {AnimatedIcon} from './icons';

type Stats={invited:number;qualified:number;pending:number;earned:number};

async function loadReferral(){
 const body=JSON.stringify({initData:getInitData()});
 const headers={'Content-Type':'application/json','apikey':PUBLISHABLE_KEY,'cache-control':'no-cache'};
 try{const r=await fetch(`${SUPABASE_URL}/functions/v1/wiener-referral-v2`,{method:'POST',headers,cache:'no-store',body});const x=await r.json();if(r.ok&&x?.ok)return{x:x.data,v2:true}}catch{}
 const r=await fetch(`${SUPABASE_URL}/functions/v1/wiener-referral-status`,{method:'POST',headers,cache:'no-store',body});
 const x=await r.json();if(!r.ok||!x?.ok)throw Error(x?.message||x?.error||'Unable to load referrals');return{x:x.data,v2:false};
}

export function Invite({data,say}:{data:Snapshot;say:any}){
 const s=data.settings||{},u=data.user;const tokenPerUsdt=Number(s.token_per_usdt||0),activeReward=Number(s.referral_active_reward||0),activeAdsRequired=Number(s.referral_active_ads_required||0),commissionPercent=Number(s.referral_commission_percent||0);const rewardUsd=tokenPerUsdt>0?activeReward/tokenPerUsdt:0;
 const[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[refs,setRefs]=useState<any[]>([]),[stats,setStats]=useState<Stats>({invited:Number(u.referrals_count||0),qualified:0,pending:0,earned:Number(u.referral_earnings||0)}),[security,setSecurity]=useState<any>({});
 const link=`https://t.me/${String(s.bot_username||'@WienerDogeFarmBot').replace('@','')}?startapp=ref_${u.telegram_id}`;
 const shareText='🌭 Join WIENER Farm\n\n🎁 Earn WIENER by watching ads, completing tasks and inviting friends.\n🚀 Invite friends and earn the configured referral reward per qualified friend.\n\n👇 Open WIENER Farm';
 const refresh=async()=>{try{setReady(false);const r=await loadReferral(),x=r.x||{};const list=x.referrals||[];setRefs(list);setStats(r.v2?{invited:Number(x.stats?.invited||0),qualified:Number(x.stats?.qualified||0),pending:Number(x.stats?.pending||0),earned:Number(x.stats?.earned||0)}:{invited:list.length,qualified:Number(x.qualified||0),pending:Math.max(0,list.length-Number(x.qualified||0)),earned:Number(u.referral_earnings||0)});setSecurity(x.security||{})}catch(e:any){say(String(e?.message||'Unable to load referrals'))}finally{setReady(true)}};
 useEffect(()=>{refresh()},[]);
 useEffect(()=>{if(security?.viewer_vpn_blocked){const msg='VPN or proxy detected. Turn it off and reopen WIENER Farm to continue referral qualification.';try{(window.Telegram?.WebApp as any)?.showAlert?.(msg)}catch{}say(msg)}},[security?.viewer_vpn_blocked]);
 const fallback=()=>window.Telegram?.WebApp?.openTelegramLink?.(`https://t.me/share/url?url=${encodeURIComponent(link)}&text=${encodeURIComponent(shareText)}`);
 const share=async()=>{if(busy)return;try{setBusy(true);const wa:any=window.Telegram?.WebApp;if(typeof wa?.shareMessage!=='function'){fallback();return}const prepared=await shareApi();if(!prepared?.id)throw Error('Share message unavailable');wa.shareMessage(prepared.id)}catch(e:any){say(String(e?.message||'Unable to prepare share message'));fallback()}finally{setBusy(false)}};
 const copy=async()=>{try{await navigator.clipboard.writeText(link);say('Invite link copied')}catch{const ta=document.createElement('textarea');ta.value=link;document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();say(ok?'Invite link copied':'Copy failed')}};
 const state=(r:any)=>{if(r.status==='banned'||r.referral_reward_eligible===false)return{label:'NOT ELIGIBLE',tone:'bad'};if(r.vpn_blocked||r.status==='vpn_blocked')return{label:'PAUSED',tone:'warn'};if(r.completion_rewarded_at||r.status==='rewarded')return{label:'COMPLETED',tone:'good'};if(r.join_rewarded_at)return{label:'IN PROGRESS',tone:'live'};return{label:'JOINED',tone:'live'}};
 const settingNum=(...keys:string[])=>{for(const k of keys){const n=Number((s as any)?.[k]);if(Number.isFinite(n)&&n>0)return n}return 0};
 const joinReward=settingNum('referral_join_reward','referral_join_bonus','referral_signup_reward','referral_reward_on_join');
 return <><style>{`
.iv{display:grid;gap:14px;padding:10px 0 120px;color:#effff6}
.iv *{box-sizing:border-box}
.iv-card{position:relative;overflow:hidden;border:1px solid rgba(104,235,165,.16);background:linear-gradient(145deg,rgba(12,72,45,.88),rgba(3,35,24,.96));box-shadow:inset 0 1px rgba(255,255,255,.05),0 14px 34px rgba(0,0,0,.14)}
.iv-balance{min-height:220px;padding:25px 24px;border-radius:28px;background:radial-gradient(circle at 82% 45%,rgba(40,220,128,.12),transparent 34%),linear-gradient(145deg,rgba(15,82,49,.88),rgba(4,39,26,.96))}
.iv-balance .iv-kicker,.iv-balance .iv-number,.iv-balance .iv-unit{position:relative;z-index:3}
.iv-kicker,.iv-label{font-size:10px;font-weight:900;letter-spacing:2.8px;color:rgba(240,255,248,.55)}
.iv-number{margin-top:9px;font-size:58px;line-height:.95;font-weight:900;color:#70e8ad}
.iv-unit{display:flex;align-items:center;gap:9px;margin-top:13px;font-size:10px;font-weight:900;letter-spacing:1.7px;color:rgba(255,255,255,.52)}
.iv-usd{padding:7px 11px;border:1px solid rgba(16,224,137,.3);border-radius:999px;color:#18df8b;letter-spacing:0}
.iv-dog{position:absolute;z-index:2;width:145px;height:145px;right:3px;top:34px;object-fit:contain;pointer-events:none;filter:drop-shadow(0 10px 18px rgba(0,0,0,.25));animation:ivdog 4.8s ease-in-out infinite}
@keyframes ivdog{0%,100%{transform:translateY(0) rotate(-2deg)}50%{transform:translateY(-7px) rotate(2deg)}}
.iv-reward{padding:23px 22px;border-radius:26px;background:linear-gradient(145deg,rgba(8,116,65,.9),rgba(4,58,35,.98))}
.iv-reward h3{margin:0;font-size:13px;letter-spacing:2.5px}
.iv-reward-main{display:flex;align-items:center;gap:9px;margin:15px 0 18px}
.iv-reward-main strong{font-size:56px;line-height:1}
.iv-reward-main>b{font-size:22px}
.iv-worth{margin-left:auto;padding-left:15px;border-left:1px solid rgba(255,255,255,.2)}
.iv-worth small{display:block;font-size:8px;letter-spacing:1.7px;opacity:.5}.iv-worth b{font-size:16px}
.iv-pills{display:flex;gap:7px;flex-wrap:wrap}.iv-pills span{padding:8px 10px;border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.05);border-radius:999px;font-size:8px;font-weight:800;color:rgba(255,255,255,.78)}
.iv-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.iv-stat{padding:17px 7px;text-align:center;border:1px solid rgba(105,235,165,.13);border-radius:18px;background:rgba(7,52,35,.8)}.iv-stat b{display:block;font-size:25px;color:#16dc89}.iv-stat span{display:block;margin-top:6px;font-size:8px;font-weight:900;letter-spacing:1.8px;opacity:.5}
.iv-box{padding:20px;border-radius:24px}.iv-link{display:grid;grid-template-columns:minmax(0,1fr) 52px;gap:8px;margin-top:10px}.iv-linktext{height:54px;display:flex;align-items:center;padding:0 13px;border:1px solid rgba(255,255,255,.07);border-radius:14px;background:rgba(0,0,0,.16);font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.iv-copy{border:1px solid rgba(135,166,230,.18);border-radius:14px;background:rgba(92,128,191,.25);color:#b9a1ff;font-size:21px}.iv-share{height:54px;width:100%;margin-top:9px;border:0;border-radius:14px;background:linear-gradient(120deg,#0bd981,#0a9f50);color:#fff;font-size:12px;font-weight:950;letter-spacing:1.8px}.iv-myinv{height:54px;margin-top:9px;display:flex;align-items:center;justify-content:center;border:1px solid rgba(255,255,255,.07);border-radius:14px;background:rgba(255,255,255,.035);font-size:10px;font-weight:900;letter-spacing:1.8px}.iv-myinv b{color:#14df8a;margin-left:7px}
.iv-title{display:flex;align-items:center;gap:8px;padding:0 5px;font-size:11px;font-weight:900;letter-spacing:2.6px}.iv-title:before{content:"";width:6px;height:6px;border-radius:50%;background:#08d77d;box-shadow:0 0 10px #08d77d}.iv-muted{margin-left:auto;font-size:8px;letter-spacing:0;opacity:.45}
.iv-pay{border-radius:24px}.iv-pay-row{display:grid;grid-template-columns:45px minmax(0,1fr) auto;gap:11px;align-items:center;min-height:82px;padding:13px 15px;border-bottom:1px solid rgba(255,255,255,.06)}.iv-pay-row:last-child{border-bottom:0}.iv-step{width:43px;height:43px;display:grid;place-items:center;border-radius:13px;background:rgba(12,166,91,.22);color:#15d985;font-size:15px;font-weight:900}.iv-step.alt{background:rgba(122,105,186,.25);color:#ad91ff}.iv-step.gold{background:rgba(193,153,37,.24);color:#f4c943}.iv-pay-main b{display:block;font-size:15px}.iv-pay-main span{display:block;margin-top:3px;font-size:10px;line-height:1.3;color:rgba(255,255,255,.46)}.iv-pay-reward{font-size:15px;font-weight:900;color:#10d881}
.iv-friends{display:grid;gap:8px}.iv-friend{padding:12px;border:1px solid rgba(255,255,255,.06);border-radius:15px;background:rgba(255,255,255,.025)}.iv-friendtop{display:grid;grid-template-columns:40px minmax(0,1fr) auto;gap:9px;align-items:center}.iv-avatar{width:40px;height:40px;display:grid;place-items:center;border-radius:12px;background:rgba(65,226,130,.12);color:#82ecaa;font-weight:900}.iv-name b{display:block;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.iv-name span{display:block;margin-top:3px;font-size:8px;opacity:.4}.iv-status{padding:5px 7px;border-radius:999px;font-size:7px;font-weight:950}.iv-status.good{color:#7aeca7}.iv-status.live{color:#ffe06b}.iv-status.warn{color:#ffc66b}.iv-status.bad{color:#ff9292}.iv-progress{height:4px;margin-top:9px;border-radius:5px;background:rgba(255,255,255,.06);overflow:hidden}.iv-progress i{display:block;height:100%;background:#17dd89}.iv-meta{display:flex;justify-content:space-between;margin-top:6px;font-size:8px;opacity:.4}
@media(max-width:390px){.iv-balance{min-height:205px;padding:23px 20px}.iv-dog{width:126px;height:126px;right:0;top:34px}.iv-number{font-size:52px}.iv-reward-main strong{font-size:51px}.iv-pay-row{grid-template-columns:42px minmax(0,1fr) auto;padding:12px}.iv-pay-main span{font-size:9px}}
`}<style id="iv-reference-overrides">.iv{gap:14px!important;padding:8px 0 125px!important}.iv-balance{min-height:258px!important;padding:25px 30px!important;border-radius:0!important;clip-path:polygon(6% 0,100% 0,100% 78%,92% 100%,0 100%,0 10%)!important;background:radial-gradient(circle at 78% 42%,rgba(49,230,130,.16),transparent 34%),linear-gradient(145deg,rgba(8,76,46,.96),rgba(3,43,28,.98))!important}.iv-kicker{font-size:11px!important;letter-spacing:2.8px!important}.iv-number{font-size:72px!important;letter-spacing:-2px!important;color:#6ce5a7!important}.iv-dog{width:145px!important;height:145px!important;right:23px!important;top:36px!important}.iv-reward{min-height:292px!important;padding:28px 31px 24px!important;clip-path:polygon(6% 0,100% 0,100% 86%,93% 100%,0 100%,0 10%)!important;background:linear-gradient(145deg,rgba(8,115,64,.96),rgba(4,64,38,.98))!important}.iv-reward h3{font-size:14px!important;letter-spacing:2.8px!important}.iv-reward-main{margin:25px 0 27px!important}.iv-reward-main strong{font-size:66px!important}.iv-reward .iv-dog-small{width:48px!important;height:48px!important}.iv-pills span{font-size:10px!important;padding:9px 12px!important}.iv-stats{gap:10px!important}.iv-stat{min-height:130px!important;padding:22px 8px 16px!important;border-radius:0!important;clip-path:polygon(8% 0,100% 0,100% 86%,88% 100%,0 100%,0 12%)!important}.iv-stat b{font-size:31px!important}.iv-stat span{font-size:9px!important}.iv-box{padding:22px 28px!important;border-radius:0!important;clip-path:polygon(6% 0,100% 0,100% 88%,94% 100%,0 100%,0 9%)!important}.iv-link{grid-template-columns:52px minmax(0,1fr)!important}.iv-linktext{height:55px!important;font-size:14px!important}.iv-copy{width:52px!important;height:55px!important}.iv-share{height:56px!important;margin-top:11px!important;border-radius:0!important;clip-path:polygon(5% 0,95% 0,100% 18%,100% 82%,95% 100%,5% 100%,0 82%,0 18%)!important}.iv-myinv{height:57px!important;margin-top:11px!important;border-radius:0!important;clip-path:polygon(5% 0,95% 0,100% 20%,100% 80%,95% 100%,5% 100%,0 80%,0 20%)!important}.iv-title{padding:6px 5px 1px!important;font-size:12px!important}.iv-pay{border-radius:0!important;clip-path:polygon(5% 0,100% 0,100% 92%,95% 100%,0 100%,0 8%)!important}.iv-pay-row{min-height:94px!important;padding:13px 18px!important}.iv-step{width:48px!important;height:48px!important}@media(max-width:390px){.iv-balance{min-height:245px!important;padding:24px 28px!important}.iv-dog{width:126px!important;height:126px!important;right:12px!important;top:39px!important}.iv-number{font-size:64px!important}.iv-reward{min-height:276px!important;padding:25px 28px 22px!important}.iv-reward-main strong{font-size:60px!important}.iv-stat{min-height:120px!important}.iv-box{padding:20px 24px!important}.iv-pay-row{padding:12px!important}}</style><div className="iv">
<section className="iv-card iv-balance"><img className="iv-dog" src="https://pixlinkhost.vercel.app/i/DTBrE-73Ag" alt="" aria-hidden="true"/><div className="iv-kicker">TOTAL BALANCE</div><div className="iv-number">{money(Math.floor(Number(u.balance||0)))}</div><div className="iv-unit"><span>◆ WIENER</span><span className="iv-usd">{tokenPerUsdt>0?("$"+(Math.floor(Number(u.balance||0))/tokenPerUsdt).toFixed(4)):"—"}</span></div></section>
<section className="iv-card iv-reward"><h3>PER FRIEND YOU INVITE</h3><div className="iv-reward-main"><strong>{activeReward?money(activeReward):"—"}</strong><b>W</b><div className="iv-worth"><small>WORTH</small><b>{tokenPerUsdt&&activeReward?("$"+(activeReward/tokenPerUsdt).toFixed(4)):"—"}</b></div></div><div className="iv-pills"><span>{joinReward?money(joinReward)+" on join":"Join reward from settings"}</span><span>{activeReward?("+"+money(activeReward)+" when active"):"Active reward from settings"}</span><span>{commissionPercent?commissionPercent+"% forever":"Commission from settings"}</span></div></section>
<div className="iv-stats"><div className="iv-stat"><b>{stats.invited}</b><span>FRIENDS</span></div><div className="iv-stat"><b>{stats.qualified}</b><span>ACTIVE</span></div><div className="iv-stat"><b>{money(stats.earned)}</b><span>EARNED</span></div></div>
<section className="iv-card iv-box"><div className="iv-label">YOUR INVITE LINK</div><div className="iv-link"><div className="iv-linktext">{link}</div><button className="iv-copy" onClick={copy} aria-label="Copy invite link">⧉</button></div><button className="iv-share" disabled={busy} onClick={share}>{busy?"PREPARING…":"➤  SHARE"}</button><div className="iv-myinv">♟ &nbsp; MY INVITES <b>{stats.invited}</b></div></section>
<div className="iv-title"><span>HOW IT PAYS</span></div>
<section className="iv-card iv-pay"><div className="iv-pay-row"><div className="iv-step">01</div><div className="iv-pay-main"><b>They join</b><span>Friend opens Wiener Farm from your invite link</span></div><div className="iv-pay-reward">{joinReward?money(joinReward):"—"}</div></div><div className="iv-pay-row"><div className="iv-step alt">02</div><div className="iv-pay-main"><b>They become active</b><span>Unlocks when the configured referral activity requirement is met</span></div><div className="iv-pay-reward">{activeReward?money(activeReward):"—"}</div></div><div className="iv-pay-row"><div className="iv-step gold">03</div><div className="iv-pay-main"><b>Forever after</b><span>Commission from the live referral settings</span></div><div className="iv-pay-reward">{commissionPercent?commissionPercent+"%":"—"}</div></div></section>
{refs.length>0&&<><div className="iv-title"><span>YOUR FRIENDS</span><span className="iv-muted">{stats.pending} pending</span></div><section className="iv-card iv-box"><div className="iv-friends">{refs.slice(0,20).map(r=>{const st=state(r),name=r.first_name||r.username||("User "+r.telegram_id),ads=Math.min(Number(r.total_ads||0),5),pct=Math.max(0,Math.min(100,ads/5*100));return <div className="iv-friend" key={r.telegram_id}><div className="iv-friendtop"><div className="iv-avatar">{String(name)[0]?.toUpperCase()||"?"}</div><div className="iv-name"><b>{name}</b><span>{r.completion_rewarded_at?"Activity reward unlocked":r.join_rewarded_at?"Join reward unlocked":"Waiting for activity"}</span></div><div className={"iv-status "+st.tone}>{st.label}</div></div><div className="iv-progress"><i style={{width:pct+"%"}}/></div><div className="iv-meta"><span>{ads}/5 ads</span><span>{r.completion_rewarded_at?"REWARDED":r.join_rewarded_at?"JOIN REWARD":"PENDING"}</span></div></div>})}</div></section></>}
</div></>;
}