const viteEnv=(import.meta as any).env||{};\n// V45 TON iOS browser compatibility
// Legacy names are kept only so older components compile. Runtime traffic is same-origin VPS only.
export const SUPABASE_URL='';
export const PUBLISHABLE_KEY='vps';
const edge=(name:string)=>`/functions/v1/${encodeURIComponent(name)}`;
export const API=edge('wiener-api');
export const ADMIN_API=edge('wiener-admin-api');
export const AD_API=edge('wiener-ad');
export const AD_USAGE_API=edge('wiener-ad-usage');
export const SECONDARY_AD_API=edge('wiener-tads');
export const ADSGRAM_TASK_API=edge('wiener-adsgram-task');
export const TASK_API=edge('wiener-task-api');
export const MANDATORY_API=edge('wiener-mandatory');
export const WITHDRAW_API=edge('wiener-withdraw');
export const DEVICE_API=edge('wiener-device');
export const PROMO_CHANNEL_API=edge('wiener-promo-channel');
export const SHARE_API=edge('wiener-share');
export const MISSION_API=edge('wiener-missions');
export const AMBASSADOR_API=edge('wiener-ambassador');
export const AMBASSADOR_PUBLISH_API=edge('wiener-ambassador-publish');

export type Tab='home'|'ads'|'tasks'|'games'|'earn'|'invite'|'wallet'|'daily'|'claim'|'profile'|'leaderboard'|'ambassador'|'admin';
export type Snapshot={user:any;settings:any;tasks:any[];completed:any[];transactions:any[];withdrawals:any[];withdrawal_methods?:any[];referrals:any[];leaderboard?:any[];rank?:number;tasks_completed_total?:number;is_admin:boolean;admin_role?:string};

export const money=(n:any,d=6)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:Math.max(0,d),minimumFractionDigits:0});
function trimDecimalString(v:string){if(!/^-?\d+\.\d+$/.test(v))return v;const x=v.replace(/(\.\d*?[1-9])0+$/,'$1').replace(/\.0+$/,'');return x==='-0'?'0':x}
function normalizeUiNumbers(v:any):any{if(typeof v==='string')return trimDecimalString(v);if(Array.isArray(v))return v.map(normalizeUiNumbers);if(v&&typeof v==='object'){const out:any={};for(const [k,val] of Object.entries(v))out[k]=normalizeUiNumbers(val);return out}return v}
const REQUEST_TIMEOUT_MS=15000;const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function requestError(status:number,x:any){const raw=String(x?.message||x?.error||'').trim();if([502,503,504].includes(status))return new Error('Server is reconnecting. Try again in a moment.');if(status===429)return new Error(raw||'Too many requests. Please wait a moment.');if(status>=500)return new Error(raw||'Temporary server error. Please try again.');return new Error(raw||'Request failed')}
async function fetchJson(url:string,init:RequestInit,timeoutMs=REQUEST_TIMEOUT_MS){const controller=new AbortController(),timer=window.setTimeout(()=>controller.abort(),timeoutMs);try{const r=await fetch(url,{...init,signal:controller.signal});const raw=await r.text();let x:any={ok:false,error:'invalid_response'};if(raw){try{x=JSON.parse(raw)}catch{x={ok:false,error:r.ok?'invalid_response':raw.slice(0,180)}}}if(!r.ok||x?.ok===false)throw requestError(r.status,x);return x}catch(e:any){if(e?.name==='AbortError')throw new Error('Connection timed out. Please try again.');if(e instanceof TypeError)throw new Error('Network connection failed. Please try again.');throw e}finally{window.clearTimeout(timer)}}
function isTransientBootstrapError(e:any){return /reconnecting|temporary server|network connection|timed out/i.test(String(e?.message||e||''))}
function sanitizeAdminSettings(input:any){if(!input||typeof input!=='object'||Array.isArray(input))return {};const blocked=new Set(['id','updated_at','telegram_webhook_secret','notification_cron_secret','adsgram_reward_secret_hash','bot_webhook_synced_at','payout_last_config_check_at','payout_low_balance_last_alert_at','payout_last_alert_reason','treasury_last_scan_block','sponsored_min_reward','sponsored_max_reward']);const out:any={};for(const [k,v]of Object.entries(input))if(!blocked.has(k)&&v!==undefined)out[k]=v;return out}
export function hapticImpact(style:'light'|'medium'|'heavy'|'rigid'|'soft'='light'){try{(window.Telegram?.WebApp as any)?.HapticFeedback?.impactOccurred?.(style)}catch{}}
export function hapticSelection(){try{(window.Telegram?.WebApp as any)?.HapticFeedback?.selectionChanged?.()}catch{}}
export function hapticNotify(type:'success'|'warning'|'error'){try{(window.Telegram?.WebApp as any)?.HapticFeedback?.notificationOccurred?.(type)}catch{}}
export const date=(v:string)=>v?new Date(v).toLocaleString():'';export const token=()=> 'WIENER';
export function cleanUserText(v:any){return String(v||'').replace(/\bFarming\b/gi,'WIENER').replace(/\bFarm\b/gi,'WIENER').replace(/\bFARM\b/g,'WIENER')}
export function getInitData(){return window.Telegram?.WebApp?.initData||''}
export async function buildTonTransfer(amount:string|number,memo:string){const {Buffer}=await import('buffer');const g=globalThis as any;if(!g.Buffer)g.Buffer=Buffer;const {beginCell,toNano}=await import('@ton/core');const nano=toNano(String(amount));const boc=beginCell().storeUint(0,32).storeStringTail(String(memo||'')).endCell().toBoc();return {amount:nano.toString(),payload:Buffer.from(boc).toString('base64')}}
export function pageFromUrl():Tab{const qs=new URLSearchParams(window.location.search),tg=window.Telegram?.WebApp as any,p=qs.get('page')||qs.get('tgWebAppStartParam')||String(tg?.initDataUnsafe?.start_param||'');const map:Record<string,Tab>={home:'home',tasks:'tasks',referral:'invite',invite:'invite',leaderboard:'leaderboard',daily:'daily',claim:'claim',profile:'profile',wallet:'wallet',ads:'ads',games:'games',play:'games',earn:'games',ambassador:'ambassador'};return map[p]||'home'}
function persistentId(key:string){try{let id=localStorage.getItem(key);if(!id){id=crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(key,id)}return id}catch{return `volatile-${navigator.userAgent.length}-${screen.width}x${screen.height}`}}
function getDeviceId(){return persistentId('wiener_device_id_v1')}function getInstallationId(){return persistentId('wiener_installation_id_v2')}
async function sha256(raw:string){try{const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw));return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('')}catch{return raw.slice(0,128)}}
async function getDeviceFingerprint(){const raw=[navigator.userAgent,navigator.language,(navigator as any).platform||'',String((navigator as any).hardwareConcurrency||''),String((navigator as any).deviceMemory||''),String((navigator as any).maxTouchPoints||''),Intl.DateTimeFormat().resolvedOptions().timeZone||'',`${screen.width}x${screen.height}`].join('|');return sha256(raw)}
async function getDeviceFingerprintV2(){const tg=window.Telegram?.WebApp as any;const raw=['v2',navigator.userAgent,navigator.language,(navigator as any).platform||'',String((navigator as any).hardwareConcurrency||''),String((navigator as any).deviceMemory||''),String((navigator as any).maxTouchPoints||''),Intl.DateTimeFormat().resolvedOptions().timeZone||'',`${screen.width}x${screen.height}`,String(window.devicePixelRatio||1),tg?.platform||''].join('|');return sha256(raw)}
export async function deviceContext(){const tg=window.Telegram?.WebApp as any;return {device_id:getDeviceId(),installation_id:getInstallationId(),device_fingerprint:await getDeviceFingerprint(),fingerprint_v2:await getDeviceFingerprintV2(),telegram_platform:String(tg?.platform||'').slice(0,32),language:String(navigator.language||'').slice(0,32),timezone:String(Intl.DateTimeFormat().resolvedOptions().timeZone||'').slice(0,64)}}
async function post(url:string,action:string,body:any={}){const x=await fetchJson(url,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUBLISHABLE_KEY,'cache-control':'no-cache'},cache:'no-store',body:JSON.stringify({action,initData:getInitData(),...body})});return normalizeUiNumbers(x.data??x)}
export async function registerDevice(){const ctx=await deviceContext();const x=await fetchJson(DEVICE_API,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUBLISHABLE_KEY},cache:'no-store',body:JSON.stringify({initData:getInitData(),...ctx})});return normalizeUiNumbers(x.data??x)}
export async function api(action:string,body:any={}){const adminAction=action.startsWith('admin_')&&action!=='admin_bootstrap';const url=action==='task_claim'?TASK_API:adminAction?ADMIN_API:API;const mapped=action==='task_claim'?'claim':action;const safeBody=action==='admin_settings_save'?{...body,settings:sanitizeAdminSettings(body?.settings)}:body;let data:any;try{data=await post(url,mapped,safeBody)}catch(e){if(action!=='bootstrap'||!isTransientBootstrapError(e))throw e;await sleep(550);data=await post(url,mapped,safeBody)}if(action==='bootstrap'){try{const st=await post(AD_USAGE_API,'status');if(data?.user){data.user.ads_watched_today=Number(st?.used||0);data.user.ads_day=new Date().toISOString().slice(0,10)}if(data?.settings&&st?.limit!=null)data.settings.daily_ad_limit=Number(st.limit)}catch{}}return data}
export async function promoChannelApi(body:{code:string;channels?:string[]}){return post(PROMO_CHANNEL_API,'publish',body)}export async function taskApi(action:'check'|'claim',body:any={}){return post(TASK_API,action,body)}export async function adApi(action:'start'|'complete'|'status',body:any={}){return post(AD_API,action,body)}export async function adUsageApi(){return post(AD_USAGE_API,'status')}export async function secondaryAdApi(action:'stats'|'start'|'reward',body:any={}){return post(SECONDARY_AD_API,action,body)}export async function adsgramTaskApi(action:'start'|'reward'|'status',body:any={}){return post(ADSGRAM_TASK_API,action,body)}export async function mandatoryApi(action:'check'|'admin_get'|'admin_save'|'admin_delete',body:any={}){return post(MANDATORY_API,action,body)}export async function withdrawApi(action:'methods'|'history'|'request'|'admin_boot'|'admin_method_save'|'admin_paid'|'admin_reject',body:any={}){return post(WITHDRAW_API,action,body)}export async function shareApi(){return post(SHARE_API,'prepare')}export async function missionApi(action:'status'|'claim',body:any={}){return post(MISSION_API,action,body)}
export async function ambassadorApi(action:string,body:any={}){if(action==='admin_publish_drop'){const url=`${AMBASSADOR_PUBLISH_API}?v=one-code-20260901`;const x=await fetchJson(url,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUBLISHABLE_KEY,'cache-control':'no-cache'},cache:'no-store',body:JSON.stringify({action:'publish',initData:getInitData(),...body})},120000);return normalizeUiNumbers(x.data??x)}return post(AMBASSADOR_API,action,body)}
