import {useEffect,useState} from 'react';
import {api,cleanUserText,date,money,type Snapshot} from './lib';
import {AnimatedIcon} from './icons';

const today=()=>new Date().toISOString().slice(0,10);
function nextDaily(data:Snapshot){const u=data.user,s=data.settings,done=u.last_daily_claim_date===today(),streak=Math.max(1,Math.min(7,Number(u.daily_streak||0)+(done?0:1))),reward=Number(s.daily_rewards?.[streak-1]||0);return {done,streak,reward}}
function readyInfo(data:Snapshot){const s=data.settings,u=data.user,last=u.last_farm_claim_at?new Date(u.last_farm_claim_at).getTime():0,next=last+Number(s.farm_claim_cooldown_seconds||0)*1000;return {ready:!last||Date.now()>=next,next}}

export function Home({data,run,setTab}:{data:Snapshot;run:any;setTab:any}){
  const s=data.settings,u=data.user,[promo,setPromo]=useState(''),{ready,next}=readyInfo(data),usd=Number(u.balance)/Number(s.token_per_usdt||10000);
  return <>
    <section className="hero card glow"><div className="eyebrow">TOTAL BALANCE</div><div className="hero-balance"><span className="coin">W</span><strong>{money(u.balance)}</strong><b>WIENER</b></div><div className="muted">≈ {usd.toFixed(4)} USDT</div><div className="stats"><div><b>{u.farm_sessions}</b><span>Sessions</span></div><div><b>{u.total_ads}</b><span>Ads</span></div><div><b>{u.referrals_count}</b><span>Referrals</span></div></div><button className="primary button-with-icon" disabled={!ready} onClick={()=>run('farm_claim',{},`+${s.farm_claim_reward} WIENER claimed`)}><AnimatedIcon name="bolt" active={ready}/>{ready?`CLAIM ${s.farm_claim_reward} WIENER`:'WIENER IS GROWING'}</button>{!ready&&<Countdown to={next}/>}</section>
    <DailyCard data={data} run={run}/>
    <section className="card promo"><div className="section-head"><div className="square mint"><AnimatedIcon name="ticket" active/></div><div><h3>Promo Code</h3><p>Redeem a code for WIENER</p></div></div><div className="promo-row"><input placeholder="ENTER CODE" value={promo} onChange={e=>setPromo(e.target.value.toUpperCase())}/><button className="primary small" onClick={()=>promo&&run('promo_claim',{code:promo},'Promo claimed')}>APPLY</button></div></section>
    <div className="quick-grid"><button className="quick" onClick={()=>setTab('tasks')}><i className="icon-wrap"><AnimatedIcon name="tasks" active/></i><b>Tasks</b><span>View all</span></button><button className="quick" onClick={()=>setTab('invite')}><i className="icon-wrap"><AnimatedIcon name="invite" active/></i><b>Invite</b><span>+{s.referral_active_reward} qualified</span></button><button className="quick" onClick={()=>setTab('ads')}><i className="icon-wrap"><AnimatedIcon name="ads" active/></i><b>Watch Ads</b><span>+{s.ad_reward} WIENER</span></button></div>
  </>
}
function Countdown({to}:{to:number}){const [n,setN]=useState(Math.max(0,to-Date.now()));useEffect(()=>{const x=setInterval(()=>setN(Math.max(0,to-Date.now())),1000);return()=>clearInterval(x)},[to]);const sec=Math.ceil(n/1000),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return <div className="countdown">Ready in {String(h).padStart(2,'0')}:{String(m).padStart(2,'0')}:{String(s).padStart(2,'0')}</div>}
function DailyCard({data,run}:{data:Snapshot;run:any}){const u=data.user,{done,streak,reward}=nextDaily(data);return <section className="card daily"><div className="section-head"><div className="square gift"><AnimatedIcon name="gift" active={!done}/></div><div><h3>Daily Bonus</h3><p>Streak · Day {u.daily_streak||0} of 7</p></div><span className="reward-chip">+{reward} WIENER</span></div><div className="days">{[1,2,3,4,5,6,7].map(d=><div key={d} className={(d===streak&&!done)?'day current':d<=Number(u.daily_streak||0)?'day done':'day'}><b>{d}</b><small>D{d}</small>{d===7&&<em>×2</em>}</div>)}</div><button className="primary" disabled={done} onClick={()=>run('daily_claim',{},'Daily WIENER claimed')}>{done?'CLAIMED TODAY':`CLAIM ${reward} WIENER`}</button></section>}

export function DailyPage({data,run}:{data:Snapshot;run:any}){return <><div className="page-title"><h2>DAILY WIENER</h2></div><DailyCard data={data} run={run}/><div className="info-box">🔥 Best streak: {data.user.best_streak||data.user.daily_streak||0} days. Claim every day to keep it active.</div></>}
export function ClaimPage({data,run}:{data:Snapshot;run:any}){const s=data.settings,{ready,next}=readyInfo(data);return <><div className="page-title"><h2>WIENER READY</h2></div><section className="hero card glow"><div className="square claim-icon"><AnimatedIcon name="bolt" active={ready}/></div><h2>{ready?'Your WIENER is ready':'Your next WIENER is growing'}</h2><p className="muted">Ready to claim: +{s.farm_claim_reward} WIENER</p><button className="primary button-with-icon" disabled={!ready} onClick={()=>run('farm_claim',{},`+${s.farm_claim_reward} WIENER claimed`)}><AnimatedIcon name="gift" active={ready}/>CLAIM WIENER</button>{!ready&&<Countdown to={next}/>}</section></>}

export function Ads({data,refresh,say}:{data:Snapshot;refresh:any;say:any}){const [busy,setBusy]=useState(false),[session,setSession]=useState('');const s=data.settings,u=data.user,used=u.ads_day===today()?Number(u.ads_watched_today):0;
  const watch=async()=>{if(!s.adsgram_block_id){say('Add AdsGram Block ID in Admin Settings');return}try{setBusy(true);const x=await api('ad_start');setSession(x.session_id);const c=window.Adsgram?.init({blockId:String(s.adsgram_block_id)});if(!c)throw Error('AdsGram SDK unavailable');await c.show();say('Ad completed — verifying reward…');for(let i=0;i<12;i++){await new Promise(r=>setTimeout(r,1500));const st=await api('ad_status',{session_id:x.session_id});if(st?.status==='credited'){say(`+${st.reward||s.ad_reward} WIENER`);await refresh();break}}}catch(e:any){say(e.message)}finally{setBusy(false)}};
  return <><div className="page-title"><h2>ADS TASK <span>{used}/{s.daily_ad_limit}</span></h2></div><section className="card ad-card"><div className="square play"><AnimatedIcon name="ads" active={!busy&&used<s.daily_ad_limit}/></div><div className="grow"><h3>AdsGram — {s.daily_ad_limit} ads</h3><p>+{s.ad_reward} WIENER each · {used}/{s.daily_ad_limit} today</p></div><button className="primary small" disabled={busy||used>=s.daily_ad_limit} onClick={watch}>{busy?'WAIT':'WATCH'}</button></section><div className="info-box">ⓘ Rewards are credited only after server verification confirms the completed ad.</div>{session&&<div className="tiny center">Verification session: {session.slice(0,8)}…</div>}</>}

export function Tasks({data,run}:{data:Snapshot;run:any}){
  const targetId=new URLSearchParams(window.location.search).get('task'),target=data.tasks.find(t=>t.id===targetId),[cat,setCat]=useState(target?.category||'official'),done=new Set(data.completed.map(x=>x.task_id)),items=data.tasks.filter(t=>t.category===cat),count=data.completed.length;
  useEffect(()=>{if(target){setCat(target.category);setTimeout(()=>document.getElementById(`task-${target.id}`)?.scrollIntoView({behavior:'smooth',block:'center'}),120)}},[targetId]);
  return <><section className="card progress-card"><div className="section-head"><div className="square check"><AnimatedIcon name="tasks" active/></div><div><h3>Your Progress</h3><p>{count} current tasks completed</p></div></div><div className="progress"><span style={{width:`${data.tasks.length?Math.min(100,count/data.tasks.length*100):0}%`}}/></div></section><div className="tabs">{['official','exclusive','partner'].map(x=><button className={cat===x?'active':''} onClick={()=>setCat(x)} key={x}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div><section className="card task-list">{items.length?items.map(t=><div className={`task ${targetId===t.id?'target-task':''}`} id={`task-${t.id}`} key={t.id}><div className="square check"><AnimatedIcon name="check" active={done.has(t.id)}/></div><div className="grow"><h3>{t.title}{t.is_daily&&<span className="tag">DAILY</span>}</h3><p>+{t.reward} WIENER · {t.description||t.category}{t.expires_at?` · Ends ${date(t.expires_at)}`:''}</p></div><button className="primary small" disabled={done.has(t.id)} onClick={()=>{if(t.url)window.Telegram?.WebApp?.openLink?.(t.url);setTimeout(()=>run('task_claim',{task_id:t.id},`+${t.reward} WIENER`),800)}}>{done.has(t.id)?'DONE':'JOIN'}</button></div>):<div className="empty">No {cat} tasks right now.</div>}</section></>}

export function Invite({data,say}:{data:Snapshot;say:any}){const s=data.settings,u=data.user,link=`https://t.me/${String(s.bot_username||'@WienerDogeFarmBot').replace('@','')}?startapp=ref_${u.telegram_id}`;const share=()=>window.Telegram?.WebApp?.openTelegramLink?.(`https://t.me/share/url?url=${encodeURIComponent(link)}&text=${encodeURIComponent('Join WIENER and earn rewards with me!')}`);return <><section className="card invite-hero"><div className="invite-icon"><AnimatedIcon name="invite" active/></div><h2>Invite Friends</h2><p>Invite friends to WIENER and earn <b>{s.referral_active_reward} WIENER</b> when they qualify after {s.referral_active_ads_required} verified ads.</p><div className="stats bigstats"><div><b>{u.referrals_count}</b><span>INVITED</span></div><div><b>{u.active_referrals_count}</b><span>QUALIFIED</span></div><div><b>{money(u.referral_earnings)}</b><span>EARNED</span></div></div></section><h4 className="eyebrow outside">YOUR INVITE LINK</h4><section className="card"><div className="link-row"><input readOnly value={link}/><button onClick={async()=>{await navigator.clipboard.writeText(link);say('Invite link copied')}}>▢</button></div><button className="primary button-with-icon" onClick={share}><AnimatedIcon name="share" active/>SHARE INVITE</button></section><div className="reward-grid"><div><i className="icon-wrap"><AnimatedIcon name="invite" active/></i><b>{u.referrals_count}</b><span>Invited</span></div><div><i className="icon-wrap"><AnimatedIcon name="check" active/></i><b>{u.active_referrals_count}</b><span>Qualified</span></div><div><i className="icon-wrap"><AnimatedIcon name="coins" active/></i><b>+{s.referral_active_reward}</b><span>Per qualified</span></div></div>{data.referrals.length>0&&<section className="card"><h3>Recent referrals</h3>{data.referrals.slice(0,8).map(r=><div className="refrow" key={r.telegram_id}><span>{r.first_name||r.username||r.telegram_id}</span><b>{r.referral_active?'QUALIFIED':`${r.total_ads}/${s.referral_active_ads_required} ads`}</b></div>)}</section>}</>}

export function LeaderboardPage({data}:{data:Snapshot}){const rows=data.leaderboard||[],medals=['🥇','🥈','🥉'];return <><div className="page-title"><h2>WIENER LEADERBOARD</h2></div><section className="card leaderboard-card"><div className="rank-me">Your Rank <b>#{data.rank||'-'}</b></div>{rows.length?rows.map((u:any,i:number)=><div className="leader-row" key={u.telegram_id}><span className="leader-pos">{medals[i]||`${i+1}.`}</span><div className="grow"><b>{u.first_name||u.username||`User ${String(u.telegram_id).slice(-4)}`}</b><small>Total earned</small></div><strong>{money(u.total_earned)} WIENER</strong></div>):<div className="empty">No rankings yet.</div>}</section></>}

export function ProfilePage({data,setTab}:{data:Snapshot;setTab:any}){const u=data.user;return <><div className="page-title"><h2>WIENER PROFILE</h2></div><section className="card profile-card"><div className="profile-avatar">{u.photo_url?<img src={u.photo_url}/>:String(u.first_name||'W')[0]}</div><h2>{u.first_name||u.username||'WIENER User'}</h2><div className="profile-grid"><div><span>Balance</span><b>{money(u.balance)} WIENER</b></div><div><span>Streak</span><b>{u.daily_streak||0} days</b></div><div><span>Best Streak</span><b>{u.best_streak||u.daily_streak||0} days</b></div><div><span>Referrals</span><b>{u.referrals_count||0}</b></div><div><span>Qualified</span><b>{u.active_referrals_count||0}</b></div><div><span>Tasks</span><b>{data.tasks_completed_total??data.completed.length}</b></div><div><span>Rank</span><b>#{data.rank||'-'}</b></div><div><span>Total Earned</span><b>{money(u.total_earned)} WIENER</b></div></div><button className="primary" onClick={()=>setTab('wallet')}>OPEN WALLET</button></section></>}

export function Wallet({data,run,setTab}:{data:Snapshot;run:any;setTab:any}){const s=data.settings,u=data.user,[wallet,setWallet]=useState(''),[amount,setAmount]=useState(''),[owner,setOwner]=useState('');const usd=Number(u.balance)/Number(s.token_per_usdt),gross=Number(amount||0)/Number(s.token_per_usdt),receive=Math.max(0,gross-Number(s.withdraw_fee_usdt));return <><section className="hero card"><div className="eyebrow">AVAILABLE TO WITHDRAW</div><div className="hero-balance"><span className="coin">W</span><strong>{money(u.balance)}</strong><b>WIENER</b></div><div className="muted">≈ {usd.toFixed(4)} USDT</div><div className="tiny">{money(s.token_per_usdt)} WIENER = 1 USDT</div></section><section className="card withdraw"><div className="section-head"><div className="square blue"><AnimatedIcon name="download" active/></div><div><h3>Withdraw</h3><p>{s.withdraw_asset_label}</p></div></div><label>YOUR WALLET ADDRESS</label><input placeholder="UQ… / EQ…" value={wallet} onChange={e=>setWallet(e.target.value)}/><label>AMOUNT</label><div className="amount-row"><input type="number" placeholder={`min ${s.minimum_withdraw}`} value={amount} onChange={e=>setAmount(e.target.value)}/><button onClick={()=>setAmount(String(u.balance))}>MAX</button></div><div className="receive">You receive ≈ <b>{receive.toFixed(4)}</b> USDT</div><div className="fee">Network fee <b>{s.withdraw_fee_usdt} USDT</b> · deducted from payout</div><button className="primary button-with-icon" disabled={!s.withdrawals_enabled} onClick={()=>run('withdraw_request',{amount:Number(amount),wallet},'Withdrawal requested')}><AnimatedIcon name="wallet" active={s.withdrawals_enabled}/>REQUEST WITHDRAWAL</button><div className="tiny center">One withdrawal every {s.withdraw_cooldown_hours}h</div></section><h4 className="eyebrow outside">TRANSACTION HISTORY</h4><section className="card history">{data.transactions.length?data.transactions.map(x=><div className="tx" key={x.id}><div className={Number(x.amount)>=0?'arrow up':'arrow down'}><AnimatedIcon name={Number(x.amount)>=0?'arrowUp':'arrowDown'} active/></div><div className="grow"><h3>{cleanUserText(x.description)}</h3><p>{date(x.created_at)}</p></div><b className={Number(x.amount)>=0?'plus':'minus'}>{Number(x.amount)>=0?'+':''}{money(x.amount)} WIENER</b></div>):<div className="empty">No transactions yet.</div>}</section>{!data.is_admin&&<section className="owner-setup"><details><summary>Owner setup</summary><p>Use the one-time bootstrap code to claim the first owner account.</p><div className="promo-row"><input placeholder="BOOTSTRAP CODE" value={owner} onChange={e=>setOwner(e.target.value)}/><button className="primary small" onClick={async()=>{try{await api('admin_bootstrap',{code:owner});await run('bootstrap',{},'Owner access enabled');setTab('admin')}catch{}}}>ACTIVATE</button></div></details></section>}</>}
