import {useCallback,useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {feedback,quickTaskApi} from './lib';

type QType='website'|'ad_provider'|'comment';
type QStatus='AVAILABLE'|'STARTED'|'VERIFYING'|'VERIFIED'|'CLAIMED'|'FAILED'|'EXPIRED';
type QTask={id:string;type:QType;title:string;description?:string;reward:number;targetUrl?:string|null;targetGroup?:string|null;verificationDuration?:number;status?:QStatus};
type Attempt={attemptId:string;taskId:string;status:QStatus;generatedComment?:string|null;targetGroup?:string|null;verificationDuration?:number};

const icon=(t:QType)=>t==='comment'?'💬':t==='ad_provider'?'📺':'🌐';
const card:CSSProperties={border:'1px solid rgba(108,235,170,.13)',background:'linear-gradient(145deg,rgba(13,54,37,.68),rgba(5,24,18,.88))',borderRadius:18,padding:12};
const btn:React.CSSProperties={border:0,borderRadius:11,padding:'10px 12px',background:'linear-gradient(135deg,#62e69d,#9de56d)',color:'#052016',fontSize:9,fontWeight:900,letterSpacing:'.05em'};

function openExternal(url:string){try{const tg:any=window.Telegram?.WebApp;const tgUrl=/^(https?:\/\/)?(www\.)?(t\.me|telegram\.me)\//i.test(url);if(tgUrl&&tg?.openTelegramLink){tg.openTelegramLink(url);return true}if(tg?.openLink){tg.openLink(url);return true}window.open(url,'_blank','noopener,noreferrer');return true}catch{return false}}
function normalize(x:any):QTask[]{const rows=Array.isArray(x?.tasks)?x.tasks:Array.isArray(x)?x:[];return rows.map((t:any)=>({id:String(t.id||t.taskId||''),type:(t.type||t.task_type||'website') as QType,title:String(t.title||'Quick Task'),description:String(t.description||''),reward:Number(t.reward||0),targetUrl:t.targetUrl??t.target_url??t.url??null,targetGroup:t.targetGroup??t.target_group??t.telegram_chat_id??null,verificationDuration:Number(t.verificationDuration??t.verification_duration??0),status:t.status})).filter((t:QTask)=>t.id&&t.reward>0)}

export function QuickTasks({say,refreshApp}:{say?:(s:string)=>void;refreshApp?:()=>Promise<any>}){
 const [tasks,setTasks]=useState<QTask[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[attempt,setAttempt]=useState<Attempt|null>(null),[note,setNote]=useState(''),[copied,setCopied]=useState(false);
 const hiddenAt=useRef<number|null>(null),elapsed=useRef(0);
 const load=useCallback(async()=>{try{const x=await quickTaskApi('list');setTasks(normalize(x));setNote('')}catch(e:any){setNote(String(e?.message||'Could not load Quick Tasks.'))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const t=window.setInterval(()=>{if(!attempt)void load()},15000);return()=>window.clearInterval(t)},[attempt,load]);
 const selected=useMemo(()=>attempt?tasks.find(x=>x.id===attempt.taskId):null,[attempt,tasks]),duration=Number(attempt?.verificationDuration||selected?.verificationDuration||0);
 const verify=useCallback(async()=>{if(!attempt||busy)return;try{const x:any=await quickTaskApi('verify',{attemptId:attempt.attemptId,elapsedMs:elapsed.current,visibilitySatisfied:elapsed.current>=duration*1000});const a=x?.attempt||x,s=String(a?.status||x?.status||'VERIFYING') as QStatus;setAttempt(v=>v?({...v,...a,status:s}):v);if(s==='VERIFIED'){feedback('success');say?.('✅ Task verified')}else if(s==='FAILED'||s==='EXPIRED'){feedback('error');say?.('⚠️ Task could not be verified')}}catch(e:any){setNote(String(e?.message||'Verification is still running.').replace(/_/g,' '))}},[attempt,busy,duration,say]);
 useEffect(()=>{const f=()=>{if(document.visibilityState==='hidden'&&!hiddenAt.current)hiddenAt.current=Date.now();if(document.visibilityState==='visible'&&hiddenAt.current){elapsed.current+=Date.now()-hiddenAt.current;hiddenAt.current=null;void verify()}};document.addEventListener('visibilitychange',f);return()=>document.removeEventListener('visibilitychange',f)},[verify]);
 useEffect(()=>{if(!attempt||['VERIFIED','FAILED','EXPIRED','CLAIMED'].includes(attempt.status))return;const t=window.setInterval(()=>void verify(),3000);return()=>window.clearInterval(t)},[attempt,verify]);
 const start=async(t:QTask)=>{if(busy)return;setBusy(t.id);setNote('');elapsed.current=0;hiddenAt.current=null;setCopied(false);try{const x:any=await quickTaskApi('start',{taskId:t.id}),a=x?.attempt||x,id=String(a?.attemptId||a?.attempt_id||'');if(!id)throw Error('Task attempt could not be created.');setAttempt({attemptId:id,taskId:t.id,status:(a?.status||'STARTED') as QStatus,generatedComment:a?.generatedComment??a?.generated_comment??null,targetGroup:a?.targetGroup??a?.target_group??t.targetGroup??null,verificationDuration:Number(a?.verificationDuration??a?.verification_duration??t.verificationDuration||0)});say?.('⚡ Task started');feedback('confirm');if(t.type!=='comment'){if(!t.targetUrl)throw Error('Task destination is not configured.');if(!openExternal(String(t.targetUrl)))throw Error('Could not open the task.')}}catch(e:any){feedback('error');setNote(String(e?.message||'Could not start task.').replace(/_/g,' '))}finally{setBusy('')}};
 const copy=async()=>{if(!attempt?.generatedComment)return;try{await navigator.clipboard.writeText(attempt.generatedComment);setCopied(true);feedback('success');say?.('Message copied')}catch{feedback('error');setNote('Copy failed. Please try again.')}};
 const group=()=>{if(!attempt?.targetGroup)return;const g=String(attempt.targetGroup),u=/^https?:\/\//i.test(g)?g:(g.startsWith('@')?'https://t.me/'+g.slice(1):'https://t.me/'+g);if(!openExternal(u))setNote('Could not open the Telegram group.');else feedback('confirm')};
 const claim=async()=>{if(!attempt||attempt.status!=='VERIFIED'||busy)return;setBusy('claim');try{const x:any=await quickTaskApi('claim',{attemptId:attempt.attemptId});if(x?.claimed!==true&&String(x?.status||x?.attempt?.status||'CLAIMED')!=='CLAIMED')throw Error(x?.message||'Reward is not claimable yet.');feedback('success');say?.('+'+Number(x?.reward??selected?.reward??0)+' WIENER received');setAttempt(null);await refreshApp?.();await load()}catch(e:any){feedback('error');setNote(String(e?.message||'Reward could not be claimed.').replace(/_/g,' '))}finally{setBusy('')}};
 if(attempt){const t=selected,verified=attempt.status==='VERIFIED',failed=attempt.status==='FAILED'||attempt.status==='EXPIRED';return <section style={{...card,marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:10}}><div><small style={{color:'#7de7b0',fontWeight:900}}>⚡ QUICK TASK</small><h3 style={{margin:'3px 0'}}>{t?.title||'Quick Task'}</h3></div><button style={{...btn,padding:'7px 11px'}} onClick={()=>{feedback('tap');setAttempt(null)}}>×</button></div>{t?.type==='comment'&&attempt.generatedComment?<><small style={{opacity:.55}}>💬 COMMUNITY TASK · Post this message in the group:</small><div style={{marginTop:9,padding:12,borderRadius:13,background:'rgba(0,0,0,.18)',fontSize:13,lineHeight:1.45}}>{attempt.generatedComment}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7,marginTop:9}}><button style={{...btn,background:'rgba(255,255,255,.06)',color:'#e7fff3'}} onClick={copy}>📋 {copied?'COPIED':'COPY MESSAGE'}</button><button style={{...btn,background:'rgba(255,255,255,.06)',color:'#e7fff3'}} onClick={group}>↗ OPEN GROUP</button></div></>:<div style={{textAlign:'center',padding:12}}><div style={{fontSize:34}}>{icon(t?.type||'website')}</div><p style={{opacity:.55,fontSize:11}}>{failed?'The required condition was not satisfied.':verified?'Verification successful.':'Complete the task and return here.'}</p>{!verified&&!failed&&duration>0&&<><div style={{height:6,borderRadius:99,background:'rgba(255,255,255,.06)',overflow:'hidden'}}><div style={{height:'100%',width:Math.min(100,Math.round(elapsed.current/(duration*1000)*100))+'%',background:'#7de7b0'}}/></div><small style={{opacity:.45}}>Verifying…</small></>}</div>}{verified&&<div style={{marginTop:10,padding:9,borderRadius:11,background:'rgba(91,231,158,.08)',color:'#9df0c1',fontSize:10}}>✅ {t?.type==='comment'?'Message verified':'Task verified'}</div>}{!verified&&!failed&&t?.type==='comment'&&<div style={{marginTop:10,padding:9,borderRadius:11,background:'rgba(255,255,255,.035)',fontSize:10,opacity:.6}}>⌛ Waiting for verification…</div>}{note&&<div style={{marginTop:9,fontSize:10,color:'#ffd58f'}}>⚠ {note}</div>}<div style={{display:'flex',alignItems:'center',marginTop:12}}>{verified&&<><b style={{marginRight:'auto',color:'#b8f27e'}}>+{t?.reward||0} WIENER</b><button style={btn} disabled={busy==='claim'} onClick={claim}>{busy==='claim'?'CLAIMING…':'CLAIM'}</button></>}{failed&&<button style={{...btn,marginLeft:'auto'}} onClick={()=>{setAttempt(null);void load()}}>RETRY</button>}</div></section>}
 return <section style={{marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginBottom:9}}><div><small style={{color:'#7de7b0',fontWeight:900,letterSpacing:'.1em'}}>⚡ QUICK TASKS</small><h2 style={{fontSize:18,margin:'3px 0'}}>Earn with quick tasks</h2></div><button style={{...btn,padding:'8px 11px'}} onClick={()=>{feedback('tap');void load()}}>↻</button></div>{loading?<div style={{...card,textAlign:'center',padding:28}}>⚡<div style={{fontSize:10,opacity:.55,marginTop:7}}>Loading quick tasks…</div></div>:tasks.length?<div style={{display:'grid',gap:8}}>{tasks.map(t=><article key={t.id} style={{...card,display:'grid',gridTemplateColumns:'40px 1fr auto',gap:10,alignItems:'center'}}><div style={{width:40,height:40,borderRadius:13,display:'grid',placeItems:'center',background:'rgba(91,231,158,.08)',fontSize:19}}>{icon(t.type)}</div><div><b style={{fontSize:13}}>{t.title}</b><p style={{margin:'3px 0 7px',fontSize:10,opacity:.52,lineHeight:1.35}}>{t.description||'Complete this quick task to earn WIENER.'}</p><strong style={{fontSize:10,color:'#b8f27e'}}>+{t.reward} WIENER</strong></div><button style={btn} disabled={busy===t.id} onClick={()=>void start(t)}>{busy===t.id?'…':'DO TASK'}</button></article>)}</div>:<div style={{...card,textAlign:'center',padding:'28px 16px',background:'rgba(255,255,255,.025)'}}><div style={{fontSize:26}}>⚡</div><h3 style={{fontSize:14,margin:'7px 0 4px'}}>No new tasks right now</h3><p style={{fontSize:10,opacity:.45,lineHeight:1.5,margin:0}}>New quick tasks appear automatically.<br/>Check again later.</p></div>}{!loading&&!tasks.length&&note&&<div style={{marginTop:8,fontSize:10,color:'#ffd58f'}}>⚠ {note}</div>}</section>
}