import {useEffect,useState} from 'react';
import {getInitData,money,PUBLISHABLE_KEY,SUPABASE_URL} from './lib';
import {AnimatedIcon} from './icons';

const RAPI=`${SUPABASE_URL}/functions/v1/wiener-raffle-api`;
async function raffleApi(action='snapshot',body:any={}){const r=await fetch(RAPI,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUBLISHABLE_KEY},body:JSON.stringify({action,initData:getInitData(),...body})});const x=await r.json();if(!r.ok||!x.ok)throw Error(x.error||'Raffle request failed');return x.data}
function useRaffle(){const [r,setR]=useState<any>(null),[err,setErr]=useState('');const load=async()=>{try{setR(await raffleApi())}catch(e:any){setErr(e.message)}};useEffect(()=>{load()},[]);return {r,err,load}}
const when=(v:any)=>v?new Date(v).toLocaleString(undefined,{weekday:'short',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}):'-';

export function HomeRaffleCard({setTab}:{setTab:any}){const {r}=useRaffle();if(!r?.enabled)return null;return <section className="card"><div className="section-head"><div className="square mint"><AnimatedIcon name="ticket" active/></div><div className="grow"><h3>Weekly Raffle</h3><p>Your Tickets: {r.tickets} · Next Draw: {when(r.ends_at)}</p></div></div><button className="primary small" onClick={()=>setTab('raffle')}>🏆 VIEW RAFFLE</button></section>}

export function ReferralRaffleCard({setTab}:{setTab:any}){const {r}=useRaffle();if(!r?.enabled)return null;return <section className="card"><div className="section-head"><div className="square mint"><AnimatedIcon name="ticket" active/></div><div><h3>🎟 Weekly Referral Raffle</h3><p>Extra entries from referrals, ads and tasks</p></div></div><div className="profile-grid"><div><span>Your Tickets</span><b>{r.tickets}</b></div><div><span>Verified This Week</span><b>{r.weekly_verified}</b></div><div><span>Prize Pool</span><b>{money(r.prize_pool)} WIENER</b></div><div><span>Next Draw</span><b>{when(r.ends_at)}</b></div></div><div className="promo-row"><button className="primary" onClick={()=>setTab('tickets')}>🎟 EARN TICKETS</button><button className="primary" onClick={()=>setTab('raffle')}>🏆 VIEW RAFFLE</button></div></section>}

export function AdsTicketProgress(){const {r}=useRaffle();if(!r?.enabled)return null;return <section className="card"><div className="section-head"><div className="square play"><AnimatedIcon name="ads" active/></div><div><h3>🎟 Raffle Ticket Progress</h3><p>{r.ads_per_ticket} ads = +1 ticket · normal WIENER ad reward stays the same</p></div></div><div className="profile-grid"><div><span>Ads Progress</span><b>{r.ads_progress}/{r.ads_goal}</b></div><div><span>Tickets Today</span><b>{r.ad_tickets_today}/{r.max_ad_tickets}</b></div></div></section>}

export function TasksTicketCard({setTab}:{setTab:any}){const {r}=useRaffle();if(!r?.enabled)return null;return <section className="card"><div className="section-head"><div className="square check"><AnimatedIcon name="tasks" active/></div><div><h3>🎟 Earn Raffle Tickets</h3><p>Complete tasks and unlock weekly ticket milestones.</p></div></div><div className="tiny">{(r.task_milestones||[]).map((m:any)=>`${m.count} Task${m.count===1?'':'s'} → +${m.tickets} Ticket${m.tickets===1?'':'s'}`).join(' · ')}</div><button className="primary small" onClick={()=>setTab('tickets')}>VIEW TICKET MISSIONS</button></section>}

export function EarnTicketsPage({setTab}:{setTab:any}){const {r,err}=useRaffle();if(err)return <div className="info-box">{err}</div>;if(!r)return <div className="loader"/>;return <><div className="page-title"><h2>🎟 EARN MORE TICKETS</h2></div><section className="card"><h3>👥 Invite Friends</h3><p>1 Verified Referral</p><div className="reward-chip">🎟 +{r.tickets_per_verified_referral} Ticket · 💰 normal referral WIENER reward</div><button className="primary" onClick={()=>setTab('invite')}>📤 INVITE FRIENDS</button></section><section className="card"><h3>📺 Watch Ads</h3><p>{r.ads_per_ticket} Ads → 🎟 +1 Ticket</p><div className="profile-grid"><div><span>Progress</span><b>{r.ads_progress}/{r.ads_goal} Ads</b></div><div><span>Daily Tickets</span><b>{r.ad_tickets_today}/{r.max_ad_tickets}</b></div></div><button className="primary" onClick={()=>setTab('ads')}>📺 WATCH ADS</button></section><section className="card"><h3>🎯 Complete Tasks</h3>{(r.task_milestones||[]).map((m:any)=><p key={m.count}>{m.count} Task{m.count===1?'':'s'} → 🎟 +{m.tickets} Ticket{m.tickets===1?'':'s'}</p>)}<p className="muted">Progress: {r.tasks_completed} tasks completed this week</p><button className="primary" onClick={()=>setTab('tasks')}>🎯 VIEW TASKS</button></section><section className="card"><h3>🏆 Referral Achievements</h3>{(r.referral_milestones||[]).map((m:any)=><p key={m.count}>{m.count} Verified Referrals → 🎟 +{m.tickets} Bonus Tickets</p>)}</section></>}

export function RafflePage({setTab}:{setTab:any}){const {r,err}=useRaffle();const [now,setNow]=useState(Date.now());useEffect(()=>{const x=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(x)},[]);if(err)return <div className="info-box">{err}</div>;if(!r)return <div className="loader"/>;const left=Math.max(0,new Date(r.ends_at).getTime()-now),d=Math.floor(left/86400000),h=Math.floor(left%86400000/3600000),m=Math.floor(left%3600000/60000);return <><div className="page-title"><h2>🎟 WEEKLY WIENER RAFFLE</h2></div><section className="hero card glow"><div className="hero-balance"><span className="coin">W</span><strong>{r.tickets}</strong><b>TICKETS</b></div><div className="profile-grid"><div><span>Verified Referrals</span><b>{r.weekly_verified}</b></div><div><span>Draw Ends In</span><b>{d}d {h}h {m}m</b></div><div><span>Prize Pool</span><b>{money(r.prize_pool)} WIENER</b></div><div><span>Status</span><b>{String(r.status).toUpperCase()}</b></div></div><button className="primary" onClick={()=>setTab('tickets')}>🎟 EARN MORE TICKETS</button></section><section className="card"><h3>🏆 Prizes</h3>{(r.prizes||[]).map((p:any,i:number)=><div className="refrow" key={i}><span>{p.count>1?`${p.count} × `:''}{p.position}</span><b>{money(p.prize)} WIENER each</b></div>)}</section><section className="card"><h3>Ticket History</h3>{r.history?.length?r.history.map((x:any,i:number)=><div className="refrow" key={i}><span>🎟 {x.amount>0?'+':''}{x.amount} — {x.reason}<small>{when(x.created_at)}</small></span><b>{x.source.replaceAll('_',' ')}</b></div>):<div className="empty">No raffle tickets yet.</div>}</section><section className="card"><h3>🏆 Previous Winners</h3>{r.previous_winners?.length?r.previous_winners.slice(0,15).map((x:any,i:number)=><div className="refrow" key={i}><span>{x.username}<small>{when(x.draw_date)}</small></span><b>+{money(x.prize)} WIENER</b></div>):<div className="empty">No previous winners yet.</div>}</section></>}

export function RaffleAdmin(){const [d,setD]=useState<any>(null),[msg,setMsg]=useState(''),[uid,setUid]=useState(''),[amount,setAmount]=useState('');const load=async()=>{try{setD(await raffleApi('admin_get'))}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[]);if(!d)return <section className="card"><h3>Tickets & Raffle</h3><p>{msg||'Loading raffle admin…'}</p></section>;const s=d.settings;const save=async(p:any)=>{await raffleApi('admin_save',{settings:{...s,...p}});setMsg('Raffle settings saved');await load()};return <section className="card"><h3>🎟 Tickets & Raffle</h3><div className="admin-grid"><label>Tickets System <input type="checkbox" checked={!!s.tickets_enabled} onChange={e=>save({tickets_enabled:e.target.checked})}/></label><label>Weekly Raffle <input type="checkbox" checked={!!s.raffle_enabled} onChange={e=>save({raffle_enabled:e.target.checked})}/></label><label>Auto Draw <input type="checkbox" checked={!!s.raffle_auto_draw} onChange={e=>save({raffle_auto_draw:e.target.checked})}/></label><label>Auto Credit <input type="checkbox" checked={!!s.raffle_auto_credit} onChange={e=>save({raffle_auto_credit:e.target.checked})}/></label></div><div className="profile-grid"><div><span>Verified Referral</span><b>+{s.raffle_tickets_per_verified_referral} ticket</b></div><div><span>Ads / Ticket</span><b>{s.raffle_ads_per_ticket}</b></div><div><span>Max Ad Tickets</span><b>{s.raffle_max_ad_tickets_per_day}/day</b></div><div><span>Past Draws</span><b>{d.raffles.length}</b></div></div><h4>Manual Ticket Adjustment</h4><div className="promo-row"><input placeholder="Telegram ID" value={uid} onChange={e=>setUid(e.target.value)}/><input placeholder="+/- Tickets" value={amount} onChange={e=>setAmount(e.target.value)}/><button onClick={async()=>{try{await raffleApi('admin_adjust',{telegram_id:Number(uid),amount:Number(amount),reason:'Admin adjustment'});setMsg('Tickets updated');setAmount('');await load()}catch(e:any){setMsg(e.message)}}}>APPLY</button></div><button className="primary small" onClick={async()=>{try{await raffleApi('admin_draw');setMsg('Draw processed');await load()}catch(e:any){setMsg(e.message)}}}>RERUN / PROCESS DUE DRAW</button>{msg&&<div className="info-box">{msg}</div>}<h4>Recent Ticket History</h4>{d.tickets.slice(0,10).map((x:any)=><div className="refrow" key={x.id}><span>{x.telegram_id} · {x.reason}</span><b>{x.amount>0?'+':''}{x.amount}</b></div>)}</section>}
