import {useEffect,useState} from 'react';
import {getInitData,money,PUBLISHABLE_KEY,SUPABASE_URL} from './lib';
import {AnimatedIcon} from './icons';

const RAPI=`${SUPABASE_URL}/functions/v1/wiener-raffle-api`;
async function raffleApi(action='snapshot',body:any={}){const r=await fetch(RAPI,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUBLISHABLE_KEY},body:JSON.stringify({action,initData:getInitData(),...body})});const x=await r.json();if(!r.ok||!x.ok)throw Error(x.error||'Raffle request failed');return x.data}
function useRaffle(){const [r,setR]=useState<any>(null),[err,setErr]=useState('');const load=async()=>{try{setR(await raffleApi())}catch(e:any){setErr(e.message)}};useEffect(()=>{load()},[]);return {r,err,load}}
const when=(v:any)=>v?new Date(v).toLocaleString(undefined,{weekday:'short',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}):'-';
const shortDay=(v:any)=>v?new Date(v).toLocaleDateString(undefined,{weekday:'short'}):'-';

function TicketIcon(){return <div className="raffle-icon"><AnimatedIcon name="ticket" active/></div>}
function Stat({label,value}:{label:string;value:any}){return <div className="raffle-stat"><span>{label}</span><strong>{value}</strong></div>}
function Progress({value,max}:{value:number;max:number}){const p=max?Math.min(100,Math.max(0,value/max*100)):0;return <div className="raffle-progress"><i style={{width:`${p}%`}}/></div>}

export function HomeRaffleCard({setTab}:{setTab:any}){const {r}=useRaffle();if(!r?.enabled)return null;return <section className="card raffle-home-card"><div className="raffle-home-copy"><TicketIcon/><div><span className="raffle-kicker">WEEKLY RAFFLE</span><h3>{r.tickets} Tickets</h3><p>Draw {shortDay(r.ends_at)} · {money(r.prize_pool)} WIENER pool</p></div></div><button className="raffle-arrow" onClick={()=>setTab('raffle')} aria-label="View raffle">›</button></section>}

export function ReferralRaffleCard({setTab}:{setTab:any}){const {r}=useRaffle();if(!r?.enabled)return null;return <section className="card raffle-referral-card"><div className="raffle-topline"><div className="raffle-title-wrap"><TicketIcon/><div><span className="raffle-kicker">WEEKLY REFERRAL RAFFLE</span><h3>Turn referrals into entries</h3></div></div><span className="raffle-live">LIVE</span></div><div className="raffle-ticket-hero"><div><span>Your weekly tickets</span><strong>{r.tickets}</strong></div><div className="raffle-draw"><span>Next draw</span><b>{when(r.ends_at)}</b></div></div><div className="raffle-stats-row"><Stat label="Verified this week" value={r.weekly_verified}/><Stat label="Prize pool" value={`${money(r.prize_pool)} WIENER`}/></div><div className="raffle-actions"><button className="primary" onClick={()=>setTab('tickets')}>EARN TICKETS</button><button className="raffle-secondary" onClick={()=>setTab('raffle')}>VIEW RAFFLE</button></div></section>}

export function AdsTicketProgress(){const {r}=useRaffle();if(!r?.enabled)return null;return <section className="card raffle-inline-card"><div className="raffle-inline-head"><div><span className="raffle-kicker">WEEKLY RAFFLE</span><h3>Ad ticket progress</h3></div><strong>{r.ad_tickets_today}/{r.max_ad_tickets}</strong></div><p>Every {r.ads_per_ticket} verified ads adds 1 raffle ticket. Your normal WIENER ad reward stays unchanged.</p><Progress value={r.ads_progress} max={r.ads_goal}/><div className="raffle-progress-meta"><span>{r.ads_progress}/{r.ads_goal} ads today</span><b>{r.ad_tickets_today} tickets earned</b></div></section>}

export function TasksTicketCard({setTab}:{setTab:any}){const {r}=useRaffle();if(!r?.enabled)return null;const next=(r.task_milestones||[]).find((m:any)=>r.tasks_completed<m.count);return <section className="card raffle-inline-card raffle-task-card"><div className="raffle-inline-head"><div><span className="raffle-kicker">EXTRA ENTRIES</span><h3>Task milestones</h3></div><button className="raffle-text-btn" onClick={()=>setTab('tickets')}>View all</button></div><p>{next?`Complete ${next.count} task${next.count===1?'':'s'} to unlock +${next.tickets} ticket${next.tickets===1?'':'s'}.`:'All task milestones completed this week.'}</p><div className="raffle-milestone-line">{(r.task_milestones||[]).map((m:any)=><span key={m.count} className={r.tasks_completed>=m.count?'done':''}>{m.count}<small>+{m.tickets}</small></span>)}</div></section>}

function Mission({icon,title,desc,reward,progress,action,onClick}:{icon:string;title:string;desc:string;reward:string;progress?:string;action:string;onClick:()=>void}){return <section className="card raffle-mission"><div className="raffle-mission-head"><div className="raffle-mission-icon">{icon}</div><div className="grow"><h3>{title}</h3><p>{desc}</p></div><span className="raffle-reward">{reward}</span></div>{progress&&<div className="raffle-mission-progress">{progress}</div>}<button className="raffle-mission-action" onClick={onClick}>{action}<span>›</span></button></section>}

export function EarnTicketsPage({setTab}:{setTab:any}){const {r,err}=useRaffle();if(err)return <div className="info-box">{err}</div>;if(!r)return <div className="loader"/>;return <><div className="page-title raffle-page-title"><span className="raffle-kicker">WEEKLY MISSIONS</span><h2>Earn Tickets</h2><p>Complete simple actions to increase your chances this week.</p></div><Mission icon="👥" title="Invite Friends" desc="1 verified referral" reward={`+${r.tickets_per_verified_referral} Ticket`} action="INVITE FRIENDS" onClick={()=>setTab('invite')}/><Mission icon="▶" title="Watch Ads" desc={`${r.ads_per_ticket} verified ads = 1 ticket`} reward={`Max ${r.max_ad_tickets}/day`} progress={`${r.ads_progress}/${r.ads_goal} ads · ${r.ad_tickets_today}/${r.max_ad_tickets} tickets today`} action="WATCH ADS" onClick={()=>setTab('ads')}/><Mission icon="✓" title="Complete Tasks" desc="Unlock milestone ticket bonuses" reward={`${r.tasks_completed} done`} progress={(r.task_milestones||[]).map((m:any)=>`${m.count} tasks +${m.tickets}`).join('  ·  ')} action="VIEW TASKS" onClick={()=>setTab('tasks')}/><section className="card raffle-achievements"><div className="raffle-inline-head"><div><span className="raffle-kicker">BONUS TICKETS</span><h3>Referral milestones</h3></div></div>{(r.referral_milestones||[]).map((m:any)=><div className="raffle-achievement-row" key={m.count}><div><b>{m.count} Verified Referrals</b><span>Weekly milestone</span></div><strong>+{m.tickets} Tickets</strong></div>)}</section></>}

export function RafflePage({setTab}:{setTab:any}){const {r,err}=useRaffle();const [now,setNow]=useState(Date.now());useEffect(()=>{const x=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(x)},[]);if(err)return <div className="info-box">{err}</div>;if(!r)return <div className="loader"/>;const left=Math.max(0,new Date(r.ends_at).getTime()-now),d=Math.floor(left/86400000),h=Math.floor(left%86400000/3600000),m=Math.floor(left%3600000/60000);return <><section className="raffle-detail-hero"><div className="raffle-topline"><div><span className="raffle-kicker">WEEKLY WIENER RAFFLE</span><h2>{r.tickets} Tickets</h2><p>Each ticket is one entry in this week's draw.</p></div><span className="raffle-live">{String(r.status).toUpperCase()}</span></div><div className="raffle-countdown"><div><span>ENDS IN</span><strong>{d}d {h}h {m}m</strong></div><div><span>PRIZE POOL</span><strong>{money(r.prize_pool)} WIENER</strong></div></div><button className="primary" onClick={()=>setTab('tickets')}>EARN MORE TICKETS</button></section><section className="card raffle-prizes"><div className="raffle-section-heading"><span className="raffle-kicker">THIS WEEK</span><h3>Prize Breakdown</h3></div>{(r.prizes||[]).map((p:any,i:number)=><div className="raffle-prize-row" key={i}><div className={`raffle-place p${i+1}`}>{i<3?['1','2','3'][i]:'+'}</div><div className="grow"><b>{p.count>1?`${p.count} ${p.position}s`:p.position}</b><span>{p.count>1?'Each winner receives':'Winner receives'}</span></div><strong>{money(p.prize)} WIENER</strong></div>)}</section><section className="card raffle-history"><div className="raffle-section-heading"><span className="raffle-kicker">YOUR ACTIVITY</span><h3>Ticket History</h3></div>{r.history?.length?r.history.map((x:any,i:number)=><div className="raffle-history-row" key={i}><div><b>{x.reason}</b><span>{when(x.created_at)}</span></div><strong className={x.amount>=0?'positive':''}>{x.amount>0?'+':''}{x.amount}</strong></div>):<div className="empty">No raffle tickets yet.</div>}</section><section className="card raffle-history"><div className="raffle-section-heading"><span className="raffle-kicker">RECENT DRAWS</span><h3>Previous Winners</h3></div>{r.previous_winners?.length?r.previous_winners.slice(0,10).map((x:any,i:number)=><div className="raffle-history-row" key={i}><div><b>{x.username}</b><span>{when(x.draw_date)}</span></div><strong className="positive">+{money(x.prize)} WIENER</strong></div>):<div className="empty">No previous winners yet.</div>}</section></>}

export function RaffleAdmin(){const [d,setD]=useState<any>(null),[msg,setMsg]=useState(''),[uid,setUid]=useState(''),[amount,setAmount]=useState('');const load=async()=>{try{setD(await raffleApi('admin_get'))}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[]);if(!d)return <section className="card"><h3>Tickets & Raffle</h3><p>{msg||'Loading raffle admin…'}</p></section>;const s=d.settings;const save=async(p:any)=>{await raffleApi('admin_save',{settings:{...s,...p}});setMsg('Raffle settings saved');await load()};return <section className="card"><h3>🎟 Tickets & Raffle</h3><div className="admin-grid"><label>Tickets System <input type="checkbox" checked={!!s.tickets_enabled} onChange={e=>save({tickets_enabled:e.target.checked})}/></label><label>Weekly Raffle <input type="checkbox" checked={!!s.raffle_enabled} onChange={e=>save({raffle_enabled:e.target.checked})}/></label><label>Auto Draw <input type="checkbox" checked={!!s.raffle_auto_draw} onChange={e=>save({raffle_auto_draw:e.target.checked})}/></label><label>Auto Credit <input type="checkbox" checked={!!s.raffle_auto_credit} onChange={e=>save({raffle_auto_credit:e.target.checked})}/></label></div><div className="profile-grid"><div><span>Verified Referral</span><b>+{s.raffle_tickets_per_verified_referral} ticket</b></div><div><span>Ads / Ticket</span><b>{s.raffle_ads_per_ticket}</b></div><div><span>Max Ad Tickets</span><b>{s.raffle_max_ad_tickets_per_day}/day</b></div><div><span>Past Draws</span><b>{d.raffles.length}</b></div></div><h4>Manual Ticket Adjustment</h4><div className="promo-row"><input placeholder="Telegram ID" value={uid} onChange={e=>setUid(e.target.value)}/><input placeholder="+/- Tickets" value={amount} onChange={e=>setAmount(e.target.value)}/><button onClick={async()=>{try{await raffleApi('admin_adjust',{telegram_id:Number(uid),amount:Number(amount),reason:'Admin adjustment'});setMsg('Tickets updated');setAmount('');await load()}catch(e:any){setMsg(e.message)}}}>APPLY</button></div><button className="primary small" onClick={async()=>{try{await raffleApi('admin_draw');setMsg('Draw processed');await load()}catch(e:any){setMsg(e.message)}}}>RERUN / PROCESS DUE DRAW</button>{msg&&<div className="info-box">{msg}</div>}<h4>Recent Ticket History</h4>{d.tickets.slice(0,10).map((x:any)=><div className="refrow" key={x.id}><span>{x.telegram_id} · {x.reason}</span><b>{x.amount>0?'+':''}{x.amount}</b></div>)}</section>}
