import {useMemo,useState} from 'react';
import {getInitData,PUBLISHABLE_KEY,SUPABASE_URL,type Snapshot} from './lib';
import {AnimatedIcon} from './icons';

async function specialTaskApi(taskId:string,action:string){const r=await fetch(`${SUPABASE_URL}/functions/v1/wiener-task-api`,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUBLISHABLE_KEY},body:JSON.stringify({action,task_id:taskId,initData:getInitData()})});const x=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok||!x.ok)throw new Error(x.message||x.error||'Task verification failed');return x.data}

export function SpecialTasks({data,say,refresh}:{data:Snapshot;say:(s:string)=>void;refresh:()=>Promise<any>}){
 const tasks=useMemo(()=>data.tasks.filter((t:any)=>t.category==='special'&&t.enabled!==false).sort((a:any,b:any)=>Number(a.sort_order||0)-Number(b.sort_order||0)),[data.tasks]);
 const done=new Set(data.completed.map((x:any)=>x.task_id));
 const [busy,setBusy]=useState('');
 if(!tasks.length)return null;
 const verify=async(t:any)=>{if(busy||done.has(t.id))return;try{setBusy(t.id);if(t.verification==='profile_name'||t.verification==='profile_bio')await specialTaskApi(t.id,'check');await specialTaskApi(t.id,'claim');say(`${t.verification==='none'?'✅ Completed':'✅ Verified'} · +${t.reward} WIENER`);await refresh()}catch(e:any){const m=String(e?.message||'Verification failed');const pretty:Record<string,string>={profile_name_requirement_not_met:'Add WIENER or 🌭 to your Telegram name, then check again.',profile_bio_requirement_not_met:'Add the required Wiener Farm link/text to your Telegram bio, then check again.',open_bot_chat_first:'Open Wiener Farm bot once, then try CHECK again.'};say(pretty[m]||m)}finally{setBusy('')}};
 const label=(t:any)=>done.has(t.id)?'DONE':busy===t.id?'…':t.verification==='none'?'CLAIM':'CHECK';
 return <><style>{`.special-wrap{margin-bottom:14px}.special-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:9px;padding:0 3px}.special-head div span{display:block;font-size:9px;font-weight:950;letter-spacing:1.5px;color:#ffe33b}.special-head h3{margin:3px 0 0;font-size:17px}.special-head small{font-size:10px;color:rgba(255,255,255,.42)}.special-list{padding:0;overflow:hidden}.special-row{display:grid;grid-template-columns:48px minmax(0,1fr) auto;gap:12px;align-items:center;padding:14px;border-bottom:1px solid rgba(255,255,255,.065)}.special-row:last-child{border-bottom:0}.special-row .square{width:48px;height:48px;border-radius:15px}.special-copy{min-width:0}.special-copy h4{margin:0;font-size:14px;line-height:1.25}.special-copy p{margin:4px 0 0;font-size:11px;line-height:1.35;color:rgba(255,255,255,.53)}.special-meta{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.special-chip{padding:3px 6px;border-radius:7px;background:rgba(255,255,255,.055);font-size:8px;font-weight:900;color:rgba(255,255,255,.55)}.special-chip.reward{color:#ffe33b;background:rgba(255,224,62,.08)}.special-row button{min-width:72px}`}</style><section className="special-wrap"><div className="special-head"><div><span>SPECIAL MISSIONS</span><h3>Extra ways to earn</h3></div><small>{tasks.filter((t:any)=>done.has(t.id)).length}/{tasks.length} done</small></div><div className="card special-list">{tasks.map((t:any)=>{const auto=t.verification==='profile_name'||t.verification==='profile_bio';return <div className="special-row" key={t.id}><div className="square check"><AnimatedIcon name={auto?'check':'gift'} active={!done.has(t.id)}/></div><div className="special-copy"><h4>{t.title}</h4><p>{t.description||'Complete this mission and claim your reward.'}</p><div className="special-meta"><span className="special-chip reward">+{t.reward} W</span><span className="special-chip">{t.is_daily?'DAILY':'ONE-TIME'}</span><span className="special-chip">{auto?'AUTO CHECK':'DIRECT CLAIM'}</span></div></div><button className="primary small" disabled={done.has(t.id)||busy===t.id} onClick={()=>verify(t)}>{label(t)}</button></div>})}</div></section></>;
}
