import {lazy,Suspense,useState} from 'react';
const Creator=lazy(()=>import('./SponsoredTaskCreator').then(m=>({default:m.SponsoredTaskCreator})));
const Manager=lazy(()=>import('./SponsoredTaskManager').then(m=>({default:m.SponsoredTaskManager})));

type Mode='create'|'manage'|'pending'|'live'|null;
export function SponsoredTaskEntry(){
 const [mode,setMode]=useState<Mode>(null);
 const managerTab=mode==='pending'?'pending':mode==='live'?'live':'all';
 return <><div className="sponsor-entry-actions"><button className="create-sponsored-task" onClick={()=>setMode('create')}>＋ CREATE TASK</button><button className="quick-sponsored-task pending" onClick={()=>setMode('pending')}>🟡 PENDING</button><button className="quick-sponsored-task live" onClick={()=>setMode('live')}>🟢 LIVE TASKS</button><button className="manage-sponsored-task" onClick={()=>setMode('manage')}>⚙ MANAGE</button></div>{mode==='create'&&<Suspense fallback={<div className="card" style={{padding:14,marginBottom:12}}>Loading task creator…</div>}><Creator onClose={()=>setMode(null)} onLive={()=>setMode('manage')}/></Suspense>}{mode&&mode!=='create'&&<Suspense fallback={<div className="card" style={{padding:14,marginBottom:12}}>Loading task manager…</div>}><Manager initialTab={managerTab} onClose={()=>setMode(null)} onCreate={()=>setMode('create')}/></Suspense>}<style>{`.sponsor-entry-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:0 0 12px}.sponsor-entry-actions button{width:100%;height:44px;border-radius:14px;font-size:10px;font-weight:950;letter-spacing:.035em}.create-sponsored-task{border:1px solid rgba(255,224,66,.25);background:linear-gradient(180deg,rgba(255,226,53,.13),rgba(255,203,0,.07));color:#ffe65b}.manage-sponsored-task{border:1px solid rgba(95,220,160,.22);background:linear-gradient(180deg,rgba(64,207,139,.12),rgba(30,150,96,.06));color:#aef2cf}.quick-sponsored-task{border:1px solid rgba(255,255,255,.09);background:rgba(255,255,255,.045);color:#fff}.quick-sponsored-task.pending{color:#ffe587}.quick-sponsored-task.live{color:#9bf0c2}`}</style></>;
}
