import {useEffect,useState} from 'react';
import {getInitData} from './lib';

type TreasuryState={keys:number;points:number;points_per_key:number;keys_today:number;daily_key_limit:number;attempts_today:number;daily_attempt_limit:number;cooldown_seconds:number;block_id:string;recent:Array<{reward:number;created_at:string}>};
const CHEST='https://surf-earn.top/template/img/games/treasury/treasure-chest.png';
async function treasuryApi(action:string,body:any={}){const r=await fetch('/functions/v1/wiener-treasury',{method:'POST',headers:{'Content-Type':'application/json','cache-control':'no-cache'},cache:'no-store',body:JSON.stringify({action,initData:getInitData(),...body})});const x=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok||x?.ok===false)throw Error(x?.message||x?.error||'Treasury unavailable');return x.data||x}
export function TreasuryEarn({refresh,say}:{refresh:any;say:any}){
 const [open,setOpen]=useState(false),[st,setSt]=useState<TreasuryState|null>(null),[busy,setBusy]=useState(false),[cooldown,setCooldown]=useState(0),[reward,setReward]=useState<number|null>(null);
 const load=async()=>{const x=await treasuryApi('status');setSt(x);setCooldown(Number(x.cooldown_seconds||0));return x};
 useEffect(()=>{if(open)load().catch((e:any)=>say(e.message))},[open]);
 useEffect(()=>{if(cooldown<=0)return;const t=setInterval(()=>setCooldown(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t)},[cooldown]);
 const showTreasury=(e:any)=>{e?.preventDefault?.();e?.stopPropagation?.();setReward(null);setOpen(true)};
 const watch=async()=>{if(!st||busy||cooldown>0)return;try{setBusy(true);const x=await treasuryApi('ad_start');const c=window.Adsgram?.init({blockId:String(x.block_id||st.block_id)});if(!c)throw Error('AdsGram SDK unavailable');const shown=await c.show();if(shown&&shown.done===false)throw Error(shown.description||'Ad was not completed');const done=await treasuryApi('ad_complete',{session_id:x.session_id,proof:x.proof});setCooldown(Number(done.cooldown_seconds||20));await load();if(Number(done.key_added||0)>0)say('🔑 Treasury key earned!')}catch(e:any){say(String(e?.message||'Treasury ad failed'))}finally{setBusy(false)}};
 const openChest=async()=>{if(!st?.keys||busy)return;try{setBusy(true);const x=await treasuryApi('open',{request_id:crypto.randomUUID()});setReward(Number(x.reward||0));await load();await refresh()}catch(e:any){say(String(e?.message||'Chest failed'))}finally{setBusy(false)}};
 const pct=st?Math.min(100,Number(st.points||0)/Math.max(1,Number(st.points_per_key||5))*100):0;
 return <><style>{`
.wf-treasury-v105{position:relative;overflow:hidden;margin:12px 0 0!important;padding:20px!important;border-radius:24px!important;border:1px solid #d1a55533!important;background:radial-gradient(ellipse at 0 0,#ffd06514,transparent 64%),linear-gradient(145deg,#1e2315,#131910)!important;box-shadow:inset 0 1px 0 #fff1,0 12px 30px #0002!important}
.wf-tv-main{display:grid;grid-template-columns:58px minmax(0,1fr);gap:14px;align-items:center}.wf-tv-icon{width:58px;height:58px;object-fit:contain;filter:drop-shadow(0 9px 14px #0007);animation:wfTvFloat 2.5s ease-in-out infinite}.wf-tv-copy h3{margin:0;font-size:20px;font-weight:950;letter-spacing:-.5px}.wf-tv-copy p{margin:4px 0 0;color:#b7bcae;font-size:12px;line-height:1.5}.wf-tv-badge{display:inline-flex;margin-top:8px;padding:5px 8px;border-radius:999px;border:1px solid #ffd28328;background:#ffc34a0c;color:#e8c875;font-size:9px;font-weight:900;letter-spacing:.25px}.wf-tv-open{width:100%;min-height:46px;margin-top:16px;border-radius:14px;border:1px solid #ffd28345;background:#ffc34a12;color:#ffd283;font-size:13px;font-weight:950;letter-spacing:.04em;box-shadow:none}.wf-tv-open:active{transform:scale(.985)}.wf-tv-meta{margin-top:14px;padding-top:13px;border-top:1px solid #ffffff0b;text-align:center;color:#8f9689;font-size:9px;font-weight:850;letter-spacing:.35px;line-height:1.5}.wf-tv-open:focus-visible,.wf-tm button:focus-visible{outline:2px solid #ffe09a;outline-offset:3px}
.wf-to{position:fixed;inset:0;z-index:10080;padding:18px;display:grid;place-items:center;background:#020806df;backdrop-filter:blur(14px)}.wf-tm{width:min(100%,390px);max-height:90vh;overflow:auto;border-radius:28px;padding:20px;background:radial-gradient(circle at 50% 0,#ffce4420,transparent 31%),linear-gradient(155deg,#17271d,#09140e);border:1px solid #e8bd5138;box-shadow:0 28px 90px #0009}.wf-th{display:flex;align-items:center;justify-content:space-between}.wf-th h2{margin:0;font-size:20px}.wf-tclose{width:38px;height:38px;border-radius:13px;border:1px solid #fff2;background:#fff1;color:#fff;font-size:18px}.wf-tchest{text-align:center;padding:12px 0 17px}.wf-tchest img{width:165px;max-width:55vw;filter:drop-shadow(0 18px 25px #0008)}.wf-tkey{display:inline-flex;padding:7px 11px;border-radius:999px;background:#ffd84d12;border:1px solid #ffd84d32;color:#ffe07a;font-weight:900;font-size:12px}.wf-tprimary,.wf-twatch{width:100%;min-height:48px;border-radius:15px;font-weight:950}.wf-tprimary{margin-top:10px;border:0;background:linear-gradient(110deg,#ffd85d,#f3a600);color:#241700}.wf-tsource{margin-top:12px;padding:15px;border-radius:20px;background:#ffffff08;border:1px solid #ffffff10}.wf-tsource-top{display:flex;justify-content:space-between;gap:10px}.wf-tsource h3{margin:0;font-size:14px}.wf-tsource p{margin:3px 0 0;font-size:10px;color:#aeb7ae}.wf-tprogress{height:7px;margin:12px 0;border-radius:999px;background:#fff1;overflow:hidden}.wf-tprogress span{display:block;height:100%;background:linear-gradient(90deg,#ffb521,#ffe174);border-radius:inherit}.wf-twatch{border:1px solid #ffe08030;background:#fff1;color:#ffe080}.wf-twatch:disabled,.wf-tprimary:disabled{opacity:.45}.wf-tsecure{margin-top:12px;text-align:center;color:#839087;font-size:9px;line-height:1.45}.wf-twin{font-size:40px;font-weight:1000;color:#ffe06c;margin:8px 0}@keyframes wfTvFloat{50%{transform:translateY(-3px) scale(1.025)}}@media(prefers-reduced-motion:reduce){.wf-tv-icon{animation:none}}
`}</style><section className="card wf-treasury-v105" data-treasury-v105="true"><div className="wf-tv-main"><img className="wf-tv-icon" src={CHEST} alt=""/><div className="wf-tv-copy"><h3>Wiener Treasury</h3><p>Earn keys. Open the chest. Win surprise WIENER.</p><span className="wf-tv-badge">🎁 UP TO 500 WIENER</span></div></div><button type="button" className="wf-tv-open" onClick={showTreasury}>OPEN</button><div className="wf-tv-meta">🔑 SERVER KEYS · 🛡 ONE-TIME CLAIM · SECURE REWARDS</div></section>{open&&<div className="wf-to" onClick={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="wf-tm"><div className="wf-th"><h2>Wiener Treasury</h2><button type="button" className="wf-tclose" onClick={()=>setOpen(false)}>×</button></div><div className="wf-tchest"><img src={CHEST} alt="Treasure chest"/><div><span className="wf-tkey">🔑 {st?.keys??'—'} keys</span></div><button type="button" className="wf-tprimary" disabled={busy||!st?.keys} onClick={openChest}>{busy?'PLEASE WAIT…':st?.keys?'OPEN CHEST':'EARN A KEY FIRST'}</button></div><div className="wf-tsource"><div className="wf-tsource-top"><div><h3>Earn Treasury Keys</h3><p>{st?`${st.points}/${st.points_per_key} points · ${st.keys_today}/${st.daily_key_limit} keys today`:'Loading secure status…'}</p></div><b>🔑</b></div><div className="wf-tprogress"><span style={{width:`${pct}%`}}/></div><button type="button" className="wf-twatch" disabled={busy||!st||cooldown>0||(st?.attempts_today??0)>=(st?.daily_attempt_limit??25)||(st?.keys_today??0)>=(st?.daily_key_limit??5)} onClick={watch}>{busy?'VERIFYING…':cooldown>0?`NEXT IN ${cooldown}s`:(st?.keys_today??0)>=(st?.daily_key_limit??5)?'DAILY KEY LIMIT':'WATCH TREASURY AD'}</button></div><div className="wf-tsecure">Keys, reward selection and chest claims are verified by the Wiener server.</div></div></div>}{reward!==null&&<div className="wf-to"><div className="wf-tm" style={{textAlign:'center'}}><img src={CHEST} alt="" style={{width:120}}/><div style={{fontSize:11,opacity:.65,fontWeight:900}}>CHEST UNLOCKED</div><div className="wf-twin">+{reward} WIENER</div><button type="button" className="wf-tprimary" onClick={()=>setReward(null)}>COLLECT</button></div></div>}</>;
}
