import {useEffect,useMemo,useState} from 'react';
import type {Snapshot,Tab} from './lib';
import {money} from './lib';
import {AnimatedIcon,type IconName} from './icons';
import {LANGUAGES,useI18n,type LangCode} from './i18n';

const WIENER_LOGO='https://pixlinkhost.vercel.app/i/uRiwapMRiQ';
function WienerLogo({size=42}:{size?:number}){return <img src={WIENER_LOGO} alt="WIENER Farm" loading="eager" decoding="sync" fetchPriority="high" style={{width:size,height:size,objectFit:'cover',display:'block',borderRadius:'50%'}}/>}

export function Splash({text}:{text:string}){const {t}=useI18n();const[phase,setPhase]=useState(0);useEffect(()=>{const timers=[window.setTimeout(()=>setPhase(1),520),window.setTimeout(()=>setPhase(2),1350),window.setTimeout(()=>setPhase(3),2600)];return()=>timers.forEach(window.clearTimeout)},[]);const phases=[text||'Opening your farm…','Syncing your rewards…','Growing your dashboard…','Almost ready…'];return <div className="center-screen wf-boot" role="status" aria-live="polite"><div className="wf-boot-ambient" aria-hidden="true"><i/><i/><i/></div><div className="wf-boot-core"><div className="wf-boot-emblem" aria-hidden="true"><div className="wf-boot-orbit"><i/><i/><i/></div><div className="wf-boot-mark"><b>W</b><span>FARM</span></div></div><div className="wf-boot-wordmark"><strong>WIENER</strong><b>FARM</b></div><div className="wf-boot-tagline">EARN · GROW · WITHDRAW</div><p key={phase} className="wf-boot-status">{phases[phase]}</p><div className="wf-boot-track" aria-hidden="true"><i/></div><small className="wf-boot-secure">{t('system.secure')}</small></div></div>}
export function OpenTelegram(){const {t}=useI18n();return <div className="center-screen"><WienerLogo size={108}/><h1>WIENER</h1><p>This Mini App uses signed Telegram authentication. Open it from <b>@WienerDogeFarmBot</b>.</p><a className="primary linkbtn" href="https://t.me/WienerDogeFarmBot">{t('system.openTelegram')}</a></div>}
export function StateScreen({icon,title,text}:{icon:string;title:string;text:string}){return <div className="center-screen"><div className="state-icon">{icon}</div><h2>{title}</h2><p>{text}</p></div>}

function LanguagePicker(){const {language,lang,setLang,t}=useI18n(),[open,setOpen]=useState(false),[q,setQ]=useState('');const filtered=useMemo(()=>{const s=q.trim().toLowerCase();return s?LANGUAGES.filter(x=>`${x.name} ${x.native} ${x.code}`.toLowerCase().includes(s)):LANGUAGES},[q]);const choose=(code:LangCode)=>{setLang(code);setOpen(false);setQ('');try{window.Telegram?.WebApp?.HapticFeedback?.selectionChanged?.()}catch{}};return <><button className="language-trigger" aria-label={t('language.title')} onClick={()=>setOpen(true)}><span>🌐</span><small>{language.code.toUpperCase()}</small></button>{open&&<div className="language-backdrop" onClick={()=>setOpen(false)}><section className="language-sheet" onClick={e=>e.stopPropagation()}><div className="language-grabber"/><div className="language-head"><div><small>{t('language.current')}</small><h3>{t('language.choose')}</h3></div><button onClick={()=>setOpen(false)}>×</button></div><div className="language-current"><span>{language.flag}</span><div><b>{language.native}</b><small>{language.name}</small></div><em>✓</em></div><div className="language-search"><span>⌕</span><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder={t('language.search')}/></div><div className="language-list">{filtered.map(x=><button key={x.code} className={x.code===lang?'active':''} onClick={()=>choose(x.code)}><span>{x.flag}</span><div><b>{x.native}</b><small>{x.name}</small></div>{x.code===lang&&<em>✓</em>}</button>)}</div></section></div>}</>}

export function Brand({data}:{data:Snapshot}){return <header className="brand wf-header"><div className="wf-brand-lockup"><div className="wf-brand-logo"><WienerLogo size={42}/></div><div className="brand-copy"><b>WIENER FARM</b><span>Earn · Grow · Withdraw</span></div></div><div className="wf-header-actions"><div className="balance-pill" aria-label="WIENER balance"><span className="mini-coin">W</span>{money(data.user.balance)}</div><LanguagePicker/></div></header>}
export function Nav({tab,setTab,admin}:{tab:Tab;setTab:(t:Tab)=>void;admin:boolean}){const {t}=useI18n();const list:[Tab,string,IconName][]=[['home',t('nav.home'),'home'],['ads','Ads','ads'],['tasks',t('nav.tasks'),'tasks'],['invite',t('nav.invite'),'invite'],['wallet',t('nav.wallet'),'wallet']];return <nav className="bottom-nav">{list.map(([k,l,icon])=><button key={k} className={tab===k?'active '+k:k} onClick={()=>setTab(k)}><AnimatedIcon name={icon} active={tab===k}/><span>{l}</span></button>)}{admin&&<button className="admin-fab" aria-label="Open admin" onClick={()=>setTab('admin')}><AnimatedIcon name="gear" active={tab==='admin'}/></button>}</nav>}
