import {useEffect,useMemo,useState} from 'react';
import {api,cleanUserText,date,money,type Snapshot,withdrawApi} from './lib';
import {AnimatedIcon} from './icons';

type Method={method_key:string;label:string;network:'TON'|'Polygon';enabled:boolean;minimum_usdt:number;fee_usdt:number;sort_order:number};
type Step='method'|'amount'|'wallet'|'review';

export function WalletV2({data,setTab}:{data:Snapshot;setTab:any}){
  const s=data.settings,u=data.user;
  const [methods,setMethods]=useState<Method[]>([]),[step,setStep]=useState<Step>('method'),[methodKey,setMethodKey]=useState(''),[amount,setAmount]=useState(''),[wallet,setWallet]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[owner,setOwner]=useState('');
  const usd=Number(u.balance)/Number(s.token_per_usdt||10000),method=methods.find(x=>x.method_key===methodKey),gross=Number(amount||0),fee=Number(method?.fee_usdt||0),receive=Math.max(0,gross-fee),neededWiener=gross*Number(s.token_per_usdt||10000);
  const load=async()=>{try{const x=await withdrawApi('methods');setMethods(x.methods||[])}catch(e:any){setMessage(e.message)}};
  useEffect(()=>{load()},[]);
  const canAmount=!!method&&method.enabled&&gross>=Number(method.minimum_usdt)&&gross>fee&&neededWiener<=Number(u.balance);
  const walletOk=useMemo(()=>{const w=wallet.trim();if(!method)return false;if(method.network==='Polygon')return /^0x[a-fA-F0-9]{40}$/.test(w);return /^(?:[EUUk0][Qq][A-Za-z0-9_-]{46}|(?:-1|0):[a-fA-F0-9]{64})$/.test(w)},[wallet,method]);
  const submit=async()=>{if(!method||busy)return;try{setBusy(true);setMessage('');await withdrawApi('request',{method_key:method.method_key,amount_usdt:gross,wallet:wallet.trim()});setMessage('✅ Withdrawal request created. Status: Pending');setStep('method');setMethodKey('');setAmount('');setWallet('')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
  const back=()=>setStep(step==='review'?'wallet':step==='wallet'?'amount':step==='amount'?'method':'method');
  return <>
    <section className="hero card"><div className="eyebrow">AVAILABLE TO WITHDRAW</div><div className="hero-balance"><span className="coin">W</span><strong>{money(u.balance)}</strong><b>WIENER</b></div><div className="muted">≈ {usd.toFixed(4)} USDT</div><div className="tiny">{money(s.token_per_usdt)} WIENER = 1 USDT</div></section>
    <section className="card withdraw-v2">
      <div className="withdraw-progress"><span className={step==='method'?'active':'done'}>1</span><i/><span className={step==='amount'?'active':['wallet','review'].includes(step)?'done':''}>2</span><i/><span className={step==='wallet'?'active':step==='review'?'done':''}>3</span><i/><span className={step==='review'?'active':''}>4</span></div>
      {step==='method'&&<><div className="section-head"><div className="square blue"><AnimatedIcon name="download" active/></div><div><h3>Select withdrawal method</h3><p>Choose the exact network you want to receive on.</p></div></div><div className="method-grid">{methods.map(m=><button key={m.method_key} disabled={!m.enabled||!s.withdrawals_enabled} className={`method-card ${methodKey===m.method_key?'selected':''} ${!m.enabled?'disabled':''}`} onClick={()=>{setMethodKey(m.method_key);setStep('amount')}}><span>{m.network==='TON'?'💎':'🟣'}</span><div><b>{m.label}</b><small>{m.enabled?`Min ${Number(m.minimum_usdt).toFixed(4)} USDT · Fee ${Number(m.fee_usdt).toFixed(4)} USDT`:'Temporarily unavailable'}</small></div><i>›</i></button>)}</div>{!s.withdrawals_enabled&&<div className="withdraw-warning">Withdrawals are temporarily unavailable.</div>}</>}
      {step==='amount'&&method&&<><button className="withdraw-back" onClick={back}>← CHANGE METHOD</button><div className="network-banner"><b>{method.label}</b><span>Selected network: <strong>{method.network}</strong></span></div><label>AMOUNT (USDT)</label><div className="amount-row"><input type="number" min={method.minimum_usdt} step="0.0001" placeholder={`Min ${method.minimum_usdt} USDT`} value={amount} onChange={e=>setAmount(e.target.value)}/><button onClick={()=>setAmount(usd.toFixed(4))}>MAX</button></div><div className="withdraw-breakdown"><div><span>Fee</span><b>{fee.toFixed(4)} USDT</b></div><div><span>You receive</span><b>{receive.toFixed(4)} USDT</b></div><div><span>WIENER needed</span><b>{money(neededWiener)} WIENER</b></div></div>{gross>0&&gross<Number(method.minimum_usdt)&&<div className="withdraw-warning">Minimum for {method.network} is {Number(method.minimum_usdt).toFixed(4)} USDT.</div>}{neededWiener>Number(u.balance)&&<div className="withdraw-warning">Insufficient WIENER balance.</div>}<button className="primary" disabled={!canAmount} onClick={()=>setStep('wallet')}>CONTINUE →</button></>}
      {step==='wallet'&&method&&<><button className="withdraw-back" onClick={back}>← BACK</button><div className="network-banner"><b>{method.label}</b><span>Wallet must support <strong>{method.network}</strong>. Network will never be changed automatically.</span></div><label>{method.network.toUpperCase()} WALLET ADDRESS</label><input placeholder={method.network==='Polygon'?'0x…':'UQ… / EQ…'} value={wallet} onChange={e=>setWallet(e.target.value.trim())}/>{wallet&&!walletOk&&<div className="withdraw-warning">Invalid {method.network} wallet address.</div>}<button className="primary" disabled={!walletOk} onClick={()=>setStep('review')}>REVIEW WITHDRAWAL →</button></>}
      {step==='review'&&method&&<><button className="withdraw-back" onClick={back}>← EDIT WALLET</button><div className="review-withdraw"><h3>Review withdrawal</h3><p>Check the network carefully before confirming.</p><div><span>Amount</span><b>{gross.toFixed(4)} USDT</b></div><div><span>Network</span><b>{method.network}</b></div><div><span>Fee</span><b>{fee.toFixed(4)} USDT</b></div><div><span>You Receive</span><b>{receive.toFixed(4)} USDT</b></div><div className="wallet-review"><span>Wallet</span><b>{wallet}</b></div></div><div className="confirm-network">You are confirming a <strong>{method.network}</strong> withdrawal. Wiener Farm will not convert this to another network.</div><button className="primary button-with-icon" disabled={busy} onClick={submit}><AnimatedIcon name="wallet" active={!busy}/>{busy?'CREATING…':'CONFIRM WITHDRAWAL'}</button></>}
      {message&&<div className="withdraw-message">{message}</div>}
    </section>
    <h4 className="eyebrow outside">WITHDRAWAL HISTORY</h4><section className="card history">{data.withdrawals?.length?data.withdrawals.map((w:any)=><div className="tx" key={w.id}><div className="arrow down"><AnimatedIcon name="arrowDown" active/></div><div className="grow"><h3>{Number(w.gross_usdt).toFixed(4)} USDT · {w.network}</h3><p>{date(w.created_at)} · {String(w.status).toUpperCase()}</p></div><b>{Number(w.receive_usdt).toFixed(4)}</b></div>):<div className="empty">No withdrawals yet.</div>}</section>
    <h4 className="eyebrow outside">TRANSACTION HISTORY</h4><section className="card history">{data.transactions.length?data.transactions.map((x:any)=><div className="tx" key={x.id}><div className={Number(x.amount)>=0?'arrow up':'arrow down'}><AnimatedIcon name={Number(x.amount)>=0?'arrowUp':'arrowDown'} active/></div><div className="grow"><h3>{cleanUserText(x.description)}</h3><p>{date(x.created_at)}</p></div><b className={Number(x.amount)>=0?'plus':'minus'}>{Number(x.amount)>=0?'+':''}{money(x.amount)} WIENER</b></div>):<div className="empty">No transactions yet.</div>}</section>
    {!data.is_admin&&<section className="owner-setup"><details><summary>Owner setup</summary><p>Use the one-time bootstrap code to claim the first owner account.</p><div className="promo-row"><input placeholder="BOOTSTRAP CODE" value={owner} onChange={e=>setOwner(e.target.value)}/><button className="primary small" onClick={async()=>{try{await api('admin_bootstrap',{code:owner});setTab('admin')}catch{}}}>ACTIVATE</button></div></details></section>}
  </>
}

export function AdminWithdrawUpgrade({say}:{say:any}){
  const [d,setD]=useState<any>(null),[busy,setBusy]=useState(false);
  const load=async()=>{try{setBusy(true);setD(await withdrawApi('admin_boot'))}catch(e:any){say(e.message)}finally{setBusy(false)}};
  useEffect(()=>{load()},[]);
  if(!d)return <section className="card admin-withdraw-v2"><h3>💸 Withdrawal System</h3><p>Loading secure withdrawal controls…</p></section>;
  const saveMethod=async(m:any)=>{try{setBusy(true);await withdrawApi('admin_method_save',{method:{method_key:m.method_key,enabled:m.enabled,minimum_usdt:Number(m.minimum_usdt),fee_usdt:Number(m.fee_usdt)}});say('✅ Withdrawal method saved');await load()}catch(e:any){say(e.message)}finally{setBusy(false)}};
  const patch=(key:string,k:string,v:any)=>setD({...d,methods:d.methods.map((m:any)=>m.method_key===key?{...m,[k]:v}:m)});
  const paid=async(w:any)=>{const tx=prompt(`Enter ${w.network} transaction hash`,'')?.trim();if(!tx)return;if(!confirm(`Mark ${Number(w.gross_usdt).toFixed(4)} USDT on ${w.network} as PAID?\n\nTX: ${tx}`))return;try{setBusy(true);const x=await withdrawApi('admin_paid',{id:w.id,tx_hash:tx});say(x.already_paid?'Already paid — notifications safely checked':'✅ Paid + user/channel notifications processed');await load()}catch(e:any){say(e.message)}finally{setBusy(false)}};
  const reject=async(w:any)=>{if(!confirm('Reject this pending withdrawal?'))return;const note=prompt('Rejection note','Rejected by admin')||'Rejected by admin';try{setBusy(true);await withdrawApi('admin_reject',{id:w.id,note});say('Withdrawal rejected');await load()}catch(e:any){say(e.message)}finally{setBusy(false)}};
  return <section className="admin-withdraw-v2">
    <div className="admin-upgrade-head"><div><span>SECURE PAYOUT CONTROL</span><h3>💸 Withdrawal Methods & Payments</h3><p>TON and Polygon are controlled independently. Paid processing is idempotent.</p></div><button onClick={load}>↻</button></div>
    <div className="method-admin-grid">{d.methods.map((m:any)=><div className="method-admin-card" key={m.method_key}><div className="method-admin-title"><div><b>{m.label}</b><small>{m.network} network</small></div><label className="method-switch"><input type="checkbox" checked={!!m.enabled} onChange={e=>patch(m.method_key,'enabled',e.target.checked)}/><span>{m.enabled?'Enabled':'Disabled'}</span></label></div><label>Minimum withdrawal (USDT)<input type="number" step="0.0001" value={m.minimum_usdt} onChange={e=>patch(m.method_key,'minimum_usdt',e.target.value)}/></label><label>Withdrawal fee (USDT)<input type="number" step="0.0001" value={m.fee_usdt} onChange={e=>patch(m.method_key,'fee_usdt',e.target.value)}/></label><button className="primary" disabled={busy} onClick={()=>saveMethod(m)}>SAVE {m.network.toUpperCase()}</button></div>)}</div>
    <div className="admin-upgrade-head compact"><div><h3>Withdrawal Requests</h3><p>User / UID / Amount / Network / Wallet / Status / Requested Time</p></div></div>
    <div className="withdraw-admin-list">{d.withdrawals.length?d.withdrawals.map((w:any)=><div className={`withdraw-admin-row status-${w.status}`} key={w.id}><div className="withdraw-admin-main"><div><b>{w.username||`User ${w.telegram_id}`}</b><small>UID {w.telegram_id} · ID {String(w.id).slice(0,8)}…</small></div><strong>{Number(w.gross_usdt).toFixed(4)} USDT</strong></div><div className="withdraw-admin-meta"><span>🌐 {w.network}</span><span>💸 Fee {Number(w.fee_usdt).toFixed(4)}</span><span>✅ Receive {Number(w.receive_usdt).toFixed(4)}</span><span>🕒 {date(w.created_at)}</span></div><code className="withdraw-wallet-code">{w.wallet_address}</code><div className="withdraw-admin-status"><b>{String(w.status).toUpperCase()}</b>{w.processing_admin&&<span>Admin {w.processing_admin}</span>}{w.processed_at&&<span>{date(w.processed_at)}</span>}</div>{w.tx_hash&&<div className="withdraw-tx">TX: {w.tx_hash}</div>}{w.status==='pending'&&<div className="row-actions"><button className="good" disabled={busy} onClick={()=>paid(w)}>MARK PAID</button><button className="danger" disabled={busy} onClick={()=>reject(w)}>REJECT</button></div>}</div>):<div className="admin-empty">No withdrawal requests.</div>}</div>
  </section>
}
