import {useEffect,useState} from 'react';
import {TonConnectUI} from '@tonconnect/ui';
import {date,getInitData,money,PUBLISHABLE_KEY,SUPABASE_URL,type Snapshot,withdrawApi} from './lib';

type Method={method_key:string;label:string;network:'TON'|'Polygon';enabled:boolean;minimum_usdt:number;fee_usdt:number;sort_order:number};
type Step='wallet'|'amount'|'review';
const GRAM_ANIM='https://wiener-farm.vercel.app/api/host/gram-icon';
const GRAM_STATIC='https://wiener-farm.vercel.app/api/host/gram-static';
const MANIFEST='https://wiener-farm.vercel.app/tonconnect-manifest.json';
let tonUI:TonConnectUI|null=null;
const getTonUI=()=>tonUI||(tonUI=new TonConnectUI({manifestUrl:MANIFEST}));
const short=(w:string)=>w.length<20?w:`${w.slice(0,8)}…${w.slice(-6)}`;
const statusView=(s:string)=>s==='paid'?{icon:'🟢',label:'PAID'}:s==='rejected'?{icon:'🔴',label:'REJECTED'}:{icon:'🟡',label:'PENDING'};
function remaining(until:string|null){if(!until)return 0;return Math.max(0,new Date(until).getTime()-Date.now())}
function formatLeft(ms:number){const t=Math.ceil(ms/1000),h=Math.floor(t/3600),m=Math.floor((t%3600)/60),s=t%60;return h?`${h}h ${m}m ${s}s`:m?`${m}m ${s}s`:`${s}s`}
async function tonApi(action:string,body:any={}){const r=await fetch(`${SUPABASE_URL}/functions/v1/wiener-ton-wallet`,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUBLISHABLE_KEY},body:JSON.stringify({action,initData:getInitData(),...body})});const x=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok||!x.ok)throw new Error(x.message||x.error||'Gram withdrawal request failed');return x.data??x}

function GramIcon({animated=false}:{animated?:boolean}){
 return <span className={`gram-icon-shell ${animated?'animated':''}`} aria-hidden="true">
  {animated?<object data={GRAM_ANIM} type="application/x-tgsticker" className="gram-tgs"><img src={GRAM_STATIC} alt=""/></object>:<img src={GRAM_STATIC} alt=""/>}
 </span>
}

export function WalletV2({data}:{data:Snapshot;setTab:any}){
 const WIENER_PER_USDT=Math.max(1,Number(data.settings?.token_per_usdt||10000));
 const preloaded=Array.isArray(data.withdrawal_methods)?data.withdrawal_methods as Method[]:[];
 const [method,setMethod]=useState<Method|null>(preloaded.find(x=>x.method_key==='gram_ton')||null);
 const [step,setStep]=useState<Step>('wallet'),[amount,setAmount]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[history,setHistory]=useState<any[]>(data.withdrawals||[]),[selected,setSelected]=useState<any>(null),[balance,setBalance]=useState(Number(data.user.balance||0)),[cooldownUntil,setCooldownUntil]=useState<string|null>(null),[cooldownMs,setCooldownMs]=useState(0),[hasPending,setHasPending]=useState((data.withdrawals||[]).some((w:any)=>String(w.status)==='pending')),[globalEnabled,setGlobalEnabled]=useState(!!data.settings.withdrawals_enabled),[tonWallet,setTonWallet]=useState(''),[tonProvider,setTonProvider]=useState(''),[tonUsd,setTonUsd]=useState<number|null>(null),[tonBusy,setTonBusy]=useState(false),[syncing,setSyncing]=useState(false);
 const entered=Number(amount||0),tonUsdNum=Number(tonUsd||0),fee=Number(method?.fee_usdt||0),minimumUsdt=Math.max(0.05,Number(method?.minimum_usdt||0)),usdValue=entered/WIENER_PER_USDT,tonGross=tonUsdNum>0?usdValue/tonUsdNum:0,tonReceive=Math.max(0,tonGross-fee);
 const canAmount=!!method&&globalEnabled&&method.enabled&&!hasPending&&cooldownMs<=0&&!!tonWallet&&tonUsdNum>0&&Number.isFinite(entered)&&entered>0&&entered<=balance+1e-9&&tonGross>=minimumUsdt&&tonGross>fee;
 const canStart=!!method&&globalEnabled&&method.enabled&&!hasPending&&cooldownMs<=0&&!!tonWallet&&tonUsdNum>0;
 const load=async(showError=false)=>{try{setSyncing(true);const [m,h,t]=await Promise.all([withdrawApi('methods'),withdrawApi('history'),tonApi('status')]);const gram=(m.methods||[]).find((x:Method)=>x.method_key==='gram_ton')||t.method||null;setMethod(gram);setBalance(Number(m.balance??balance));setCooldownUntil(m.cooldown_until||null);setCooldownMs(remaining(m.cooldown_until||null));setHasPending(!!m.has_pending);setGlobalEnabled(m.settings?.withdrawals_enabled!==false);setHistory(h||[]);setTonUsd(t.ton_usd==null?null:Number(t.ton_usd));if(t.wallet?.address){setTonWallet(String(t.wallet.address));setTonProvider(String(t.wallet.provider||'TON Connect'))}else{setTonWallet('');setTonProvider('')}}catch(e:any){if(showError||!preloaded.length)setMessage(String(e.message||e).replace(/_/g,' '))}finally{setSyncing(false)}};
 const bindConnected=async(w:any,silent=false)=>{if(!w?.account?.address)return false;const rawAddress=String(w.account.address),provider=String(w.device?.appName||w.device?.name||'TON Connect');try{const bound=await tonApi('bind',{address:rawAddress,provider});setTonWallet(String(bound.address));setTonProvider(String(bound.provider||provider));if(!silent)setMessage('✅ Gram wallet connected');return true}catch(e:any){try{await getTonUI().disconnect()}catch{}setTonWallet('');setTonProvider('');const raw=String(e.message||e);setMessage(raw.includes('ton_wallet_already_used')?'This TON wallet is already connected to another WIENER Farm account.':raw.replace(/_/g,' '));return false}};
 useEffect(()=>{const ui=getTonUI();let alive=true;const syncNow=async()=>{if(!alive)return;try{setSyncing(true);const current=(ui as any).wallet;if(current?.account?.address)await bindConnected(current,true);await load(false)}finally{if(alive)setSyncing(false)}};syncNow();const off=ui.onStatusChange(async(w:any)=>{if(w?.account?.address){await bindConnected(w);await load(false)}else{setTonWallet('');setTonProvider('');await load(false)}});const onFocus=()=>syncNow();const onVisible=()=>{if(document.visibilityState==='visible')syncNow()};window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onVisible);return()=>{alive=false;try{off()}catch{}window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onVisible)}},[]);
 useEffect(()=>{if(!cooldownUntil)return;const tick=()=>setCooldownMs(remaining(cooldownUntil));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[cooldownUntil]);
 const connect=async()=>{try{setTonBusy(true);setMessage('');await getTonUI().openModal()}catch(e:any){setMessage(String(e.message||e))}finally{setTonBusy(false)}};
 const disconnect=async()=>{try{setTonBusy(true);await getTonUI().disconnect();await tonApi('unbind');setTonWallet('');setTonProvider('');setStep('wallet');await load(false)}catch(e:any){setMessage(String(e.message||e).replace(/_/g,' '))}finally{setTonBusy(false)}};
 const quick=(v:'min'|'25'|'50'|'max')=>{if(!method)return;const minW=Math.ceil(minimumUsdt*tonUsdNum*WIENER_PER_USDT),raw=v==='min'?minW:v==='25'?balance*.25:v==='50'?balance*.5:balance;setAmount(String(Math.max(0,Math.floor(raw))))};
 const submit=async()=>{if(!canAmount||busy)return;try{setBusy(true);setMessage('');const x=await tonApi('withdraw',{amount_wiener:entered});setBalance(Number(x.balance??balance));setHistory(p=>x.withdrawal?[x.withdrawal,...p]:p);setHasPending(true);setAmount('');setStep('wallet');if(x.ton_usd)setTonUsd(Number(x.ton_usd));setMessage('✅ Gram (TON) withdrawal request created. Status: Pending')}catch(e:any){const raw=String(e.message||e);setMessage(raw.includes('ton_price_unavailable')?'Live TON price is temporarily unavailable. Please try again shortly.':raw.replace(/_/g,' '))}finally{setBusy(false)}};
 const progress=['Wallet','WIENER','Review'],idx=step==='wallet'?0:step==='amount'?1:2;
 return <div className="wallet-v2-page compact-gram-wallet"><style>{`
 .compact-gram-wallet{padding-bottom:calc(104px + env(safe-area-inset-bottom,0px))}
 .gram-icon-shell{position:relative;width:42px;height:42px;display:grid;place-items:center;flex:0 0 auto;border-radius:14px;background:linear-gradient(145deg,rgba(73,178,255,.18),rgba(25,78,155,.08));border:1px solid rgba(109,198,255,.18);box-shadow:inset 0 1px 0 rgba(255,255,255,.16),0 8px 22px rgba(0,83,170,.16)}
 .gram-icon-shell:after{content:'';position:absolute;inset:6px;border-radius:10px;background:radial-gradient(circle at 32% 25%,rgba(255,255,255,.2),transparent 54%);pointer-events:none}.gram-icon-shell img,.gram-icon-shell object{width:31px;height:31px;object-fit:contain;display:block}.gram-icon-shell.animated{animation:gramFloat 3s ease-in-out infinite}.gram-tgs{pointer-events:none}@keyframes gramFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-2px)}}
 .ton-connect-card{position:relative;overflow:hidden;padding:14px;margin:0 0 10px;border-radius:20px}.ton-connect-card:before{content:'';position:absolute;width:130px;height:130px;right:-55px;top:-70px;border-radius:50%;background:radial-gradient(circle,rgba(51,161,255,.16),transparent 68%);pointer-events:none}.ton-connect-main{position:relative;display:flex;align-items:center;gap:11px}.ton-connect-copy{min-width:0;flex:1}.ton-connect-copy span{font-size:9px;opacity:.52;font-weight:900;letter-spacing:.1em}.ton-connect-copy b{display:block;margin-top:2px;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ton-connect-copy small{display:flex;align-items:center;gap:5px;margin-top:2px;font-size:10px;opacity:.58}.wallet-live-dot{width:6px;height:6px;border-radius:50%;background:#54e58a;box-shadow:0 0 9px rgba(84,229,138,.7)}.wallet-sync{font-size:8px;opacity:.45;margin-left:auto}.connected-pill{display:inline-flex;align-items:center;gap:5px;margin-top:6px;padding:4px 7px;border-radius:999px;background:rgba(58,224,138,.08);border:1px solid rgba(73,226,148,.14);font-size:9px;font-weight:850;color:#a9f4cb}.ton-connect-actions{margin-top:10px;display:flex;gap:8px}.ton-connect-actions button{position:relative;flex:1;min-height:42px;padding:0 12px;border-radius:14px;border:1px solid rgba(255,255,255,.08);background:linear-gradient(180deg,rgba(255,255,255,.09),rgba(255,255,255,.035));box-shadow:inset 0 1px 0 rgba(255,255,255,.11),0 6px 14px rgba(0,0,0,.12);color:#fff;font-size:12px;font-weight:950;letter-spacing:.02em;transition:.16s transform}.ton-connect-actions button:active{transform:translateY(2px) scale(.987)}.ton-connect-actions .connect{border-color:rgba(103,202,255,.3);background:linear-gradient(180deg,#34b4ff,#087fdc);box-shadow:inset 0 1px 0 rgba(255,255,255,.28),0 8px 20px rgba(8,126,228,.23)}
 .compact-balance{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 14px;margin-bottom:10px;border-radius:18px}.compact-balance .balance-copy span{font-size:9px;opacity:.48;font-weight:900;letter-spacing:.09em}.compact-balance .balance-copy div{display:flex;align-items:baseline;gap:7px;margin-top:1px}.compact-balance strong{font-size:27px;line-height:1}.compact-balance b{font-size:11px;opacity:.62}.compact-balance .rate{text-align:right;font-size:10px;line-height:1.35;opacity:.58}.compact-balance .rate strong{display:block;font-size:11px;color:#fff;opacity:1}
 .compact-gram-wallet .withdraw-v2{padding:13px 14px;border-radius:20px}.compact-gram-wallet .withdraw-progress{margin:0 0 11px}.compact-gram-wallet .progress-node span{width:31px;height:31px;font-size:12px}.compact-gram-wallet .progress-node small{font-size:9px;margin-top:4px}.compact-gram-wallet .step-panel{padding-top:0}.compact-gram-wallet .cooldown-state{margin:8px 0;padding:10px 11px;border-radius:13px;font-size:11px}.wallet-ready-card{display:flex;align-items:center;gap:10px;padding:11px 12px;border-radius:15px;background:rgba(31,145,236,.07);border:1px solid rgba(80,177,255,.12)}.wallet-ready-card .gram-icon-shell{width:32px;height:32px;border-radius:10px}.wallet-ready-card .gram-icon-shell img,.wallet-ready-card .gram-icon-shell object{width:23px;height:23px}.wallet-ready-card div{min-width:0;flex:1}.wallet-ready-card b{display:block;font-size:12px}.wallet-ready-card span{display:block;margin-top:2px;font-size:10px;opacity:.56;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.gram-note{margin-top:8px;padding:9px 10px;border-radius:12px;background:rgba(20,145,255,.07);border:1px solid rgba(36,158,255,.1);font-size:10px;line-height:1.35;opacity:.72}.network-title{display:flex;align-items:center;gap:8px}.network-title .gram-icon-shell{width:28px;height:28px;border-radius:9px}.network-title .gram-icon-shell img,.network-title .gram-icon-shell object{width:20px;height:20px}.compact-gram-wallet .network-banner{padding:10px 11px;border-radius:14px;margin-bottom:10px}.compact-gram-wallet .network-banner b{font-size:12px}.compact-gram-wallet .network-banner span{font-size:10px}.compact-gram-wallet .primary{min-height:44px;border-radius:14px;font-size:12px}.compact-gram-wallet .withdraw-history-section{padding-bottom:6px}.compact-gram-wallet .section-title{margin-top:12px}
 `}</style>
 <section className="ton-connect-card glass-panel"><div className="ton-connect-main"><GramIcon animated/><div className="ton-connect-copy"><span>GRAM WALLET · TON</span><b>{tonWallet?short(tonWallet):'Connect your TON wallet'}</b><small>{tonWallet?<><i className="wallet-live-dot"/>{tonProvider||'TON Connect'} · Synced</>:<>Secure TON Connect · No seed phrase</>} {syncing&&<em className="wallet-sync">SYNCING…</em>}</small>{tonWallet&&<div className="connected-pill"><i className="wallet-live-dot"/> CONNECTED</div>}</div></div><div className="ton-connect-actions">{tonWallet?<><button className="connect" onClick={()=>{setAmount('');setStep('amount')}} disabled={!canStart}>WITHDRAW GRAM</button><button onClick={disconnect} disabled={tonBusy}>DISCONNECT</button></>:<button className="connect" onClick={connect} disabled={tonBusy}>{tonBusy?'OPENING WALLET…':'CONNECT TON WALLET'}</button>}</div></section>
 <section className="compact-balance glass-panel"><div className="balance-copy"><span>AVAILABLE BALANCE</span><div><strong>{money(balance)}</strong><b>W</b></div></div><div className="rate"><strong>{money(WIENER_PER_USDT)} = 1 USDT</strong>{tonUsd?`Gram ≈ $${money(tonUsd,3)}`:'Loading Gram price…'}</div></section>
 <section className="withdraw-v2 glass-panel"><div className="withdraw-progress">{progress.map((label,i)=><div className="progress-node" key={label}><span className={i<idx?'done':i===idx?'active':''}>{i<idx?'✓':i+1}</span><small>{label}</small>{i<2&&<i className={i<idx?'done':''}/>}</div>)}</div>
 {cooldownMs>0&&<div className="cooldown-state">Next withdrawal in <b>{formatLeft(cooldownMs)}</b></div>}{hasPending&&<div className="cooldown-state">Withdrawal pending · wait for processing before another request.</div>}{!globalEnabled&&<div className="cooldown-state">Withdrawals are temporarily disabled.</div>}
 {step==='wallet'&&<div className="step-panel">{tonWallet?<div className="wallet-ready-card"><GramIcon/><div><b>Ready for Gram withdrawal</b><span>{short(tonWallet)} · {tonProvider||'TON Connect'}</span></div></div>:<div className="gram-note">Connect your TON wallet above to continue. WIENER Farm never receives your seed phrase or private key.</div>}{tonWallet&&<button className="primary" disabled={!canStart} onClick={()=>{setAmount('');setStep('amount')}}>ENTER WIENER AMOUNT</button>}</div>}
 {step==='amount'&&method&&<div className="step-panel"><button className="withdraw-back" onClick={()=>setStep('wallet')}>← Back</button><div className="network-banner"><div className="network-title"><GramIcon/><div><b>Gram (TON)</b><span>{short(tonWallet)}</span></div></div></div><div className="available-line"><span>Available</span><b>{money(balance)} WIENER</b></div><label>ENTER AMOUNT IN WIENER</label><input className="withdraw-input" type="number" inputMode="decimal" step="1" placeholder="0 WIENER" value={amount} onChange={e=>setAmount(e.target.value)}/><div className="quick-withdraw"><button onClick={()=>quick('min')}>MIN</button><button onClick={()=>quick('25')}>25%</button><button onClick={()=>quick('50')}>50%</button><button onClick={()=>quick('max')}>MAX</button></div><div className="withdraw-breakdown"><div><span>WIENER deducted</span><b>{money(Math.min(entered,balance),1)}</b></div><div><span>USD value</span><b>${money(usdValue,6)}</b></div><div><span>Gram price</span><b>${money(tonUsdNum,3)}</b></div><div><span>Gram value</span><b>{money(tonGross,6)} GRAM</b></div><div><span>Fee</span><b>{money(fee,6)} GRAM</b></div><div><span>You receive</span><b>{money(tonReceive,6)} GRAM</b></div></div>{entered>balance+1e-9&&<div className="withdraw-warning">Insufficient WIENER balance.</div>}{entered>0&&tonGross<Number(method.minimum_usdt)&&<div className="withdraw-warning">Minimum is {money(minimumUsdt,4)} GRAM (about {Math.ceil(Number(method.minimum_usdt)*tonUsdNum*WIENER_PER_USDT)} WIENER at the current price).</div>}<button className="primary" disabled={!canAmount} onClick={()=>setStep('review')}>REVIEW WITHDRAWAL</button></div>}
 {step==='review'&&method&&<div className="step-panel"><button className="withdraw-back" onClick={()=>setStep('amount')}>← Back</button><div className="review-withdraw"><h3 className="network-title"><GramIcon/> Review Gram</h3><div><span>WIENER Amount</span><b>{money(entered,1)} WIENER</b></div><div><span>USD Value</span><b>${money(usdValue,6)}</b></div><div><span>Live Gram Price</span><b>≈ ${money(tonUsdNum,3)}</b></div><div><span>Estimated Gram</span><b>{money(tonGross,6)} GRAM</b></div><div><span>Fee</span><b>{money(fee,6)} GRAM</b></div><div><span>You Receive</span><b>{money(tonReceive,6)} GRAM</b></div><div><span>Wallet</span><b>{short(tonWallet)}</b></div></div><div className="gram-note">Final Gram amount may move slightly because the backend refreshes the TON price on confirmation.</div><button className="primary confirm-withdraw" disabled={busy||!canAmount} onClick={submit}>{busy?'CALCULATING…':'CONFIRM GRAM WITHDRAWAL'}</button></div>}
 {message&&<div className="withdraw-message">{message}</div>}</section>
 <section className="withdraw-history-section"><div className="section-title"><div><h3>Withdrawal History</h3><p>Tap any row for full details.</p></div><button onClick={()=>load(true)}>↻</button></div><div className="withdraw-history-list">{history.length?history.map((w:any)=>{const st=statusView(String(w.status)),u=w.method_key==='gram_ton'?'GRAM':'USDT';return <button className="withdraw-history-row" key={w.id} onClick={()=>setSelected(w)}><div><b>{money(w.gross_usdt,4)} {u} · {w.network}</b><small>{date(w.created_at)}</small></div><div><strong>{money(w.receive_usdt,4)} {u}</strong><span>{st.icon} {st.label}</span></div></button>}):<div className="history-empty">No withdrawals yet.</div>}</div></section>
 {selected&&<div className="withdraw-sheet-backdrop" onClick={()=>setSelected(null)}><div className="withdraw-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-grabber"/><div className="sheet-head"><h3>Withdrawal Details</h3><button onClick={()=>setSelected(null)}>×</button></div>{(()=>{const u=selected.method_key==='gram_ton'?'GRAM':'USDT';return [['Withdrawal ID',selected.id],['WIENER Deducted',`${money(Number(selected.amount_farm||0),1)} WIENER`],['Requested Amount',`${money(selected.gross_usdt,6)} ${u}`],['Fee',`${money(selected.fee_usdt,6)} ${u}`],['Amount Received',`${money(selected.receive_usdt,6)} ${u}`],['Network',selected.network],['Wallet',selected.wallet_address],['Requested',date(selected.created_at)],['Status',statusView(String(selected.status)).label],['TX Hash',selected.tx_hash||'—']].map(([k,v])=><div className="sheet-row" key={String(k)}><span>{k}</span><b>{v}</b></div>)})()}{selected.explorer_url&&<button className="primary" onClick={()=>window.Telegram?.WebApp?.openLink?.(selected.explorer_url)}>OPEN BLOCKCHAIN EXPLORER</button>}</div></div>}
 </div>
}