import {useEffect,useState} from 'react';
import {TonConnectUI} from '@tonconnect/ui';
import {date,getInitData,money,PUBLISHABLE_KEY,SUPABASE_URL,type Snapshot,withdrawApi} from './lib';

type Method={method_key:string;label:string;network:'TON'|'Polygon';enabled:boolean;minimum_usdt:number;fee_usdt:number;sort_order:number};
type Step='wallet'|'amount'|'review';
const GRAM_ANIM='https://wiener-farm.vercel.app/api/host/gram-icon';
const GRAM_STATIC='https://wiener-farm.vercel.app/api/host/gram-static';
const MANIFEST='https://wiener-farm.vercel.app/tonconnect-manifest.json';
const WIENER_PER_USDT=15000;
let tonUI:TonConnectUI|null=null;
const getTonUI=()=>tonUI||(tonUI=new TonConnectUI({manifestUrl:MANIFEST}));
const short=(w:string)=>w.length<20?w:`${w.slice(0,8)}…${w.slice(-6)}`;
const statusView=(s:string)=>s==='paid'?{icon:'🟢',label:'PAID'}:s==='rejected'?{icon:'🔴',label:'REJECTED'}:{icon:'🟡',label:'PENDING'};
function remaining(until:string|null){if(!until)return 0;return Math.max(0,new Date(until).getTime()-Date.now())}
function formatLeft(ms:number){const t=Math.ceil(ms/1000),h=Math.floor(t/3600),m=Math.floor((t%3600)/60),s=t%60;return h?`${h}h ${m}m ${s}s`:m?`${m}m ${s}s`:`${s}s`}
async function tonApi(action:string,body:any={}){const r=await fetch(`${SUPABASE_URL}/functions/v1/wiener-ton-wallet`,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUBLISHABLE_KEY},body:JSON.stringify({action,initData:getInitData(),...body})});const x=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok||!x.ok)throw new Error(x.message||x.error||'Gram withdrawal request failed');return x.data??x}

function GramIcon({animated=false}:{animated?:boolean}){
 return <span className={`gram-icon-shell ${animated?'animated':''}`} aria-hidden="true">
  {animated?<object data={GRAM_ANIM} type="application/x-tgsticker" className="gram-tgs"><img src={GRAM_STATIC} alt=""/></object>:<img src={GRAM_STATIC} alt=""/>}
 </span>
}

export function WalletV2({data}:{data:Snapshot;setTab:any}){
 const preloaded=Array.isArray(data.withdrawal_methods)?data.withdrawal_methods as Method[]:[];
 const [method,setMethod]=useState<Method|null>(preloaded.find(x=>x.method_key==='gram_ton')||null);
 const [step,setStep]=useState<Step>('wallet'),[amount,setAmount]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[history,setHistory]=useState<any[]>(data.withdrawals||[]),[selected,setSelected]=useState<any>(null),[balance,setBalance]=useState(Number(data.user.balance||0)),[cooldownUntil,setCooldownUntil]=useState<string|null>(null),[cooldownMs,setCooldownMs]=useState(0),[hasPending,setHasPending]=useState((data.withdrawals||[]).some((w:any)=>String(w.status)==='pending')),[globalEnabled,setGlobalEnabled]=useState(!!data.settings.withdrawals_enabled),[tonWallet,setTonWallet]=useState(''),[tonProvider,setTonProvider]=useState(''),[tonUsd,setTonUsd]=useState<number|null>(null),[tonBusy,setTonBusy]=useState(false),[syncing,setSyncing]=useState(false);
 const entered=Number(amount||0),tonUsdNum=Number(tonUsd||0),fee=Number(method?.fee_usdt||0),usdValue=entered/WIENER_PER_USDT,tonGross=tonUsdNum>0?usdValue/tonUsdNum:0,tonReceive=Math.max(0,tonGross-fee);
 const canAmount=!!method&&globalEnabled&&method.enabled&&!hasPending&&cooldownMs<=0&&!!tonWallet&&tonUsdNum>0&&Number.isFinite(entered)&&entered>0&&entered<=balance+1e-9&&tonGross>=Number(method.minimum_usdt)&&tonGross>fee;
 const load=async(showError=false)=>{try{setSyncing(true);const [m,h,t]=await Promise.all([withdrawApi('methods'),withdrawApi('history'),tonApi('status')]);const gram=(m.methods||[]).find((x:Method)=>x.method_key==='gram_ton')||t.method||null;setMethod(gram);setBalance(Number(m.balance??balance));setCooldownUntil(m.cooldown_until||null);setCooldownMs(remaining(m.cooldown_until||null));setHasPending(!!m.has_pending);setGlobalEnabled(m.settings?.withdrawals_enabled!==false);setHistory(h||[]);setTonUsd(t.ton_usd==null?null:Number(t.ton_usd));if(t.wallet?.address){setTonWallet(String(t.wallet.address));setTonProvider(String(t.wallet.provider||'TON Connect'))}else{setTonWallet('');setTonProvider('')}}catch(e:any){if(showError||!preloaded.length)setMessage(String(e.message||e).replace(/_/g,' '))}finally{setSyncing(false)}};
 const bindConnected=async(w:any,silent=false)=>{if(!w?.account?.address)return false;const rawAddress=String(w.account.address),provider=String(w.device?.appName||w.device?.name||'TON Connect');try{const bound=await tonApi('bind',{address:rawAddress,provider});setTonWallet(String(bound.address));setTonProvider(String(bound.provider||provider));if(!silent)setMessage('✅ Gram (TON) wallet connected');return true}catch(e:any){try{await getTonUI().disconnect()}catch{}setTonWallet('');setTonProvider('');const raw=String(e.message||e);setMessage(raw.includes('ton_wallet_already_used')?'This TON wallet is already connected to another WIENER Farm account.':raw.replace(/_/g,' '));return false}};
 useEffect(()=>{const ui=getTonUI();let alive=true;const syncNow=async()=>{if(!alive)return;try{setSyncing(true);const current=(ui as any).wallet;if(current?.account?.address)await bindConnected(current,true);await load(false)}finally{if(alive)setSyncing(false)}};syncNow();const off=ui.onStatusChange(async(w:any)=>{if(w?.account?.address){await bindConnected(w);await load(false)}else{setTonWallet('');setTonProvider('');await load(false)}});const onFocus=()=>syncNow();const onVisible=()=>{if(document.visibilityState==='visible')syncNow()};window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onVisible);return()=>{alive=false;try{off()}catch{}window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onVisible)}},[]);
 useEffect(()=>{if(!cooldownUntil)return;const tick=()=>setCooldownMs(remaining(cooldownUntil));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[cooldownUntil]);
 const connect=async()=>{try{setTonBusy(true);setMessage('');await getTonUI().openModal()}catch(e:any){setMessage(String(e.message||e))}finally{setTonBusy(false)}};
 const disconnect=async()=>{try{setTonBusy(true);await getTonUI().disconnect();await tonApi('unbind');setTonWallet('');setTonProvider('');setStep('wallet');await load(false)}catch(e:any){setMessage(String(e.message||e).replace(/_/g,' '))}finally{setTonBusy(false)}};
 const quick=(v:'min'|'25'|'50'|'max')=>{if(!method)return;const minW=Math.ceil(Number(method.minimum_usdt)*tonUsdNum*WIENER_PER_USDT),raw=v==='min'?minW:v==='25'?balance*.25:v==='50'?balance*.5:balance;setAmount(String(Math.max(0,Math.floor(raw))))};
 const submit=async()=>{if(!canAmount||busy)return;try{setBusy(true);setMessage('');const x=await tonApi('withdraw',{amount_wiener:entered});setBalance(Number(x.balance??balance));setHistory(p=>x.withdrawal?[x.withdrawal,...p]:p);setHasPending(true);setAmount('');setStep('wallet');if(x.ton_usd)setTonUsd(Number(x.ton_usd));setMessage('✅ Gram (TON) withdrawal request created. Status: Pending')}catch(e:any){const raw=String(e.message||e);setMessage(raw.includes('ton_price_unavailable')?'Live TON price is temporarily unavailable. Please try again shortly.':raw.replace(/_/g,' '))}finally{setBusy(false)}};
 const progress=['Wallet','WIENER','Review'],idx=step==='wallet'?0:step==='amount'?1:2;
 return <div className="wallet-v2-page"><style>{`
 .gram-icon-shell{position:relative;width:46px;height:46px;display:grid;place-items:center;flex:0 0 auto;border-radius:16px;background:linear-gradient(145deg,rgba(73,178,255,.2),rgba(25,78,155,.08));border:1px solid rgba(109,198,255,.2);box-shadow:inset 0 1px 0 rgba(255,255,255,.18),0 12px 30px rgba(0,83,170,.18);transform:translateZ(0)}
 .gram-icon-shell:after{content:'';position:absolute;inset:6px;border-radius:12px;background:radial-gradient(circle at 32% 25%,rgba(255,255,255,.24),transparent 54%);pointer-events:none}.gram-icon-shell img,.gram-icon-shell object{width:34px;height:34px;object-fit:contain;display:block}.gram-icon-shell.animated{animation:gramFloat 3s ease-in-out infinite}.gram-tgs{pointer-events:none}@keyframes gramFloat{0%,100%{transform:translateY(0) rotate(-2deg)}50%{transform:translateY(-3px) rotate(2deg)}}
 .ton-connect-card{position:relative;overflow:hidden;padding:16px;margin-bottom:14px;border-radius:22px}.ton-connect-card:before{content:'';position:absolute;width:160px;height:160px;right:-65px;top:-80px;border-radius:50%;background:radial-gradient(circle,rgba(51,161,255,.19),transparent 68%);pointer-events:none}.ton-connect-main{position:relative;display:flex;align-items:center;gap:12px}.ton-connect-copy{min-width:0;flex:1}.ton-connect-copy span{font-size:10px;opacity:.58;font-weight:900;letter-spacing:.09em}.ton-connect-copy b{display:block;margin-top:4px;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ton-connect-copy small{display:flex;align-items:center;gap:5px;margin-top:4px;opacity:.62}.wallet-live-dot{width:6px;height:6px;border-radius:50%;background:#54e58a;box-shadow:0 0 10px rgba(84,229,138,.75)}.wallet-sync{font-size:9px;opacity:.48;margin-left:auto}.ton-connect-actions{margin-top:13px;display:flex;gap:9px}.ton-connect-actions button{position:relative;isolation:isolate;flex:1;min-height:46px;padding:0 14px;border-radius:15px;border:1px solid rgba(255,255,255,.09);background:linear-gradient(180deg,rgba(255,255,255,.1),rgba(255,255,255,.045));box-shadow:inset 0 1px 0 rgba(255,255,255,.12),0 7px 18px rgba(0,0,0,.14);color:#fff;font-weight:950;letter-spacing:.025em;transition:.18s transform,.18s filter}.ton-connect-actions button:active{transform:translateY(2px) scale(.985)}.ton-connect-actions .connect{border:1px solid rgba(103,202,255,.34);background:linear-gradient(180deg,#37b7ff,#087ee4);box-shadow:inset 0 1px 0 rgba(255,255,255,.3),0 10px 24px rgba(8,126,228,.28)}.ton-connect-actions .connect:after{content:'';position:absolute;z-index:-1;left:7%;right:7%;bottom:-7px;height:18px;border-radius:50%;background:rgba(23,145,240,.2);filter:blur(8px)}.connected-pill{display:inline-flex;align-items:center;gap:6px;margin-top:8px;padding:5px 8px;border-radius:999px;background:rgba(58,224,138,.09);border:1px solid rgba(73,226,148,.15);font-size:10px;font-weight:850;color:#a9f4cb}.gram-note{margin-top:9px;padding:10px 12px;border-radius:13px;background:rgba(20,145,255,.08);border:1px solid rgba(36,158,255,.12);font-size:11px;opacity:.8}.network-title{display:flex;align-items:center;gap:9px}.network-title .gram-icon-shell{width:30px;height:30px;border-radius:10px}.network-title .gram-icon-shell img,.network-title .gram-icon-shell object{width:22px;height:22px}
 `}</style>
 <section className="ton-connect-card glass-panel"><div className="ton-connect-main"><GramIcon animated/><div className="ton-connect-copy"><span>GRAM WALLET · TON</span><b>{tonWallet?short(tonWallet):'Connect your TON wallet'}</b><small>{tonWallet?<><i className="wallet-live-dot"/>{tonProvider||'TON Connect'} · Synced</>:<>Secure TON Connect · No seed phrase</>} {syncing&&<em className="wallet-sync">SYNCING…</em>}</small>{tonWallet&&<div className="connected-pill"><i className="wallet-live-dot"/> CONNECTED & READY</div>}</div></div><div className="ton-connect-actions">{tonWallet?<><button className="connect" onClick={()=>{setAmount('');setStep('amount')}} disabled={!method?.enabled||!globalEnabled||hasPending||cooldownMs>0||tonUsdNum<=0}>WITHDRAW GRAM</button><button onClick={disconnect} disabled={tonBusy}>DISCONNECT</button></>:<button className="connect" onClick={connect} disabled={tonBusy}>{tonBusy?'OPENING WALLET…':'CONNECT TON WALLET'}</button>}</div></section>
 <section className="withdraw-balance glass-panel"><span className="eyebrow">AVAILABLE BALANCE</span><div><strong>{money(balance)}</strong><b>WIENER</b></div><p>15,000 WIENER = 1 USDT{tonUsd?` · Gram ≈ $${tonUsd.toFixed(3)}`:''}</p></section>
 <section className="withdraw-v2 glass-panel"><div className="withdraw-progress">{progress.map((label,i)=><div className="progress-node" key={label}><span className={i<idx?'done':i===idx?'active':''}>{i<idx?'✓':i+1}</span><small>{label}</small>{i<2&&<i className={i<idx?'done':''}/>}</div>)}</div>
 {cooldownMs>0&&<div className="cooldown-state">Next withdrawal available in <b>{formatLeft(cooldownMs)}</b></div>}{hasPending&&<div className="cooldown-state">Withdrawal pending · another request unlocks after processing.</div>}
 {!globalEnabled&&<div className="cooldown-state">Withdrawals are temporarily disabled.</div>}
 {step==='wallet'&&<div className="step-panel"><div className="network-banner"><div className="network-title"><GramIcon/><div><b>Gram (TON)</b><span>Native TON payout using your connected wallet. No manual wallet address.</span></div></div></div>{tonWallet?<><div className="review-withdraw"><div><span>Status</span><b>✅ Connected</b></div><div><span>Wallet</span><b>{short(tonWallet)}</b></div><div><span>Provider</span><b>{tonProvider||'TON Connect'}</b></div></div><div className="gram-note">One TON wallet can only be linked to one WIENER Farm account.</div><button className="primary" disabled={!method?.enabled||!globalEnabled||hasPending||cooldownMs>0||tonUsdNum<=0} onClick={()=>{setAmount('');setStep('amount')}}>ENTER WIENER AMOUNT</button></>:<><div className="gram-note">Connect Tonkeeper, TON Space, MyTonWallet or another TON Connect wallet. WIENER Farm never receives your seed phrase or private key.</div><button className="primary" onClick={connect} disabled={tonBusy}>{tonBusy?'CONNECTING…':'CONNECT TON WALLET'}</button></>}</div>}
 {step==='amount'&&method&&<div className="step-panel"><button className="withdraw-back" onClick={()=>setStep('wallet')}>← Back</button><div className="network-banner"><div className="network-title"><GramIcon/><div><b>Gram (TON)</b><span>Connected: <strong>{short(tonWallet)}</strong></span></div></div></div><div className="available-line"><span>Available</span><b>{money(balance)} WIENER</b></div><label>ENTER AMOUNT IN WIENER</label><input className="withdraw-input" type="number" inputMode="decimal" step="1" placeholder="0 WIENER" value={amount} onChange={e=>setAmount(e.target.value)}/><div className="quick-withdraw"><button onClick={()=>quick('min')}>MIN</button><button onClick={()=>quick('25')}>25%</button><button onClick={()=>quick('50')}>50%</button><button onClick={()=>quick('max')}>MAX</button></div><div className="withdraw-breakdown"><div><span>WIENER deducted</span><b>{money(Math.min(entered,balance),1)}</b></div><div><span>USD value</span><b>${usdValue.toFixed(6)}</b></div><div><span>Gram price</span><b>${tonUsdNum.toFixed(3)}</b></div><div><span>Gram value</span><b>{tonGross.toFixed(6)} GRAM</b></div><div><span>Fee</span><b>{fee.toFixed(6)} GRAM</b></div><div><span>You receive</span><b>{tonReceive.toFixed(6)} GRAM</b></div></div>{entered>balance+1e-9&&<div className="withdraw-warning">Insufficient WIENER balance.</div>}{entered>0&&tonGross<Number(method.minimum_usdt)&&<div className="withdraw-warning">Minimum is {Number(method.minimum_usdt).toFixed(4)} GRAM (about {Math.ceil(Number(method.minimum_usdt)*tonUsdNum*WIENER_PER_USDT)} WIENER at the current price).</div>}<div className="gram-note">Automatic conversion: WIENER ÷ 15,000 = USD value, then USD value ÷ live TON/USD price = Gram.</div><button className="primary" disabled={!canAmount} onClick={()=>setStep('review')}>REVIEW WITHDRAWAL</button></div>}
 {step==='review'&&method&&<div className="step-panel"><button className="withdraw-back" onClick={()=>setStep('amount')}>← Back</button><div className="review-withdraw"><h3 className="network-title"><GramIcon/> Review Gram (TON)</h3><div><span>WIENER Amount</span><b>{money(entered,1)} WIENER</b></div><div><span>WIENER Rate</span><b>15,000 = 1 USDT</b></div><div><span>USD Value</span><b>${usdValue.toFixed(6)}</b></div><div><span>Live Gram Price</span><b>≈ ${tonUsdNum.toFixed(3)}</b></div><div><span>Estimated Gram</span><b>{tonGross.toFixed(6)} GRAM</b></div><div><span>Fee</span><b>{fee.toFixed(6)} GRAM</b></div><div><span>You Receive</span><b>{tonReceive.toFixed(6)} GRAM</b></div><div><span>Connected Wallet</span><b>{short(tonWallet)}</b></div><div><span>Network</span><b>TON</b></div></div><div className="gram-note">The backend fetches a fresh TON price on confirmation, so the final Gram amount may move slightly with the market.</div><button className="primary confirm-withdraw" disabled={busy||!canAmount} onClick={submit}>{busy?'CALCULATING…':'CONFIRM GRAM WITHDRAWAL'}</button></div>}
 {message&&<div className="withdraw-message">{message}</div>}</section>
 <section className="withdraw-history-section"><div className="section-title"><div><h3>Withdrawal History</h3><p>Tap any row for full details.</p></div><button onClick={()=>load(true)}>↻</button></div><div className="withdraw-history-list">{history.length?history.map((w:any)=>{const st=statusView(String(w.status)),u=w.method_key==='gram_ton'?'GRAM':'USDT';return <button className="withdraw-history-row" key={w.id} onClick={()=>setSelected(w)}><div><b>{Number(w.gross_usdt).toFixed(4)} {u} · {w.network}</b><small>{date(w.created_at)}</small></div><div><strong>{Number(w.receive_usdt).toFixed(4)} {u}</strong><span>{st.icon} {st.label}</span></div></button>}):<div className="history-empty">No withdrawals yet.</div>}</div></section>
 {selected&&<div className="withdraw-sheet-backdrop" onClick={()=>setSelected(null)}><div className="withdraw-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-grabber"/><div className="sheet-head"><h3>Withdrawal Details</h3><button onClick={()=>setSelected(null)}>×</button></div>{(()=>{const u=selected.method_key==='gram_ton'?'GRAM':'USDT';return [['Withdrawal ID',selected.id],['WIENER Deducted',`${money(Number(selected.amount_farm||0),1)} WIENER`],['Requested Amount',`${Number(selected.gross_usdt).toFixed(6)} ${u}`],['Fee',`${Number(selected.fee_usdt).toFixed(6)} ${u}`],['Amount Received',`${Number(selected.receive_usdt).toFixed(6)} ${u}`],['Network',selected.network],['Wallet',selected.wallet_address],['Requested',date(selected.created_at)],['Status',statusView(String(selected.status)).label],['TX Hash',selected.tx_hash||'—']].map(([k,v])=><div className="sheet-row" key={String(k)}><span>{k}</span><b>{v}</b></div>)})()}{selected.explorer_url&&<button className="primary" onClick={()=>window.Telegram?.WebApp?.openLink?.(selected.explorer_url)}>OPEN BLOCKCHAIN EXPLORER</button>}</div></div>}
 </div>
}