import {useEffect,useMemo,useState} from 'react';
import {date,money,type Snapshot,withdrawApi} from './lib';
import {AnimatedIcon} from './icons';

type Method={method_key:string;label:string;network:'TON'|'Polygon';enabled:boolean;minimum_usdt:number;fee_usdt:number;sort_order:number};
type Step='method'|'amount'|'wallet'|'review';
const TON_ICON='https://pixlinkhost.vercel.app/i/1AcOzN0LcQ';
const USDT_ICON='https://pixlinkhost.vercel.app/i/DtKRX3jFfg';
const stepIndex:Record<Step,number>={method:0,amount:1,wallet:2,review:3};
const errText:Record<string,string>={withdraw_cooldown:'Please wait until your withdrawal cooldown ends.',withdrawal_already_pending:'You already have a pending withdrawal.',withdraw_method_disabled:'This withdrawal method is temporarily unavailable.',below_minimum:'Amount is below the current minimum.',insufficient_balance:'Insufficient WIENER balance.',invalid_polygon_wallet:'Enter a valid Polygon 0x wallet address.',invalid_ton_wallet:'Enter a valid TON wallet address.',invalid_amount:'Enter a valid withdrawal amount.',withdrawals_disabled:'Withdrawals are temporarily unavailable.',amount_below_fee:'Amount must be greater than the withdrawal fee.'};
const humanError=(e:any)=>errText[String(e?.message||e)]||'Something went wrong. Please try again.';
const haptic=(kind:'light'|'medium'|'success'|'error'='light')=>{try{const h=(window as any).Telegram?.WebApp?.HapticFeedback;if(kind==='success'||kind==='error')h?.notificationOccurred?.(kind);else h?.impactOccurred?.(kind)}catch{}};
const shortWallet=(w:string)=>w.length<18?w:`${w.slice(0,8)}…${w.slice(-6)}`;
const statusView=(s:string)=>s==='paid'?{icon:'🟢',label:'PAID'}:s==='rejected'?{icon:'🔴',label:'REJECTED'}:{icon:'🟡',label:'PENDING'};
const floor4=(v:number)=>Math.floor(Math.max(0,v)*10000)/10000;
function remaining(until:string|null){if(!until)return 0;return Math.max(0,new Date(until).getTime()-Date.now())}
function formatLeft(ms:number){const t=Math.ceil(ms/1000),h=Math.floor(t/3600),m=Math.floor((t%3600)/60),s=t%60;return h?`${h}h ${m}m ${s}s`:m?`${m}m ${s}s`:`${s}s`}

export function WalletV2({data}:{data:Snapshot;setTab:any}){
  const s=data.settings;
  const [methods,setMethods]=useState<Method[]>([]),[step,setStep]=useState<Step>('method'),[methodKey,setMethodKey]=useState(''),[amount,setAmount]=useState(''),[wallet,setWallet]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[history,setHistory]=useState<any[]>(data.withdrawals||[]),[selected,setSelected]=useState<any>(null),[balance,setBalance]=useState(Number(data.user.balance||0)),[cooldownUntil,setCooldownUntil]=useState<string|null>(null),[cooldownMs,setCooldownMs]=useState(0),[hasPending,setHasPending]=useState(false),[globalEnabled,setGlobalEnabled]=useState(!!s.withdrawals_enabled);
  const rate=Number(s.token_per_usdt||10000),usd=balance/rate,method=methods.find(x=>x.method_key===methodKey),gross=Number(amount||0),fee=Number(method?.fee_usdt||0),receive=Math.max(0,gross-fee),needed=gross*rate;
  const load=async()=>{try{const [m,h]=await Promise.all([withdrawApi('methods'),withdrawApi('history')]);setMethods(m.methods||[]);setBalance(Number(m.balance??balance));setCooldownUntil(m.cooldown_until||null);setCooldownMs(remaining(m.cooldown_until||null));setHasPending(!!m.has_pending);setGlobalEnabled(m.settings?.withdrawals_enabled!==false);setHistory(h||[])}catch(e:any){setMessage(humanError(e))}};
  useEffect(()=>{load()},[]);
  useEffect(()=>{if(!cooldownUntil)return;const tick=()=>setCooldownMs(remaining(cooldownUntil));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[cooldownUntil]);
  const walletOk=useMemo(()=>{const w=wallet.trim();if(!method)return false;return method.network==='Polygon'?/^0x[a-fA-F0-9]{40}$/.test(w):/^(?:[EUUk0][Qq][A-Za-z0-9_-]{46}|(?:-1|0):[a-fA-F0-9]{64})$/.test(w)},[wallet,method]);
  const canAmount=!!method&&globalEnabled&&method.enabled&&!hasPending&&cooldownMs<=0&&Number.isFinite(gross)&&gross>=Number(method.minimum_usdt)&&gross>fee&&needed<=balance+1e-9;
  const go=(next:Step)=>{haptic('light');setStep(next);setMessage('')};
  const choose=(m:Method)=>{if(!m.enabled||!globalEnabled)return;haptic('light');setMethodKey(m.method_key);setAmount('');setWallet('');setStep('amount')};
  const quick=(v:'min'|'25'|'50'|'max')=>{if(!method)return;const max=usd,raw=v==='min'?Number(method.minimum_usdt):v==='25'?max*.25:v==='50'?max*.5:max,safe=v==='min'?Math.max(0,raw):floor4(raw);setAmount(safe.toFixed(4));haptic('light')};
  const submit=async()=>{if(!method||busy||!walletOk||!canAmount)return;haptic('medium');try{setBusy(true);setMessage('');const x=await withdrawApi('request',{method_key:method.method_key,amount_usdt:gross,wallet:wallet.trim()});setBalance(Number(x.balance??balance));setHistory(p=>x.withdrawal?[x.withdrawal,...p]:p);setHasPending(true);setCooldownUntil(new Date(Date.now()+Number(s.withdraw_cooldown_hours||0)*3600000).toISOString());setStep('method');setMethodKey('');setAmount('');setWallet('');setMessage('✅ Withdrawal request created. Status: Pending');haptic('success')}catch(e:any){setMessage(humanError(e));haptic('error')}finally{setBusy(false)}};
  const idx=stepIndex[step];
  return <div className="wallet-v2-page">
    <section className="withdraw-balance glass-panel"><span className="eyebrow">AVAILABLE BALANCE</span><div><strong>{money(balance)}</strong><b>WIENER</b></div><p>≈ {usd.toFixed(4)} USDT</p></section>
    <section className="withdraw-v2 glass-panel">
      <div className="withdraw-progress">{['Select','Amount','Wallet','Review'].map((label,i)=><div className="progress-node" key={label}><span className={i<idx?'done':i===idx?'active':''}>{i<idx?'✓':i+1}</span><small>{label}</small>{i<3&&<i className={i<idx?'done':''}/>}</div>)}</div>
      {cooldownMs>0&&<div className="cooldown-state">Next withdrawal available in <b>{formatLeft(cooldownMs)}</b></div>}
      {hasPending&&<div className="cooldown-state">You already have a pending withdrawal.</div>}
      {step==='method'&&<div className="step-panel"><div className="step-copy"><h3>Select withdrawal method</h3><p>Choose the exact network. WIENER never changes it automatically.</p></div><div className="method-grid">{methods.map(m=><button key={m.method_key} onClick={()=>choose(m)} disabled={!m.enabled||!globalEnabled} className={`method-card ${!m.enabled||!globalEnabled?'disabled':''}`}><span className="method-icon"><img src={m.network==='TON'?TON_ICON:USDT_ICON} alt={m.network==='TON'?'TON':'USDT'} style={{width:42,height:42,objectFit:'contain',display:'block'}}/></span><div><b>{m.label}</b><small>{m.enabled&&globalEnabled?`Min ${Number(m.minimum_usdt).toFixed(4)} USDT · Fee ${Number(m.fee_usdt).toFixed(4)} USDT`:'Temporarily unavailable'}</small></div>{(!m.enabled||!globalEnabled)&&<em>Unavailable</em>}<i>›</i></button>)}</div></div>}
      {step==='amount'&&method&&<div className="step-panel"><button className="withdraw-back" onClick={()=>go('method')}>← Back</button><div className="network-banner"><b>{method.label}</b><span>Selected network: <strong>{method.network}</strong></span></div><div className="available-line"><span>Available</span><b>{money(balance)} WIENER · ≈ {usd.toFixed(4)} USDT</b></div><label>ENTER WITHDRAWAL AMOUNT</label><input className="withdraw-input" type="number" inputMode="decimal" step="0.0001" placeholder="0.0000 USDT" value={amount} onChange={e=>setAmount(e.target.value)}/><div className="quick-withdraw"><button onClick={()=>quick('min')}>MIN</button><button onClick={()=>quick('25')}>25%</button><button onClick={()=>quick('50')}>50%</button><button onClick={()=>quick('max')}>MAX</button></div><div className="withdraw-breakdown"><div><span>Amount</span><b>{gross.toFixed(4)} USDT</b></div><div><span>Fee</span><b>{fee.toFixed(4)} USDT</b></div><div><span>You receive</span><b>{receive.toFixed(4)} USDT</b></div></div>{gross>0&&gross<Number(method.minimum_usdt)&&<div className="withdraw-warning">Minimum is {Number(method.minimum_usdt).toFixed(4)} USDT.</div>}{needed>balance+1e-9&&<div className="withdraw-warning">Insufficient WIENER balance.</div>}<button className="primary" disabled={!canAmount} onClick={()=>go('wallet')}>CONTINUE</button></div>}
      {step==='wallet'&&method&&<div className="step-panel"><button className="withdraw-back" onClick={()=>go('amount')}>← Back</button><div className="network-banner"><b>{method.label}</b><span>{method.network==='TON'?'Only enter a TON-compatible wallet. Funds will be sent using the TON network.':'Only enter a Polygon-compatible wallet. Funds will be sent using the Polygon network.'}</span></div><label>{method.network.toUpperCase()} WALLET ADDRESS</label><input className={`withdraw-input ${wallet&&!walletOk?'invalid':''}`} placeholder={method.network==='Polygon'?'0x…':'UQ… / EQ…'} value={wallet} onChange={e=>setWallet(e.target.value.trim())}/>{wallet&&!walletOk&&<div className="withdraw-warning" onMouseEnter={()=>haptic('error')}>Invalid {method.network} wallet address.</div>}<button className="primary" disabled={!walletOk||!canAmount} onClick={()=>go('review')}>REVIEW WITHDRAWAL</button></div>}
      {step==='review'&&method&&<div className="step-panel"><button className="withdraw-back" onClick={()=>go('wallet')}>← Back</button><div className="review-withdraw"><h3>Review Withdrawal</h3><div><span>Amount</span><b>{gross.toFixed(4)} USDT</b></div><div><span>Network</span><b>{method.network}</b></div><div><span>Fee</span><b>{fee.toFixed(4)} USDT</b></div><div><span>You Receive</span><b>{receive.toFixed(4)} USDT</b></div><div><span>Wallet</span><b>{shortWallet(wallet)}</b></div></div><button className="primary confirm-withdraw" disabled={busy||!walletOk||!canAmount} onClick={submit}>{busy?'CREATING…':'CONFIRM WITHDRAWAL'}</button></div>}
      {message&&<div className="withdraw-message">{message}</div>}
    </section>
    <section className="withdraw-history-section"><div className="section-title"><div><h3>Withdrawal History</h3><p>Tap any row for full details.</p></div><button onClick={load}>↻</button></div><div className="withdraw-history-list">{history.length?history.map((w:any)=>{const st=statusView(String(w.status));return <button className="withdraw-history-row" key={w.id} onClick={()=>{setSelected(w);haptic('light')}}><div><b>{Number(w.gross_usdt).toFixed(4)} USDT · {w.network}</b><small>{date(w.created_at)}</small></div><div><strong>{Number(w.receive_usdt).toFixed(4)} USDT</strong><span>{st.icon} {st.label}</span></div></button>}):<div className="history-empty">No withdrawals yet.</div>}</div></section>
    {selected&&<div className="withdraw-sheet-backdrop" onClick={()=>setSelected(null)}><div className="withdraw-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-grabber"/><div className="sheet-head"><h3>Withdrawal Details</h3><button onClick={()=>setSelected(null)}>×</button></div>{[['Withdrawal ID',selected.id],['Requested Amount',`${Number(selected.gross_usdt).toFixed(4)} USDT`],['Fee',`${Number(selected.fee_usdt).toFixed(4)} USDT`],['Amount Received',`${Number(selected.receive_usdt).toFixed(4)} USDT`],['Network',selected.network],['Wallet',selected.wallet_address],['Requested',date(selected.created_at)],['Processed',selected.processed_at?date(selected.processed_at):'—'],['Status',statusView(String(selected.status)).label],['TX Hash',selected.tx_hash||'—']].map(([k,v])=><div className="sheet-row" key={String(k)}><span>{k}</span><b>{v}</b></div>)}{selected.explorer_url&&<button className="primary" onClick={()=>window.Telegram?.WebApp?.openLink?.(selected.explorer_url)}>OPEN BLOCKCHAIN EXPLORER</button>}</div></div>}
  </div>
}

export function AdminWithdrawUpgrade({say}:{say:any}){
  const [d,setD]=useState<any>(null),[busy,setBusy]=useState(false);
  const load=async()=>{try{setBusy(true);setD(await withdrawApi('admin_boot'))}catch(e:any){say(humanError(e))}finally{setBusy(false)}};
  useEffect(()=>{load()},[]);
  if(!d)return <section className="admin-withdraw-v2 glass-panel"><h3>💸 Withdrawal System</h3><p>Loading secure payout controls…</p></section>;
  const patch=(key:string,k:string,v:any)=>setD({...d,methods:d.methods.map((m:any)=>m.method_key===key?{...m,[k]:v}:m)});
  const save=async(m:any)=>{try{setBusy(true);await withdrawApi('admin_method_save',{method:{method_key:m.method_key,enabled:m.enabled,minimum_usdt:Number(m.minimum_usdt),fee_usdt:Number(m.fee_usdt)}});say('✅ Withdrawal method saved');await load()}catch(e:any){say(humanError(e))}finally{setBusy(false)}};
  const paid=async(w:any)=>{const tx=prompt(`Enter ${w.network} transaction hash`,'')?.trim();if(!tx)return;if(!confirm(`Confirm PAID?\n\nAmount: ${Number(w.gross_usdt).toFixed(4)} USDT\nNetwork: ${w.network}\nTX: ${tx}`))return;try{setBusy(true);await withdrawApi('admin_paid',{id:w.id,tx_hash:tx});say('✅ Paid, user notified and @WienerPay post processed');await load()}catch(e:any){say(humanError(e))}finally{setBusy(false)}};
  const reject=async(w:any)=>{const note=prompt('Rejection reason (optional)','Rejected by admin')||'Rejected by admin';if(!confirm(`Reject this ${w.network} withdrawal?`))return;try{setBusy(true);await withdrawApi('admin_reject',{id:w.id,note});say('🔴 Withdrawal rejected and user notified');await load()}catch(e:any){say(humanError(e))}finally{setBusy(false)}};
  return <section className="admin-withdraw-v2 glass-panel"><div className="admin-upgrade-head"><div><span>SECURE PAYOUT CONTROL</span><h3>Withdrawal Methods</h3><p>Changes apply instantly without redeployment.</p></div><button onClick={load}>↻</button></div><div className="method-admin-grid">{d.methods.map((m:any)=><div className="method-admin-card" key={m.method_key}><div className="method-admin-title"><div style={{display:'flex',alignItems:'center',gap:10}}><img src={m.network==='TON'?TON_ICON:USDT_ICON} alt={m.network==='TON'?'TON':'USDT'} style={{width:32,height:32,objectFit:'contain',display:'block'}}/><div><b>{m.label}</b><small>{m.network} network</small></div></div><label className="method-switch"><input type="checkbox" checked={!!m.enabled} onChange={e=>patch(m.method_key,'enabled',e.target.checked)}/><span>{m.enabled?'Enabled':'Disabled'}</span></label></div><label>Minimum withdrawal<input type="number" step="0.0001" value={m.minimum_usdt} onChange={e=>patch(m.method_key,'minimum_usdt',e.target.value)}/></label><label>Withdrawal fee<input type="number" step="0.0001" value={m.fee_usdt} onChange={e=>patch(m.method_key,'fee_usdt',e.target.value)}/></label><button className="primary" disabled={busy} onClick={()=>save(m)}>SAVE {m.network.toUpperCase()}</button></div>)}</div><div className="admin-upgrade-head compact"><div><h3>Withdrawal Requests</h3><p>Pending → Paid or Rejected only.</p></div></div><div className="withdraw-admin-list">{d.withdrawals.length?d.withdrawals.map((w:any)=>{const st=statusView(String(w.status));return <div className={`withdraw-admin-row status-${w.status}`} key={w.id}><div className="withdraw-admin-main"><div><b>{w.username||`User ${w.telegram_id}`}</b><small>UID {w.telegram_id}</small></div><strong>{Number(w.gross_usdt).toFixed(4)} USDT</strong></div><div className="withdraw-admin-meta"><span>ID {String(w.id).slice(0,8)}…</span><span>🌐 {w.network}</span><span>Fee {Number(w.fee_usdt).toFixed(4)}</span><span>Final {Number(w.receive_usdt).toFixed(4)}</span><span>{date(w.created_at)}</span></div><code className="withdraw-wallet-code">{w.wallet_address}</code><div className="withdraw-admin-status"><b>{st.icon} {st.label}</b>{w.processing_admin&&<span>Admin {w.processing_admin}</span>}{w.processed_at&&<span>{date(w.processed_at)}</span>}</div>{w.tx_hash&&<div className="withdraw-tx">TX: {w.tx_hash}</div>}{w.status==='pending'&&<div className="row-actions"><button className="good" disabled={busy} onClick={()=>paid(w)}>✅ MARK PAID</button><button className="danger" disabled={busy} onClick={()=>reject(w)}>❌ REJECT</button></div>}</div>}):<div className="admin-empty">No withdrawal requests.</div>}</div></section>
}