import {useEffect,useMemo,useState} from 'react';
import {TonConnectUI} from '@tonconnect/ui';
import {date,getInitData,money,PUBLISHABLE_KEY,SUPABASE_URL,type Snapshot,withdrawApi} from './lib';

type Method={method_key:string;label:string;network:'TON'|'Polygon';enabled:boolean;minimum_usdt:number;fee_usdt:number;sort_order:number};
type Step='method'|'amount'|'wallet'|'review';
const TON_ICON='https://pixlinkhost.vercel.app/i/1AcOzN0LcQ';
const USDT_ICON='https://pixlinkhost.vercel.app/i/DtKRX3jFfg';
const MANIFEST='https://wiener-farm.vercel.app/tonconnect-manifest.json';
let tonUI:TonConnectUI|null=null;
const getTonUI=()=>tonUI||(tonUI=new TonConnectUI({manifestUrl:MANIFEST}));
const short=(w:string)=>w.length<20?w:`${w.slice(0,8)}…${w.slice(-6)}`;
const floor4=(v:number)=>Math.floor(Math.max(0,v)*10000+1e-9)/10000;
const statusView=(s:string)=>s==='paid'?{icon:'🟢',label:'PAID'}:s==='rejected'?{icon:'🔴',label:'REJECTED'}:{icon:'🟡',label:'PENDING'};
function remaining(until:string|null){if(!until)return 0;return Math.max(0,new Date(until).getTime()-Date.now())}
function formatLeft(ms:number){const t=Math.ceil(ms/1000),h=Math.floor(t/3600),m=Math.floor((t%3600)/60),s=t%60;return h?`${h}h ${m}m ${s}s`:m?`${m}m ${s}s`:`${s}s`}
async function tonApi(action:string,body:any={}){const r=await fetch(`${SUPABASE_URL}/functions/v1/wiener-ton-wallet`,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUBLISHABLE_KEY},body:JSON.stringify({action,initData:getInitData(),...body})});const x=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok||!x.ok)throw new Error(x.message||x.error||'TON wallet request failed');return x.data??x}

export function WalletV2({data}:{data:Snapshot;setTab:any}){
 const s=data.settings;
 const preloaded=Array.isArray(data.withdrawal_methods)?data.withdrawal_methods as Method[]:[];
 const [methods,setMethods]=useState<Method[]>(preloaded),[step,setStep]=useState<Step>('method'),[methodKey,setMethodKey]=useState(''),[amount,setAmount]=useState(''),[wallet,setWallet]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[history,setHistory]=useState<any[]>(data.withdrawals||[]),[selected,setSelected]=useState<any>(null),[balance,setBalance]=useState(Number(data.user.balance||0)),[cooldownUntil,setCooldownUntil]=useState<string|null>(null),[cooldownMs,setCooldownMs]=useState(0),[hasPending,setHasPending]=useState((data.withdrawals||[]).some((w:any)=>String(w.status)==='pending')),[globalEnabled,setGlobalEnabled]=useState(!!s.withdrawals_enabled),[tonWallet,setTonWallet]=useState(''),[tonProvider,setTonProvider]=useState(''),[tonRate,setTonRate]=useState<number|null>(null),[tonBusy,setTonBusy]=useState(false);
 const method=methods.find(x=>x.method_key===methodKey),isGram=methodKey==='gram_ton',baseRate=Number(s.token_per_usdt||15000),tonRateNum=Number(tonRate||0),entered=Number(amount||0),configuredFee=Number(method?.fee_usdt||0);
 const usdtGross=isGram?0:entered,usdtFee=!isGram&&usdtGross>0&&usdtGross<0.05?0:(!isGram?configuredFee:0),usdtReceive=Math.max(0,usdtGross-usdtFee),usdtNeeded=usdtGross*baseRate,usdtAvailable=balance/baseRate;
 const wienerAmount=isGram?entered:0,tonGross=isGram&&tonRateNum>0?wienerAmount/tonRateNum:0,tonFee=isGram?configuredFee:0,tonReceive=Math.max(0,tonGross-tonFee);
 const walletOk=useMemo(()=>{if(!method)return false;if(isGram)return !!tonWallet;const w=wallet.trim();return method.network==='Polygon'?/^0x[a-fA-F0-9]{40}$/.test(w):/^(?:[EUUk0][Qq][A-Za-z0-9_-]{46}|(?:-1|0):[a-fA-F0-9]{64})$/.test(w)},[wallet,method,isGram,tonWallet]);
 const canAmount=!!method&&globalEnabled&&method.enabled&&!hasPending&&cooldownMs<=0&&(isGram?(!!tonWallet&&tonRateNum>0&&Number.isFinite(wienerAmount)&&wienerAmount>0&&wienerAmount<=balance+1e-9&&tonGross>=Number(method.minimum_usdt)&&tonGross>tonFee):(Number.isFinite(usdtGross)&&usdtGross>=Number(method.minimum_usdt)&&usdtGross>usdtFee&&usdtNeeded<=balance+1e-9));
 const load=async(showError=false)=>{try{const [m,h,t]=await Promise.all([withdrawApi('methods'),withdrawApi('history'),tonApi('status')]);if(Array.isArray(m.methods))setMethods(m.methods);setBalance(Number(m.balance??balance));setCooldownUntil(m.cooldown_until||null);setCooldownMs(remaining(m.cooldown_until||null));setHasPending(!!m.has_pending);setGlobalEnabled(m.settings?.withdrawals_enabled!==false);setHistory(h||[]);setTonRate(t.wiener_per_ton==null?null:Number(t.wiener_per_ton));if(t.wallet?.address){setTonWallet(String(t.wallet.address));setTonProvider(String(t.wallet.provider||'TON Connect'))}else{setTonWallet('');setTonProvider('')}}catch(e:any){if(showError||!preloaded.length)setMessage(String(e.message||e).replace(/_/g,' '))}};
 useEffect(()=>{load(false);const ui=getTonUI();const off=ui.onStatusChange(async(w:any)=>{if(!w?.account?.address)return;const address=String(w.account.address),provider=String(w.device?.appName||w.device?.name||'TON Connect');try{await tonApi('bind',{address,provider});setTonWallet(address);setTonProvider(provider);setMessage('✅ TON wallet connected')}catch(e:any){try{await ui.disconnect()}catch{}setTonWallet('');setTonProvider('');const raw=String(e.message||e);setMessage(raw.includes('ton_wallet_already_used')?'This TON wallet is already connected to another WIENER Farm account.':raw.replace(/_/g,' '))}});return()=>{try{off()}catch{}}},[]);
 useEffect(()=>{if(!cooldownUntil)return;const tick=()=>setCooldownMs(remaining(cooldownUntil));tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[cooldownUntil]);
 const connect=async()=>{try{setTonBusy(true);setMessage('');await getTonUI().openModal()}catch(e:any){setMessage(String(e.message||e))}finally{setTonBusy(false)}};
 const disconnect=async()=>{try{setTonBusy(true);await getTonUI().disconnect();await tonApi('unbind');setTonWallet('');setTonProvider('');if(isGram)setWallet('')}catch(e:any){setMessage(String(e.message||e).replace(/_/g,' '))}finally{setTonBusy(false)}};
 const choose=(m:Method)=>{if(!m.enabled||!globalEnabled)return;setMethodKey(m.method_key);setAmount('');setWallet('');setStep(m.method_key==='gram_ton'?'wallet':'amount');setMessage('')};
 const quick=(v:'min'|'25'|'50'|'max')=>{if(!method)return;if(isGram){const minW=Math.ceil(Number(method.minimum_usdt)*tonRateNum*100)/100,raw=v==='min'?minW:v==='25'?balance*.25:v==='50'?balance*.5:balance;setAmount((v==='min'?raw:Math.floor(raw*100)/100).toFixed(2));return}const raw=v==='min'?Number(method.minimum_usdt):v==='25'?usdtAvailable*.25:v==='50'?usdtAvailable*.5:usdtAvailable;setAmount((v==='min'?raw:floor4(raw)).toFixed(4))};
 const submit=async()=>{if(!method||busy||!walletOk||!canAmount)return;try{setBusy(true);setMessage('');let x:any;if(isGram){x=await tonApi('withdraw',{amount_wiener:wienerAmount})}else{x=await withdrawApi('request',{method_key:method.method_key,amount_usdt:usdtGross,wallet:wallet.trim()})}setBalance(Number(x.balance??balance));setHistory(p=>x.withdrawal?[x.withdrawal,...p]:p);setHasPending(true);setStep('method');setMethodKey('');setAmount('');setWallet('');setMessage(`✅ ${isGram?'TON':'USDT'} withdrawal request created. Status: Pending`)}catch(e:any){setMessage(String(e.message||e).replace(/_/g,' '))}finally{setBusy(false)}};
 const idx=isGram?({method:0,wallet:1,amount:2,review:3}[step]):({method:0,amount:1,wallet:2,review:3}[step]);
 const progress=isGram?['Select','Wallet','WIENER','Review']:['Select','Amount','Wallet','Review'];
 return <div className="wallet-v2-page"><style>{`.ton-connect-card{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:15px 16px;margin-bottom:14px}.ton-connect-copy{min-width:0}.ton-connect-copy span{font-size:10px;opacity:.5;font-weight:900;letter-spacing:.08em}.ton-connect-copy b{display:block;margin-top:4px;font-size:14px}.ton-connect-copy small{display:block;margin-top:3px;opacity:.55}.ton-connect-actions{display:flex;gap:7px}.ton-connect-actions button{height:38px;padding:0 12px;border-radius:12px;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.06);color:#fff;font-weight:900}.ton-connect-actions .connect{background:linear-gradient(180deg,#25a8ff,#0787e8);border:0}.gram-note{margin-top:9px;padding:10px 12px;border-radius:13px;background:rgba(20,145,255,.08);border:1px solid rgba(36,158,255,.12);font-size:11px;opacity:.8}`}</style>
 <section className="ton-connect-card glass-panel"><div className="ton-connect-copy"><span>TON CONNECT</span><b>{tonWallet?short(tonWallet):'Connect TON wallet'}</b><small>{tonWallet?`${tonProvider} · Connected TON wallet`:'One TON wallet can only be used by one WIENER account'}</small></div><div className="ton-connect-actions">{tonWallet?<button onClick={disconnect} disabled={tonBusy}>Disconnect</button>:<button className="connect" onClick={connect} disabled={tonBusy}>{tonBusy?'…':'CONNECT'}</button>}</div></section>
 <section className="withdraw-balance glass-panel"><span className="eyebrow">AVAILABLE BALANCE</span><div><strong>{money(balance)}</strong><b>WIENER</b></div><p>{tonRate?`${tonRate.toLocaleString()} WIENER = 1 TON · `:''}{baseRate.toLocaleString()} WIENER = 1 USDT</p></section>
 <section className="withdraw-v2 glass-panel"><div className="withdraw-progress">{progress.map((label,i)=><div className="progress-node" key={label}><span className={i<idx?'done':i===idx?'active':''}>{i<idx?'✓':i+1}</span><small>{label}</small>{i<3&&<i className={i<idx?'done':''}/>}</div>)}</div>
 {cooldownMs>0&&<div className="cooldown-state">Next withdrawal available in <b>{formatLeft(cooldownMs)}</b></div>}{hasPending&&<div className="cooldown-state">Withdrawal pending · another request unlocks after processing.</div>}
 {step==='method'&&<div className="step-panel"><div className="step-copy"><h3>Choose payout method</h3><p>Connect your wallet first for native TON withdrawal.</p></div><div className="method-grid">{methods.map(m=>{const gram=m.method_key==='gram_ton',ready=!gram||!!tonRate;return <button key={m.method_key} onClick={()=>choose(m)} disabled={!m.enabled||!globalEnabled||!ready} className={`method-card ${!m.enabled||!globalEnabled||!ready?'disabled':''}`}><span className="method-icon"><img src={m.network==='TON'?TON_ICON:USDT_ICON} alt="" style={{width:42,height:42,objectFit:'contain',display:'block'}}/></span><div><b>{gram?'TON Withdrawal':m.label}</b><small>{gram?(tonRate?`${tonRate.toLocaleString()} WIENER = 1 TON · Min ${Number(m.minimum_usdt).toFixed(4)} TON`:'TON rate not configured yet'):`${m.network} · Min ${Number(m.minimum_usdt).toFixed(4)} USDT · 0 fee below 0.0500 USDT`}</small></div>{(!m.enabled||!ready)&&<em>Unavailable</em>}<i>›</i></button>})}</div></div>}
 {step==='wallet'&&method&&isGram&&<div className="step-panel"><button className="withdraw-back" onClick={()=>setStep('method')}>← Back</button><div className="network-banner"><b>Connect TON Wallet</b><span>TON will only be sent to the wallet connected here.</span></div>{tonWallet?<><div className="review-withdraw"><div><span>Status</span><b>✅ Connected</b></div><div><span>TON wallet</span><b>{short(tonWallet)}</b></div><div><span>Provider</span><b>{tonProvider||'TON Connect'}</b></div></div><div className="gram-note">This wallet is reserved for this WIENER Farm account. The same wallet cannot be linked to another account.</div><button className="primary" disabled={hasPending||cooldownMs>0} onClick={()=>{setAmount('');setStep('amount')}}>CONTINUE</button></>:<><div className="gram-note">Connect Tonkeeper, TON Space, MyTonWallet or another TON Connect wallet. No seed phrase is shared with WIENER Farm.</div><button className="primary" onClick={connect} disabled={tonBusy}>{tonBusy?'CONNECTING…':'CONNECT TON WALLET'}</button></>}</div>}
 {step==='amount'&&method&&isGram&&<div className="step-panel"><button className="withdraw-back" onClick={()=>setStep('wallet')}>← Back</button><div className="network-banner"><b>TON Withdrawal</b><span>Connected: <strong>{short(tonWallet)}</strong></span></div><div className="available-line"><span>Available</span><b>{money(balance)} WIENER</b></div><label>ENTER AMOUNT IN WIENER</label><input className="withdraw-input" type="number" inputMode="decimal" step="1" placeholder="0 WIENER" value={amount} onChange={e=>setAmount(e.target.value)}/><div className="quick-withdraw"><button onClick={()=>quick('min')}>MIN</button><button onClick={()=>quick('25')}>25%</button><button onClick={()=>quick('50')}>50%</button><button onClick={()=>quick('max')}>MAX</button></div><div className="withdraw-breakdown"><div><span>WIENER deducted</span><b>{money(Math.min(wienerAmount,balance),1)}</b></div><div><span>TON value</span><b>{tonGross.toFixed(6)} TON</b></div><div><span>Fee</span><b>{tonFee.toFixed(6)} TON</b></div><div><span>You receive</span><b>{tonReceive.toFixed(6)} TON</b></div></div>{wienerAmount>balance+1e-9&&<div className="withdraw-warning">Insufficient WIENER balance.</div>}{wienerAmount>0&&tonGross<Number(method.minimum_usdt)&&<div className="withdraw-warning">Minimum is {Number(method.minimum_usdt).toFixed(4)} TON ({Math.ceil(Number(method.minimum_usdt)*tonRateNum)} WIENER at the current rate).</div>}<button className="primary" disabled={!canAmount} onClick={()=>setStep('review')}>REVIEW WITHDRAWAL</button></div>}
 {step==='review'&&method&&isGram&&<div className="step-panel"><button className="withdraw-back" onClick={()=>setStep('amount')}>← Back</button><div className="review-withdraw"><h3>Review TON Withdrawal</h3><div><span>WIENER Amount</span><b>{money(wienerAmount,1)} WIENER</b></div><div><span>Rate</span><b>{tonRateNum.toLocaleString()} WIENER = 1 TON</b></div><div><span>TON Value</span><b>{tonGross.toFixed(6)} TON</b></div><div><span>Fee</span><b>{tonFee.toFixed(6)} TON</b></div><div><span>You Receive</span><b>{tonReceive.toFixed(6)} TON</b></div><div><span>Connected Wallet</span><b>{short(tonWallet)}</b></div><div><span>Network</span><b>TON</b></div></div><button className="primary confirm-withdraw" disabled={busy||!canAmount||!tonWallet} onClick={submit}>{busy?'CREATING…':'CONFIRM TON WITHDRAWAL'}</button></div>}
 {step==='amount'&&method&&!isGram&&<div className="step-panel"><button className="withdraw-back" onClick={()=>setStep('method')}>← Back</button><div className="network-banner"><b>{method.label}</b><span>Network: <strong>{method.network}</strong></span></div><div className="available-line"><span>Available</span><b>{money(balance)} WIENER · max {floor4(usdtAvailable).toFixed(4)} USDT</b></div><label>ENTER WITHDRAWAL AMOUNT</label><input className="withdraw-input" type="number" inputMode="decimal" step="0.0001" placeholder="0.0000 USDT" value={amount} onChange={e=>setAmount(e.target.value)}/><div className="quick-withdraw"><button onClick={()=>quick('min')}>MIN</button><button onClick={()=>quick('25')}>25%</button><button onClick={()=>quick('50')}>50%</button><button onClick={()=>quick('max')}>MAX</button></div><div className="withdraw-breakdown"><div><span>WIENER used</span><b>{money(Math.min(usdtNeeded,balance),1)}</b></div><div><span>Fee</span><b>{usdtFee.toFixed(4)} USDT</b></div><div><span>You receive</span><b>{usdtReceive.toFixed(4)} USDT</b></div></div>{usdtGross>0&&usdtGross<0.05&&<div className="cooldown-state">0 withdrawal fee below 0.0500 USDT.</div>}{usdtGross>0&&usdtGross<Number(method.minimum_usdt)&&<div className="withdraw-warning">Minimum is {Number(method.minimum_usdt).toFixed(4)} USDT.</div>}{usdtNeeded>balance+1e-9&&<div className="withdraw-warning">Insufficient WIENER balance.</div>}<button className="primary" disabled={!canAmount} onClick={()=>setStep('wallet')}>CONTINUE</button></div>}
 {step==='wallet'&&method&&!isGram&&<div className="step-panel"><button className="withdraw-back" onClick={()=>setStep('amount')}>← Back</button><div className="network-banner"><b>{method.label}</b><span>{method.network==='TON'?'Enter a TON-compatible wallet.':'Enter a Polygon-compatible wallet.'}</span></div><label>{method.network.toUpperCase()} WALLET ADDRESS</label><input className="withdraw-input" placeholder={method.network==='Polygon'?'0x…':'UQ… / EQ…'} value={wallet} onChange={e=>setWallet(e.target.value.trim())}/>{wallet&&!walletOk&&<div className="withdraw-warning">Invalid {method.network} wallet address.</div>}<button className="primary" disabled={!walletOk||!canAmount} onClick={()=>setStep('review')}>REVIEW WITHDRAWAL</button></div>}
 {step==='review'&&method&&!isGram&&<div className="step-panel"><button className="withdraw-back" onClick={()=>setStep('wallet')}>← Back</button><div className="review-withdraw"><h3>Review Withdrawal</h3><div><span>Amount</span><b>{usdtGross.toFixed(4)} USDT</b></div><div><span>WIENER deducted</span><b>{money(usdtNeeded,1)}</b></div><div><span>Network</span><b>{method.network}</b></div><div><span>Fee</span><b>{usdtFee.toFixed(4)} USDT</b></div><div><span>You Receive</span><b>{usdtReceive.toFixed(4)} USDT</b></div><div><span>Wallet</span><b>{short(wallet)}</b></div></div><button className="primary confirm-withdraw" disabled={busy||!walletOk||!canAmount} onClick={submit}>{busy?'CREATING…':'CONFIRM WITHDRAWAL'}</button></div>}
 {message&&<div className="withdraw-message">{message}</div>}</section>
 <section className="withdraw-history-section"><div className="section-title"><div><h3>Withdrawal History</h3><p>Tap any row for full details.</p></div><button onClick={()=>load(true)}>↻</button></div><div className="withdraw-history-list">{history.length?history.map((w:any)=>{const st=statusView(String(w.status)),u=w.method_key==='gram_ton'?'TON':'USDT';return <button className="withdraw-history-row" key={w.id} onClick={()=>setSelected(w)}><div><b>{Number(w.gross_usdt).toFixed(4)} {u} · {w.network}</b><small>{date(w.created_at)}</small></div><div><strong>{Number(w.receive_usdt).toFixed(4)} {u}</strong><span>{st.icon} {st.label}</span></div></button>}):<div className="history-empty">No withdrawals yet.</div>}</div></section>
 {selected&&<div className="withdraw-sheet-backdrop" onClick={()=>setSelected(null)}><div className="withdraw-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-grabber"/><div className="sheet-head"><h3>Withdrawal Details</h3><button onClick={()=>setSelected(null)}>×</button></div>{(()=>{const u=selected.method_key==='gram_ton'?'TON':'USDT';return [['Withdrawal ID',selected.id],['WIENER Deducted',`${money(Number(selected.amount_farm||0),1)} WIENER`],['Requested Amount',`${Number(selected.gross_usdt).toFixed(6)} ${u}`],['Fee',`${Number(selected.fee_usdt).toFixed(6)} ${u}`],['Amount Received',`${Number(selected.receive_usdt).toFixed(6)} ${u}`],['Network',selected.network],['Wallet',selected.wallet_address],['Requested',date(selected.created_at)],['Status',statusView(String(selected.status)).label],['TX Hash',selected.tx_hash||'—']].map(([k,v])=><div className="sheet-row" key={String(k)}><span>{k}</span><b>{v}</b></div>)})()}{selected.explorer_url&&<button className="primary" onClick={()=>window.Telegram?.WebApp?.openLink?.(selected.explorer_url)}>OPEN BLOCKCHAIN EXPLORER</button>}</div></div>}
 </div>
}
